# Generated by Django 4.0 on 2022-02-19 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antiepilepsymedicine',
            options={'verbose_name': ('antiepilepsy medicine',), 'verbose_name_plural': 'antiepilepsy medicines'},
        ),
        migrations.AlterModelOptions(
            name='assessment',
            options={'verbose_name': ('assessment',), 'verbose_name_plural': 'assessments'},
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'child or young person', 'verbose_name_plural': 'children and young people'},
        ),
        migrations.AlterModelOptions(
            name='comorbidity',
            options={'verbose_name': 'comorbidity', 'verbose_name_plural': 'comorbidities'},
        ),
        migrations.AlterModelOptions(
            name='electroclinicalsyndrome',
            options={'verbose_name': ('electroclinical syndrome',), 'verbose_name_plural': 'electroclinical syndromes'},
        ),
        migrations.AlterModelOptions(
            name='epilepsycontext',
            options={'verbose_name': 'epilepsy context', 'verbose_name_plural': 'epilepsy contexts'},
        ),
        migrations.AlterModelOptions(
            name='hospitaltrust',
            options={'verbose_name': 'hospital trust', 'verbose_name_plural': 'hospital trusts'},
        ),
        migrations.AlterModelOptions(
            name='initialassessment',
            options={'verbose_name': 'initial assessment', 'verbose_name_plural': 'initial assessments'},
        ),
        migrations.AlterModelOptions(
            name='investigations',
            options={'verbose_name': 'investigations'},
        ),
        migrations.AlterModelOptions(
            name='nonepilepsy',
            options={'verbose_name': 'Nonepilepsy'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': ('Registration',), 'verbose_name_plural': 'Registrations'},
        ),
        migrations.AlterModelOptions(
            name='rescuemedicine',
            options={'verbose_name': ('Rescue Medicine',), 'verbose_name_plural': 'Rescue Medicines'},
        ),
        migrations.AlterModelOptions(
            name='seizurecause',
            options={'verbose_name': ('Main cause of seizure(s)',), 'verbose_name_plural': 'Main causes of seizure(s)'},
        ),
        migrations.AlterModelOptions(
            name='seizuretype',
            options={'verbose_name': ('Main type of seizure(s)',), 'verbose_name_plural': 'Main types of seizure(s)'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'site', 'verbose_name_plural': 'sites'},
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='does_the_child_have_any_of_the_childrens_epilepsy_surgical_service_referral_criteria',
            new_name='childrens_epilepsy_surgical_service_referral_criteria_met',
        ),
        migrations.RenameField(
            model_name='initialassessment',
            old_name='has_frequency_or_number_of_episodes_since_the_first_episode_been_documented',
            new_name='has_number_of_episodes_since_the_first_been_documented',
        ),
    ]
