ETHNICITIES = (
    ("A", "White British"),
    ("B", "White - Irish"),
    ("C", "White - Any other White background"),
    ("D", "Mixed (White and Black Caribbean)"),
    ("E", "Mixed (White and Black African)"),
    ("F", "Mixed (White and Asian)"),
    ("G", "Mixed - Any other mixed background"),
    ("H", "Indian or British Indian"),
    ("J", "Asian or Asian British - Pakistani"),
    ("K", "Asian or Asian British - Bangladeshi"),
    ("L", "Asian or Asian British - Any other Asian background"),
    ("M", "Black or Black British - Caribbean"),
    ("N", "Black or Black British - African"),
    ("P", "Black or Black British - Any other Black background"),
    ("S", "Other Ethnic Groups - Any other ethnic group"),
    ("R", "Other Ethnic Groups - Chinese"),
    ("Z", "Not Stated"),
)
