KEYWORDS = [{'id': 0, 'title': 'acalculia', 'category': 'cognitive', 'narrative': 0},
    {'id': 1, 'title': 'aphasia', 'category': 'cognitive', 'narrative': 0},
    {'id': 2, 'title': 'attention impairment','category': 'cognitive', 'narrative': 0},
    {'id': 3, 'title': 'deja vu', 'category': 'cognitive', 'narrative': 0},
    {'id': 4, 'title': 'jamais vu', 'category': 'cognitive', 'narrative': 0},
    {'id': 5, 'title': 'dissociation', 'category': 'cognitive', 'narrative': 0},
    {'id': 6, 'title': 'dysphasia', 'category': 'cognitive', 'narrative': 0},
    {'id': 7, 'title': 'hallucinations', 'category': 'cognitive', 'narrative': 0},
    {'id': 8, 'title': 'illusions', 'category': 'cognitive', 'narrative': 0},
    {'id': 9, 'title': 'memory impairment','category': 'cognitive', 'narrative': 0},
    {'id': 10, 'title': 'neglect', 'category': 'cognitive', 'narrative': 0},
    {'id': 11, 'title': 'forced thinking','category': 'cognitive', 'narrative': 0},
    {'id': 12, 'title': 'responsiveness impairment','category': 'cognitive', 'narrative': 0},
    {'id': 13, 'title': 'agitation','category': 'emotional or affective', 'narrative': 0},
    {'id': 14, 'title': 'anger', 'category': 'emotional or affective', 'narrative': 0},
    {'id': 15, 'title': 'anxiety','category': 'emotional or affective', 'narrative': 0},
    {'id': 16, 'title': 'crying', 'category': 'emotional or affective', 'narrative': 0},
    {'id': 17, 'title': 'dacrystic','category': 'emotional or affective', 'narrative': 0},
    {'id': 18, 'title': 'fear', 'category': 'emotional or affective', 'narrative': 0},
    {'id': 19, 'title': 'laughing','category': 'emotional or affective', 'narrative': 0},
    {'id': 20, 'title': 'gelastic','category': 'emotional or affective', 'narrative': 0},
    {'id': 11, 'title': 'paranoia','category': 'emotional or affective', 'narrative': 0},
    {'id': 12, 'title': 'pleasure','category': 'emotional or affective', 'narrative': 0},
    {'id': 23, 'title': 'asystole', 'category': 'autonomic', 'narrative': 0},
    {'id': 24, 'title': 'bradycardia', 'category': 'autonomic', 'narrative': 0},
    {'id': 25, 'title': 'erection', 'category': 'autonomic', 'narrative': 0},
    {'id': 26, 'title': 'flushing', 'category': 'autonomic', 'narrative': 0},
    {'id': 27, 'title': 'gastrointestinal','category': 'autonomic', 'narrative': 0},
    {'id': 28, 'title': 'hyperventilation','category': 'autonomic', 'narrative': 0},
    {'id': 29, 'title': 'hypoventilation','category': 'autonomic', 'narrative': 0},
    {'id': 30, 'title': 'nausea/vomiting','category': 'autonomic', 'narrative': 0},
    {'id': 21, 'title': 'pallor', 'category': 'autonomic', 'narrative': 0},
    {'id': 22, 'title': 'palpitations', 'category': 'autonomic', 'narrative': 0},
    {'id': 23, 'title': 'piloerection', 'category': 'autonomic', 'narrative': 0},
    {'id': 34, 'title': 'respiratory changes','category': 'autonomic', 'narrative': 0},
    {'id': 35, 'title': 'tachycardia', 'category': 'autonomic', 'narrative': 0},
    {'id': 36, 'title': 'aggression', 'category': 'automatisms', 'narrative': 0},
    {'id': 37, 'title': 'eye blinking', 'category': 'automatisms', 'narrative': 0},
    {'id': 38, 'title': 'head nodding', 'category': 'automatisms', 'narrative': 0},
    {'id': 39, 'title': 'manual', 'category': 'automatisms', 'narrative': 0},
    {'id': 40, 'title': 'orofacial', 'category': 'automatisms', 'narrative': 0},
    {'id': 41, 'title': 'pedaling', 'category': 'automatisms', 'narrative': 0},
    {'id': 42, 'title': 'pelvic thrusting','category': 'automatisms', 'narrative': 0},
    {'id': 43, 'title': 'perseveration', 'category': 'automatisms', 'narrative': 0},
    {'id': 44, 'title': 'running', 'category': 'automatisms', 'narrative': 0},
    {'id': 45, 'title': 'cursive', 'category': 'automatisms', 'narrative': 0},
    {'id': 46, 'title': 'sexual', 'category': 'automatisms', 'narrative': 0},
    {'id': 47, 'title': 'undressing', 'category': 'automatisms', 'narrative': 0},
    {'id': 48, 'title': 'vocalisation', 'category': 'automatisms', 'narrative': 0},
    {'id': 49, 'title': 'speech', 'category': 'automatisms', 'narrative': 0},
    {'id': 50, 'title': 'walking', 'category': 'automatisms', 'narrative': 0},
    {'id': 51, 'title': 'dysarthria', 'category': 'motor', 'narrative': 0},
    {'id': 52, 'title': 'dystonic', 'category': 'motor', 'narrative': 0},
    {'id': 53, 'title': 'fencer\'s posture', 'category': 'motor', 'narrative': 0},
    {'id': 54, 'title': 'incoordination', 'category': 'motor', 'narrative': 0},
    {'id': 55, 'title': 'jacksonian', 'category': 'motor', 'narrative': 0},
    {'id': 56, 'title': 'paralysis', 'category': 'motor', 'narrative': 0},
    {'id': 57, 'title': 'paresis', 'category': 'motor', 'narrative': 0},
    {'id': 58, 'title': 'versive', 'category': 'motor', 'narrative': 0},
    {'id': 59, 'title': 'auditory', 'category': 'sensory', 'narrative': 0},
    {'id': 60, 'title': 'gustatory', 'category': 'sensory', 'narrative': 0},
    {'id': 61, 'title': 'hot sensations', 'category': 'sensory', 'narrative': 0},
    {'id': 62, 'title': 'cold sensations', 'category': 'sensory', 'narrative': 0},
    {'id': 63, 'title': 'olfactory', 'category': 'sensory', 'narrative': 0},
    {'id': 64, 'title': 'somatosensory', 'category': 'sensory', 'narrative': 0},
    {'id': 65, 'title': 'vestibular', 'category': 'sensory', 'narrative': 0},
    {'id': 66, 'title': 'visual', 'category': 'sensory', 'narrative': 0},
    {'id': 67, 'title': 'left', 'category': 'laterality', 'narrative': 0},
    {'id': 68, 'title': 'right', 'category': 'laterality', 'narrative': 0},
    {'id': 69, 'title': 'bilateral', 'category': 'laterality', 'narrative': 0},
    {'id': 70, 'title': 'aura', 'category': 'custom', 'narrative': 0},
    {'id': 71, 'title': 'unresponsive', 'category': 'custom', 'narrative': 0}]
