INDIVIDUAL_KPI_MEASURES = (
    (
        ('paediatrician_with_expertise_in_epilepsies',
         'Paediatrician with expertise in epilepsies'),
        ('epilepsy_specialist_nurse', 'epilepsy specialist nurse'),
        ('tertiary_input', 'tertiary input'),
        ('epilepsy_surgery_referral', 'epilepsy surgery referral'),
        ('ecg', 'ECG'),
        ('mri', 'MRI'),
        ('assessment_of_mental_health_issues',
         'assessment_of_mental_health_issues'),
        ('mental_health_support', 'mental_health_support'),
        ('sodium_valproate', 'sodium_valproate'),
        ('comprehensive_care_planning_agreement',
         'comprehensive_care_planning_agreement'),
        ('patient_held_individualised_epilepsy_document',
         'patient_held_individualised_epilepsy_document'),
        ('patient_carer_parent_agreement_to_the_care_planning',
         'patient_carer_parent_agreement_to_the_care_planning'),
        ('care_planning_has_been_updated_when_necessary',
         'care_planning_has_been_updated_when_necessary'),
        ('comprehensive_care_planning_content',
         'comprehensive_care_planning_content'),
        ('parental_prolonged_seizures_care_plan',
         'parental_prolonged_seizures_care_plan'),
        ('water_safety', 'water_safety'),
        ('first_aid', 'first_aid'),
        ('general_participation_and_risk', 'general_participation_and_risk'),
        ('service_contact_details', 'service_contact_details'),
        ('sudep', 'sudep'),
        ('school_individual_healthcare_plan',
         'school_individual_healthcare_plan'),
    )
)
