INDIVIDUAL_KPI_MEASURES = (
    (
        ('paediatrician_with_expertise_in_epilepsies',
         'Paediatrician with expertise in epilepsies'),
        ('epilepsy_specialist_nurse', 'Epilepsy specialist nurse'),
        ('tertiary_input', 'Tertiary input'),
        ('epilepsy_surgery_referral', 'Epilepsy surgery referral'),
        ('ecg', 'ECG'),
        ('mri', 'MRI'),
        ('assessment_of_mental_health_issues',
         'Assessment of mental health issues'),
        ('mental_health_support', 'Mental health support'),
        ('sodium_valproate', 'Sodium valproate'),
        ('comprehensive_care_planning_agreement',
         'Comprehensive care planning agreement'),
        ('patient_held_individualised_epilepsy_document',
         'Patient-held individualised epilepsy document'),
        ('patient_carer_parent_agreement_to_the_care_planning',
         'Patient/Carer agreement to the care planning'),
        ('care_planning_has_been_updated_when_necessary',
         'Care planning has been updated when necessary'),
        ('comprehensive_care_planning_content',
         'Comprehensive care planning content'),
        ('parental_prolonged_seizures_care_plan',
         'Parental prolonged seizures care plan'),
        ('water_safety', 'Water safety'),
        ('first_aid', 'First aid'),
        ('general_participation_and_risk', 'General participation and risk'),
        ('service_contact_details', 'Service contact details'),
        ('sudep', 'SUDEP (sudden unexplained death in epilepsy)'),
        ('school_individual_healthcare_plan',
         'School individual healthcare plan'),
    )
)
KPI_SCORE = {
    "NOT_SCORED": None,
    "FAIL": 0,
    "PASS": 1,
    "INELIGIBLE": 2,
}