# Medications

ANTIEPILEPSY_MEDICINE_TYPES = (
    (1, "Acetazolamide"),
    (2, "ACTH"),
    (3, "Carbamazepine"),
    (4, "Clobazam"),
    (5, "Clonazepam"),
    (6, "Eslicarbazepine acetate"),
    (7, "Ethosuximide"),
    (8, "Gabapentin"),
    (9, "Lacosamide"),
    (10, "Lamotrigine"),
    (11, "Levetiracetam"),
    (12, "Methylprednisolone"),
    (13, "Nitrazepam"),
    (14, "Oxcarbazepine"),
    (15, "Perampanel"),
    (16, "Piracetam"),
    (17, "Phenobarbital"),
    (18, "Phenytoin"),
    (19, "Pregabalin"),
    (20, "Prednisolone"),
    (21, "Primidone"),
    (22, "Rufinamide"),
    (23, "Sodium valproate"),
    (24, "Stiripentol"),
    (25, "Sulthiame"),
    (26, "Tiagabine"),
    (27, "Topiramate"),
    (28, "Vigabatrin"),
    (29, "Zonisamide"),
    (0, "Other")
)

BENZODIAZEPINE_TYPES = (
    (1000, "Buccal midazolam"),
    (1001, "Rectal diazepam"),
    (1002, "Other"),
    (1003, "Lorazepam")
)

ANTIEPILEPSY_MEDICINES = (
    (0, "Acetazolamide"),
    (1, "ACTH"),
    (2, "Carbamazepine"),
    (3, "Clobazam"),
    (4, "Clonazepam"),
    (5, "Eslicarbazepine acetate"),
    (6, "Ethosuximide"),
    (31, "Gabapentin"),
    (7, "Lacosamide"),
    (8, "Lamotrigine"),
    (9, "Levetiracetam"),
    (10, "Methylprednisolone"),
    (11, "Nitrazepam"),
    (12, "Oxcarbazepine"),
    (13, "Perampanel"),
    (14, "Piracetam"),
    (15, "Phenobarbital"),
    (16, "Phenytoin"),
    (17, "Pregabalin"),
    (18, "Prednisolone"),
    (19, "Primidone"),
    (20, "Rufinamide"),
    (21, "Sodium valproate"),
    (22, "Stiripentol"),
    (23, "Sulthiame"),
    (24, "Tiagabine"),
    (25, "Topiramate"),
    (26, "Vigabatrin"),
    (27, "Zonisamide"),
    (28, "Epidyolex® "),
    (29, "Other Cannabis-based medicinal product"),
    (30, "Other")
)
