"""
For seeding OPENUKNetwork table and organisation OPENUK relationships
OPEN_UK_NETWORKS is a list of all networks and their unique id
OPEN_UK_NETWORKS_TRUSTS has list of trusts and related OPENUK network
"""
OPEN_UK_NETWORKS = [
    {
        "OPEN_UK_Network_Name": "Birmingham Regional Paediatric Neurology Forum",
        "OPEN_UK_Network_Code": "BRPNF",
        "country": "England",
    },
    {
        "OPEN_UK_Network_Name": "Children's Epilepsy Workstream in Trent",
        "OPEN_UK_Network_Code": "CEWT",
        "country": "England",
    },
    {
        "OPEN_UK_Network_Name": "Eastern Paediatric Epilepsy Network",
        "OPEN_UK_Network_Code": "EPEN",
        "country": "England",
    },
    {
        "OPEN_UK_Network_Name": "Mersey and North Wales network 'Epilepsy In Childhood' interest group",
        "OPEN_UK_Network_Code": "EPIC",
        "country": "Wales",
    },
    {
        "OPEN_UK_Network_Name": "North Thames Paediatric Epilepsy Network",
        "OPEN_UK_Network_Code": "NTPEN",
        "country": "England",
    },
    {
        "OPEN_UK_Network_Name": "North West Children and Young People's Epilepsy Interest Group",
        "OPEN_UK_Network_Code": "NWEIG",
        "country": "England",
    },
    {
        "OPEN_UK_Network_Name": "Oxford region epilepsy interest group",
        "OPEN_UK_Network_Code": "ORENG",
        "country": "England",
    },
    {
        "OPEN_UK_Network_Name": "Paediatric Epilepsy Network for the North East and Cumbria",
        "OPEN_UK_Network_Code": "PENNEC",
        "country": "England",
    },
    {
        "OPEN_UK_Network_Name": "South East Thames Paediatric Epilepsy Group",
        "OPEN_UK_Network_Code": "SETPEG",
        "country": "England",
    },
    {
        "OPEN_UK_Network_Name": "South Wales Epilepsy Forum",
        "OPEN_UK_Network_Code": "SWEP",
        "country": "Wales",
    },
    {
        "OPEN_UK_Network_Name": "South West Interest Group Paediatric Epilepsy",
        "OPEN_UK_Network_Code": "SWIPE",
        "country": "England",
    },
    {
        "OPEN_UK_Network_Name": "South West Thames Paediatric Epilepsy Group",
        "OPEN_UK_Network_Code": "SWTPEG",
        "country": "England",
    },
    {
        "OPEN_UK_Network_Name": "Trent Epilepsy Network",
        "OPEN_UK_Network_Code": "TEN",
        "country": "England",
    },
    {
        "OPEN_UK_Network_Name": "Wessex Paediatric Neurosciences Network",
        "OPEN_UK_Network_Code": "WPNN",
        "country": "England",
    },
    {
        "OPEN_UK_Network_Name": "Yorkshire Paediatric Neurology Network",
        "OPEN_UK_Network_Code": "YPEN",
        "country": "England",
    },
]

OPEN_UK_NETWORKS_TRUSTS = [
    {
        "ods trust code": "7A1",
        "OPEN UK Network Name": "Mersey and North Wales network 'Epilepsy In Childhood' interest group",
        "OPEN UK Network Code": "EPIC",
        "country": "Wales",
    },
    {
        "ods trust code": "7A2",
        "OPEN UK Network Name": "South Wales Epilepsy Forum",
        "OPEN UK Network Code": "SWEP",
        "country": "Wales",
    },
    {
        "ods trust code": "7A3",
        "OPEN UK Network Name": "South Wales Epilepsy Forum",
        "OPEN UK Network Code": "SWEP",
        "country": "Wales",
    },
    {
        "ods trust code": "7A4",
        "OPEN UK Network Name": "South Wales Epilepsy Forum",
        "OPEN UK Network Code": "SWEP",
        "country": "Wales",
    },
    {
        "ods trust code": "7A5",
        "OPEN UK Network Name": "South Wales Epilepsy Forum",
        "OPEN UK Network Code": "SWEP",
        "country": "Wales",
    },
    {
        "ods trust code": "7A6",
        "OPEN UK Network Name": "South Wales Epilepsy Forum",
        "OPEN UK Network Code": "SWEP",
        "country": "Wales",
    },
    {  # added by Simon
        "ods trust code": "7A7",
        "OPEN UK Network Name": "South Wales Epilepsy Forum",
        "OPEN UK Network Code": "SWEP",
        "country": "Wales",
    },
    {
        "ods trust code": "R0A",
        "OPEN UK Network Name": "North West Children and Young People's Epilepsy Interest Group",
        "OPEN UK Network Code": "NWEIG",
        "country": "England",
    },
    {  # added by Simon
        "ods trust code": "RM3",
        "OPEN UK Network Name": "North West Children and Young People's Epilepsy Interest Group",
        "OPEN UK Network Code": "NWEIG",
        "country": "England",
    },
    {
        "ods trust code": "R1A",
        "OPEN UK Network Name": "Birmingham Regional Paediatric Neurology Forum",
        "OPEN UK Network Code": "BRPNF",
        "country": "England",
    },
    {
        "ods trust code": "R1C",
        "OPEN UK Network Name": "Wessex Paediatric Neurosciences Network",
        "OPEN UK Network Code": "WPNN",
        "country": "England",
    },
    {
        "ods trust code": "R1F",
        "OPEN UK Network Name": "Wessex Paediatric Neurosciences Network",
        "OPEN UK Network Code": "WPNN",
        "country": "England",
    },
    {
        "ods trust code": "R1H",
        "OPEN UK Network Name": "North Thames Paediatric Epilepsy Network",
        "OPEN UK Network Code": "NTPEN",
        "country": "England",
    },
    {
        "ods trust code": "R1K",
        "OPEN UK Network Name": "North Thames Paediatric Epilepsy Network",
        "OPEN UK Network Code": "NTPEN",
        "country": "England",
    },
    {
        "ods trust code": "RA2",
        "OPEN UK Network Name": "South West Thames Paediatric Epilepsy Group",
        "OPEN UK Network Code": "SWTPEG",
        "country": "England",
    },
    {
        "ods trust code": "RA4",
        "OPEN UK Network Name": "South West Interest Group Paediatric Epilepsy",
        "OPEN UK Network Code": "SWIPE",
        "country": "England",
    },
    {
        "ods trust code": "RA7",
        "OPEN UK Network Name": "South West Interest Group Paediatric Epilepsy",
        "OPEN UK Network Code": "SWIPE",
        "country": "England",
    },
    {
        # added by Simon
        "ods trust code": "RVN",
        "OPEN UK Network Name": "South West Interest Group Paediatric Epilepsy",
        "OPEN UK Network Code": "SWIPE",
        "country": "England",
    },
    {
        # added by Simon
        "ods trust code": "RVJ",
        "OPEN UK Network Name": "South West Interest Group Paediatric Epilepsy",
        "OPEN UK Network Code": "SWIPE",
        "country": "England",
    },
    {
        "ods trust code": "RA9",
        "OPEN UK Network Name": "South West Interest Group Paediatric Epilepsy",
        "OPEN UK Network Code": "SWIPE",
        "country": "England",
    },
    {
        "ods trust code": "RAE",
        "OPEN UK Network Name": "Yorkshire Paediatric Neurology Network",
        "OPEN UK Network Code": "YPEN",
        "country": "England",
    },
    {
        "ods trust code": "RAJ",
        "OPEN UK Network Name": "North Thames Paediatric Epilepsy Network",
        "OPEN UK Network Code": "NTPEN",
        "country": "England",
    },
    {  # added by Simon
        "ods trust code": "R1L",
        "OPEN UK Network Name": "North Thames Paediatric Epilepsy Network",
        "OPEN UK Network Code": "NTPEN",
        "country": "England",
    },
    {
        "ods trust code": "RAL",
        "OPEN UK Network Name": "North Thames Paediatric Epilepsy Network",
        "OPEN UK Network Code": "NTPEN",
        "country": "England",
    },
    {
        "ods trust code": "RAP",
        "OPEN UK Network Name": "North Thames Paediatric Epilepsy Network",
        "OPEN UK Network Code": "NTPEN",
        "country": "England",
    },
    {
        "ods trust code": "RAS",
        "OPEN UK Network Name": "North Thames Paediatric Epilepsy Network",
        "OPEN UK Network Code": "NTPEN",
        "country": "England",
    },
    {
        "ods trust code": "RAT",
        "OPEN UK Network Name": "North Thames Paediatric Epilepsy Network",
        "OPEN UK Network Code": "NTPEN",
        "country": "England",
    },
    {
        "ods trust code": "RAX",
        "OPEN UK Network Name": "South West Thames Paediatric Epilepsy Group",
        "OPEN UK Network Code": "SWTPEG",
        "country": "England",
    },
    {
        "ods trust code": "RH5",
        "OPEN UK Network Name": "South West Interest Group Paediatric Epilepsy",
        "OPEN UK Network Code": "SWIPE",
        "country": "England",
    },
    {
        "ods trust code": "RBD",
        "OPEN UK Network Name": "Wessex Paediatric Neurosciences Network",
        "OPEN UK Network Code": "WPNN",
        "country": "England",
    },
    {  # Added by Simon
        "ods trust code": "R0D",
        "OPEN UK Network Name": "Wessex Paediatric Neurosciences Network",
        "OPEN UK Network Code": "WPNN",
        "country": "England",
    },
    {  # Added by Simon
        "ods trust code": "RDY",
        "OPEN UK Network Name": "Wessex Paediatric Neurosciences Network",
        "OPEN UK Network Code": "WPNN",
        "country": "England",
    },
    {
        "ods trust code": "RBK",
        "OPEN UK Network Name": "Birmingham Regional Paediatric Neurology Forum",
        "OPEN UK Network Code": "BRPNF",
        "country": "England",
    },
    {  # added by Simon
        "ods trust code": "RYK",
        "OPEN UK Network Name": "Birmingham Regional Paediatric Neurology Forum",
        "OPEN UK Network Code": "BRPNF",
        "country": "England",
    },
    {
        "ods trust code": "RBL",
        "OPEN UK Network Name": "Mersey and North Wales network 'Epilepsy In Childhood' interest group",
        "OPEN UK Network Code": "EPIC",
        "country": "England",
    },
    {
        "ods trust code": "RBN",
        "OPEN UK Network Name": "Mersey and North Wales network 'Epilepsy In Childhood' interest group",
        "OPEN UK Network Code": "EPIC",
        "country": "England",
    },
    {
        "ods trust code": "RBS",
        "OPEN UK Network Name": "Mersey and North Wales network 'Epilepsy In Childhood' interest group",
        "OPEN UK Network Code": "EPIC",
        "country": "England",
    },
    {
        "ods trust code": "RBT",
        "OPEN UK Network Name": "Mersey and North Wales network 'Epilepsy In Childhood' interest group",
        "OPEN UK Network Code": "EPIC",
        "country": "England",
    },
    {
        "ods trust code": "RH8",
        "OPEN UK Network Name": "South West Interest Group Paediatric Epilepsy",
        "OPEN UK Network Code": "SWIPE",
        "country": "England",
    },
    {
        "ods trust code": "RC1",
        "OPEN UK Network Name": "Eastern Paediatric Epilepsy Network",
        "OPEN UK Network Code": "EPEN",
        "country": "England",
    },
    {
        "ods trust code": "RC9",
        "OPEN UK Network Name": "Eastern Paediatric Epilepsy Network",
        "OPEN UK Network Code": "EPEN",
        "country": "England",
    },
    {
        "ods trust code": "RCB",
        "OPEN UK Network Name": "Yorkshire Paediatric Neurology Network",
        "OPEN UK Network Code": "YPEN",
        "country": "England",
    },
    {
        "ods trust code": "RCD",
        "OPEN UK Network Name": "Yorkshire Paediatric Neurology Network",
        "OPEN UK Network Code": "YPEN",
        "country": "England",
    },
    {
        "ods trust code": "RCF",
        "OPEN UK Network Name": "Yorkshire Paediatric Neurology Network",
        "OPEN UK Network Code": "YPEN",
        "country": "England",
    },
    {
        "ods trust code": "RCU",
        "OPEN UK Network Name": "Trent Epilepsy Network",
        "OPEN UK Network Code": "TEN",
        "country": "England",
    },
    {
        "ods trust code": "RCX",
        "OPEN UK Network Name": "Eastern Paediatric Epilepsy Network",
        "OPEN UK Network Code": "EPEN",
        "country": "England",
    },
    {
        "ods trust code": "RD1",
        "OPEN UK Network Name": "South West Interest Group Paediatric Epilepsy",
        "OPEN UK Network Code": "SWIPE",
        "country": "England",
    },
    {
        "ods trust code": "RD3",
        "OPEN UK Network Name": "Wessex Paediatric Neurosciences Network",
        "OPEN UK Network Code": "WPNN",
        "country": "England",
    },
    {
        "ods trust code": "RD8",
        "OPEN UK Network Name": "Oxford region epilepsy interest group",
        "OPEN UK Network Code": "ORENG",
        "country": "England",
    },
    {
        "ods trust code": "RDD",
        "OPEN UK Network Name": "North Thames Paediatric Epilepsy Network",
        "OPEN UK Network Code": "NTPEN",
        "country": "England",
    },
    # {
    #     "ods trust code": "RDE1",
    #     "OPEN UK Network Name": "Eastern Paediatric Epilepsy Network",
    #     "OPEN UK Network Code": "EPEN",
    #     "country": "England",
    # },
    {  # added by Simon
        "ods trust code": "RDE",
        "OPEN UK Network Name": "Eastern Paediatric Epilepsy Network",
        "OPEN UK Network Code": "EPEN",
        "country": "England",
    },
    {
        "ods trust code": "RDR",
        "OPEN UK Network Name": "South East Thames Paediatric Epilepsy Group",
        "OPEN UK Network Code": "SETPEG",
        "country": "England",
    },
    {
        "ods trust code": "RDU",
        "OPEN UK Network Name": "South West Thames Paediatric Epilepsy Group",
        "OPEN UK Network Code": "SWTPEG",
        "country": "England",
    },
    {
        "ods trust code": "REF",
        "OPEN UK Network Name": "South West Interest Group Paediatric Epilepsy",
        "OPEN UK Network Code": "SWIPE",
        "country": "England",
    },
    {
        "ods trust code": "RF4",
        "OPEN UK Network Name": "North Thames Paediatric Epilepsy Network",
        "OPEN UK Network Code": "NTPEN",
        "country": "England",
    },
    {
        "ods trust code": "RFF",
        "OPEN UK Network Name": "Trent Epilepsy Network",
        "OPEN UK Network Code": "TEN",
        "country": "England",
    },
    {  # Added by Simon
        "ods trust code": "RXG",
        "OPEN UK Network Name": "Trent Epilepsy Network",
        "OPEN UK Network Code": "TEN",
        "country": "England",
    },
    {
        "ods trust code": "RFR",
        "OPEN UK Network Name": "Trent Epilepsy Network",
        "OPEN UK Network Code": "TEN",
        "country": "England",
    },
    {
        "ods trust code": "RFS",
        "OPEN UK Network Name": "Trent Epilepsy Network",
        "OPEN UK Network Code": "TEN",
        "country": "England",
    },
    # {
    #     "ods trust code": "RGN1",
    #     "OPEN UK Network Name": "Eastern Paediatric Epilepsy Network",
    #     "OPEN UK Network Code": "EPEN",
    #     "country": "England",
    # },
    {
        "ods trust code": "RGP",
        "OPEN UK Network Name": "Eastern Paediatric Epilepsy Network",
        "OPEN UK Network Code": "EPEN",
        "country": "England",
    },
    {
        "ods trust code": "RGR",
        "OPEN UK Network Name": "Eastern Paediatric Epilepsy Network",
        "OPEN UK Network Code": "EPEN",
        "country": "England",
    },
    {
        "ods trust code": "RGT",
        "OPEN UK Network Name": "Eastern Paediatric Epilepsy Network",
        "OPEN UK Network Code": "EPEN",
        "country": "England",
    },
    {  # Added by Simon
        "ods trust code": "RGN",
        "OPEN UK Network Name": "Eastern Paediatric Epilepsy Network",
        "OPEN UK Network Code": "EPEN",
        "country": "England",
    },
    {  # Added by Simon
        "ods trust code": "RYV",
        "OPEN UK Network Name": "Eastern Paediatric Epilepsy Network",
        "OPEN UK Network Code": "EPEN",
        "country": "England",
    },
    {
        "ods trust code": "RHM",
        "OPEN UK Network Name": "Wessex Paediatric Neurosciences Network",
        "OPEN UK Network Code": "WPNN",
        "country": "England",
    },
    {
        "ods trust code": "RHU",
        "OPEN UK Network Name": "Wessex Paediatric Neurosciences Network",
        "OPEN UK Network Code": "WPNN",
        "country": "England",
    },
    {
        "ods trust code": "RHW",
        "OPEN UK Network Name": "Oxford region epilepsy interest group",
        "OPEN UK Network Code": "ORENG",
        "country": "England",
    },
    {  # Added by Simon
        "ods trust code": "RWX",
        "OPEN UK Network Name": "Oxford region epilepsy interest group",
        "OPEN UK Network Code": "ORENG",
        "country": "England",
    },
    {
        "ods trust code": "RJ1",
        "OPEN UK Network Name": "South East Thames Paediatric Epilepsy Group",
        "OPEN UK Network Code": "SETPEG",
        "country": "England",
    },
    {
        "ods trust code": "RJ2",
        "OPEN UK Network Name": "South East Thames Paediatric Epilepsy Group",
        "OPEN UK Network Code": "SETPEG",
        "country": "England",
    },
    {
        "ods trust code": "RJ6",
        "OPEN UK Network Name": "South West Thames Paediatric Epilepsy Group",
        "OPEN UK Network Code": "SWTPEG",
        "country": "England",
    },
    {
        "ods trust code": "RJ7",
        "OPEN UK Network Name": "South West Thames Paediatric Epilepsy Group",
        "OPEN UK Network Code": "SWTPEG",
        "country": "England",
    },
    {
        "ods trust code": "RJC",
        "OPEN UK Network Name": "Birmingham Regional Paediatric Neurology Forum",
        "OPEN UK Network Code": "BRPNF",
        "country": "England",
    },
    {
        "ods trust code": "RJE",
        "OPEN UK Network Name": "North West Children and Young People's Epilepsy Interest Group",
        "OPEN UK Network Code": "NWEIG",
        "country": "England",
    },
    {
        "ods trust code": "RJL",
        "OPEN UK Network Name": "Trent Epilepsy Network",
        "OPEN UK Network Code": "TEN",
        "country": "England",
    },
    {
        "ods trust code": "RJN",
        "OPEN UK Network Name": "North West Children and Young People's Epilepsy Interest Group",
        "OPEN UK Network Code": "NWEIG",
        "country": "England",
    },
    {
        "ods trust code": "RJR",
        "OPEN UK Network Name": "Mersey and North Wales network 'Epilepsy In Childhood' interest group",
        "OPEN UK Network Code": "EPIC",
        "country": "England",
    },
    {
        "ods trust code": "RJZ",
        "OPEN UK Network Name": "South East Thames Paediatric Epilepsy Group",
        "OPEN UK Network Code": "SETPEG",
        "country": "England",
    },
    {
        "ods trust code": "RK5",
        "OPEN UK Network Name": "Children's Epilepsy Workstream in Trent",
        "OPEN UK Network Code": "CEWT",
        "country": "England",
    },
    {
        "ods trust code": "RK9",
        "OPEN UK Network Name": "South West Interest Group Paediatric Epilepsy",
        "OPEN UK Network Code": "SWIPE",
        "country": "England",
    },
    {
        "ods trust code": "RKB",
        "OPEN UK Network Name": "Birmingham Regional Paediatric Neurology Forum",
        "OPEN UK Network Code": "BRPNF",
        "country": "England",
    },
    {
        "ods trust code": "RKE",
        "OPEN UK Network Name": "North Thames Paediatric Epilepsy Network",
        "OPEN UK Network Code": "NTPEN",
        "country": "England",
    },
    {
        "ods trust code": "RL4",
        "OPEN UK Network Name": "Birmingham Regional Paediatric Neurology Forum",
        "OPEN UK Network Code": "BRPNF",
        "country": "England",
    },
    # {
    #     "ods trust code": "RLN1",
    #     "OPEN UK Network Name": "Paediatric Epilepsy Network for the North East and Cumbria",
    #     "OPEN UK Network Code": "PENNEC",
    #     "country": "England",
    # },
    {
        "ods trust code": "RLQ",
        "OPEN UK Network Name": "Birmingham Regional Paediatric Neurology Forum",
        "OPEN UK Network Code": "BRPNF",
        "country": "England",
    },
    {
        "ods trust code": "RLT",
        "OPEN UK Network Name": "Birmingham Regional Paediatric Neurology Forum",
        "OPEN UK Network Code": "BRPNF",
        "country": "England",
    },
    {
        "ods trust code": "RM1",
        "OPEN UK Network Name": "Eastern Paediatric Epilepsy Network",
        "OPEN UK Network Code": "EPEN",
        "country": "England",
    },
    {
        "ods trust code": "RMC",
        "OPEN UK Network Name": "North West Children and Young People's Epilepsy Interest Group",
        "OPEN UK Network Code": "NWEIG",
        "country": "England",
    },
    {
        "ods trust code": "RMP",
        "OPEN UK Network Name": "North West Children and Young People's Epilepsy Interest Group",
        "OPEN UK Network Code": "NWEIG",
        "country": "England",
    },
    {
        "ods trust code": "RN3",
        "OPEN UK Network Name": "Oxford region epilepsy interest group",
        "OPEN UK Network Code": "ORENG",
        "country": "England",
    },
    {
        "ods trust code": "RN5",
        "OPEN UK Network Name": "Wessex Paediatric Neurosciences Network",
        "OPEN UK Network Code": "WPNN",
        "country": "England",
    },
    {  # Added by Simon
        "ods trust code": "RN3",
        "OPEN UK Network Name": "Wessex Paediatric Neurosciences Network",
        "OPEN UK Network Code": "WPNN",
        "country": "England",
    },
    {  # Added by Simon
        "ods trust code": "RW1",
        "OPEN UK Network Name": "Wessex Paediatric Neurosciences Network",
        "OPEN UK Network Code": "WPNN",
        "country": "England",
    },
    {
        "ods trust code": "RN7",
        "OPEN UK Network Name": "South East Thames Paediatric Epilepsy Group",
        "OPEN UK Network Code": "SETPEG",
        "country": "England",
    },
    {
        "ods trust code": "RNA",
        "OPEN UK Network Name": "Birmingham Regional Paediatric Neurology Forum",
        "OPEN UK Network Code": "BRPNF",
        "country": "England",
    },
    {
        "ods trust code": "RNL",
        "OPEN UK Network Name": "Paediatric Epilepsy Network for the North East and Cumbria",
        "OPEN UK Network Code": "PENNEC",
        "country": "England",
    },
    {
        "ods trust code": "RNQ",
        "OPEN UK Network Name": "Oxford region epilepsy interest group",
        "OPEN UK Network Code": "ORENG",
        "country": "England",
    },
    {
        "ods trust code": "RP1",
        "OPEN UK Network Name": "Oxford region epilepsy interest group",
        "OPEN UK Network Code": "ORENG",
        "country": "England",
    },
    {
        "ods trust code": "RNS",
        "OPEN UK Network Name": "Oxford region epilepsy interest group",
        "OPEN UK Network Code": "ORENG",
        "country": "England",
    },
    {
        "ods trust code": "RNZ",
        "OPEN UK Network Name": "Wessex Paediatric Neurosciences Network",
        "OPEN UK Network Code": "WPNN",
        "country": "England",
    },
    {
        "ods trust code": "RP4",
        "OPEN UK Network Name": "North Thames Paediatric Epilepsy Network",
        "OPEN UK Network Code": "NTPEN",
        "country": "England",
    },
    {
        "ods trust code": "RP5",
        "OPEN UK Network Name": "Trent Epilepsy Network",
        "OPEN UK Network Code": "TEN",
        "country": "England",
    },
    {
        "ods trust code": "RPA",
        "OPEN UK Network Name": "South East Thames Paediatric Epilepsy Group",
        "OPEN UK Network Code": "SETPEG",
        "country": "England",
    },
    {
        "ods trust code": "RQ3",
        "OPEN UK Network Name": "Birmingham Regional Paediatric Neurology Forum",
        "OPEN UK Network Code": "BRPNF",
        "country": "England",
    },
    {  # Added by Simon
        "ods trust code": "RRK",
        "OPEN UK Network Name": "Birmingham Regional Paediatric Neurology Forum",
        "OPEN UK Network Code": "BRPNF",
        "country": "England",
    },
    {
        "ods trust code": "RXW",
        "OPEN UK Network Name": "Mersey and North Wales network 'Epilepsy In Childhood' interest group",
        "OPEN UK Network Code": "EPIC",
        "country": "England",
    },
    {
        "ods trust code": "RQ8",
        "OPEN UK Network Name": "Eastern Paediatric Epilepsy Network",
        "OPEN UK Network Code": "EPEN",
        "country": "England",
    },
    {
        "ods trust code": "RQM",
        "OPEN UK Network Name": "North Thames Paediatric Epilepsy Network",
        "OPEN UK Network Code": "NTPEN",
        "country": "England",
    },
    {  # Added by Simon
        "ods trust code": "RY9",
        "OPEN UK Network Name": "North Thames Paediatric Epilepsy Network",
        "OPEN UK Network Code": "NTPEN",
        "country": "England",
    },
    {
        "ods trust code": "RQW",
        "OPEN UK Network Name": "Eastern Paediatric Epilepsy Network",
        "OPEN UK Network Code": "EPEN",
        "country": "England",
    },
    {
        "ods trust code": "RQX",
        "OPEN UK Network Name": "North Thames Paediatric Epilepsy Network",
        "OPEN UK Network Code": "NTPEN",
        "country": "England",
    },
    {
        "ods trust code": "RR1",
        "OPEN UK Network Name": "Birmingham Regional Paediatric Neurology Forum",
        "OPEN UK Network Code": "BRPNF",
        "country": "England",
    },
    {
        "ods trust code": "RR7",
        "OPEN UK Network Name": "Paediatric Epilepsy Network for the North East and Cumbria",
        "OPEN UK Network Code": "PENNEC",
        "country": "England",
    },
    {
        "ods trust code": "RR8",
        "OPEN UK Network Name": "Yorkshire Paediatric Neurology Network",
        "OPEN UK Network Code": "YPEN",
        "country": "England",
    },
    {
        "ods trust code": "RRF",
        "OPEN UK Network Name": "North West Children and Young People's Epilepsy Interest Group",
        "OPEN UK Network Code": "NWEIG",
        "country": "England",
    },
    {
        "ods trust code": "RRV",
        "OPEN UK Network Name": "North Thames Paediatric Epilepsy Network",
        "OPEN UK Network Code": "NTPEN",
        "country": "England",
    },
    {
        "ods trust code": "RT5",
        "OPEN UK Network Name": "Children's Epilepsy Workstream in Trent",
        "OPEN UK Network Code": "CEWT",
        "country": "England",
    },
    {
        "ods trust code": "RTD",
        "OPEN UK Network Name": "Paediatric Epilepsy Network for the North East and Cumbria",
        "OPEN UK Network Code": "PENNEC",
        "country": "England",
    },
    {  # Added by Simon
        "ods trust code": "R0B",
        "OPEN UK Network Name": "Paediatric Epilepsy Network for the North East and Cumbria",
        "OPEN UK Network Code": "PENNEC",
        "country": "England",
    },
    {
        "ods trust code": "RTE",
        "OPEN UK Network Name": "South West Interest Group Paediatric Epilepsy",
        "OPEN UK Network Code": "SWIPE",
        "country": "England",
    },
    {
        "ods trust code": "RTF",
        "OPEN UK Network Name": "Paediatric Epilepsy Network for the North East and Cumbria",
        "OPEN UK Network Code": "PENNEC",
        "country": "England",
    },
    # {
    #     "ods trust code": "RTG1",
    #     "OPEN UK Network Name": "Children's Epilepsy Workstream in Trent",
    #     "OPEN UK Network Code": "CEWT",
    #     "country": "England",
    # },
    {  # added by Simon
        "ods trust code": "RTG",
        "OPEN UK Network Name": "Children's Epilepsy Workstream in Trent",
        "OPEN UK Network Code": "CEWT",
        "country": "England",
    },
    {  # added by Simon
        "ods trust code": "RY8",
        "OPEN UK Network Name": "Children's Epilepsy Workstream in Trent",
        "OPEN UK Network Code": "CEWT",
        "country": "England",
    },
    {
        "ods trust code": "RTH",
        "OPEN UK Network Name": "Oxford region epilepsy interest group",
        "OPEN UK Network Code": "ORENG",
        "country": "England",
    },
    {
        "ods trust code": "RTK",
        "OPEN UK Network Name": "South West Thames Paediatric Epilepsy Group",
        "OPEN UK Network Code": "SWTPEG",
        "country": "England",
    },
    {
        "ods trust code": "RTP",
        "OPEN UK Network Name": "South West Thames Paediatric Epilepsy Group",
        "OPEN UK Network Code": "SWTPEG",
        "country": "England",
    },
    {
        "ods trust code": "RTR",
        "OPEN UK Network Name": "Paediatric Epilepsy Network for the North East and Cumbria",
        "OPEN UK Network Code": "PENNEC",
        "country": "England",
    },
    {  # Added by Simon
        "ods trust code": "RXP",
        "OPEN UK Network Name": "Paediatric Epilepsy Network for the North East and Cumbria",
        "OPEN UK Network Code": "PENNEC",
        "country": "England",
    },
    {
        "ods trust code": "RTX",
        "OPEN UK Network Name": "North West Children and Young People's Epilepsy Interest Group",
        "OPEN UK Network Code": "NWEIG",
        "country": "England",
    },
    {  # added by Simon
        "ods trust code": "RNN",
        "OPEN UK Network Name": "North West Children and Young People's Epilepsy Interest Group",
        "OPEN UK Network Code": "NWEIG",
        "country": "England",
    },
    {
        "ods trust code": "RV3",
        "OPEN UK Network Name": "North Thames Paediatric Epilepsy Network",
        "OPEN UK Network Code": "NTPEN",
        "country": "England",
    },
    {
        "ods trust code": "RVR",
        "OPEN UK Network Name": "South West Thames Paediatric Epilepsy Group",
        "OPEN UK Network Code": "SWTPEG",
        "country": "England",
    },
    {
        "ods trust code": "RVV",
        "OPEN UK Network Name": "South East Thames Paediatric Epilepsy Group",
        "OPEN UK Network Code": "SETPEG",
        "country": "England",
    },
    {
        "ods trust code": "RVW",
        "OPEN UK Network Name": "Paediatric Epilepsy Network for the North East and Cumbria",
        "OPEN UK Network Code": "PENNEC",
        "country": "England",
    },
    {
        "ods trust code": "RVY",
        "OPEN UK Network Name": "Mersey and North Wales network 'Epilepsy In Childhood' interest group",
        "OPEN UK Network Code": "EPIC",
        "country": "England",
    },
    # {
    #     "ods trust code": "RW61",
    #     "OPEN UK Network Name": "North West Children and Young People's Epilepsy Interest Group",
    #     "OPEN UK Network Code": "NWEIG",
    #     "country": "England",
    # },
    {
        "ods trust code": "RWA",
        "OPEN UK Network Name": "Yorkshire Paediatric Neurology Network",
        "OPEN UK Network Code": "YPEN",
        "country": "England",
    },
    {
        "ods trust code": "RWD",
        "OPEN UK Network Name": "Children's Epilepsy Workstream in Trent",
        "OPEN UK Network Code": "CEWT",
        "country": "England",
    },
    {
        "ods trust code": "RWE",
        "OPEN UK Network Name": "Children's Epilepsy Workstream in Trent",
        "OPEN UK Network Code": "CEWT",
        "country": "England",
    },
    {
        "ods trust code": "RWF",
        "OPEN UK Network Name": "South East Thames Paediatric Epilepsy Group",
        "OPEN UK Network Code": "SETPEG",
        "country": "England",
    },
    {
        "ods trust code": "RWG",
        "OPEN UK Network Name": "North Thames Paediatric Epilepsy Network",
        "OPEN UK Network Code": "NTPEN",
        "country": "England",
    },
    {
        "ods trust code": "RWH",
        "OPEN UK Network Name": "Eastern Paediatric Epilepsy Network",
        "OPEN UK Network Code": "EPEN",
        "country": "England",
    },
    {
        "ods trust code": "RWJ",
        "OPEN UK Network Name": "North West Children and Young People's Epilepsy Interest Group",
        "OPEN UK Network Code": "NWEIG",
        "country": "England",
    },
    {
        "ods trust code": "RWP",
        "OPEN UK Network Name": "Birmingham Regional Paediatric Neurology Forum",
        "OPEN UK Network Code": "BRPNF",
        "country": "England",
    },
    {
        "ods trust code": "RWW",
        "OPEN UK Network Name": "Mersey and North Wales network 'Epilepsy In Childhood' interest group",
        "OPEN UK Network Code": "EPIC",
        "country": "England",
    },
    {
        "ods trust code": "RWY",
        "OPEN UK Network Name": "Yorkshire Paediatric Neurology Network",
        "OPEN UK Network Code": "YPEN",
        "country": "England",
    },
    {
        "ods trust code": "RX1",
        "OPEN UK Network Name": "Children's Epilepsy Workstream in Trent",
        "OPEN UK Network Code": "CEWT",
        "country": "England",
    },
    {
        "ods trust code": "RXC",
        "OPEN UK Network Name": "South East Thames Paediatric Epilepsy Group",
        "OPEN UK Network Code": "SETPEG",
        "country": "England",
    },
    {
        "ods trust code": "RXF",
        "OPEN UK Network Name": "Yorkshire Paediatric Neurology Network",
        "OPEN UK Network Code": "YPEN",
        "country": "England",
    },
    {
        "ods trust code": "RXH",
        "OPEN UK Network Name": "South East Thames Paediatric Epilepsy Group",
        "OPEN UK Network Code": "SETPEG",
        "country": "England",
    },
    {
        "ods trust code": "RXK",
        "OPEN UK Network Name": "Birmingham Regional Paediatric Neurology Forum",
        "OPEN UK Network Code": "BRPNF",
        "country": "England",
    },
    {
        "ods trust code": "RXL",
        "OPEN UK Network Name": "North West Children and Young People's Epilepsy Interest Group",
        "OPEN UK Network Code": "NWEIG",
        "country": "England",
    },
    {
        "ods trust code": "RXN",
        "OPEN UK Network Name": "North West Children and Young People's Epilepsy Interest Group",
        "OPEN UK Network Code": "NWEIG",
        "country": "England",
    },
    {
        "ods trust code": "RXP",
        "OPEN UK Network Name": "Paediatric Epilepsy Network for the North East and Cumbria",
        "OPEN UK Network Code": "PENNEC",
        "country": "England",
    },
    {
        "ods trust code": "RXQ",
        "OPEN UK Network Name": "Oxford region epilepsy interest group",
        "OPEN UK Network Code": "ORENG",
        "country": "England",
    },
    {
        "ods trust code": "RXR",
        "OPEN UK Network Name": "North West Children and Young People's Epilepsy Interest Group",
        "OPEN UK Network Code": "NWEIG",
        "country": "England",
    },
    {
        "ods trust code": "RY3",
        "OPEN UK Network Name": "Eastern Paediatric Epilepsy Network",
        "OPEN UK Network Code": "EPEN",
        "country": "England",
    },
    {
        "ods trust code": "RY6",
        "OPEN UK Network Name": "Yorkshire Paediatric Neurology Network",
        "OPEN UK Network Code": "YPEN",
        "country": "England",
    },
    {
        "ods trust code": "RYG",
        "OPEN UK Network Name": "Birmingham Regional Paediatric Neurology Forum",
        "OPEN UK Network Code": "BRPNF",
        "country": "England",
    },
    {
        "ods trust code": "RYJ",
        "OPEN UK Network Name": "North Thames Paediatric Epilepsy Network",
        "OPEN UK Network Code": "NTPEN",
        "country": "England",
    },
    {
        "ods trust code": "RYR",
        "OPEN UK Network Name": "Wessex Paediatric Neurosciences Network",
        "OPEN UK Network Code": "WPNN",
        "country": "England",
    },
    {
        "ods trust code": "RYW",
        "OPEN UK Network Name": "Birmingham Regional Paediatric Neurology Forum",
        "OPEN UK Network Code": "BRPNF",
        "country": "England",
    },
]
