UNKNOWN_POSTCODES = ['ZZ99 3CZ', 'ZZ99 3GZ', 'ZZ99 3WZ', 'ZZ99 3VZ']

# DUMMY_POSTCODES = [
#     {
#         "postcode": "NR7 0FD",
#         "quality": 1,
#         "eastings": 628184,
#         "northings": 309688,
#         "country": "England",
#         "nhs_ha": "East of England",
#         "longitude": 1.37089,
#         "latitude": 52.636928,
#         "european_electoral_region": "Eastern",
#         "primary_care_trust": "Norfolk",
#         "region": "East of England",
#         "lsoa": "Broadland 016C",
#         "msoa": "Broadland 016",
#         "incode": "0FD",
#         "outcode": "NR7",
#         "parliamentary_constituency": "Norwich North",
#         "admin_district": "Broadland",
#         "parish": "Thorpe St. Andrew",
#         "admin_county": "Norfolk",
#         "admin_ward": "Thorpe St Andrew South East",
#         "ced": "Thorpe St. Andrew",
#         "ccg": "NHS Norfolk and Waveney",
#         "nuts": "Norwich and East Norfolk",
#         "codes": {
#             "admin_district": "E07000144",
#             "admin_county": "E10000020",
#             "admin_ward": "E05005782",
#             "parish": "E04006256",
#             "parliamentary_constituency": "E14000863",
#             "ccg": "E38000239",
#             "ccg_id": "26A",
#             "ced": "E58001026",
#             "nuts": "TLH15",
#             "lsoa": "E01026576",
#             "msoa": "E02005535",
#             "lau2": "E07000144"
#         }
#     },
#     {
#         "postcode": "PR2 8NR",
#         "quality": 1,
#         "eastings": 353510,
#         "northings": 431459,
#         "country": "England",
#         "nhs_ha": "North West",
#         "longitude": -2.706941,
#         "latitude": 53.777376,
#         "european_electoral_region": "North West",
#         "primary_care_trust": "Central Lancashire",
#         "region": "North West",
#         "lsoa": "Preston 006D",
#         "msoa": "Preston 006",
#         "incode": "8NR",
#         "outcode": "PR2",
#         "parliamentary_constituency": "Wyre and Preston North",
#         "admin_district": "Preston",
#         "parish": "Preston, unparished area",
#         "admin_county": "Lancashire",
#         "admin_ward": "Garrison",
#         "ced": "Preston Central East",
#         "ccg": "NHS Greater Preston",
#         "nuts": "Mid Lancashire",
#         "codes": {
#             "admin_district": "E07000123",
#             "admin_county": "E10000017",
#             "admin_ward": "E05012199",
#             "parish": "E43000225",
#             "parliamentary_constituency": "E14001057",
#             "ccg": "E38000227",
#             "ccg_id": "01E",
#             "ced": "E58000804",
#             "nuts": "TLD45",
#             "lsoa": "E01025243",
#             "msoa": "E02005258",
#             "lau2": "E07000123"
#         }
#     },
#     {
#         "postcode": "DE55 1RA",
#         "quality": 1,
#         "eastings": 442102,
#         "northings": 354021,
#         "country": "England",
#         "nhs_ha": "East Midlands",
#         "longitude": -1.372925,
#         "latitude": 53.081759,
#         "european_electoral_region": "East Midlands",
#         "primary_care_trust": "Derbyshire County",
#         "region": "East Midlands",
#         "lsoa": "Amber Valley 003E",
#         "msoa": "Amber Valley 003",
#         "incode": "1RA",
#         "outcode": "DE55",
#         "parliamentary_constituency": "Amber Valley",
#         "admin_district": "Amber Valley",
#         "parish": "Somercotes",
#         "admin_county": "Derbyshire",
#         "admin_ward": "Somercotes",
#         "ced": "Alfreton and Somercotes",
#         "ccg": "NHS Derby and Derbyshire",
#         "nuts": "South and West Derbyshire",
#         "codes": {
#             "admin_district": "E07000032",
#             "admin_county": "E10000007",
#             "admin_ward": "E05003299",
#             "parish": "E04002692",
#             "parliamentary_constituency": "E14000533",
#             "ccg": "E38000229",
#             "ccg_id": "15M",
#             "ced": "E58000193",
#             "nuts": "TLF13",
#             "lsoa": "E01019471",
#             "msoa": "E02004031",
#             "lau2": "E07000032"
#         }
#     },
#     {
#         "postcode": "DD4 9JG",
#         "quality": 1,
#         "eastings": 342765,
#         "northings": 733294,
#         "country": "Scotland",
#         "nhs_ha": "Tayside",
#         "longitude": -2.931043,
#         "latitude": 56.488247,
#         "european_electoral_region": "Scotland",
#         "primary_care_trust": "Dundee Community Health Partnership",
#         "region": null,
#         "lsoa": "Whitfield - 04",
#         "msoa": "Whitfield",
#         "incode": "9JG",
#         "outcode": "DD4",
#         "parliamentary_constituency": "Dundee East",
#         "admin_district": "Dundee City",
#         "parish": null,
#         "admin_county": null,
#         "admin_ward": "North East",
#         "ced": null,
#         "ccg": "Dundee Community Health Partnership",
#         "nuts": "Angus and Dundee City",
#         "codes": {
#             "admin_district": "S12000042",
#             "admin_county": "S99999999",
#             "admin_ward": "S13002830",
#             "parish": "S99999999",
#             "parliamentary_constituency": "S14000015",
#             "ccg": "S03000039",
#             "ccg_id": "039",
#             "ced": "S99999999",
#             "nuts": "TLM71",
#             "lsoa": "S01007785",
#             "msoa": "S02001462",
#             "lau2": "S30000049"
#         }
#     },
#     {
#         "postcode": "TW7 4PS",
#         "quality": 1,
#         "eastings": 515157,
#         "northings": 177199,
#         "country": "England",
#         "nhs_ha": "London",
#         "longitude": -0.343022,
#         "latitude": 51.482033,
#         "european_electoral_region": "London",
#         "primary_care_trust": "Hounslow",
#         "region": "London",
#         "lsoa": "Hounslow 009D",
#         "msoa": "Hounslow 009",
#         "incode": "4PS",
#         "outcode": "TW7",
#         "parliamentary_constituency": "Brentford and Isleworth",
#         "admin_district": "Hounslow",
#         "parish": "Hounslow, unparished area",
#         "admin_county": null,
#         "admin_ward": "Osterley and Spring Grove",
#         "ced": null,
#         "ccg": "NHS North West London",
#         "nuts": "Hounslow and Richmond upon Thames",
#         "codes": {
#             "admin_district": "E09000018",
#             "admin_county": "E99999999",
#             "admin_ward": "E05000363",
#             "parish": "E43000208",
#             "parliamentary_constituency": "E14000593",
#             "ccg": "E38000256",
#             "ccg_id": "W2U3Z",
#             "ced": "E99999999",
#             "nuts": "TLI75",
#             "lsoa": "E01002680",
#             "msoa": "E02000534",
#             "lau2": "E09000018"
#         }
#     },
#     {
#         "postcode": "SR1 1DP",
#         "quality": 1,
#         "eastings": 439835,
#         "northings": 557088,
#         "country": "England",
#         "nhs_ha": "North East",
#         "longitude": -1.380266,
#         "latitude": 54.906935,
#         "european_electoral_region": "North East",
#         "primary_care_trust": "Sunderland Teaching",
#         "region": "North East",
#         "lsoa": "Sunderland 013B",
#         "msoa": "Sunderland 013",
#         "incode": "1DP",
#         "outcode": "SR1",
#         "parliamentary_constituency": "Sunderland Central",
#         "admin_district": "Sunderland",
#         "parish": "Sunderland, unparished area",
#         "admin_county": null,
#         "admin_ward": "Hendon",
#         "ced": null,
#         "ccg": "NHS Sunderland",
#         "nuts": "Sunderland",
#         "codes": {
#             "admin_district": "E08000024",
#             "admin_county": "E99999999",
#             "admin_ward": "E05001158",
#             "parish": "E43000178",
#             "parliamentary_constituency": "E14000982",
#             "ccg": "E38000176",
#             "ccg_id": "00P",
#             "ced": "E99999999",
#             "nuts": "TLC23",
#             "lsoa": "E01008703",
#             "msoa": "E02001803",
#             "lau2": "E08000024"
#         }
#     },
#     {
#         "postcode": "AB24 2SU",
#         "quality": 1,
#         "eastings": 393406,
#         "northings": 808454,
#         "country": "Scotland",
#         "nhs_ha": "Grampian",
#         "longitude": -2.110675,
#         "latitude": 57.166871,
#         "european_electoral_region": "Scotland",
#         "primary_care_trust": "Aberdeen City Community Health Partnership",
#         "region": null,
#         "lsoa": "Tillydrone - 03",
#         "msoa": "Tillydrone",
#         "incode": "2SU",
#         "outcode": "AB24",
#         "parliamentary_constituency": "Aberdeen North",
#         "admin_district": "Aberdeen City",
#         "parish": null,
#         "admin_county": null,
#         "admin_ward": "Tillydrone/Seaton/Old Aberdeen",
#         "ced": null,
#         "ccg": "Aberdeen City Community Health Partnership",
#         "nuts": "Aberdeen City and Aberdeenshire",
#         "codes": {
#             "admin_district": "S12000033",
#             "admin_county": "S99999999",
#             "admin_ward": "S13002840",
#             "parish": "S99999999",
#             "parliamentary_constituency": "S14000001",
#             "ccg": "S03000012",
#             "ccg_id": "012",
#             "ced": "S99999999",
#             "nuts": "TLM50",
#             "lsoa": "S01006677",
#             "msoa": "S02001266",
#             "lau2": "S30000026"
#         }
#     },
#     {
#         "postcode": "BD23 5QS",
#         "quality": 1,
#         "eastings": 397838,
#         "northings": 464970,
#         "country": "England",
#         "nhs_ha": "Yorkshire and the Humber",
#         "longitude": -2.034539,
#         "latitude": 54.080645,
#         "european_electoral_region": "Yorkshire and The Humber",
#         "primary_care_trust": "North Yorkshire and York",
#         "region": "Yorkshire and The Humber",
#         "lsoa": "Craven 002C",
#         "msoa": "Craven 002",
#         "incode": "5QS",
#         "outcode": "BD23",
#         "parliamentary_constituency": "Skipton and Ripon",
#         "admin_district": "Craven",
#         "parish": "Threshfield",
#         "admin_county": "North Yorkshire",
#         "admin_ward": "Upper Wharfedale",
#         "ced": "Mid Craven",
#         "ccg": "NHS Bradford District and Craven",
#         "nuts": "North Yorkshire CC",
#         "codes": {
#             "admin_district": "E07000163",
#             "admin_county": "E10000023",
#             "admin_ward": "E05006206",
#             "parish": "E04007125",
#             "parliamentary_constituency": "E14000928",
#             "ccg": "E38000232",
#             "ccg_id": "36J",
#             "ced": "E58001069",
#             "nuts": "TLE22",
#             "lsoa": "E01027585",
#             "msoa": "E02005743",
#             "lau2": "E07000163"
#         }
#     },
#     {
#         "postcode": "BA7 7JR",
#         "quality": 1,
#         "eastings": 363651,
#         "northings": 133244,
#         "country": "England",
#         "nhs_ha": "South West",
#         "longitude": -2.520467,
#         "latitude": 51.097342,
#         "european_electoral_region": "South West",
#         "primary_care_trust": "Somerset",
#         "region": "South West",
#         "lsoa": "South Somerset 002C",
#         "msoa": "South Somerset 002",
#         "incode": "7JR",
#         "outcode": "BA7",
#         "parliamentary_constituency": "Somerton and Frome",
#         "admin_district": "South Somerset",
#         "parish": "Ansford",
#         "admin_county": "Somerset",
#         "admin_ward": "Cary",
#         "ced": "Castle Cary",
#         "ccg": "NHS Somerset",
#         "nuts": "Somerset CC",
#         "codes": {
#             "admin_district": "E07000189",
#             "admin_county": "E10000027",
#             "admin_ward": "E05012519",
#             "parish": "E04008659",
#             "parliamentary_constituency": "E14000932",
#             "ccg": "E38000150",
#             "ccg_id": "11X",
#             "ced": "E58001294",
#             "nuts": "TLK23",
#             "lsoa": "E01029168",
#             "msoa": "E02006076",
#             "lau2": "E07000189"
#         }
#     },
#     {
#         "postcode": "PR2 1TJ",
#         "quality": 1,
#         "eastings": 349841,
#         "northings": 431145,
#         "country": "England",
#         "nhs_ha": "North West",
#         "longitude": -2.762559,
#         "latitude": 53.774213,
#         "european_electoral_region": "North West",
#         "primary_care_trust": "Central Lancashire",
#         "region": "North West",
#         "lsoa": "Preston 013C",
#         "msoa": "Preston 013",
#         "incode": "1TJ",
#         "outcode": "PR2",
#         "parliamentary_constituency": "Preston",
#         "admin_district": "Preston",
#         "parish": "Preston, unparished area",
#         "admin_county": "Lancashire",
#         "admin_ward": "Lea & Larches",
#         "ced": "Preston South West",
#         "ccg": "NHS Greater Preston",
#         "nuts": "Mid Lancashire",
#         "codes": {
#             "admin_district": "E07000123",
#             "admin_county": "E10000017",
#             "admin_ward": "E05012202",
#             "parish": "E43000225",
#             "parliamentary_constituency": "E14000885",
#             "ccg": "E38000227",
#             "ccg_id": "01E",
#             "ced": "E58000811",
#             "nuts": "TLD45",
#             "lsoa": "E01025265",
#             "msoa": "E02005265",
#             "lau2": "E07000123"
#         }
#     },
#     {
#         "postcode": "NR13 5GF",
#         "quality": 1,
#         "eastings": 630852,
#         "northings": 310828,
#         "country": "England",
#         "nhs_ha": "East of England",
#         "longitude": 1.411064,
#         "latitude": 52.646057,
#         "european_electoral_region": "Eastern",
#         "primary_care_trust": "Norfolk",
#         "region": "East of England",
#         "lsoa": "Broadland 008A",
#         "msoa": "Broadland 008",
#         "incode": "5GF",
#         "outcode": "NR13",
#         "parliamentary_constituency": "Broadland",
#         "admin_district": "Broadland",
#         "parish": "Great and Little Plumstead",
#         "admin_county": "Norfolk",
#         "admin_ward": "Plumstead",
#         "ced": "Thorpe St. Andrew",
#         "ccg": "NHS Norfolk and Waveney",
#         "nuts": "Norwich and East Norfolk",
#         "codes": {
#             "admin_district": "E07000144",
#             "admin_county": "E10000020",
#             "admin_ward": "E05005774",
#             "parish": "E04006221",
#             "parliamentary_constituency": "E14000603",
#             "ccg": "E38000239",
#             "ccg_id": "26A",
#             "ced": "E58001026",
#             "nuts": "TLH15",
#             "lsoa": "E01026545",
#             "msoa": "E02005527",
#             "lau2": "E07000144"
#         }
#     },
#     {
#         "postcode": "AL6 0SF",
#         "quality": 1,
#         "eastings": 525241,
#         "northings": 217541,
#         "country": "England",
#         "nhs_ha": "East of England",
#         "longitude": -0.183411,
#         "latitude": 51.842441,
#         "european_electoral_region": "Eastern",
#         "primary_care_trust": "Hertfordshire",
#         "region": "East of England",
#         "lsoa": "Welwyn Hatfield 001A",
#         "msoa": "Welwyn Hatfield 001",
#         "incode": "0SF",
#         "outcode": "AL6",
#         "parliamentary_constituency": "Welwyn Hatfield",
#         "admin_district": "Welwyn Hatfield",
#         "parish": "Welwyn",
#         "admin_county": "Hertfordshire",
#         "admin_ward": "Welwyn East",
#         "ced": "Welwyn",
#         "ccg": "NHS East and North Hertfordshire",
#         "nuts": "Hertfordshire CC",
#         "codes": {
#             "admin_district": "E07000241",
#             "admin_county": "E10000015",
#             "admin_ward": "E05011072",
#             "parish": "E04004822",
#             "parliamentary_constituency": "E14001027",
#             "ccg": "E38000049",
#             "ccg_id": "06K",
#             "ced": "E58000675",
#             "nuts": "TLH23",
#             "lsoa": "E01023965",
#             "msoa": "E02004980",
#             "lau2": "E07000241"
#         }
#     },
#     {
#         "postcode": "SE22 9DJ",
#         "quality": 1,
#         "eastings": 533870,
#         "northings": 174799,
#         "country": "England",
#         "nhs_ha": "London",
#         "longitude": -0.074598,
#         "latitude": 51.45635,
#         "european_electoral_region": "London",
#         "primary_care_trust": "Southwark",
#         "region": "London",
#         "lsoa": "Southwark 030B",
#         "msoa": "Southwark 030",
#         "incode": "9DJ",
#         "outcode": "SE22",
#         "parliamentary_constituency": "Dulwich and West Norwood",
#         "admin_district": "Southwark",
#         "parish": "Southwark, unparished area",
#         "admin_county": null,
#         "admin_ward": "Goose Green",
#         "ced": null,
#         "ccg": "NHS South East London",
#         "nuts": "Lewisham and Southwark",
#         "codes": {
#             "admin_district": "E09000028",
#             "admin_county": "E99999999",
#             "admin_ward": "E05011103",
#             "parish": "E43000218",
#             "parliamentary_constituency": "E14000673",
#             "ccg": "E38000244",
#             "ccg_id": "72Q",
#             "ced": "E99999999",
#             "nuts": "TLI44",
#             "lsoa": "E01003954",
#             "msoa": "E02000836",
#             "lau2": "E09000028"
#         }
#     },
#     {
#         "postcode": "GL20 7JN",
#         "quality": 1,
#         "eastings": 394808,
#         "northings": 237717,
#         "country": "England",
#         "nhs_ha": "West Midlands",
#         "longitude": -2.077103,
#         "latitude": 52.03783,
#         "european_electoral_region": "West Midlands",
#         "primary_care_trust": "Worcestershire",
#         "region": "West Midlands",
#         "lsoa": "Wychavon 019E",
#         "msoa": "Wychavon 019",
#         "incode": "7JN",
#         "outcode": "GL20",
#         "parliamentary_constituency": "West Worcestershire",
#         "admin_district": "Wychavon",
#         "parish": "Kemerton",
#         "admin_county": "Worcestershire",
#         "admin_ward": "South Bredon Hill",
#         "ced": "Bredon",
#         "ccg": "NHS Herefordshire and Worcestershire",
#         "nuts": "Worcestershire CC",
#         "codes": {
#             "admin_district": "E07000238",
#             "admin_county": "E10000034",
#             "admin_ward": "E05007924",
#             "parish": "E04010408",
#             "parliamentary_constituency": "E14001035",
#             "ccg": "E38000236",
#             "ccg_id": "18C",
#             "ced": "E58001676",
#             "nuts": "TLG12",
#             "lsoa": "E01032412",
#             "msoa": "E02006766",
#             "lau2": "E07000238"
#         }
#     },
# ]
