SWANSEA_BAY_UNIVERSITY_HEALTH_BOARD = [{
    "location_code": "",
    "location_name": "Cefn Coed Hospital",
    "address": "",
    "postcode": "",
    "region": "Swansea Bay University Health Board",
    "region_code": "W11000031"
},
    {
    "location_code": "",
    "location_name": "Garngoch Hospital ",
    "address": "",
    "postcode": "",
    "region": "Swansea Bay University Health Board",
    "region_code": "W11000031"
},
    {
    "location_code": "",
    "location_name": "Gellinudd Hospital",
    "address": "",
    "postcode": "",
    "region": "Swansea Bay University Health Board",
    "region_code": "W11000031"
},
    {
    "location_code": "",
    "location_name": "Glanrhyd Hospital",
    "address": "",
    "postcode": "",
    "region": "Swansea Bay University Health Board",
    "region_code": "W11000031"
},
    {
    "location_code": "",
    "location_name": "Gorseinon Hospital",
    "address": "",
    "postcode": "",
    "region": "Swansea Bay University Health Board",
    "region_code": "W11000031"
},
    {
    "location_code": "",
    "location_name": "Hill House Hospital",
    "address": "",
    "postcode": "",
    "region": "Swansea Bay University Health Board",
    "region_code": "W11000031"
},
    {
    "location_code": "",
    "location_name": "Morriston Hospital",
    "address": "",
    "postcode": "",
    "region": "Swansea Bay University Health Board",
    "region_code": "W11000031"
},
    {
    "location_code": "",
    "location_name": "Maesteg Community Hospital",
    "address": "",
    "postcode": "",
    "region": "Swansea Bay University Health Board",
    "region_code": "W11000031"
},
    {
    "location_code": "",
    "location_name": "Neath Port Talbot Hospital",
    "address": "",
    "postcode": "",
    "region": "Swansea Bay University Health Board",
    "region_code": "W11000031"
},
    {
    "location_code": "",
    "location_name": "Princess of Wales Hospital",
    "address": "",
    "postcode": "",
    "region": "Swansea Bay University Health Board",
    "region_code": "W11000031"
},
    {
    "location_code": "",
    "location_name": "Singleton Hospital",
    "address": "",
    "postcode": "",
    "region": "Swansea Bay University Health Board",
    "region_code": "W11000031"
},
    {
    "location_code": "",
    "location_name": "Tonna Hospital",
    "address": "",
    "postcode": "",
    "region": "Swansea Bay University Health Board",
    "region_code": "W11000031"
},
    {
    "location_code": "",
    "location_name": "Cimla Hospital",
    "address": "",
    "postcode": "",
    "region": "Swansea Bay University Health Board",
    "region_code": "W11000031"
}]

ANEURAN_BEVAN_LOCAL_HEALTH_BOARD = [
    {
        "location_name": "Chepstow Community Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Aneuran Bevan Local Health Board",
        "region_code": "W11000028"
    },
    {
        "location_name": "County Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Aneuran Bevan Local Health Board",
        "region_code": "W11000028"
    },
    {
        "location_name": "Llanfrechfa Grange Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Aneuran Bevan Local Health Board",
        "region_code": "W11000028"
    },
    {
        "location_name": "Maindiff Court Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Aneuran Bevan Local Health Board",
        "region_code": "W11000028"
    },
    {
        "location_name": "Nevill Hall Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Aneuran Bevan Local Health Board",
        "region_code": "W11000028"
    },
    {
        "location_name": "Redwood Memorial Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Aneuran Bevan Local Health Board",
        "region_code": "W11000028"
    },
    {
        "location_name": "Royal Gwent Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Aneuran Bevan Local Health Board",
        "region_code": "W11000028"
    },
    {
        "location_name": "St Cadoc's Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Aneuran Bevan Local Health Board",
        "region_code": "W11000028"
    },
    {
        "location_name": "St Woolos Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Aneuran Bevan Local Health Board",
        "region_code": "W11000028"
    },
    {
        "location_name": "Ysbyty Aneurin Bevan",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Aneuran Bevan Local Health Board",
        "region_code": "W11000028"
    },
    {
        "location_name": "Ysbyty’r Tri Chwm",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Aneuran Bevan Local Health Board",
        "region_code": "W11000028"
    },
    {
        "location_name": "Ysbyty Ystrad Fawr",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Aneuran Bevan Local Health Board",
        "region_code": "W11000028"
    },
]

BETSI_CADWALADR_UNIVERSITY_HEALTH_BOARD = [
    {
        "location_name": "Flint Community Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Deeside Community Hospital ",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Chirk Community Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Holywell Community Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Mold Community Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Penley Polish Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Wrexham Maelor Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Bryn Beryl Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Bryn y Neuadd Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Cefni Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Dolgellau Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Eryri Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Ffestiniog Memorial Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Llandudno General Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Tywyn Memorial Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Ysbyty Gwynedd",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Abergele Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Colwyn Bay Community Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Denbigh Community Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Glan Clwyd Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Ysbyty Penrhos Stanley",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Llangollen Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "North Wales Cancer Treatment Centre",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Prestatyn Community Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Royal Alexandra Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Ruthin Community Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
    {
        "location_name": "Ysbyty Alltwen",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Betsi Cadwaladr University Health Board",
        "region_code": "W11000023"
    },
]

CARDIFF_AND_VALE_HEALTH_BOARD = [
    {
        "location_name": "Cardiff Royal Infirmary",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Cardiff and Vale University Health Board",
        "region_code": "W11000029"
    },
    {
        "location_name": "Lansdowne Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Cardiff and Vale University Health Board",
        "region_code": "W11000029"
    },
    {
        "location_name": "Rookwood Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Cardiff and Vale University Health Board",
        "region_code": "W11000029"
    },
    {
        "location_name": "St David's Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Cardiff and Vale University Health Board",
        "region_code": "W11000029"
    },
    {
        "location_name": "University Dental Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Cardiff and Vale University Health Board",
        "region_code": "W11000029"
    },
    {
        "location_name": "University Hospital of Wales",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Cardiff and Vale University Health Board",
        "region_code": "W11000029"
    },
    {
        "location_name": "Whitchurch Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Cardiff and Vale University Health Board",
        "region_code": "W11000029"
    },
    {
        "location_name": "Children's Hospital for Wales",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Cardiff and Vale University Health Board",
        "region_code": "W11000029"
    },
    {
        "location_name": "Barry Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Cardiff and Vale University Health Board",
        "region_code": "W11000029"
    },
    {
        "location_name": "Llandough Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Cardiff and Vale University Health Board",
        "region_code": "W11000029"
    },
]

CWM_TAF_HEALTH_BOARD = [
    {
        "location_name": "Dewi Sant Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Cwm Taf Morgannwg University Health Board",
        "region_code": "W11000030"
    },
    {
        "location_name": "Ysbyty Cwm Rhondda",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Cwm Taf Morgannwg University Health Board",
        "region_code": "W11000030"
    },
    {
        "location_name": "Ysbyty Cwm Cynon",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Cwm Taf Morgannwg University Health Board",
        "region_code": "W11000030"
    },
    {
        "location_name": "Pontypridd & District Cottage Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Cwm Taf Morgannwg University Health Board",
        "region_code": "W11000030"
    },
    {
        "location_name": "Prince Charles Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Cwm Taf Morgannwg University Health Board",
        "region_code": "W11000030"
    },
    {
        "location_name": "Royal Glamorgan Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Cwm Taf Morgannwg University Health Board",
        "region_code": "W11000030"
    },
    {
        "location_name": "St Tydfil's General Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Cwm Taf Morgannwg University Health Board",
        "region_code": "W11000030"
    },
    {
        "location_name": "Ysbyty George Thomas",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Cwm Taf Morgannwg University Health Board",
        "region_code": "W11000030"
    },
]

HYWEL_DDA_LOCAL_HEALTH_BOARD = [
    {
        "location_name": "Amman Valley Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Hywel Dda Local Health Board",
        "region_code": "W11000025"
    },
    {
        "location_name": "Bronglais General Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Hywel Dda Local Health Board",
        "region_code": "W11000025"
    },
    {
        "location_name": "Bryntirion Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Hywel Dda Local Health Board",
        "region_code": "W11000025"
    },
    {
        "location_name": "Cardigan & District Memorial Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Hywel Dda Local Health Board",
        "region_code": "W11000025"
    },
    {
        "location_name": "Llandovery Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Hywel Dda Local Health Board",
        "region_code": "W11000025"
    },
    {
        "location_name": "Mynydd Mawr Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Hywel Dda Local Health Board",
        "region_code": "W11000025"
    },
    {
        "location_name": "Prince Phillip Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Hywel Dda Local Health Board",
        "region_code": "W11000025"
    },
    {
        "location_name": "South Pembrokeshire Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Hywel Dda Local Health Board",
        "region_code": "W11000025"
    },
    {
        "location_name": "Tenby Cottage Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Hywel Dda Local Health Board",
        "region_code": "W11000025"
    },
    {
        "location_name": "Tregaron Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Hywel Dda Local Health Board",
        "region_code": "W11000025"
    },
    {
        "location_name": "West Wales General Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Hywel Dda Local Health Board",
        "region_code": "W11000025"
    },
    {
        "location_name": "Withybush General Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Hywel Dda Local Health Board",
        "region_code": "W11000025"
    },
]

POWYS_TEACHING_LOCAL_HEALTH_BOARD = [
    {
        "location_name": "Brecon War Memorial Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Powys Teaching Local Health Board",
        "region_code": "W11000024"
    },
    {
        "location_name": "Bro Ddyfi Community Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Powys Teaching Local Health Board",
        "region_code": "W11000024"
    },
    {
        "location_name": "Bronllys Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Powys Teaching Local Health Board",
        "region_code": "W11000024"
    },
    {
        "location_name": "Builth Wells Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Powys Teaching Local Health Board",
        "region_code": "W11000024"
    },
    {
        "location_name": "Knighton Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Powys Teaching Local Health Board",
        "region_code": "W11000024"
    },
    {
        "location_name": "Llandrindod Wells County War Memorial Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Powys Teaching Local Health Board",
        "region_code": "W11000024"
    },
    {
        "location_name": "Llanidloes Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Powys Teaching Local Health Board",
        "region_code": "W11000024"
    },
    {
        "location_name": "Montgomery County Infirmary",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Powys Teaching Local Health Board",
        "region_code": "W11000024"
    },
    {
        "location_name": "Victoria Memorial Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Powys Teaching Local Health Board",
        "region_code": "W11000024"
    },
    {
        "location_name": "Ystradgynlais Community Hospital",
        "location_code": "",
        "address": "",
        "postcode": "",
        "region": "Powys Teaching Local Health Board",
        "region_code": "W11000024"
    },
]

# VELINDRE_NHS_TRUST = [
#     {
#         "location_name": "Velindre Hospital",
#         "location_code": "",
#         "address": "",
#         "postcode": "",
#         "region": "Velindre NHS Trust"
#     }
# ]

WALES_HOSPITALS = SWANSEA_BAY_UNIVERSITY_HEALTH_BOARD + ANEURAN_BEVAN_LOCAL_HEALTH_BOARD + BETSI_CADWALADR_UNIVERSITY_HEALTH_BOARD + \
    CARDIFF_AND_VALE_HEALTH_BOARD + CWM_TAF_HEALTH_BOARD + \
    HYWEL_DDA_LOCAL_HEALTH_BOARD + POWYS_TEACHING_LOCAL_HEALTH_BOARD

WELSH_HOSPITALS = [
    {
        "Address1": "Waunarlwydd Road",
        "Address2": "Cockett",
        "Address3": None,
        "City": "Swansea",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "West Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A3FJ",
        "OrganisationID": None,
        "OrganisationName": "Cefn Coed Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Swansea Bay University Health Board",
        "ParentONSCode": "W11000031",
        "ParentODSCode": "7A3",
        "Phone": None,
        "Postcode": "SA2 0GH",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Ty Maes Y Gruffydd Cefn Coed Hospital",
        "Address2": "Cockett",
        "Address3": None,
        "City": "Swansea",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "West Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "RT4UY",
        "OrganisationID": None,
        "OrganisationName": "Cefn Coed Regional Hq",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Swansea Bay University Health Board",
        "ParentONSCode": "W11000031",
        "ParentODSCode": "7A3",
        "Phone": None,
        "Postcode": "SA2 0GP",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Hospital Road",
        "Address2": "Gorseinon",
        "Address3": None,
        "City": "Swansea",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "West Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A3FK",
        "OrganisationID": None,
        "OrganisationName": "Ty Garngoch (Day Hospital)",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Swansea Bay University Health Board",
        "ParentONSCode": "W11000031",
        "ParentODSCode": "7A3",
        "Phone": None,
        "Postcode": "SA4 4LH",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Pen-Y-Fai",
        "Address2": None,
        "Address3": None,
        "City": "Bridgend",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Mid Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A3FA",
        "OrganisationID": None,
        "OrganisationName": "Glanrhyd Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Swansea Bay University Health Board",
        "ParentONSCode": "W11000031",
        "ParentODSCode": "7A3",
        "Phone": None,
        "Postcode": "CF31 4LN",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Brynawel Road",
        "Address2": "Gorseinon",
        "Address3": None,
        "City": "Swansea",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "West Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A3EM",
        "OrganisationID": None,
        "OrganisationName": "Gorseinon Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Swansea Bay University Health Board",
        "ParentONSCode": "W11000031",
        "ParentODSCode": "7A3",
        "Phone": None,
        "Postcode": "SA4 4UU",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Heol Maes Eglwys",
        "Address2": "Cwmrhydyceirw",
        "Address3": None,
        "City": "Swansea",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "West Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A3C7",
        "OrganisationID": None,
        "OrganisationName": "Morriston Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Swansea Bay University Health Board",
        "ParentONSCode": "W11000031",
        "ParentODSCode": "7A3",
        "Phone": None,
        "Postcode": "SA6 6NL",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Neath Road",
        "Address2": None,
        "Address3": None,
        "City": "Maesteg",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Mid Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A3B9",
        "OrganisationID": None,
        "OrganisationName": "Maesteg General Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Swansea Bay University Health Board",
        "ParentONSCode": "W11000031",
        "ParentODSCode": "7A3",
        "Phone": None,
        "Postcode": "CF34 9PW",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Baglan Way",
        "Address2": None,
        "Address3": None,
        "City": "Port Talbot",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "West Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A3CJ",
        "OrganisationID": None,
        "OrganisationName": "Neath Port Talbot Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Swansea Bay University Health Board",
        "ParentONSCode": "W11000031",
        "ParentODSCode": "7A3",
        "Phone": None,
        "Postcode": "SA12 7BX",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Stourbridge Road",
        "Address2": None,
        "Address3": None,
        "City": "Bromsgrove",
        "Country": "England",
        "CountryONSCode": "W92000004",
        "County": "Worcestershire",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "RWP06",
        "OrganisationID": None,
        "OrganisationName": "Princess Of Wales Community Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Swansea Bay University Health Board",
        "ParentONSCode": "W11000031",
        "ParentODSCode": "7A3",
        "Phone": None,
        "Postcode": "B61 0BB",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Coity Road",
        "Address2": None,
        "Address3": None,
        "City": "Bridgend",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Mid Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A3B7",
        "OrganisationID": None,
        "OrganisationName": "Princess Of Wales Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Swansea Bay University Health Board",
        "ParentONSCode": "W11000031",
        "ParentODSCode": "7A3",
        "Phone": None,
        "Postcode": "CF31 1RQ",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Stourbridge Road",
        "Address2": None,
        "Address3": None,
        "City": "Bromsgrove",
        "Country": "England",
        "CountryONSCode": "W92000004",
        "County": "Worcestershire",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "R1ACG",
        "OrganisationID": None,
        "OrganisationName": "Princess Of Wales Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Swansea Bay University Health Board",
        "ParentONSCode": "W11000031",
        "ParentODSCode": "R1A",
        "Phone": None,
        "Postcode": "B61 0BB",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Lynn Road",
        "Address2": None,
        "Address3": None,
        "City": "ELY",
        "Country": "England",
        "CountryONSCode": "W92000004",
        "County": "Cambridgeshire",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "RT1FD",
        "OrganisationID": None,
        "OrganisationName": "Princess Of Wales Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Swansea Bay University Health Board",
        "ParentONSCode": "W11000031",
        "ParentODSCode": "RT1",
        "Phone": None,
        "Postcode": "CB6 1DN",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Sketty Lane",
        "Address2": "Sketty",
        "Address3": None,
        "City": "Swansea",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "West Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A3C4",
        "OrganisationID": None,
        "OrganisationName": "Singleton Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Swansea Bay University Health Board",
        "ParentONSCode": "W11000031",
        "ParentODSCode": "7A3",
        "Phone": None,
        "Postcode": "SA2 8QA",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Tonna Uchaf",
        "Address2": "Tonna",
        "Address3": None,
        "City": "Neath",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "West Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A3KB",
        "OrganisationID": None,
        "OrganisationName": "Tonna Day Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Swansea Bay University Health Board",
        "ParentONSCode": "W11000031",
        "ParentODSCode": "7A3",
        "Phone": None,
        "Postcode": "SA11 3LX",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Tonna Uchaf",
        "Address2": "Tonna",
        "Address3": None,
        "City": "Neath",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "West Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A3FL",
        "OrganisationID": None,
        "OrganisationName": "Tonna Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Swansea Bay University Health Board",
        "ParentONSCode": "W11000031",
        "ParentODSCode": "7A3",
        "Phone": None,
        "Postcode": "SA11 3LX",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Cimla Common",
        "Address2": None,
        "Address3": None,
        "City": "Neath",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "West Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A3DR",
        "OrganisationID": None,
        "OrganisationName": "Cimla Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Swansea Bay University Health Board",
        "ParentONSCode": "W11000031",
        "ParentODSCode": "7A3",
        "Phone": None,
        "Postcode": "SA11 3SU",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Tempest Way",
        "Address2": None,
        "Address3": None,
        "City": "Chepstow",
        "Country": "WALES",
        "CountryONSCode": "W92000004",
        "County": "Gwent",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A6BJ",
        "OrganisationID": None,
        "OrganisationName": "Chepstow Community Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Aneuran Bevan Local Health Board",
        "ParentONSCode": "W11000028",
        "ParentODSCode": "7A6",
        "Phone": None,
        "Postcode": "NP16 5YX",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Llanfrechfa",
        "Address2": None,
        "Address3": None,
        "City": "Cwmbran",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Gwent",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A6G5",
        "OrganisationID": None,
        "OrganisationName": "Llanfrechfa Grange Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Aneuran Bevan Local Health Board",
        "ParentONSCode": "W11000028",
        "ParentODSCode": "7A6",
        "Phone": None,
        "Postcode": "NP44 8YN",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Ross Road",
        "Address2": None,
        "Address3": None,
        "City": "Abergavenny",
        "Country": "WALES",
        "CountryONSCode": "W92000004",
        "County": "Gwent",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A6FN",
        "OrganisationID": None,
        "OrganisationName": "Maindiff Court Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Aneuran Bevan Local Health Board",
        "ParentONSCode": "W11000028",
        "ParentODSCode": "7A6",
        "Phone": None,
        "Postcode": "NP7 8NF",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Brecon Road",
        "Address2": None,
        "Address3": None,
        "City": "Abergavenny",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": None,
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "O9L6S",
        "OrganisationID": None,
        "OrganisationName": "Homeward Bound Unit Nevill Hall",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Aneuran Bevan Local Health Board",
        "ParentONSCode": "W11000028",
        "ParentODSCode": "7A6",
        "Phone": None,
        "Postcode": "NP7 7EG",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Brecon Road",
        "Address2": None,
        "Address3": None,
        "City": "Abergavenny",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": None,
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A623",
        "OrganisationID": None,
        "OrganisationName": "Nevill Hall Childrens Centre",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Aneuran Bevan Local Health Board",
        "ParentONSCode": "W11000028",
        "ParentODSCode": "7A6",
        "Phone": None,
        "Postcode": "NP7 7EG",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Brecon Road",
        "Address2": None,
        "Address3": None,
        "City": "Abergavenny",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Gwent",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A6AM",
        "OrganisationID": None,
        "OrganisationName": "Nevill Hall Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Aneuran Bevan Local Health Board",
        "ParentONSCode": "W11000028",
        "ParentODSCode": "7A6",
        "Phone": None,
        "Postcode": "NP7 7EG",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Cardiff Road",
        "Address2": None,
        "Address3": None,
        "City": "Newport",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Gwent",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A6AR",
        "OrganisationID": None,
        "OrganisationName": "Royal Gwent Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Aneuran Bevan Local Health Board",
        "ParentONSCode": "W11000028",
        "ParentODSCode": "7A6",
        "Phone": None,
        "Postcode": "NP20 2UB",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Lodge Road",
        "Address2": "Caerleon",
        "Address3": None,
        "City": "Newport",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Gwent",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A6F7",
        "OrganisationID": None,
        "OrganisationName": "St Cadocs Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Aneuran Bevan Local Health Board",
        "ParentONSCode": "W11000028",
        "ParentODSCode": "7A6",
        "Phone": None,
        "Postcode": "NP18 3XQ",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "131 Stow Hill",
        "Address2": None,
        "Address3": None,
        "City": "Newport",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Gwent",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A6AT",
        "OrganisationID": None,
        "OrganisationName": "St Woolos Community",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Aneuran Bevan Local Health Board",
        "ParentONSCode": "W11000028",
        "ParentODSCode": "7A6",
        "Phone": None,
        "Postcode": "NP20 4SZ",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Lime Avenue",
        "Address2": None,
        "Address3": None,
        "City": "Ebbw Vale",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": None,
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A6AU",
        "OrganisationID": None,
        "OrganisationName": "Ysbyty Aneurin Bevan",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Aneuran Bevan Local Health Board",
        "ParentONSCode": "W11000028",
        "ParentODSCode": "7A6",
        "Phone": None,
        "Postcode": "NP23 6GL",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Ebbw Vale Community Hospital",
        "Address2": "College Road",
        "Address3": None,
        "City": "Ebbw Vale",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Gwent",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A6FR",
        "OrganisationID": None,
        "OrganisationName": "Ysbyty Tri Chwm",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Aneuran Bevan Local Health Board",
        "ParentONSCode": "W11000028",
        "ParentODSCode": "7A6",
        "Phone": None,
        "Postcode": "NP23 6HA",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Ystrad Fawr Way",
        "Address2": "Ystrad Mynach",
        "Address3": None,
        "City": "Hengoed",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Mid Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A6AV",
        "OrganisationID": None,
        "OrganisationName": "Ysbyty Ystrad Fawr",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Aneuran Bevan Local Health Board",
        "ParentONSCode": "W11000028",
        "ParentODSCode": "7A6",
        "Phone": None,
        "Postcode": "CF82 7EP",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Cornist Road",
        "Address2": None,
        "Address3": None,
        "City": "Flint",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Clwyd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1AA",
        "OrganisationID": None,
        "OrganisationName": "Flint Community Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "CH6 5HG",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Plough Lane",
        "Address2": "Shotton",
        "Address3": None,
        "City": "Deeside",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Clwyd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1CC",
        "OrganisationID": None,
        "OrganisationName": "Deeside Community Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "CH5 1XS",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Chirk",
        "Address2": None,
        "Address3": None,
        "City": "Wrexham",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "CLWYD",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1A7",
        "OrganisationID": None,
        "OrganisationName": "Chirk Community Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL14 5LN",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Halkyn Road",
        "Address2": None,
        "Address3": None,
        "City": "Holywell",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Clwyd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1AB",
        "OrganisationID": None,
        "OrganisationName": "Holywell Community Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "CH8 7TZ",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Ash Grove",
        "Address2": None,
        "Address3": None,
        "City": "Mold",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": None,
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1AD",
        "OrganisationID": None,
        "OrganisationName": "Mold Community Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "CH7 1XG",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Ashgrove",
        "Address2": None,
        "Address3": None,
        "City": "Mold",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Clwyd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "RL105",
        "OrganisationID": None,
        "OrganisationName": "Mold Community Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "CH7 1XG",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Whitchurch Road",
        "Address2": "Bangor-On-Dee",
        "Address3": None,
        "City": "Wrexham",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Clwyd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1D4",
        "OrganisationID": None,
        "OrganisationName": "Penley Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL13 0AY",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Croesnewydd Road",
        "Address2": "Wrexham Technology Park",
        "Address3": None,
        "City": "Wrexham",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Clwyd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1A4",
        "OrganisationID": None,
        "OrganisationName": "Wrexham Maelor Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL13 7TD",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Croesnewydd Road",
        "Address2": "Wrexham Technology Park",
        "Address3": None,
        "City": "Wrexham",
        "Country": "England",
        "CountryONSCode": "W92000004",
        "County": "Clwyd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "R1DD4",
        "OrganisationID": None,
        "OrganisationName": "Wrexham Maelor Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL13 7TD",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Croesnewydd Road",
        "Address2": "Wrexham Technology Park",
        "Address3": None,
        "City": "Wrexham",
        "Country": "England",
        "CountryONSCode": "W92000004",
        "County": "Clwyd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "RET32",
        "OrganisationID": None,
        "OrganisationName": "Wrexham Maelor Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL13 7TD",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Croesnewydd Road",
        "Address2": "Wrexham Technology Park",
        "Address3": None,
        "City": "Wrexham",
        "Country": "England",
        "CountryONSCode": "W92000004",
        "County": None,
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "RJR65",
        "OrganisationID": None,
        "OrganisationName": "Wrexham Maelor Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL13 7TD",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Croesnewydd Road",
        "Address2": "Wrexham Technology Park",
        "Address3": None,
        "City": "Wrexham",
        "Country": "England",
        "CountryONSCode": "W92000004",
        "County": "Clwyd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "RL111",
        "OrganisationID": None,
        "OrganisationName": "Wrexham Maelor Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL13 7TD",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Caernarvon Road",
        "Address2": None,
        "Address3": None,
        "City": "Pwllheli",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Gwynedd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1AX",
        "OrganisationID": None,
        "OrganisationName": "Bryn Beryl Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL53 6TT",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Aber Road",
        "Address2": None,
        "Address3": None,
        "City": "Llanfairfechan",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Gwynedd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1GE",
        "OrganisationID": None,
        "OrganisationName": "Bryn-Y-Neuadd Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL33 0HH",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Bridge Street",
        "Address2": None,
        "Address3": None,
        "City": "Llangefni",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Gwynedd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1DD",
        "OrganisationID": None,
        "OrganisationName": "Cefni Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL77 7PP",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Dogellau & Barmouth District Hospit",
        "Address2": None,
        "Address3": None,
        "City": "Dolgellau",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "GWYNEDD",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1AY",
        "OrganisationID": None,
        "OrganisationName": "Dolgellau & Barmouth District Hospital Site",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL40 1NT",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "The Park",
        "Address2": None,
        "Address3": None,
        "City": "Caernarfon",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Gwynedd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1DG",
        "OrganisationID": None,
        "OrganisationName": "Eryri Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL55 2YE",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Wynne Road",
        "Address2": None,
        "Address3": None,
        "City": "Blaenau Ffestiniog",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Gwynedd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1PL",
        "OrganisationID": None,
        "OrganisationName": "Canolfan Goffa Ffestiniog",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL41 3DW",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Llandudno General Hospital",
        "Address2": None,
        "Address3": None,
        "City": "Llandudno",
        "Country": "WALES",
        "CountryONSCode": "W92000004",
        "County": "Gwynedd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1AV",
        "OrganisationID": None,
        "OrganisationName": "Llandudno General Hospital Site",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL30 1LB",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Tywyn & District War Memorial Hospi",
        "Address2": None,
        "Address3": None,
        "City": "Tywyn",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Gwynedd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1B2",
        "OrganisationID": None,
        "OrganisationName": "Tywyn & District War Memorial Hospital Site",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL36 9HH",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Penrhosgarnedd",
        "Address2": None,
        "Address3": None,
        "City": "Bangor",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Gwynedd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1AU",
        "OrganisationID": None,
        "OrganisationName": "Ysbyty Gwynedd",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL57 2PW",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Llanfair Road",
        "Address2": None,
        "Address3": None,
        "City": "Abergele",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Clwyd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1A2",
        "OrganisationID": None,
        "OrganisationName": "Abergele Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL22 8DP",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Hesketh Road",
        "Address2": "Old Colwyn",
        "Address3": None,
        "City": "Colwyn Bay",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Clwyd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1A8",
        "OrganisationID": None,
        "OrganisationName": "Colwyn Bay Community Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL29 8AY",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Ruthin Road",
        "Address2": None,
        "Address3": None,
        "City": "Denbigh",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Clwyd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1A9",
        "OrganisationID": None,
        "OrganisationName": "Denbigh Community Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL16 3ES",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Rhuddlan Road",
        "Address2": "Bodelwyddan",
        "Address3": None,
        "City": "Rhyl",
        "Country": "England",
        "CountryONSCode": "W92000004",
        "County": "Clwyd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "RL121",
        "OrganisationID": None,
        "OrganisationName": "Glan Clwyd Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL18 5UJ",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Penrhos Beach Road",
        "Address2": None,
        "Address3": None,
        "City": "Holyhead",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Gwynedd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1DC",
        "OrganisationID": None,
        "OrganisationName": "Ysbyty Penrhos Stanley",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL65 2QA",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Regent Street",
        "Address2": None,
        "Address3": None,
        "City": "Llangollen",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Clwyd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1S1",
        "OrganisationID": None,
        "OrganisationName": "Llangollen Clinic",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL20 8HL",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Glan Clwyd Hospital",
        "Address2": "Rhuddlan Road",
        "Address3": "Bodelwyddan",
        "City": "Rhyl",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Clwyd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1HD",
        "OrganisationID": None,
        "OrganisationName": "North Wales Cancer Treatment Centre",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL18 5UJ",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "23 Kings Avenue",
        "Address2": None,
        "Address3": None,
        "City": "Prestatyn",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "CLWYD",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1S4",
        "OrganisationID": None,
        "OrganisationName": "Prestatyn Clinic",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL19 9AA",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Marine Drive",
        "Address2": None,
        "Address3": None,
        "City": "Rhyl",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "CLWYD",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1A5",
        "OrganisationID": None,
        "OrganisationName": "Royal Alexandra Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL18 3AS",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Llanrhydd Street",
        "Address2": None,
        "Address3": None,
        "City": "Ruthin",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "CLWYD",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1AF",
        "OrganisationID": None,
        "OrganisationName": "Ruthin Community Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL15 1PS",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Tremadog",
        "Address2": None,
        "Address3": None,
        "City": "Porthmadog",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": None,
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A1CA",
        "OrganisationID": None,
        "OrganisationName": "Ysbyty Alltwen",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Betsi Cadwaladr University Health Board",
        "ParentONSCode": "W11000023",
        "ParentODSCode": "7A1",
        "Phone": None,
        "Postcode": "LL49 9AQ",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "18-20 Fairwater Road",
        "Address2": None,
        "Address3": None,
        "City": "Cardiff",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "South Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A4BX",
        "OrganisationID": None,
        "OrganisationName": "Rookwood Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Cardiff and Vale University Health Board",
        "ParentONSCode": "W11000029",
        "ParentODSCode": "7A4",
        "Phone": None,
        "Postcode": "CF5 2YN",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Cowbridge Road East",
        "Address2": None,
        "Address3": None,
        "City": "Cardiff",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "South Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A4FE",
        "OrganisationID": None,
        "OrganisationName": "St David's Community Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Cardiff and Vale University Health Board",
        "ParentONSCode": "W11000029",
        "ParentODSCode": "7A4",
        "Phone": None,
        "Postcode": "CF11 9XB",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Heath Park",
        "Address2": None,
        "Address3": None,
        "City": "Cardiff",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "South Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A4BV",
        "OrganisationID": None,
        "OrganisationName": "University Hospital Of Wales",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Cardiff and Vale University Health Board",
        "ParentONSCode": "W11000029",
        "ParentODSCode": "7A4",
        "Phone": None,
        "Postcode": "CF14 4XW",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Heath Park",
        "Address2": None,
        "Address3": None,
        "City": "Cardiff",
        "Country": "England",
        "CountryONSCode": "W92000004",
        "County": "South Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "R2F2E",
        "OrganisationID": None,
        "OrganisationName": "University Hospital Of Wales",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Cardiff and Vale University Health Board",
        "ParentONSCode": "W11000029",
        "ParentODSCode": "7A4",
        "Phone": None,
        "Postcode": "CF14 4XW",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "C/O John Radcliffe Hospital",
        "Address2": "Headley Way",
        "Address3": "Headington",
        "City": "Oxford",
        "Country": "England",
        "CountryONSCode": "W92000004",
        "County": None,
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "Rth18",
        "OrganisationID": None,
        "OrganisationName": "University Hospital Of Wales",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Cardiff and Vale University Health Board",
        "ParentONSCode": "W11000029",
        "ParentODSCode": "7A4",
        "Phone": None,
        "Postcode": "OX3 9DU",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Cardiff & Vale University Health Bd",
        "Address2": "Heath Park",
        "Address3": None,
        "City": "Cardiff",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "South Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A4H1",
        "OrganisationID": None,
        "OrganisationName": "Noahs Ark Childrens Hospital For Wales",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Cardiff and Vale University Health Board",
        "ParentONSCode": "W11000029",
        "ParentODSCode": "7A4",
        "Phone": None,
        "Postcode": "CF14 4XW",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Colcot Road",
        "Address2": None,
        "Address3": None,
        "City": "Barry",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "South Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A4CH",
        "OrganisationID": None,
        "OrganisationName": "The Barry Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Cardiff and Vale University Health Board",
        "ParentONSCode": "W11000029",
        "ParentODSCode": "7A4",
        "Phone": None,
        "Postcode": "CF62 8YH",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Penlan Road",
        "Address2": "Llandough",
        "Address3": None,
        "City": "Penarth",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "South Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A4C1",
        "OrganisationID": None,
        "OrganisationName": "University Hospital Llandough",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Cardiff and Vale University Health Board",
        "ParentONSCode": "W11000029",
        "ParentODSCode": "7A4",
        "Phone": None,
        "Postcode": "CF64 2XX",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Albert Road",
        "Address2": None,
        "Address3": None,
        "City": "Pontypridd",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Mid Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A5DK",
        "OrganisationID": None,
        "OrganisationName": "Dewi Sant Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Cwm Taf Morgannwg University Health Board",
        "ParentONSCode": "W11000030",
        "ParentODSCode": "7A5",
        "Phone": None,
        "Postcode": "CF37 1LB",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Partridge Road",
        "Address2": "Llwynypia",
        "Address3": None,
        "City": "Tonypandy",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Mid Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A5CA",
        "OrganisationID": None,
        "OrganisationName": "Ysbyty Cwm Rhondda",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Cwm Taf Morgannwg University Health Board",
        "ParentONSCode": "W11000030",
        "ParentODSCode": "7A5",
        "Phone": None,
        "Postcode": "CF40 2LX",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "New Road",
        "Address2": None,
        "Address3": None,
        "City": "Mountain Ash",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Mid Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A5HA",
        "OrganisationID": None,
        "OrganisationName": "Ysbyty Cwm Cynon",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Cwm Taf Morgannwg University Health Board",
        "ParentONSCode": "W11000030",
        "ParentODSCode": "7A5",
        "Phone": None,
        "Postcode": "CF45 4BZ",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "The Common",
        "Address2": None,
        "Address3": None,
        "City": "Pontypridd",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Mid Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A5BK",
        "OrganisationID": None,
        "OrganisationName": "Pontypridd & District Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Cwm Taf Morgannwg University Health Board",
        "ParentONSCode": "W11000030",
        "ParentODSCode": "7A5",
        "Phone": None,
        "Postcode": "CF37 4AX",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Prince Charles Hospital",
        "Address2": None,
        "Address3": None,
        "City": "Merthyr Tydfil",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Mid Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A5B3",
        "OrganisationID": None,
        "OrganisationName": "Prince Charles Hospital Site",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Cwm Taf Morgannwg University Health Board",
        "ParentONSCode": "W11000030",
        "ParentODSCode": "7A5",
        "Phone": None,
        "Postcode": "CF47 9DT",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Ynysmaerdy",
        "Address2": None,
        "Address3": None,
        "City": "Pontyclun",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Mid Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A5B1",
        "OrganisationID": None,
        "OrganisationName": "The Royal Glamorgan Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Cwm Taf Morgannwg University Health Board",
        "ParentONSCode": "W11000030",
        "ParentODSCode": "7A5",
        "Phone": None,
        "Postcode": "CF72 8XR",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Cwmparc Road",
        "Address2": None,
        "Address3": None,
        "City": "Treorchy",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Mid Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A5DV",
        "OrganisationID": None,
        "OrganisationName": "Ysbyty George Thomas",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Cwm Taf Morgannwg University Health Board",
        "ParentONSCode": "W11000030",
        "ParentODSCode": "7A5",
        "Phone": None,
        "Postcode": "CF42 6YG",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Folland Road",
        "Address2": "Glanamman",
        "Address3": None,
        "City": "Ammanford",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Dyfed",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A2E1",
        "OrganisationID": None,
        "OrganisationName": "Amman Valley Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Hywel Dda Local Health Board",
        "ParentONSCode": "W11000025",
        "ParentODSCode": "7A2",
        "Phone": None,
        "Postcode": "SA18 2BQ",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Caradoc Road",
        "Address2": None,
        "Address3": None,
        "City": "Aberystwyth",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Dyfed",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A2AJ",
        "OrganisationID": None,
        "OrganisationName": "Bronglais General Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Hywel Dda Local Health Board",
        "ParentONSCode": "W11000025",
        "ParentODSCode": "7A2",
        "Phone": None,
        "Postcode": "SY23 1ER",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Elm Crescent",
        "Address2": None,
        "Address3": None,
        "City": "Bridgend",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Mid Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A3NC",
        "OrganisationID": None,
        "OrganisationName": "Bryntirion Infant Welfare Clinic",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Hywel Dda Local Health Board",
        "ParentONSCode": "W11000025",
        "ParentODSCode": "7A2",
        "Phone": None,
        "Postcode": "CF31 4EA",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Feidrfair",
        "Address2": None,
        "Address3": None,
        "City": "Cardigan",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Dyfed",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A2M7",
        "OrganisationID": None,
        "OrganisationName": "Cardigan Health Centre",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Hywel Dda Local Health Board",
        "ParentONSCode": "W11000025",
        "ParentODSCode": "7A2",
        "Phone": None,
        "Postcode": "SA43 1EB",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Rhodfa'r Felin",
        "Address2": None,
        "Address3": None,
        "City": "Cardigan",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Ceredigion",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A2L7",
        "OrganisationID": None,
        "OrganisationName": "Cardigan Integrated Care Centre",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Hywel Dda Local Health Board",
        "ParentONSCode": "W11000025",
        "ParentODSCode": "7A2",
        "Phone": None,
        "Postcode": "SA43 1JX",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Llanfair Road",
        "Address2": None,
        "Address3": None,
        "City": "Llandovery",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Dyfed",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A2AH",
        "OrganisationID": None,
        "OrganisationName": "Llandovery Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Hywel Dda Local Health Board",
        "ParentONSCode": "W11000025",
        "ParentODSCode": "7A2",
        "Phone": None,
        "Postcode": "SA20 0LA",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Mercia Drive",
        "Address2": "Mynydd Isa",
        "Address3": None,
        "City": "Mold",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Clwyd",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A122",
        "OrganisationID": None,
        "OrganisationName": "Mynydd Isa Clinic",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Hywel Dda Local Health Board",
        "ParentONSCode": "W11000025",
        "ParentODSCode": "7A2",
        "Phone": None,
        "Postcode": "CH7 6UH",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Gas Lane",
        "Address2": None,
        "Address3": None,
        "City": "Tenby",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Dyfed",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A2JA",
        "OrganisationID": None,
        "OrganisationName": "New Tenby Cottage Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Hywel Dda Local Health Board",
        "ParentONSCode": "W11000025",
        "ParentODSCode": "7A2",
        "Phone": None,
        "Postcode": "SA70 8AG",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Dewi Road",
        "Address2": None,
        "Address3": None,
        "City": "Tregaron",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "DYFED",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A2D8",
        "OrganisationID": None,
        "OrganisationName": "Tregaron Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Hywel Dda Local Health Board",
        "ParentONSCode": "W11000025",
        "ParentODSCode": "7A2",
        "Phone": None,
        "Postcode": "SY25 6JP",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Dolgwili Road",
        "Address2": None,
        "Address3": None,
        "City": "Carmarthen",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Dyfed",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A2AG",
        "OrganisationID": None,
        "OrganisationName": "West Wales General Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Hywel Dda Local Health Board",
        "ParentONSCode": "W11000025",
        "ParentODSCode": "7A2",
        "Phone": None,
        "Postcode": "SA31 2AF",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Fishguard Road",
        "Address2": None,
        "Address3": None,
        "City": "Haverfordwest",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Dyfed",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A2BL",
        "OrganisationID": None,
        "OrganisationName": "Withybush General Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Hywel Dda Local Health Board",
        "ParentONSCode": "W11000025",
        "ParentODSCode": "7A2",
        "Phone": None,
        "Postcode": "SA61 2PZ",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Child Health Section",
        "Address2": "Withybush Hospital",
        "Address3": "Fishguard Road",
        "City": "Haverfordwest",
        "Country": "WALES",
        "CountryONSCode": "W92000004",
        "County": "Dyfed",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A2BM",
        "OrganisationID": None,
        "OrganisationName": "Withybush Hospital Child Health Section",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Hywel Dda Local Health Board",
        "ParentONSCode": "W11000025",
        "ParentODSCode": "7A2",
        "Phone": None,
        "Postcode": "SA61 2PZ",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Cerrigcochion Road",
        "Address2": None,
        "Address3": None,
        "City": "Brecon",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Powys",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A7BT",
        "OrganisationID": None,
        "OrganisationName": "Breconshire War Memorial Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Powys Teaching Local Health Board",
        "ParentONSCode": "W11000024",
        "ParentODSCode": "7A7",
        "Phone": None,
        "Postcode": "LD3 7NS",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Heol Maengwyn",
        "Address2": None,
        "Address3": None,
        "City": "Machynlleth",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Powys",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A7BQ",
        "OrganisationID": None,
        "OrganisationName": "Broddyfi Community Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Powys Teaching Local Health Board",
        "ParentONSCode": "W11000024",
        "ParentODSCode": "7A7",
        "Phone": None,
        "Postcode": "SY20 8AD",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Bronllys",
        "Address2": None,
        "Address3": None,
        "City": "Brecon",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Powys",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A7EH",
        "OrganisationID": None,
        "OrganisationName": "Bronllys Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Powys Teaching Local Health Board",
        "ParentONSCode": "W11000024",
        "ParentODSCode": "7A7",
        "Phone": None,
        "Postcode": "LD3 0LY",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Park Road",
        "Address2": None,
        "Address3": None,
        "City": "Builth Wells",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Powys",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A73F",
        "OrganisationID": None,
        "OrganisationName": "Builth Wells Clinic",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Powys Teaching Local Health Board",
        "ParentONSCode": "W11000024",
        "ParentODSCode": "7A7",
        "Phone": None,
        "Postcode": "LD2 3BA",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Ffrydd Road",
        "Address2": None,
        "Address3": None,
        "City": "Knighton",
        "Country": "WALES",
        "CountryONSCode": "W92000004",
        "County": "Powys",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A7EG",
        "OrganisationID": None,
        "OrganisationName": "Knighton Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Powys Teaching Local Health Board",
        "ParentONSCode": "W11000024",
        "ParentODSCode": "7A7",
        "Phone": None,
        "Postcode": "LD7 1DF",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Temple Street",
        "Address2": None,
        "Address3": None,
        "City": "Llandrindod Wells",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Powys",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A7BN",
        "OrganisationID": None,
        "OrganisationName": "Llandrindod Wells Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Powys Teaching Local Health Board",
        "ParentONSCode": "W11000024",
        "ParentODSCode": "7A7",
        "Phone": None,
        "Postcode": "LD1 5HF",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Eastgate Street",
        "Address2": None,
        "Address3": None,
        "City": "Llanidloes",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "Powys",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A7BP",
        "OrganisationID": None,
        "OrganisationName": "Llanidloes And District War Memorial Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Powys Teaching Local Health Board",
        "ParentONSCode": "W11000024",
        "ParentODSCode": "7A7",
        "Phone": None,
        "Postcode": "SY18 6HF",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Llanfair Road",
        "Address2": None,
        "Address3": None,
        "City": "Newtown",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "POWYS",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A7BR",
        "OrganisationID": None,
        "OrganisationName": "Montgomeryshire County Infirmary",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Powys Teaching Local Health Board",
        "ParentONSCode": "W11000024",
        "ParentODSCode": "7A7",
        "Phone": None,
        "Postcode": "SY16 2DW",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Salop Road",
        "Address2": None,
        "Address3": None,
        "City": "Welshpool",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "POWYS",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7A7BS",
        "OrganisationID": None,
        "OrganisationName": "Victoria Memorial Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Powys Teaching Local Health Board",
        "ParentONSCode": "W11000024",
        "ParentODSCode": "7A7",
        "Phone": None,
        "Postcode": "SY21 7DU",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
    {
        "Address1": "Glanrhyd Road",
        "Address2": "Ystradgynlais",
        "Address3": None,
        "City": "Swansea",
        "Country": "Wales",
        "CountryONSCode": "W92000004",
        "County": "West Glamorgan",
        "Email": None,
        "Fax": None,
        "IsPimsManaged": None,
        "OrganisationCode": "7a7ej",
        "OrganisationID": None,
        "OrganisationName": "Ystradgynlais Community Hospital",
        "OrganisationStatus": "Visible",
        "OrganisationType": None,
        "ParentName": "Powys Teaching Local Health Board",
        "ParentONSCode": "W11000024",
        "ParentODSCode": "7A7",
        "Phone": None,
        "Postcode": "Sa9 1au",
        "Sector": "NHS Sector",
        "SubType": None,
        "Website": None,
    },
]
