#!/bin/bash

# DEPRECATED script - we have now moved to using Docker Compose in dev
# This script left in the codebase just in case it is ever needed

# Creates and runs a Docker container for Postgres
docker run --name epilepsy12postgres -e POSTGRES_USER=epilepsy12user -e POSTGRES_PASSWORD=epilepsy12 -e POSTGRES_DB=epilepsy12db -p 5432:5432 -d postgres

# Pull in Environment variables
source example.env

# Migrations
python manage.py makemigrations
python manage.py migrate

# Seed DB
python manage.py seed --mode=seed_organisations
python manage.py seed --mode=seed_semiology_keywords
python manage.py seed --mode=seed_dummy_cases