#!/bin/bash

# DEPRECATED script - we have now moved to using Docker Compose in dev
# This script left in the codebase just in case it is ever needed

# Migrations
python manage.py makemigrations
python manage.py migrate