# Generated by Django 4.0.4 on 2022-07-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0005_remove_registration_epilepsy_surgery_centre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='assessment_complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='epilepsy_context_complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='initial_assessment_complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='investigation_management_complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='multiaxial_description_complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='referring_clinician',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
