# Generated by Django 4.0.4 on 2022-07-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0006_alter_registration_assessment_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='lead_hospital',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='lead_hospital'),
        ),
    ]
