# Generated by Django 4.0.4 on 2022-07-15 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0007_registration_lead_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='ethnicity',
            field=models.CharField(choices=[('N', 'African'), ('L', 'Any other Asian background'), ('P', 'Any other Black background'), ('S', 'Any other ethnic group'), ('G', 'Any other mixed background'), ('C', 'Any other White background'), ('K', 'Bangladeshi or British Bangladeshi'), ('A', 'British, Mixed British'), ('M', 'Caribbean'), ('R', 'Chinese'), ('H', 'Indian or British Indian'), ('B', 'Irish'), ('Z', 'Not Stated'), ('J', 'Pakistani or British Pakistani'), ('F', 'White and Asian'), ('E', 'White and Black African'), ('D', 'White and Black Caribbean')], max_length=4),
        ),
        migrations.AlterField(
            model_name='case',
            name='locked',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Locked'),
        ),
        migrations.AlterField(
            model_name='case',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='locked by'),
        ),
    ]
