# Generated by Django 4.0.4 on 2022-07-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0009_registration_eligibility_criteria_met'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.DateField(default=None, null=True, verbose_name='Date on which registered for the the Epilepsy12 audit'),
        ),
    ]
