# Generated by Django 4.0.4 on 2022-07-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0010_alter_registration_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_close_date',
            field=models.DateField(default=None, null=True, verbose_name='Date at which the registration is due to close'),
        ),
    ]
