# Generated by Django 4.0.4 on 2022-07-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0012_remove_assessment_paroxysmal_episode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='tertiary_paediatric_neurology_centre',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='tertiary_paediatric_neurology_centre'),
        ),
    ]
