# Generated by Django 4.0.4 on 2022-07-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0018_alter_epilepsycontext_diagnosis_of_epilepsy_withdrawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site',
            field=models.ManyToManyField(related_name='as_site', to='epilepsy12.hospitaltrust'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_is_childrens_epilepsy_surgery_centre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='site_is_general_paediatric_centre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='site_is_paediatric_neurology_centre',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_is_primary_centre_of_epilepsy_care',
            field=models.BooleanField(default=False),
        ),
    ]
