# Generated by Django 4.0.4 on 2022-07-31 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0019_site_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='site',
        ),
        migrations.AddField(
            model_name='site',
            name='hospital_trust',
            field=models.OneToOneField(default="King's College Hospital", on_delete=django.db.models.deletion.DO_NOTHING, related_name='hospital_site', to='epilepsy12.hospitaltrust'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_is_actively_involved_in_epilepsy_care',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_is_childrens_epilepsy_surgery_centre',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_is_general_paediatric_centre',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_is_paediatric_neurology_centre',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_is_primary_centre_of_epilepsy_care',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
