# Generated by Django 4.0.4 on 2022-08-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0023_investigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='eeg_performed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='eeg_request_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
