# Generated by Django 4.0.4 on 2022-08-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0028_rename_has_rescue_medication_prescribed_management_has_rescue_medication_been_prescribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiepilepsymedicine',
            name='antiepilepsy_medicine_snomed_preferred_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='antiepilepsy medicine SNOMED-CT preferred name'),
        ),
        migrations.AlterField(
            model_name='antiepilepsymedicine',
            name='antiepilepsy_medicine_snomed_code',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='antiepilepsy medicine SNOMED-CT code'),
        ),
    ]
