# Generated by Django 4.0.4 on 2022-08-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0029_antiepilepsymedicine_antiepilepsy_medicine_snomed_preferred_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiepilepsymedicine',
            name='antiepilepsy_medicine_snomed_code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='antiepilepsy medicine SNOMED-CT code'),
        ),
    ]
