# Generated by Django 4.0.4 on 2022-08-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0033_alter_investigation_ct_head_scan_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='childrens_epilepsy_surgical_service_referral_criteria_met',
            field=models.BooleanField(default=None, null=True, verbose_name="Have the criteria for referral to a children's epilepsy surgery service been met?"),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='consultant_paediatrician_input_date',
            field=models.DateField(default=None, null=True, verbose_name='Date seen by a consultant paediatrician with expertise in epilepsy.'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='consultant_paediatrician_referral_date',
            field=models.DateField(default=None, null=True, verbose_name='Date of referral to a consultant paediatrician with expertise in epilepsy.'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='consultant_paediatrician_referral_made',
            field=models.BooleanField(default=None, null=True, verbose_name='Has a referral been made to a consultant paediatrician with an interest in epilepsy?'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='epilepsy_specialist_nurse_referral_made',
            field=models.BooleanField(default=None, null=True, verbose_name='Has a referral to an epilepsy nurse specialist been made?'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='experienced_prolonged_focal_seizures',
            field=models.BooleanField(default=None, null=True, verbose_name='Were there any prolonged focal seizures?'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='paediatric_neurologist_input_date',
            field=models.DateField(default=None, null=True, verbose_name='Date seen by consultant paediatric neurologist.'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='paediatric_neurologist_referral_date',
            field=models.DateField(default=None, null=True, verbose_name='Date of referral to a consultant paediatric neurologist.'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='paediatric_neurologist_referral_made',
            field=models.BooleanField(default=None, null=True, verbose_name='Has a referral to a consultant paediatric neurologist been made?'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='prolonged_generalized_convulsive_seizures',
            field=models.BooleanField(default=None, null=True, verbose_name='Were there any prolonged generalised epileptic seizures?'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='were_any_of_the_epileptic_seizures_convulsive',
            field=models.BooleanField(default=None, null=True, verbose_name='Were any of the epileptic seizures convulsive?'),
        ),
    ]
