# Generated by Django 4.0.4 on 2022-08-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0035_assessment_childrens_epilepsy_surgical_service_referral_made'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='epilepsy_surgery_centre',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='tertiary_paediatric_neurology_centre',
        ),
    ]
