# Generated by Django 4.0.4 on 2022-08-14 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0038_alter_site_hospital_trust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='hospital_trust',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_trust', to='epilepsy12.hospitaltrust'),
        ),
    ]
