# Generated by Django 4.0.4 on 2022-08-21 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0051_alter_auditprogress_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seizuretype',
            name='assessment',
        ),
    ]
