# Generated by Django 4.0.4 on 2022-08-24 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import epilepsy12.models.epilepsy12user


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0056_remove_management_rescue_medication_prescribed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElectroClinicalSyndrome',
        ),
        migrations.DeleteModel(
            name='SeizureCause',
        ),
        migrations.DeleteModel(
            name='SeizureType',
        ),
        migrations.AddField(
            model_name='initialassessment',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initialassessment',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created%(app_label)s_%(class)s_related',
                                    to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AddField(
            model_name='initialassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='initialassessment',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated%(app_label)s_%(class)s_related',
                                    to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
    ]
