# Generated by Django 4.0 on 2022-03-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'case', 'verbose_name_plural': 'cases'},
        ),
    ]
