# Generated by Django 4.1.1 on 2022-09-11 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='epilepsy12.case'),
        ),
        migrations.AlterField(
            model_name='site',
            name='hospital_trust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site', to='epilepsy12.hospitaltrust'),
        ),
    ]
