# Generated by Django 4.0 on 2022-03-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialassessment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='initialassessment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='initialassessment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='initialassessment',
            name='updated_by',
        ),
    ]
