# Generated by Django 4.0.4 on 2022-06-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desscribe',
            name='seizure_cause_mitochondrial_sctid',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='SNOMED CT identifier of mitochondrial disease type'),
        ),
    ]
