# Generated by Django 4.0 on 2022-04-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epilepsy12user',
            name='bio',
            field=models.CharField(blank=True, help_text='Share something about yourself.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='epilepsy12user',
            name='email',
            field=models.EmailField(help_text='Enter your email address.', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='epilepsy12user',
            name='first_name',
            field=models.CharField(blank=True, help_text='Enter your first name', max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='epilepsy12user',
            name='hospital_trust',
            field=models.CharField(help_text='Enter the main hospital trust where you work.', max_length=100),
        ),
        migrations.AlterField(
            model_name='epilepsy12user',
            name='surname',
            field=models.CharField(blank=True, help_text='Enter your surname', max_length=150, null=True, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='epilepsy12user',
            name='username',
            field=models.CharField(help_text='Select a unique username.', max_length=150, unique=True),
        ),
    ]
