# Generated by Django 4.0 on 2022-04-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='index_of_multiple_deprivation_quintile',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='index of multiple deprivation calculated from MySociety data.'),
        ),
    ]
