# Generated by Django 4.1.1 on 2022-09-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='hospital_trusts',
            field=models.ManyToManyField(related_name='cases', through='epilepsy12.Site', to='epilepsy12.hospitaltrust'),
        ),
    ]
