# Generated by Django 4.0.4 on 2022-05-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_type',
            field=models.CharField(choices=[('FO', 'Focal onset'), ('GO', 'Generalised onset'), ('UO', 'Unknown onset'), ('UC', 'Unclassified')], max_length=3, verbose_name='If epileptic, what is the seizure type (s)?'),
        ),
    ]
