# Generated by Django 4.0.4 on 2022-09-07 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0002_alter_epilepsy12user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epilepsy12user',
            options={'permissions': (('can_view_child_nhs_number', "Can view a child's NHS Number"), ('can_view_child_date_of_birth', "Can view a child's date of birth"), ('can_delete_child_case_data', "Can irreversibly delete a child's case data."), ('can_update_child_case_data', "Can edit or update a child's case data."), ('can_lock_child_case_data_from_editing', "Can lock a child's record from editing."), ('can_unlock_child_case_data_from_editing', "Can unlock a child's record from editing."), ('can_opt_out_child_from_inclusion_in_audit', "Can sanction an opt out from participating in the audit. Note all the child's date except Epilepsy12 unique identifier are irretrievably deleted."), ('can_view_child_case_data', "Can view a child's demographic and case information."), ('can_approve_eligibility', 'Can approve eligibility for Epilepsy12.'), ('can_remove_approval_of_eligibility', 'Can remove approval of eligibiltiy for Epilepsy12.'), ('can_view_lead_clinician', 'Can view the lead clinician'), ('can_allocate_lead_clinician', 'Can allocate the lead clinician.'), ('can_edit_lead_clinician', 'Can edit the lead clinician.'), ('can_register_child_in_epilepsy12', 'Can register child in Epilepsy12. (A cohort number is automatically allocaeted)'), ('can_unregister_child_in_epilepsy12', 'Can unregister a child in Epilepsy. Their record and previously entered data is untouched.'), ('can_view_first_paediatric_assessment_fields', 'Can view all information gathered at first assessment.'), ('can_edit_first_paediatric_assessment_fields', 'Can edit all information gathered at first assessment.'), ('can_view_epilepsy_context_fields', 'Can view all fiedls related to epilepsy context.'), ('can_edit_epilepsy_context_fields', 'Can edit all fiedls related to epilepsy context.'), ('can_view_multiaxial_diagnosis_fields', 'Can only view fields relating to multiaxial diagnosis.'), ('can_edit_multiaxial_diagnosis_fields', 'Can only create or edit fields relating to multiaxial diagnosis.'), ('can_view_seizure_episodes', 'Can only view seizure episodes'), ('can_add_seizure_episode', 'Can add a new seizure episode'), ('can_update_seizure_episode', 'Can edit or update a seizure episode but not delete.'), ('can_delete_seizure_episode', 'Can delete a seizure episode.'), ('can_add_syndrome', 'Can add a new syndrome.'), ('can_edit_syndrome_fields', 'Can edit or update an epilepsy syndrome, but not delete.'), ('can_delete_syndrome', 'Can delete an epilepsy syndrome'), ('can_view_comorbidities', 'Can view comorbidities'), ('can_add_comorbidity', 'Can add a comorbidity'), ('can_edit_comorbidity_fields', 'Can edit or update but not delete a comorbidity.'), ('can_delete_comorbidity', 'Can delete a comorbidity.'), ('can_view_milestones', 'Can view milestones in Epilepsy12 audit.'), ('can_edit_milestones_fields', 'Can edit or update milestones in Epilepsy12 audit.'), ('can_view_general_paediatric_centre', 'Can view general paediatric centre.'), ('can_allocate_general_paediatric_centre', 'Can allocate general paediatric centre.'), ('can_update_general_paediatric_centre', 'Can edit or update but not delete general paediatric centre.'), ('can_delete_general_paediatric_centre', 'Can delete general paediatric centre.'), ('can_view_tertiary_neurology_centre', 'Can view tertiary neurology centre.'), ('can_allocate_tertiary_neurology_centre', 'Can allocate tertiary neurology centre.'), ('can_edit_tertiary_neurology_centre', 'Can edit or update but not delete tertiary neurology centre.'), ('can_delete_tertiary_neurology_centre', 'Can delete tertiary neurology centre.'), ('can_view_childrens_epilepsy_surgery_centre', "Can view children's epilepsy surgery centre."), ('can_allocate_childrens_epilepsy_surgery_centre', "Can allocate children's epilepsy surgery centre."), ('can_edit_childrens_epilepsy_surgery_centre', "Can edit or update but not delete children's epilepsy surgery centre."), ('can_delete_childrens_epilepsy_surgery_centre', "Can delete children's epilepsy surgery centre."), ('can_view_investigations_fields', 'Can view investigations.'), ('can_edit_investigations_fields', 'Can edit investigations.'), ('can_view_management_fields', 'Can view epilepsy management and care plans.'), ('can_edit_management_fields', 'Can edit or update epilepsy management and care plans.'), ('can_view_antiepilepsy_medicines', 'Can only view antiepilepsy medicines.'), ('can_edit_antiepilepsy_medicines', 'Can edit or update but not delete antiepilepsy medicines.'), ('can_delete_antiepilepsy_medicines', 'Can delete antiepilepsy medicines.'), ('can_view_rescue_medicines', 'Can only view rescue medicines.'), ('can_edit_rescue_medicines', 'Can edit or update but not delete rescue medicines.'), ('can_delete_rescue_medicines', 'Can delete rescue medicines.'), ('can_add_hospital_trusts', 'Can add a new hospital trust.'), ('can_edit_hospital_trusts', "Can edit or update a hospital trust's details."), ('can_delete_hospital_trusts', 'Can delete a hospital trust or its details.'), ('can_add_keywords', 'Can add new semiology key words.'), ('can_edit_keywords', 'Can edit or update but not delete semiology key words.'), ('can_delete_keywords', 'Can delete semiology key words.')), 'verbose_name': 'Epilepsy12 User', 'verbose_name_plural': 'Epilepsy12 Users'},
        ),
        migrations.AlterModelOptions(
            name='hospitaltrust',
            options={'ordering': ('OrganisationName',), 'verbose_name': 'Hospital Trust', 'verbose_name_plural': 'Hospital Trusts'},
        ),
        migrations.RemoveIndex(
            model_name='hospitaltrust',
            name='epilepsy12__ParentN_6c4b26_idx',
        ),
        migrations.AlterField(
            model_name='epilepsy12user',
            name='hospital_employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epilepsy12.hospitaltrust'),
        ),
        migrations.AddIndex(
            model_name='hospitaltrust',
            index=models.Index(fields=['OrganisationName'], name='epilepsy12__Organis_abe360_idx'),
        ),
    ]
