# Generated by Django 4.0.4 on 2022-07-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0002_desscribe_seizure_cause_mitochondrial_sctid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desscribe',
            name='epileptic_generalised_onset',
            field=models.CharField(blank=True, choices=[('AEM', 'Absence with eyelid myoclonia'), ('Aab', 'Atypical absence'), ('Ato', 'Atonic'), ('Clo', 'Clonic'), ('EpS', 'Epileptic spasms'), ('MAb', 'Myoclonic absence'), ('MAt', 'Myoclonic-atonic'), ('MTC', 'Myoclonic-tonic-clonic'), ('MyC', 'Myoclonic'), ('Oth', 'Other'), ('TAb', 'Typical absence'), ('TCl', 'Tonic-clonic'), ('Ton', 'Tonic')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_genetic',
            field=models.CharField(blank=True, choices=[('AnS', 'Angelman Syndrome'), ('ChA', 'Chromosomal abnormality'), ('DrS', 'Dravet syndrome'), ('GTD', 'Glucose Transporter Defect'), ('GeA', 'Gene abnormality'), ('ReS', 'Rett Syndrome')], default=None, max_length=3, null=True, verbose_name='main identified genetic cause of seizure(s)'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_immune_antibody',
            field=models.CharField(blank=True, choices=[('GAD', 'GAD'), ('MOG', 'MOG'), ('NMD', 'NMDAR'), ('Oth', 'Other'), ('TPO', 'TPO'), ('VGK', 'VGKC')], default=None, max_length=3, null=True, verbose_name='autoantibody identified as cause of seizure(s).'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_structural',
            field=models.CharField(blank=True, choices=[('FCD', 'Focal cortical dysplasia'), ('HyH', 'Hypothalamic Hamartoma'), ('LGT', 'Low grade tumour'), ('MCD', 'Malformations of Cortical Development'), ('NR', 'Not required'), ('StW', 'Sturge Weber'), ('TBI', 'Traumatic brain injury'), ('TbS', 'Tuberous Sclerosis'), ('TuO', 'Tumour (other)'), ('Vas', 'Vascular (eg arterial ischaemic stroke venous ischaemia cerebral haemorrhage)')], default=None, max_length=3, null=True, verbose_name='main identified structural cause of seizure(s)'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_structural_snomed_code',
            field=models.CharField(blank=True, choices=[('FCD', 'Focal cortical dysplasia'), ('HyH', 'Hypothalamic Hamartoma'), ('LGT', 'Low grade tumour'), ('MCD', 'Malformations of Cortical Development'), ('NR', 'Not required'), ('StW', 'Sturge Weber'), ('TBI', 'Traumatic brain injury'), ('TbS', 'Tuberous Sclerosis'), ('TuO', 'Tumour (other)'), ('Vas', 'Vascular (eg arterial ischaemic stroke venous ischaemia cerebral haemorrhage)')], default=None, max_length=3, null=True, verbose_name='SNOMED-CT code for main identified structural cause of seizure(s)'),
        ),
    ]
