# Generated by Django 4.1.1 on 2022-09-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0002_alter_site_case_alter_site_hospital_trust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epilepsy12user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Audit Centre Lead Clinician'), (2, 'Audit Centre Clinician'), (3, 'Audit Centre Administrator'), (4, 'RCPCH Audit Lead'), (5, 'RCPCH Audit Analyst'), (6, 'RCPCH Audit Administrator'), (7, 'RCPCH Audit Children and Family')], null=True),
        ),
    ]
