# Generated by Django 4.0 on 2022-04-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0002_alter_registration_lead_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='epilepsy_surgery_centre',
            field=models.CharField(max_length=100, null=True, verbose_name='epilepsy_surgical_centre'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='lead_hospital',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='lead_hospital'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='tertiary_paediatric_neurology_centre',
            field=models.CharField(default=None, max_length=100, verbose_name='tertiary_paediatric_neurology_centre'),
        ),
    ]
