# Generated by Django 4.0 on 2022-03-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0002_remove_initialassessment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialassessment',
            name='epilepsy_context',
        ),
    ]
