# Generated by Django 4.0.4 on 2022-05-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0002_alter_desscribe_generalised_onset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_other_details',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
