# Generated by Django 4.0.4 on 2022-05-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0003_alter_desscribe_focal_onset_other_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_other_details',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
