# Generated by Django 4.0 on 2022-04-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0003_alter_registration_epilepsy_surgery_centre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='epilepsy_surgery_centre',
            field=models.CharField(max_length=100, null=True, verbose_name='epilepsy_surgery_centre'),
        ),
    ]
