# Generated by Django 4.1.1 on 2022-09-25 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0003_alter_epilepsy12user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'permissions': (('can_allocate_general_paediatric_centre', 'Can allocate general paediatric centre.'), ('can_update_general_paediatric_centre', 'Can edit or update but not delete general paediatric centre.'), ('can_delete_general_paediatric_centre', 'Can delete general paediatric centre.'), ('can_allocate_tertiary_neurology_centre', 'Can allocate tertiary neurology centre.'), ('can_edit_tertiary_neurology_centre', 'Can edit or update but not delete tertiary neurology centre.'), ('can_delete_tertiary_neurology_centre', 'Can delete tertiary neurology centre.'), ('can_confirm_childrens_epilepsy_surgical_service_referral_criteria_met', "Can confirm children's epilepsy surgery centre referral criteria have been met."), ('can_allocate_childrens_epilepsy_surgery_centre', "Can allocate children's epilepsy surgery centre."), ('can_edit_childrens_epilepsy_surgery_centre', "Can edit or update but not delete children's epilepsy surgery centre."), ('can_delete_childrens_epilepsy_surgery_centre', "Can delete children's epilepsy surgery centre.")), 'verbose_name': 'Milestones', 'verbose_name_plural': 'Milestones'},
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'permissions': [('can_view_child_nhs_number', "Can view a child's NHS Number"), ('can_view_child_date_of_birth', "Can view a child's date of birth"), ('can_lock_child_case_data_from_editing', "Can lock a child's record from editing."), ('can_unlock_child_case_data_from_editing', "Can unlock a child's record from editing."), ('can_opt_out_child_from_inclusion_in_audit', "Can sanction an opt out from participating in the audit. Note all the child's date except Epilepsy12 unique identifier are irretrievably deleted."), ('can_only_view_child_case_data', "Can only view a child's demographic and case information."), ('can_consent_to_audit_participation', 'Can consent to participating in Epilepsy12.')], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'permissions': [('can_approve_eligibility', 'Can approve eligibility for Epilepsy12.'), ('can_remove_approval_of_eligibility', 'Can remove approval of eligibiltiy for Epilepsy12.'), ('can_register_child_in_epilepsy12', 'Can register child in Epilepsy12. (A cohort number is automatically allocaeted)'), ('can_unregister_child_in_epilepsy12', 'Can unregister a child in Epilepsy. Their record and previously entered data is untouched.')], 'verbose_name': 'Registration', 'verbose_name_plural': 'Registrations'},
        ),
    ]
