# Generated by Django 4.0 on 2022-03-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0003_remove_initialassessment_epilepsy_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epilepsycontext',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='epilepsycontext',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='epilepsycontext',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='epilepsycontext',
            name='updated_by',
        ),
    ]
