# Generated by Django 4.0.4 on 2022-05-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0003_alter_desscribe_epilepsy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desscribe',
            name='epilepsy_status',
            field=models.IntegerField(choices=[(0, 'epilepsy'), (1, 'nonepilepsy'), (2, 'unknown')], verbose_name='Is the episode(s) epileptic? Is this epilepsy?'),
        ),
    ]
