# Generated by Django 4.0 on 2022-04-14 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0003_investigation_management_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation_management',
            name='assessment',
        ),
        migrations.AddField(
            model_name='investigation_management',
            name='registration',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='epilepsy12.registration', verbose_name='Related Registration'),
        ),
    ]
