# Generated by Django 4.0 on 2022-04-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0004_remove_investigation_management_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='desscribe_complete',
            field=models.BooleanField(default=False),
        ),
    ]
