# Generated by Django 4.0.4 on 2022-05-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0004_alter_desscribe_focal_onset_other_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_atonic',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_automatisms',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_autonomic',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_behavioural_arrest',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_centrotemporal',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_clonic',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_cognitive',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_emotional',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_epileptic_spasms',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_focal_to_bilateral_tonic_clonic',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_frontal',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_gelastic',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_hyperkinetic',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_impaired_awareness',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_left',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_myoclonic',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_occipital',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_other',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_other_details',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_parietal',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_right',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_sensory',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_temporal',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_tonic',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='generalised_onset',
            field=models.CharField(blank=True, choices=[('TCl', 'Tonic-clonic'), ('Clo', 'Clonic'), ('Ton', 'Tonic'), ('MyC', 'Myoclonic'), ('MTC', 'Myoclonic-tonic-clonic'), ('MAt', 'Myoclonic-atonic'), ('Ato', 'Atonic'), ('EpS', 'Epileptic spasms'), ('TAb', 'Typical absence'), ('Aab', 'Atypical absence'), ('MAb', 'Myoclonic absence'), ('AEM', 'Absence with eyelid myoclonia'), ('Oth', 'Other')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='non_epileptic_seizure_type',
            field=models.CharField(blank=True, choices=[('SAS', 'Syncope And Anoxic Seizures'), ('BPP', 'Behavioral Psychological And Psychiatric Disorders'), ('SRC', 'Sleep Related Conditions'), ('PMD', 'Paroxysmal Movement Disorders'), ('MAD', 'Migraine Associated Disorders'), ('ME', 'Miscellaneous Events'), ('Oth', 'Other')], default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='nonepileptic_seizure_behavioural',
            field=models.CharField(blank=True, choices=[('a', 'Daydreaming /inattention'), ('b', 'Infantile gratification'), ('c', 'Eidetic imagery'), ('d', 'Tantrums and rage reactions'), ('e', 'Out of body experiences'), ('f', 'Panic attacks'), ('g', 'Dissociative states'), ('h', 'Non-epileptic seizures'), ('i', 'Hallucinations in psychiatric disorders'), ('j', 'Fabricated / factitious illness')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='nonepileptic_seizure_migraine',
            field=models.CharField(blank=True, choices=[('a', 'Migraine with visual aura'), ('b', 'Familial hemiplegic migraine'), ('c', 'Benign paroxysmal torticollis'), ('d', 'Benign paroxysmal vertigo'), ('e', 'Cyclical vomiting')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='nonepileptic_seizure_miscellaneous',
            field=models.CharField(blank=True, choices=[('a', 'Benign myoclonus of infancy and shuddering attacks'), ('b', 'Jitteriness'), ('c', 'Sandifer syndrome'), ('d', 'Non-epileptic head drops'), ('e', 'Spasmus nutans'), ('f', 'Raised intracranial pressure'), ('g', 'Paroxysmal extreme pain disorder'), ('h', 'Spinal myoclonus')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='nonepileptic_seizure_other',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='nonepileptic_seizure_paroxysmal',
            field=models.CharField(blank=True, choices=[('a', 'Tics'), ('b', 'Stereotypies'), ('c', 'Paroxysmal kinesigenic dyskinesia'), ('d', 'Paroxysmal nonkinesigenic dyskinesia'), ('e', 'Paroxysmal exercise induced dyskinesia'), ('f', 'Benign paroxysmal tonic upgaze'), ('g', 'Episodic ataxias'), ('h', 'Alternating hemiplegia'), ('i', 'Hyperekplexia'), ('j', 'Opsoclonus-myoclonus syndrome')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='nonepileptic_seizure_sleep',
            field=models.CharField(blank=True, choices=[('a', 'Sleep related rhythmic movement disorders'), ('b', 'Hypnogogic jerks'), ('c', 'Parasomnias'), ('d', 'REM sleep disorders'), ('e', 'Benign neonatal sleep myoclonus'), ('f', 'Periodic leg movements'), ('g', 'Narcolepsy-cataplexy')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='nonepileptic_seizure_syncope',
            field=models.CharField(blank=True, choices=[('a', 'Vasovagal syncope'), ('b', 'Reflex anoxic seizures'), ('c', 'Breath-holding attacks'), ('d', 'Hyperventilation syncope'), ('e', 'Compulsive valsalva'), ('f', 'Neurological syncope'), ('g', 'Imposed upper airways obstruction'), ('h', 'Orthostatic intolerance'), ('i', 'Long QT and cardiac syncope'), ('j', 'Hyper-cyanotic spells')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='nonepileptic_seizure_unknown_onset',
            field=models.CharField(blank=True, choices=[('TCl', 'Tonic-clonic'), ('EpS', 'Epileptic spasms'), ('BAr', 'Behaviour arrest'), ('Oth', 'Other')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_chromosomal_abnormality',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='main identified chromosomal cause of seizure(s)'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_gene_abnormality_snomed_code',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='SNOMED-CT code for main identified genetic cause of seizure(s)'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_immune',
            field=models.CharField(blank=True, choices=[('RaE', 'Rasmussen Encephalitis'), ('AnM', 'Antibody mediated')], default=None, max_length=3, verbose_name='main identified immune cause of seizure(s).'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_immune_antibody',
            field=models.CharField(blank=True, choices=[('VGK', 'VGKC'), ('NMD', 'NMDAR'), ('GAD', 'GAD'), ('TPO', 'TPO'), ('MOG', 'MOG'), ('Oth', 'Other')], default=None, max_length=3, verbose_name='autoantibody identified as cause of seizure(s).'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_immune_antibody_other',
            field=models.CharField(blank=True, default=None, max_length=250, verbose_name='other identified antibody not previously specified causing seizure(s).'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_immune_snomed_code',
            field=models.CharField(blank=True, default=None, max_length=250, verbose_name='SNOMED-CT code for main identified immune cause of seizure(s).'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_infectious',
            field=models.CharField(blank=True, default=None, max_length=250, verbose_name='main identified infectious cause of seizure(s)'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_infectious_snomed_code',
            field=models.CharField(blank=True, default=None, max_length=250, verbose_name='SNOMED-CT code for main identified infectious cause of seizure(s)'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_metabolic',
            field=models.CharField(blank=True, choices=[('Mit', 'Mitochondrial disorder'), ('Neu', 'Neuronal Ceroid Lipofuscinosis (Batten Disease)'), ('PPM', 'Disorder of pyridoxine/pyridoxal phosphate metabolism'), ('BiM', 'Disorder of biotin metabolism'), ('CrM', 'Disorder of creatine metabolism'), ('AmA', 'Disorder of amino acid'), ('UrA', 'Disorder of urea cycle'), ('PyP', 'Disorder of pyrimidine and purine'), ('Cho', 'Disorder of cholesterol'), ('Oth', 'Other neurometabolic disorder')], default=None, max_length=3, verbose_name='main identified metabolic cause of seizure(s)'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_metabolic_other',
            field=models.CharField(blank=True, default=None, max_length=250, verbose_name='other identified metabolic cause of seizure(s) not previously specified.'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_metabolic_snomed_code',
            field=models.CharField(blank=True, default=None, max_length=250, verbose_name='SNOMED-CT code for other identified metabolic cause of seizure(s) not previously specified.'),
        ),
    ]
