# Generated by Django 4.0.4 on 2022-07-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0004_alter_desscribe_syndrome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='epilepsy_surgery_centre',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='lead_hospital',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='tertiary_paediatric_neurology_centre',
        ),
        migrations.AddField(
            model_name='assessment',
            name='epilepsy_surgery_centre',
            field=models.CharField(max_length=100, null=True, verbose_name='epilepsy_surgery_centre'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='lead_hospital',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='lead_hospital'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='tertiary_paediatric_neurology_centre',
            field=models.CharField(default=None, max_length=100, verbose_name='tertiary_paediatric_neurology_centre'),
        ),
    ]
