# Generated by Django 4.0.4 on 2022-09-08 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0004_alter_case_options_alter_epilepsy12user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'permissions': [('can_view_child_nhs_number', "Can view a child's NHS Number"), ('can_view_child_date_of_birth', "Can view a child's date of birth"), ('can_delete_child_case_data', "Can irreversibly delete a child's case data."), ('can_update_child_case_data', "Can edit or update a child's case data."), ('can_lock_child_case_data_from_editing', "Can lock a child's record from editing."), ('can_unlock_child_case_data_from_editing', "Can unlock a child's record from editing."), ('can_opt_out_child_from_inclusion_in_audit', "Can sanction an opt out from participating in the audit. Note all the child's date except Epilepsy12 unique identifier are irretrievably deleted."), ('can_view_child_case_data', "Can view a child's demographic and case information."), ('can_consent_to_audit_participation', 'Can consent to participating in Epilepsy12.')], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelOptions(
            name='epilepsy12user',
            options={'verbose_name': 'Epilepsy12 User', 'verbose_name_plural': 'Epilepsy12 Users'},
        ),
    ]
