# Generated by Django 4.1.1 on 2022-09-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0004_alter_assessment_options_alter_case_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'permissions': (('can_only_view_general_paediatric_centre', 'Can only view general paediatric centre.'), ('can_only_view_tertiary_neurology_centre', 'Can only view tertiary neurology centre.'), ('can_only_view_childrens_epilepsy_surgery_centre', "Can only view children's epilepsy surgery centre."), ('can_allocate_general_paediatric_centre', 'Can allocate general paediatric centre.'), ('can_update_general_paediatric_centre', 'Can edit or update but not delete general paediatric centre.'), ('can_delete_general_paediatric_centre', 'Can delete general paediatric centre.'), ('can_allocate_tertiary_neurology_centre', 'Can allocate tertiary neurology centre.'), ('can_edit_tertiary_neurology_centre', 'Can edit or update but not delete tertiary neurology centre.'), ('can_delete_tertiary_neurology_centre', 'Can delete tertiary neurology centre.'), ('can_confirm_childrens_epilepsy_surgical_service_referral_criteria_met', "Can confirm children's epilepsy surgery centre referral criteria have been met."), ('can_allocate_childrens_epilepsy_surgery_centre', "Can allocate children's epilepsy surgery centre."), ('can_edit_childrens_epilepsy_surgery_centre', "Can edit or update but not delete children's epilepsy surgery centre."), ('can_delete_childrens_epilepsy_surgery_centre', "Can delete children's epilepsy surgery centre.")), 'verbose_name': 'Milestones', 'verbose_name_plural': 'Milestones'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'permissions': [('can_approve_eligibility', 'Can approve eligibility for Epilepsy12.'), ('can_remove_approval_of_eligibility', 'Can remove approval of eligibiltiy for Epilepsy12.'), ('can_register_child_in_epilepsy12', 'Can register child in Epilepsy12. (A cohort number is automatically allocaeted)'), ('can_unregister_child_in_epilepsy12', 'Can unregister a child in Epilepsy. Their record and previously entered data is untouched.'), ('can_only_view_general_paediatric_centre', 'Can only view general paediatric centre.'), ('can_allocate_general_paediatric_centre', 'Can allocate general paediatric centre.'), ('can_update_general_paediatric_centre', 'Can edit or update but not delete general paediatric centre.'), ('can_delete_general_paediatric_centre', 'Can delete general paediatric centre.')], 'verbose_name': 'Registration', 'verbose_name_plural': 'Registrations'},
        ),
    ]
