# Generated by Django 4.0.4 on 2022-09-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0005_alter_case_options_alter_epilepsy12user_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NonEpilepsy',
        ),
        migrations.AlterModelOptions(
            name='antiepilepsymedicine',
            options={'verbose_name': 'Antiepilepsy Medicine', 'verbose_name_plural': 'Antiepilepsy Medicines'},
        ),
        migrations.AlterModelOptions(
            name='assessment',
            options={'verbose_name': 'Milestones', 'verbose_name_plural': 'Milestones'},
        ),
        migrations.AlterModelOptions(
            name='management',
            options={'verbose_name': 'Management Plan', 'verbose_name_plural': 'Management Plans'},
        ),
    ]
