# Generated by Django 4.0 on 2022-04-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0005_registration_desscribe_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='desscribe_complete',
        ),
    ]
