# Generated by Django 4.0.4 on 2022-07-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0005_role_alter_epilepsy12user_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
