# Generated by Django 4.2 on 2023-04-24 11:46
import logging

from django.db import migrations

# Logging setup
logger = logging.getLogger(__name__)


def seed_epilepsy_causes(apps, schema_editor):
    """
    This returns all the snomed ct definitions and codes for epilepsy causes.
    Should be run periodically to compare with value in database and update record if has changed
    """

    # Get models
    EpilepsyCause = apps.get_model("epilepsy12", "EpilepsyCause")

    logger.info("\033[33m Seeding all the epilepsy causes from SNOMED... \033[33m")
    if EpilepsyCause.objects.count() > 150:
        logger.info("Causes already exist. Skipping this step...")
        return
    index = 0
    import json
    from django.conf import settings

    # settings.BASE_DIR points to 'rcpch-audit-engine'
    # .parent takes you up to the workspace root, then we navigate into epilepsy12
    path = settings.BASE_DIR / "epilepsy12" / "constants" / "epilepsycauses.json"
    with open(path, "r") as file:
        epilepsy_causes = json.load(file)
    for cause in epilepsy_causes:
        if EpilepsyCause.objects.filter(conceptId=cause["conceptId"]).exists():
            # duplicate conceptId
            pass
        else:
            new_cause = EpilepsyCause(
                conceptId=cause["conceptId"],
                term=cause["term"],
                preferredTerm=cause["preferredTerm"],
            )
            try:
                new_cause.save()
                index += 1
            except Exception as e:
                logger.info(f"Epilepsy cause {cause['preferredTerm']} not added. {e}")
    logger.info(f"{index} epilepsy causes added")


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0005_seed_organisations"),
    ]

    operations = [migrations.RunPython(seed_epilepsy_causes)]
