# Generated by Django 4.1.2 on 2022-10-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0005_alter_assessment_options_alter_registration_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='individualised_care_plan_includes_aihp',
        ),
    ]
