# Generated by Django 4.0 on 2022-03-20 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0005_alter_epilepsycontext_diagnosis_of_epilepsy_withdrawn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epilepsycontext',
            name='registration',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='epilepsy12.registration', verbose_name='Related Registration'),
        ),
    ]
