# Generated by Django 4.0.4 on 2022-05-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0005_alter_desscribe_focal_onset_atonic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desscribe',
            name='generalised_onset_other_details',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='nonepileptic_seizure_unknown_onset_other_details',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
