# Generated by Django 4.2 on 2023-04-24 13:24

from django.db import migrations

from ..constants import KEYWORDS
from ..models import Keyword


def seed_semiology_keywords(apps, schema_editor):
    added = 0
    print("\033[33m", "Seeding all the epilepsy semiology keywords...", "\033[33m")
    for index, semiology_keyword in enumerate(KEYWORDS):
        if Keyword.objects.filter(keyword=semiology_keyword["title"]).exists():
            print("Keywords already exist. Skipping this step...")
            return
        new_keyword = Keyword(
            keyword=semiology_keyword["title"], category=semiology_keyword["category"]
        )
        try:
            new_keyword.save()
        except Exception as e:
            print(f"Error at {semiology_keyword['title']}: error: {e}")
        added += 1
        print(
            f"added {semiology_keyword['title']} in category {semiology_keyword['category']}"
        )
    print(f"Keywords added: {added}")


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0006_seed_epilepsy_causes"),
    ]

    operations = [migrations.RunPython(seed_semiology_keywords)]
