# Generated by Django 4.0.4 on 2022-05-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0006_alter_desscribe_generalised_onset_other_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desscribe',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='What is the episode(s) like and is the description adequate?', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='epilepsy_or_nonepilepsy_status',
            field=models.CharField(blank=True, choices=[('E', 'Epilepsy'), ('NE', 'Non-epilepsy'), ('U', 'Uncertain')], default='E', max_length=3, verbose_name='Is a diagnosis of epilepsy definite, or uncertain.'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='epileptic_seizure_type',
            field=models.CharField(choices=[('FO', 'Focal onset'), ('GO', 'Generalised onset'), ('UO', 'Unknown onset'), ('UC', 'Unclassified')], default='FO', max_length=3, verbose_name='If epileptic, what is the seizure type (s)?'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_chromosomal_abnormality',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='main identified chromosomal cause of seizure(s)'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_gene_abnormality',
            field=models.CharField(blank=True, choices=[('UBE', 'UBE3A'), ('GLU', 'GLUT1'), ('SLC', 'SLC2A1'), ('MEC', 'MECP2'), ('SCN', 'SCN1A'), ('STX', 'STXBP1'), ('CDK', 'CDKL5'), ('KCN', 'KCNQ2'), ('SCN', 'SCN2A'), ('KCN', 'KCNT1'), ('ARX', 'ARX'), ('FOX', 'FOXG1'), ('PCD', 'PCDH19'), ('GRI', 'GRIN2A'), ('Oth', 'Other')], default=None, max_length=3, null=True, verbose_name='main identified gene abnormality cause of seizure(s)'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_gene_abnormality_snomed_code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='SNOMED-CT code for main identified genetic cause of seizure(s)'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_genetic',
            field=models.CharField(blank=True, choices=[('DrS', 'Dravet syndrome'), ('GTD', 'Glucose Transporter Defect'), ('AnS', 'Angelman Syndrome'), ('ReS', 'Rett Syndrome'), ('ChA', 'Chromosomal abnormality'), ('GeA', 'Gene abnormality')], default=None, max_length=3, null=True, verbose_name='main identified genetic cause of seizure(s)'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_genetic_other',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='other identified genetic cause of seizure(s) not previously specified.'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_immune',
            field=models.CharField(blank=True, choices=[('RaE', 'Rasmussen Encephalitis'), ('AnM', 'Antibody mediated')], default=None, max_length=3, null=True, verbose_name='main identified immune cause of seizure(s).'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_immune_antibody',
            field=models.CharField(blank=True, choices=[('VGK', 'VGKC'), ('NMD', 'NMDAR'), ('GAD', 'GAD'), ('TPO', 'TPO'), ('MOG', 'MOG'), ('Oth', 'Other')], default=None, max_length=3, null=True, verbose_name='autoantibody identified as cause of seizure(s).'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_immune_antibody_other',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='other identified antibody not previously specified causing seizure(s).'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_immune_snomed_code',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='SNOMED-CT code for main identified immune cause of seizure(s).'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_infectious',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='main identified infectious cause of seizure(s)'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_infectious_snomed_code',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='SNOMED-CT code for main identified infectious cause of seizure(s)'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_main',
            field=models.CharField(blank=True, choices=[('Str', 'Structural'), ('Gen', 'Genetic'), ('Inf', 'Infectious'), ('Met', 'Metabolic'), ('Imm', 'Immune'), ('NK', 'Not known')], default=None, max_length=3, null=True, verbose_name='main identified cause of seizure(s)'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_main_snomed_code',
            field=models.CharField(blank=True, choices=[('Str', 'Structural'), ('Gen', 'Genetic'), ('Inf', 'Infectious'), ('Met', 'Metabolic'), ('Imm', 'Immune'), ('NK', 'Not known')], default=None, max_length=3, null=True, verbose_name='SNOMED-CT code for main identified cause of seizure(s)'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_metabolic',
            field=models.CharField(blank=True, choices=[('Mit', 'Mitochondrial disorder'), ('Neu', 'Neuronal Ceroid Lipofuscinosis (Batten Disease)'), ('PPM', 'Disorder of pyridoxine/pyridoxal phosphate metabolism'), ('BiM', 'Disorder of biotin metabolism'), ('CrM', 'Disorder of creatine metabolism'), ('AmA', 'Disorder of amino acid'), ('UrA', 'Disorder of urea cycle'), ('PyP', 'Disorder of pyrimidine and purine'), ('Cho', 'Disorder of cholesterol'), ('Oth', 'Other neurometabolic disorder')], default=None, max_length=3, null=True, verbose_name='main identified metabolic cause of seizure(s)'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_metabolic_other',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='other identified metabolic cause of seizure(s) not previously specified.'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_metabolic_snomed_code',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='SNOMED-CT code for other identified metabolic cause of seizure(s) not previously specified.'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_structural',
            field=models.CharField(blank=True, choices=[('TbS', 'Tuberous Sclerosis'), ('StW', 'Sturge Weber'), ('FCD', 'Focal cortical dysplasia'), ('HyH', 'Hypothalamic Hamartoma'), ('LGT', 'Low grade tumour'), ('TuO', 'Tumour (other)'), ('MCD', 'Malformations of Cortical Development'), ('Vas', 'Vascular (eg arterial ischaemic stroke venous ischaemia cerebral haemorrhage)'), ('TBI', 'Traumatic brain injury'), ('NR', 'Not required')], default=None, max_length=3, null=True, verbose_name='main identified structural cause of seizure(s)'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='seizure_cause_structural_snomed_code',
            field=models.CharField(blank=True, choices=[('TbS', 'Tuberous Sclerosis'), ('StW', 'Sturge Weber'), ('FCD', 'Focal cortical dysplasia'), ('HyH', 'Hypothalamic Hamartoma'), ('LGT', 'Low grade tumour'), ('TuO', 'Tumour (other)'), ('MCD', 'Malformations of Cortical Development'), ('Vas', 'Vascular (eg arterial ischaemic stroke venous ischaemia cerebral haemorrhage)'), ('TBI', 'Traumatic brain injury'), ('NR', 'Not required')], default=None, max_length=3, null=True, verbose_name='SNOMED-CT code for main identified structural cause of seizure(s)'),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='syndrome',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Is there an identifiable epilepsy syndrome?'),
        ),
    ]
