# Generated by Django 4.2 on 2023-04-24 14:00

# Python

# Third-party Imports
from django.db import migrations

# RCPCH Imports
from ..models import ComorbidityEntity
from ..general_functions import fetch_paediatric_neurodisability_outpatient_diagnosis_simple_reference_set

def seed_comorbidities(apps, schema_editor):
    """
    This returns all the snomed ct definitions and codes for epilepsy causes.
    Should be run periodically to compare with value in database and update record if has changed
    """
    print('\033[33m', 'Seeding comorbidities from paediatric neurodisability reference set...', '\033[33m')
    if ComorbidityEntity.objects.count() > 0:
        print('Comorbidities already exist. Skipping...')
        return
    # ecl = '<< 35919005'
    # comorbidity_choices = fetch_ecl(ecl)
    comorbidity_choices = fetch_paediatric_neurodisability_outpatient_diagnosis_simple_reference_set()

    for index,comorbidity_choice in enumerate(comorbidity_choices):
        
        # filters out Autism-related entries
        if comorbidity_choice['conceptId'] == 35919005:
            print(f"Filtering out autism-related SNOMED conceptId: {comorbidity_choice['preferredTerm']}")
            continue
        
        new_comorbidity = ComorbidityEntity(
            conceptId=comorbidity_choice['conceptId'],
            term=comorbidity_choice['term'],
            preferredTerm=comorbidity_choice['preferredTerm'],
            description=None,
            snomed_ct_edition=None,
            snomed_ct_version=None,
            icd_code=None,
            icd_version=None,
            dsm_code=None,
            dsm_version=None,
        )
        try:
            new_comorbidity.save()
        except Exception as e:
            print(
                f"Comorbidity {comorbidity_choice.preferredTerm} not added. {e}")
    print(f"{index} comorbidities added")


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0006_seed_syndromes"),
    ]

    operations = [migrations.RunPython(seed_comorbidities)]
