# Generated by Django 4.0 on 2022-04-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0006_remove_registration_desscribe_complete'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hospitaltrust',
            name='epilepsy12__hospita_a838eb_idx',
        ),
        migrations.RemoveField(
            model_name='hospitaltrust',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hospitaltrust',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='hospitaltrust',
            name='hospital_trust_name',
        ),
        migrations.RemoveField(
            model_name='hospitaltrust',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hospitaltrust',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='hospitaltrust',
            name='Address1',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltrust',
            name='Address2',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltrust',
            name='Address3',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltrust',
            name='City',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltrust',
            name='County',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltrust',
            name='Email',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltrust',
            name='Fax',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltrust',
            name='IsPimsManaged',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltrust',
            name='Latitude',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltrust',
            name='Longitude',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltrust',
            name='OrganisationCode',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltrust',
            name='OrganisationID',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltrust',
            name='OrganisationName',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltrust',
            name='OrganisationStatus',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltrust',
            name='OrganisationType',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltrust',
            name='ParentName',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltrust',
            name='ParentODSCode',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltrust',
            name='Phone',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltrust',
            name='Postcode',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltrust',
            name='Sector',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltrust',
            name='SubType',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltrust',
            name='Website',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='hospitaltrust',
            index=models.Index(fields=['OrganisationName'], name='epilepsy12__Organis_abe360_idx'),
        ),
    ]
