# Generated by Django 4.0 on 2022-03-21 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0006_epilepsycontext_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comorbidity',
            name='epilepsy_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epilepsy_context_comorbidity', to='epilepsy12.epilepsycontext'),
        ),
    ]
