# Generated by Django 4.1.2 on 2022-10-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0007_alter_case_ethnicity_alter_case_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth (YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='case',
            name='nhs_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='NHS Number'),
        ),
        migrations.AlterField(
            model_name='case',
            name='postcode',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='postcode'),
        ),
        migrations.AlterField(
            model_name='case',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Known'), (1, 'Male'), (2, 'Female'), (9, 'Not Specified')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='surname'),
        ),
    ]
