# Generated by Django 4.0.4 on 2022-05-22 17:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0007_alter_desscribe_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desscribe',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='What is the episode(s) like and is the description adequate?', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='description_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='add a key word', max_length=500), blank=True, null=True, size=None),
        ),
    ]
