# Generated by Django 4.0 on 2022-03-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0007_alter_comorbidity_epilepsy_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comorbidity',
            name='epilepsy_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comorbidities', to='epilepsy12.epilepsycontext'),
        ),
    ]
