# Generated by Django 4.0 on 2022-04-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0008_alter_comorbidity_epilepsy_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='assessment_date',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='electroclinical_syndrome',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='investigations',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='nonepilepsy',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='seizure_causes',
        ),
        migrations.AddField(
            model_name='registration',
            name='assessment_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='experienced_prolonged_focal_seizures',
            field=models.BooleanField(default=False, verbose_name='Were there any prolonged focal seizures?'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='has_an_aed_been_given',
            field=models.BooleanField(default=False, verbose_name='Has an antiepilepsy medicine been given?'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='paroxysmal_episode',
            field=models.BooleanField(default=False, verbose_name='Were any episodes paroxysmal?'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='prolonged_generalized_convulsive_seizures',
            field=models.BooleanField(default=False, verbose_name='Were there any prolonged generalised epileptic seizures?'),
        ),
    ]
