# Generated by Django 4.0.4 on 2022-05-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0008_alter_desscribe_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desscribe',
            name='relevant_impairments_behavioural_educational',
            field=models.BooleanField(blank=True, default=None, max_length=50, null=True, verbose_name='Are there any relevant impairments: behavioural or educational, emotional problems?'),
        ),
    ]
