# Generated by Django 4.2.1 on 2023-05-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0008_seed_medicines"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinvestigations",
            name="eeg_request_date",
            field=models.DateField(
                blank=True,
                default=None,
                help_text={
                    "label": "Date EEG requested",
                    "reference": "Date EEG requested. Even if the EEG was not performed, a request date is still required.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmanagement",
            name="individualised_care_plan_addresses_sudep",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text={
                    "label": "Sudden unexpected death in epilepsy (SUDEP)",
                    "reference": "Does the individualised care plan address sudden unexpected death in epilepsy?",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="investigations",
            name="eeg_request_date",
            field=models.DateField(
                blank=True,
                default=None,
                help_text={
                    "label": "Date EEG requested",
                    "reference": "Date EEG requested. Even if the EEG was not performed, a request date is still required.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="care_planning_has_been_updated_when_necessary",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "iii. Care planning has been updated when necessary",
                    "reference": "Percentage of children and young people with epilepsy after 12 months where there is evidence that the care plan has been updated where necessary.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="first_aid",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "iii. First aid",
                    "reference": "Percentage of children and young people with epilepsy with evidence of discussion regarding first aid.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="general_participation_and_risk",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "iv. General participation and risk",
                    "reference": "Percentage of children and young people with epilepsy with evidence of discussion regarding general participation and risk.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="parental_prolonged_seizures_care_plan",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "i. Parental prolonged seizures care plan",
                    "reference": "Percentage of children and young people with epilepsy who have been prescribed rescue medication and have evidence of a written prolonged seizures plan.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="patient_carer_parent_agreement_to_the_care_planning",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "ii. Patient/carer/parent agreement to the care planning",
                    "reference": "Percentage of children and young people with epilepsy after 12 months where there was evidence of agreement between the person, their family and/or carers as appropriate.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="patient_held_individualised_epilepsy_document",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "i. Patient-held individualised epilepsy document/copy of clinic letter that includes care planning information",
                    "reference": "Percentage of children and young people with epilepsy after 12 months that had an individualised epilepsy document with individualised epilepsy document or a copy clinic letter that includes care planning information.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="service_contact_details",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "vi. Service contact details",
                    "reference": "Percentage of children and young people with epilepsy with evidence of being given service contact details.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="sudep",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "v. Sudden unexpected death in epilepsy",
                    "reference": "Percentage of children and young people with epilepsy with evidence of discussion regarding SUDEP (Sudden unexpected death in epilepsy) and evidence of a prolonged seizures care plan.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="water_safety",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "ii. Water safety",
                    "reference": "Percentage of children and young people with epilepsy with evidence of discussion regarding water safety.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="management",
            name="individualised_care_plan_addresses_sudep",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text={
                    "label": "Sudden unexpected death in epilepsy (SUDEP)",
                    "reference": "Does the individualised care plan address sudden unexpected death in epilepsy?",
                },
                null=True,
            ),
        ),
    ]
