# Generated by Django 4.2.1 on 2023-05-07 22:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0009_alter_historicalinvestigations_eeg_request_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryBoundaries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ctry22cd", models.CharField(max_length=9)),
                ("ctry22nm", models.CharField(max_length=16)),
                ("ctry22nmw", models.CharField(max_length=17)),
                ("bng_e", models.BigIntegerField()),
                ("bng_n", models.BigIntegerField()),
                ("long", models.FloatField()),
                ("lat", models.FloatField()),
                ("globalid", models.CharField(max_length=38)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegratedCareBoardBoundaries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icb23cd", models.CharField(max_length=9)),
                ("icb23nm", models.CharField(max_length=77)),
                ("bng_e", models.BigIntegerField()),
                ("bng_n", models.BigIntegerField()),
                ("long", models.FloatField()),
                ("lat", models.FloatField()),
                ("globalid", models.CharField(max_length=38)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocalHealthBoardBoundaries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lhb22cd", models.CharField(max_length=9)),
                ("lhb22nm", models.CharField(max_length=41)),
                ("lhb22nmw", models.CharField(max_length=40)),
                ("bng_e", models.FloatField()),
                ("bng_n", models.FloatField()),
                ("long", models.FloatField()),
                ("lat", models.FloatField()),
                ("globalid", models.CharField(max_length=38)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NHSEnglandRegionBoundaries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nhser20cd", models.CharField(max_length=9)),
                ("nhser20nm", models.CharField(max_length=24)),
                ("bng_e", models.BigIntegerField()),
                ("bng_n", models.BigIntegerField()),
                ("long", models.FloatField()),
                ("lat", models.FloatField()),
                ("globalid", models.CharField(max_length=38)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
    ]
