# Generated by Django 4.1.2 on 2022-10-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0010_alter_initialassessment_first_paediatric_assessment_in_acute_or_nonacute_setting'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='initialassessment',
            name='epilepsy12__date_of_e184d3_idx',
        ),
        migrations.RemoveField(
            model_name='initialassessment',
            name='date_of_initial_assessment',
        ),
        migrations.RemoveField(
            model_name='initialassessment',
            name='date_of_referral_to_general_paediatrics',
        ),
        migrations.RemoveField(
            model_name='initialassessment',
            name='diagnostic_status',
        ),
        migrations.RemoveField(
            model_name='initialassessment',
            name='general_paediatrics_referral_made',
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='has_description_of_the_episode_or_episodes_been_gathered',
            field=models.BooleanField(default=None, null=True, verbose_name='has a description of the episode(s) been gathered?'),
        ),
    ]
