# Generated by Django 4.2.1 on 2023-05-07 22:08

from django.db import migrations
from django.apps import apps as django_apps

import os
from django.contrib.gis.utils import LayerMapping

# Each key in the nhsenglandregionboundaries_mapping dictionary corresponds to
# a field in the NHSRegionBoundaries model.
nhsenglandregionboundaries_mapping = {
    "nhser20cd": "nhser20cd",
    "nhser20nm": "nhser20nm",
    "bng_e": "bng_e",
    "bng_n": "bng_n",
    "long": "long",
    "lat": "lat",
    "globalid": "GlobalID",
    "geom": "MULTIPOLYGON",
}

app_config = django_apps.get_app_config("epilepsy12")
app_path = app_config.path

NHS_England_Regions_April_2020_FEB_EN_2022 = os.path.join(
    app_path,
    "shape_files",
    "NHS_England_Regions_April_2020_FEB_EN_2022",
    "NHS_England_Regions_April_2020_FEB_EN.shp",
)


def load(apps, schema_editor, verbose=True):
    NHSEnglandRegionBoundaries = apps.get_model(
        "epilepsy12", "NHSEnglandRegionBoundaries"
    )
    lm = LayerMapping(
        NHSEnglandRegionBoundaries,
        NHS_England_Regions_April_2020_FEB_EN_2022,
        nhsenglandregionboundaries_mapping,
        transform=False,
        encoding="utf-8",
    )
    lm.save(strict=True, verbose=verbose)


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0010_countryboundaries_integratedcareboardboundaries_and_more"),
    ]

    operations = [migrations.RunPython(load)]
