# Generated by Django 4.2.5 on 2023-09-05 13:55

from django.db import migrations

from epilepsy12.common_view_functions import _seed_all_aggregation_models

def seed_kpi_aggregations(apps, schema_editor):
    
    _seed_all_aggregation_models()
    

class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0010_seed_medicines"),
    ]

    operations = [migrations.RunPython(seed_kpi_aggregations)]
