# Generated by Django 4.2.1 on 2023-05-08 06:30

import os
from django.db import migrations
from django.apps import apps as django_apps
from django.contrib.gis.utils import LayerMapping

countryboundaries_mapping = {
    "ctry22cd": "CTRY22CD",
    "ctry22nm": "CTRY22NM",
    "ctry22nmw": "CTRY22NMW",
    "bng_e": "BNG_E",
    "bng_n": "BNG_N",
    "long": "LONG",
    "lat": "LAT",
    "globalid": "GlobalID",
    "geom": "MULTIPOLYGON",
}

integratedcareboardboundaries_mapping = {
    "icb23cd": "ICB23CD",
    "icb23nm": "ICB23NM",
    "bng_e": "BNG_E",
    "bng_n": "BNG_N",
    "long": "LONG",
    "lat": "LAT",
    "globalid": "GlobalID",
    "geom": "MULTIPOLYGON",
}

localhealthboardboundaries_mapping = {
    "lhb22cd": "LHB22CD",
    "lhb22nm": "LHB22NM",
    "lhb22nmw": "LHB22NMW",
    "bng_e": "BNG_E",
    "bng_n": "BNG_N",
    "long": "LONG",
    "lat": "LAT",
    "globalid": "GlobalID",
    "geom": "MULTIPOLYGON",
}

app_config = django_apps.get_app_config("epilepsy12")
app_path = app_config.path

Countries_December_2022_UK_BUC = os.path.join(
    app_path,
    "shape_files",
    "Countries_December_2022_UK_BUC",
    "CTRY_DEC_2022_UK_BUC.shp",
)

Integrated_Care_Boards_April_2023_EN_BSC = os.path.join(
    app_path,
    "shape_files",
    "Integrated_Care_Boards_April_2023_EN_BSC",
    "ICB_APR_2023_EN_BSC.shp",
)

Local_Health_Boards_April_2022_WA_BUC_2022 = os.path.join(
    app_path,
    "shape_files",
    "Local_Health_Boards_April_2022_WA_BUC_2022",
    "LHB_APR_2022_WA_BUC.shp",
)


def load(apps, schema_editor, verbose=True):
    CountryBoundaries = apps.get_model("epilepsy12", "CountryBoundaries")
    lm = LayerMapping(
        CountryBoundaries,
        Countries_December_2022_UK_BUC,
        countryboundaries_mapping,
        transform=False,
        encoding="utf-8",
    )
    lm.save(strict=True, verbose=verbose)

    IntegratedCareBoardBoundaries = apps.get_model(
        "epilepsy12", "IntegratedCareBoardBoundaries"
    )
    lm = LayerMapping(
        IntegratedCareBoardBoundaries,
        Integrated_Care_Boards_April_2023_EN_BSC,
        integratedcareboardboundaries_mapping,
        transform=False,
        encoding="utf-8",
    )
    lm.save(strict=True, verbose=verbose)

    LocalHealthBoardBoundaries = apps.get_model(
        "epilepsy12", "LocalHealthBoardBoundaries"
    )
    lm = LayerMapping(
        LocalHealthBoardBoundaries,
        Local_Health_Boards_April_2022_WA_BUC_2022,
        localhealthboardboundaries_mapping,
        transform=False,
        encoding="utf-8",
    )
    lm.save(strict=True, verbose=verbose)


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0011_nhs_england_region_boundaries_seed"),
    ]

    operations = [migrations.RunPython(load)]
