# Generated by Django 4.0.4 on 2022-07-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0011_alter_registration_registration_close_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='paroxysmal_episode',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='childrens_epilepsy_surgical_service_input_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name="Date seen by children's epilepsy surgery service"),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='childrens_epilepsy_surgical_service_referral_criteria_met',
            field=models.BooleanField(default=False, null=True, verbose_name="Have the criteria for referral to a children's epilepsy surgery service been met?"),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='childrens_epilepsy_surgical_service_referral_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name="Date of referral to a children's epilepsy surgery service"),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='consultant_paediatrician_input_date',
            field=models.DateField(null=True, verbose_name='Date seen by a consultant paediatrician with an interest in epilepsy.'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='consultant_paediatrician_referral_date',
            field=models.DateField(null=True, verbose_name='Date of referral to a consultant paediatrician with an interest in epilepsy.'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='consultant_paediatrician_referral_made',
            field=models.BooleanField(default=False, null=True, verbose_name='Has a referral been made to a consultant paediatrician with an interest in epilepsy?'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='experienced_prolonged_focal_seizures',
            field=models.BooleanField(default=False, null=True, verbose_name='Were there any prolonged focal seizures?'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='has_an_aed_been_given',
            field=models.BooleanField(default=False, null=True, verbose_name='Has an antiepilepsy medicine been given?'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='paediatric_neurologist_input_date',
            field=models.DateField(null=True, verbose_name='Date seen by consultant paediatric neurologist.'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='paediatric_neurologist_referral_date',
            field=models.DateField(null=True, verbose_name='Date of referral to a consultant paediatric neurologist.'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='paediatric_neurologist_referral_made',
            field=models.BooleanField(default=False, null=True, verbose_name='Has a referral to a consultant paediatric neurologist been made?'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='prolonged_generalized_convulsive_seizures',
            field=models.BooleanField(default=False, null=True, verbose_name='Were there any prolonged generalised epileptic seizures?'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='rescue_medication_prescribed',
            field=models.BooleanField(default=False, null=True, verbose_name='Has a rescue medicine been prescribed?'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='were_any_of_the_epileptic_seizures_convulsive',
            field=models.BooleanField(default=False, null=True, verbose_name='Were any of the epileptic seizures convulsive?'),
        ),
    ]
