# Generated by Django 4.0.4 on 2022-05-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0011_alter_desscribe_focal_onset_atonic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desscribe',
            name='focal_onset_other_details',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
