# Generated by Django 4.2.5 on 2023-09-05 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0011_seed_kpi_aggregations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trust",
            options={
                "ordering": ("name",),
                "verbose_name": "Trust",
                "verbose_name_plural": "Trusts",
            },
        ),
        migrations.RenameField(
            model_name="trust",
            old_name="trust_name",
            new_name="name",
        ),
    ]
