# Generated by Django 4.1.2 on 2022-10-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0011_remove_initialassessment_epilepsy12__date_of_e184d3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialassessment',
            name='has_description_of_the_episode_or_episodes_been_gathered',
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='behavioural_or_emotional_problems',
            field=models.BooleanField(default=None, help_text={'label': 'Presence or absence of emotional or behavioural problems', 'reference': 'Has the presence or absence of emotional or behavioural problems been documented?'}, null=True),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='developmental_learning_or_schooling_problems',
            field=models.BooleanField(default=None, help_text={'label': 'Presence or absence of learning, developmental or educational difficulties', 'reference': 'Has the presence or absence of developmental, learning or school-based problems been recorded?'}, null=True),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='first_paediatric_assessment_in_acute_or_nonacute_setting',
            field=models.IntegerField(choices=[(1, 'Acute'), (2, 'Non-acute'), (3, "Don't know")], default=None, help_text={'label': 'Is the first paediatric assessment in an acute or nonacute setting?', 'reference': 'Is the first paediatric assessment in an acute or nonacute setting?'}, null=True),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='general_examination_performed',
            field=models.BooleanField(default=None, help_text={'label': 'General examination', 'reference': 'has a general paediatric examination been performed?'}, null=True),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='has_number_of_episodes_since_the_first_been_documented',
            field=models.BooleanField(default=None, help_text={'label': 'The approximate frequency or number of episodes since the first episode', 'reference': 'Has the approximate frequency or number of episodes since the first recorded episode been documented?'}, null=True),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='neurological_examination_performed',
            field=models.BooleanField(default=None, help_text={'label': 'Neurological examination', 'reference': 'Has a neurological examination been performed?'}, null=True),
        ),
    ]
