# Generated by Django 4.2.7 on 2023-11-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0012_alter_countrykpiaggregation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nationalkpiaggregation",
            name="cohort",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
