# Generated by Django 4.1.2 on 2022-10-18 10:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0012_remove_initialassessment_has_description_of_the_episode_or_episodes_been_gathered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='childrens_epilepsy_surgical_service_input_date',
            field=models.DateField(blank=True, default=None, help_text={'label': "Date seen by children's epilepsy surgery service", 'reference': "Date seen by children's epilepsy surgery service"}, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='childrens_epilepsy_surgical_service_referral_date',
            field=models.DateField(blank=True, default=None, help_text={'label': "Date of referral to a children's epilepsy surgery service", 'reference': "Date of referral to a children's epilepsy surgery service"}, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='childrens_epilepsy_surgical_service_referral_made',
            field=models.BooleanField(blank=True, default=None, help_text={'label': "Has a referral to a children's epilepsy surgery service been made?", 'reference': "Has a referral to a children's epilepsy surgery service been made?"}, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='consultant_paediatrician_input_date',
            field=models.DateField(blank=True, default=None, help_text={'label': 'Date seen by a consultant paediatrician with expertise in epilepsies.', 'reference': 'Date seen by a consultant paediatrician with expertise in epilepsies.'}, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='consultant_paediatrician_referral_date',
            field=models.DateField(blank=True, default=None, help_text={'label': 'Date of referral to a consultant paediatrician with expertise in epilepsies.', 'reference': 'Has a referral been made to a consultant paediatrician with expertise in epilepsies?'}, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='consultant_paediatrician_referral_made',
            field=models.BooleanField(blank=True, default=None, help_text={'label': 'Has a referral been made to a consultant paediatrician with expertise in epilepsies?', 'reference': 'Has a referral been made to a consultant paediatrician with expertise in epilepsies?'}, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='epilepsy_specialist_nurse_input_date',
            field=models.DateField(blank=True, default=None, help_text={'label': 'Date seen by an epilepsy nurse specialist', 'reference': 'Date seen by an epilepsy nurse specialist'}, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='epilepsy_specialist_nurse_referral_date',
            field=models.DateField(blank=True, default=None, help_text={'label': 'Date of referral to an epilepsy nurse specialist', 'reference': 'Date of referral to an epilepsy nurse specialist'}, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='epilepsy_specialist_nurse_referral_made',
            field=models.BooleanField(blank=True, default=None, help_text={'label': 'Has a referral to an epilepsy nurse specialist been made?', 'reference': 'Has a referral to an epilepsy nurse specialist been made?'}, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='paediatric_neurologist_input_date',
            field=models.DateField(blank=True, default=None, help_text={'label': 'Date seen by consultant paediatric neurologist.', 'reference': 'Date seen by consultant paediatric neurologist.'}, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='paediatric_neurologist_referral_date',
            field=models.DateField(blank=True, default=None, help_text={'label': 'Date of referral to a consultant paediatric neurologist.', 'reference': 'Date of referral to a consultant paediatric neurologist.'}, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='paediatric_neurologist_referral_made',
            field=models.BooleanField(blank=True, default=None, help_text={'label': 'Has a referral to a consultant paediatric neurologist been made?', 'reference': 'Has a referral to a consultant paediatric neurologist been made?'}, null=True),
        ),
        migrations.AlterField(
            model_name='comorbidity',
            name='comorbidity_diagnosis',
            field=models.CharField(default=None, help_text={'label': 'What is the comorbidity?', 'reference': 'What is the comorbidity?'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comorbidity',
            name='comorbidity_diagnosis_date',
            field=models.DateField(default=None, help_text={'label': 'What is the date of diagnosis?', 'reference': 'What is the date of diagnosis?'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='epilepsycontext',
            name='diagnosis_of_epilepsy_withdrawn',
            field=models.BooleanField(default=None, help_text={'label': 'has the diagnosis of epilepsy been withdrawn?', 'reference': 'In the first year after first assessment, has a diagnosis of epilepsy been withdrawn because it has been subsequently deemed incorrect?'}, null=True),
        ),
        migrations.AlterField(
            model_name='epilepsycontext',
            name='experienced_prolonged_focal_seizures',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Uncertain')], default=None, help_text={'label': 'Has the child at any point in time experienced prolonged focal seizures?', 'reference': 'Has the child at any point in time experienced prolonged focal convulsive seizures > 5 min duration (or successive continuing > 5min)?'}, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='epilepsycontext',
            name='experienced_prolonged_generalized_convulsive_seizures',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Uncertain')], default=None, help_text={'label': 'Has the child at any point in time experienced prolonged generalised seizures?', 'reference': 'Has the child at any point in time experienced prolonged generalised convulsive seizures > 5 min duration (or successive continuing > 5min)?'}, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='epilepsycontext',
            name='is_there_a_family_history_of_epilepsy',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Uncertain')], default=None, help_text={'label': 'Is there a family history of epilepsy?', 'reference': 'Is there a family history of epilepsy?'}, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='epilepsycontext',
            name='previous_acute_symptomatic_seizure',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Uncertain')], default=None, help_text={'label': 'At any point in time has the child had acute symptomatic seizure(s)?', 'reference': 'At any point in time has the child had acute symptomatic seizure(s)?'}, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='epilepsycontext',
            name='previous_febrile_seizure',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Uncertain')], default=None, help_text={'label': 'At any point in time has the child had febrile seizure(s)?', 'reference': 'At any point in time has the child had febrile seizure(s)?'}, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='epilepsycontext',
            name='previous_neonatal_seizures',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Uncertain')], default=None, help_text={'label': 'Were there seizures in the neonatal period?', 'reference': 'Were there seizures in the neonatal period?'}, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.CharField(blank=True, default='', help_text={'label': 'What is the episode(s) like and is the description adequate?', 'reference': 'What is the episode(s) like and is the description adequate?'}, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='epilepsy_or_nonepilepsy_status',
            field=models.CharField(blank=True, choices=[('E', 'Epileptic'), ('NE', 'Non-epileptic'), ('U', 'Uncertain')], default=None, help_text={'label': 'Is a diagnosis of epilepsy definite, or uncertain.', 'reference': 'Is a diagnosis of epilepsy definite, or uncertain.'}, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='epileptic_seizure_onset_type',
            field=models.CharField(choices=[('FO', 'Focal onset'), ('GO', 'Generalised onset'), ('UO', 'Unknown onset'), ('UC', 'Unclassified')], default=None, help_text={'label': 'How best would describe the onset of the epileptic episode?', 'reference': 'How best would describe the onset of the epileptic episode?'}, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_definition',
            field=models.CharField(choices=[('a', 'This was a single episode'), ('b', 'This was a cluster within 24 hours'), ('c', 'These were 2 or more episodes more than 24 hours apart'), ('d', 'The patient was diagnosed as having epilepsy for another reason')], default=None, help_text={'label': 'Episode definition', 'reference': 'Episode definition. Part of case definition and defines if represents a cluster or discrete episodes.'}, max_length=1, null=True, verbose_name='Episode definition. Part of case definition and defines if represents a cluster or discrete episodes.'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='has_description_of_the_episode_or_episodes_been_gathered',
            field=models.BooleanField(default=None, help_text={'label': 'Has a description of the episode or episodes been gathered?', 'reference': 'Has a description of the episode or episodes been gathered?'}, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='has_number_of_episodes_since_the_first_been_documented',
            field=models.BooleanField(default=None, help_text={'label': 'Has the frequency of episodes since the first recorded been documented?', 'reference': 'Has the frequency of episodes since the first recorded been documented?'}, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='nonepileptic_seizure_type',
            field=models.CharField(blank=True, choices=[('SAS', 'Syncope And Anoxic Seizures'), ('BPP', 'Behavioral Psychological And Psychiatric Disorders'), ('SRC', 'Sleep Related Conditions'), ('PMD', 'Paroxysmal Movement Disorders'), ('MAD', 'Migraine Associated Disorders'), ('ME', 'Miscellaneous Events'), ('Oth', 'Other')], default=None, help_text={'label': 'How best describes the generalised nature of the nonepileptic episode(s)?', 'reference': 'How best describes the generalised nature of the nonepileptic episode(s)?'}, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='seizure_onset_date',
            field=models.DateField(blank=True, default=None, help_text={'label': 'When did the episode happen?', 'reference': 'Date the episode occurred or was witnessed.'}, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='seizure_onset_date_confidence',
            field=models.CharField(choices=[('Apx', 'Approximate date'), ('Exc', 'Exact date'), ('NK', 'Not known')], default=None, help_text={'label': 'Confidence in reported date of episode', 'reference': 'How accurate is the date of this episode?'}, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='were_any_of_the_epileptic_seizures_convulsive',
            field=models.BooleanField(default=None, help_text={'label': 'Were any of the epileptic seizures convulsive?', 'reference': 'Were any of the epileptic seizures convulsive?'}, null=True),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='ct_head_scan_status',
            field=models.BooleanField(blank=True, default=None, help_text={'label': 'Has a CT head been performed?', 'reference': 'Has a CT head been performed?'}, null=True),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='eeg_indicated',
            field=models.BooleanField(blank=True, default=None, help_text={'label': 'Is an EEG indicated?', 'reference': 'Is an EEG indicated?'}, null=True),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='eeg_performed_date',
            field=models.DateField(blank=True, default=None, help_text={'label': 'Date EEG performed', 'reference': 'Date EEG performed'}, null=True),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='eeg_request_date',
            field=models.DateField(blank=True, default=None, help_text={'label': 'Date EEG requested', 'reference': 'Date EEG requested'}, null=True),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='mri_brain_performed_date',
            field=models.DateField(blank=True, default=None, help_text={'label': 'MRI brain performed date', 'reference': 'MRI brain performed date'}, null=True),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='mri_brain_requested_date',
            field=models.DateField(blank=True, default=None, help_text={'label': 'MRI brain requested date', 'reference': 'MRI brain requested date'}, null=True),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='mri_indicated',
            field=models.BooleanField(blank=True, default=None, help_text={'label': 'Is an MRI brain indicated?', 'reference': 'Is an MRI brain indicated?'}, null=True),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='twelve_lead_ecg_status',
            field=models.BooleanField(blank=True, default=None, help_text={'label': 'Has a 12-Lead ECG been performed', 'reference': 'Has a 12-Lead ECG been performed'}, null=True),
        ),
        migrations.AlterField(
            model_name='multiaxialdiagnosis',
            name='epilepsy_cause',
            field=models.CharField(blank=True, default=None, help_text={'label': 'What is the main identified cause of the epilepsy?', 'reference': 'What is the main identified cause of the epilepsy?'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='multiaxialdiagnosis',
            name='epilepsy_cause_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, help_text={'label': 'Which category/categories best apply to this epilepsy?', 'reference': 'Which category/categories best apply to this epilepsy?'}, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='multiaxialdiagnosis',
            name='epilepsy_cause_known',
            field=models.BooleanField(blank=True, default=None, help_text={'label': 'Has a cause for the epilepsy been identified?', 'reference': 'Has a cause for the epilepsy been identified?'}, null=True),
        ),
        migrations.AlterField(
            model_name='multiaxialdiagnosis',
            name='relevant_impairments_behavioural_educational',
            field=models.BooleanField(blank=True, default=None, help_text={'label': 'Are there any relevant impairment, behavioural, educational or emotional problems?', 'reference': 'Are there any relevant impairment, behavioural, educational or emotional problems?'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='multiaxialdiagnosis',
            name='syndrome_present',
            field=models.BooleanField(blank=True, default=None, help_text={'label': 'Is there an identifiable epilepsy syndrome?', 'reference': 'Is there an identifiable epilepsy syndrome?'}, null=True),
        ),
        migrations.AlterField(
            model_name='syndrome',
            name='syndrome_diagnosis_active',
            field=models.BooleanField(default=None, help_text={'label': 'Is the diagnosis of the syndrome still relevant?', 'reference': 'Is the diagnosis of the syndrome still relevant?'}, null=True),
        ),
        migrations.AlterField(
            model_name='syndrome',
            name='syndrome_diagnosis_date',
            field=models.DateField(blank=True, default=None, help_text={'label': 'The date the syndrome diagnosis was made.', 'reference': 'The date the syndrome diagnosis was made.'}, null=True),
        ),
        migrations.AlterField(
            model_name='syndrome',
            name='syndrome_name',
            field=models.IntegerField(blank=True, choices=[(27, 'CDKL5-DEE'), (16, 'Childhood absence epilepsy'), (5, 'Childhood occipital visual epilepsy'), (34, 'DEE or EE with spike-and-wave activation in sleep'), (23, 'Dravet syndrome'), (20, 'Early infantile DEE'), (21, 'Epilepsy of infancy with migrating focal seizures'), (11, 'Epilepsy with auditory features'), (15, 'Epilepsy with eyelid myoclonia'), (19, 'Epilepsy with generalized tonic–clonic seizures alone'), (14, 'Epilepsy with myoclonic absences'), (32, 'Epilepsy with myoclonic–atonic seizures'), (39, 'Epilepsy with reading-induced seizures'), (24, 'Etiology-specific DEEs'), (10, 'Familial focal epilepsy with variable foci'), (8, 'Familial mesial temporal lobe epilepsy'), (35, 'Febrile infection-related epilepsy syndrome'), (29, 'GLUT1DS-DEE'), (31, 'Gelastic seizures with HH'), (12, 'Genetic epilepsy with febrile seizures plus'), (36, 'Hemiconvulsion–hemiplegia–epilepsy'), (22, 'Infantile epileptic spasms syndrome'), (17, 'Juvenile absence epilepsy'), (18, 'Juvenile myoclonic epilepsy'), (25, 'KCNQ2-DEE'), (33, 'Lennox–Gastaut syndrome'), (7, 'Mesial temporal lobe epilepsy with hippocampal sclerosis'), (13, 'Myoclonic epilepsy in infancy'), (28, 'PCDH19 clustering epilepsy'), (6, 'Photosensitive occipital lobe epilepsy'), (38, 'Progressive myoclonus epilepsies'), (26, 'Pyridoxine-dependent and pyridox(am)ine 5′ phosphate deficiency DEE'), (37, 'Rasmussen syndrome'), (1, 'Self-limited (familial) infantile epilepsy'), (0, 'Self-limited (familial) neonatal epilepsy'), (4, 'Self-limited epilepsy with autonomic seizures'), (3, 'Self-limited epilepsy with centrotemporal spikes'), (2, 'Self-limited familial neonatal-infantile epilepsy'), (9, 'Sleep-related hypermotor (hyperkinetic) epilepsy'), (30, 'Sturge–Weber syndrome')], default=None, help_text={'label': 'Select an identifiable epilepsy syndrome?', 'reference': 'Select an identifiable epilepsy syndrome?'}, null=True),
        ),
    ]
