# Generated by Django 4.2.1 on 2023-06-04 22:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import epilepsy12.models_folder.help_text_mixin


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0012_remaining_boundaries_seed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorganisation",
            name="Geocode_Coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, default=None, null=True, srid=27700
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="Geocode_Coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, default=None, null=True, srid=27700
            ),
        ),
        migrations.CreateModel(
            name="KPIAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paediatrician_with_expertise_in_epilepsies",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "paediatrician_with_expertise_in_epilepsies_average",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "paediatrician_with_expertise_in_epilepsies_total",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_specialist_nurse",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_specialist_nurse_average",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_specialist_nurse_total",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "tertiary_input",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "tertiary_input_average",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "tertiary_input_total",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_surgery_referral",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_surgery_referral_average",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_surgery_referral_total",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "ecg",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "ecg_average",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "ecg_total",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mri",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mri_average",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mri_total",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "assessment_of_mental_health_issues",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "assessment_of_mental_health_issues_average",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "assessment_of_mental_health_issues_total",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mental_health_support",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mental_health_support_average",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mental_health_support_total",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sodium_valproate",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sodium_valproate_average",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sodium_valproate_total",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_agreement",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_agreement_average",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_agreement_total",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_held_individualised_epilepsy_document",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_held_individualised_epilepsy_document_average",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_held_individualised_epilepsy_document_total",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_carer_parent_agreement_to_the_care_planning",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_carer_parent_agreement_to_the_care_planning_average",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_carer_parent_agreement_to_the_care_planning_total",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "care_planning_has_been_updated_when_necessary",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "care_planning_has_been_updated_when_necessary_average",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "care_planning_has_been_updated_when_necessary_total",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_content",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_content_average",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_content_total",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "parental_prolonged_seizures_care_plan",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "parental_prolonged_seizures_care_plan_average",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "parental_prolonged_seizures_care_plan_total",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "water_safety",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "water_safety_average",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "water_safety_total",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "first_aid",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "first_aid_average",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "first_aid_total",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "general_participation_and_risk",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "general_participation_and_risk_average",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "general_participation_and_risk_total",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "service_contact_details",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "service_contact_details_average",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "service_contact_details_total",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sudep",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sudep_average",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sudep_total",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "school_individual_healthcare_plan",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "school_individual_healthcare_plan_average",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "school_individual_healthcare_plan_total",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "total_number_of_cases",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "abstraction_level",
                    models.CharField(
                        choices=[
                            ("organisation", "Organisation"),
                            ("trust", "Trust/Local Health Board"),
                            ("icb", "Integrated Care Board"),
                            ("open_uk", "OPEN UK region"),
                            ("nhs_region", "NHS England Region"),
                            ("country", "Country"),
                            ("national", "National"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "open_access",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="epilepsy12.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI Aggregation Result ",
                "verbose_name_plural": "KPI Aggregation Results ",
            },
            bases=(
                models.Model,
                epilepsy12.models_folder.help_text_mixin.HelpTextMixin,
            ),
        ),
    ]
