# Generated by Django 4.0.4 on 2022-05-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0012_alter_desscribe_focal_onset_other_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desscribe',
            old_name='non_epileptic_seizure_type',
            new_name='nonepileptic_seizure_type',
        ),
    ]
