# Generated by Django 4.0.4 on 2022-07-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0013_alter_assessment_tertiary_paediatric_neurology_centre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialassessment',
            name='behavioural_or_emotional_problems',
            field=models.BooleanField(default=False, null=True, verbose_name='are there any behaviour or emotional comorbid conditions present?'),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='date_of_initial_assessment',
            field=models.DateField(default=None, null=True, verbose_name='On what date did the initial assessment occur?'),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='date_of_referral_to_general_paediatrics',
            field=models.DateField(default=None, null=True, verbose_name='date of referral to general paediatrics'),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='developmental_learning_or_schooling_problems',
            field=models.BooleanField(default=False, null=True, verbose_name='has the presence or absence of developmental, learning or school-based problems been recorded?'),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='diagnostic_status',
            field=models.CharField(choices=[('a', 'The child has had an episode or episodes where one or more are considered epileptic'), ('b', 'The child has had an episode or episodes that are considered non-epileptic only'), ('c', 'The child has had an episode or episodes where there remains uncertainty whether episodes were epileptic or not.')], default=None, max_length=1, null=True, verbose_name='Status of epilepsy diagnosis. Must have epilepsy or probable epilepsy to be included.'),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='first_paediatric_assessment_in_acute_or_nonacute_setting',
            field=models.IntegerField(choices=[(1, 'Acute'), (2, 'Non-acute'), (3, "Don't know")], default=None, null=True, verbose_name='Is the first paediatric assessment in an acute or nonacute setting?'),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='general_examination_performed',
            field=models.BooleanField(default=False, null=True, verbose_name='has a general clinical examination been performed?'),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='has_description_of_the_episode_or_episodes_been_gathered',
            field=models.BooleanField(default=False, null=True, verbose_name='has a description of the episode or episodes been gathered?'),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='has_number_of_episodes_since_the_first_been_documented',
            field=models.BooleanField(default=False, null=True, verbose_name='has the frequency of episodes since the first recorded been documented?'),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='neurological_examination_performed',
            field=models.BooleanField(default=False, null=True, verbose_name='has a neurological examination been performed?'),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='when_the_first_epileptic_episode_occurred',
            field=models.DateField(default=None, null=True, verbose_name='what is the date that the first epileptic episode occurred?'),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='when_the_first_epileptic_episode_occurred_confidence',
            field=models.CharField(choices=[('Apx', 'Approximate date'), ('Exc', 'Exact date'), ('NK', 'Not known')], default=None, max_length=3, null=True, verbose_name='how accurate is the date of the first epileptic episode?'),
        ),
    ]
