# Generated by Django 4.2.7 on 2023-11-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0013_alter_nationalkpiaggregation_cohort"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsite",
            name="active_transfer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalsite",
            name="transfer_request_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="active_transfer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="site",
            name="transfer_request_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
