# Generated by Django 4.0.4 on 2022-05-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0013_rename_non_epileptic_seizure_type_desscribe_nonepileptic_seizure_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desscribe',
            old_name='epileptic_seizure_type',
            new_name='epileptic_seizure_onset_type',
        ),
        migrations.AlterField(
            model_name='desscribe',
            name='nonepileptic_seizure_behavioural',
            field=models.CharField(blank=True, choices=[('a', 'Daydreaming / Inattention'), ('b', 'Infantile gratification'), ('c', 'Eidetic imagery'), ('d', 'Tantrums and rage reactions'), ('e', 'Out of body experiences'), ('f', 'Panic attacks'), ('g', 'Dissociative states'), ('h', 'Non-epileptic seizures'), ('i', 'Hallucinations in psychiatric disorders'), ('j', 'Fabricated / factitious illness')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='nonepilepsy',
            name='nonepilepsy_behavioural_symptoms',
            field=models.CharField(choices=[('a', 'Daydreaming / Inattention'), ('b', 'Infantile gratification'), ('c', 'Eidetic imagery'), ('d', 'Tantrums and rage reactions'), ('e', 'Out of body experiences'), ('f', 'Panic attacks'), ('g', 'Dissociative states'), ('h', 'Non-epileptic seizures'), ('i', 'Hallucinations in psychiatric disorders'), ('j', 'Fabricated / factitious illness')], max_length=3, verbose_name='Type of behavioural arrest described.'),
        ),
        migrations.AlterField(
            model_name='seizuretype',
            name='nonepileptic_seizure_behavioural',
            field=models.CharField(choices=[('a', 'Daydreaming / Inattention'), ('b', 'Infantile gratification'), ('c', 'Eidetic imagery'), ('d', 'Tantrums and rage reactions'), ('e', 'Out of body experiences'), ('f', 'Panic attacks'), ('g', 'Dissociative states'), ('h', 'Non-epileptic seizures'), ('i', 'Hallucinations in psychiatric disorders'), ('j', 'Fabricated / factitious illness')], default=None, max_length=3),
        ),
    ]
