# Generated by Django 4.0.4 on 2022-09-03 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0013_multiaxialdiagnosis_epilepsy_cause_known_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiepilepsymedicine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='record created on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='antiepilepsymedicine',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record craeted by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='antiepilepsymedicine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='record updated on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='antiepilepsymedicine',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='record created on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record craeted by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='record updated on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='record created on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record craeted by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='record updated on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='case',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='comorbidity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='record created on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='comorbidity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record craeted by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='comorbidity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='record updated on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='comorbidity',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='epilepsycontext',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='record created on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='epilepsycontext',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record craeted by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='epilepsycontext',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='record updated on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='epilepsycontext',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='record created on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record craeted by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='record updated on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='record created on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record craeted by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='record updated on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='record created on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record craeted by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='record updated on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='management',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='record created on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='management',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record craeted by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='management',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='record updated on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='management',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='multiaxialdiagnosis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='record created on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='multiaxialdiagnosis',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record craeted by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='multiaxialdiagnosis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='record updated on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='multiaxialdiagnosis',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='record created on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record craeted by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='record updated on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='site',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='record created on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='site',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record craeted by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='site',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='record updated on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='site',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='syndrome',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='record created on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='syndrome',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record craeted by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='syndrome',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='record updated on <function now at 0x109e80f70>'),
        ),
        migrations.AlterField(
            model_name='syndrome',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
    ]
