# Generated by Django 4.1.2 on 2022-10-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0013_alter_assessment_childrens_epilepsy_surgical_service_input_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='were_any_of_the_epileptic_seizures_convulsive',
        ),
        migrations.AddField(
            model_name='epilepsycontext',
            name='were_any_of_the_epileptic_seizures_convulsive',
            field=models.BooleanField(default=None, help_text={'label': 'Were any of the epileptic seizures convulsive?', 'reference': 'Were any of the epileptic seizures convulsive?'}, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='seizure_onset_date',
            field=models.DateField(blank=True, default=None, help_text={'label': 'When did the first episode of this type happen?', 'reference': 'Date the first episode of this type occurred or was witnessed.'}, null=True),
        ),
    ]
