# Generated by Django 4.0.4 on 2022-05-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0014_rename_epileptic_seizure_type_desscribe_epileptic_seizure_onset_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desscribe',
            old_name='generalised_onset',
            new_name='epileptic_generalised_onset',
        ),
        migrations.RenameField(
            model_name='desscribe',
            old_name='generalised_onset_other_details',
            new_name='epileptic_generalised_onset_other_details',
        ),
    ]
