# Generated by Django 4.0.4 on 2022-07-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0014_alter_initialassessment_behavioural_or_emotional_problems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialassessment',
            name='general_paediatrics_referral_made',
            field=models.BooleanField(default=False, null=True, verbose_name='date of referral to general paediatrics'),
        ),
    ]
