# Generated by Django 4.2.7 on 2023-11-05 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0014_historicalsite_active_transfer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsite",
            name="transfer_origin_organisation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="epilepsy12.organisation",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="transfer_origin_organisation",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="origin_organisation",
                to="epilepsy12.organisation",
            ),
        ),
    ]
