# Generated by Django 4.2.2 on 2023-06-16 13:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0014_remove_epilepsy12user_bio_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="epilepsy12user",
            old_name="is_clinician",
            new_name="is_rcpch_staff",
        ),
        migrations.RenameField(
            model_name="historicalepilepsy12user",
            old_name="is_clinician",
            new_name="is_rcpch_staff",
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="Geocode_Coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, default=None, null=True, srid=27700
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="Geocode_Coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, default=None, null=True, srid=27700
            ),
        ),
    ]
