# Generated by Django 4.0.4 on 2022-07-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0015_initialassessment_general_paediatrics_referral_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialassessment',
            name='episode_definition',
            field=models.CharField(choices=[('a', 'This was a single episode'), ('b', 'This was a cluster within 24 hours'), ('c', 'These were 2 or more episodes more than 24 hours apart'), ('d', 'The patient was diagnosed as having epilepsy for another reason')], default=None, max_length=1, null=True, verbose_name='Episode definition. Part of case definition and defines if represents a cluster or discrete episodes.'),
        ),
    ]
