# Generated by Django 4.2.7 on 2023-11-10 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0015_historicalsite_transfer_origin_organisation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="transfer_origin_organisation",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="origin_organisation",
                to="epilepsy12.organisation",
            ),
        ),
    ]
