# Generated by Django 4.0.4 on 2022-05-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0015_rename_generalised_onset_desscribe_epileptic_generalised_onset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desscribe',
            name='syndrome',
            field=models.IntegerField(blank=True, choices=[(0, 'Self-limited (familial) neonatal epilepsy'), (1, 'Self-limited (familial) infantile epilepsy'), (2, 'Self-limited familial neonatal-infantile epilepsy'), (3, 'Self-limited epilepsy with centrotemporal spikes'), (4, 'Self-limited epilepsy with autonomic seizures'), (5, 'Childhood occipital visual epilepsy'), (6, 'Photosensitive occipital lobe epilepsy'), (7, 'Mesial temporal lobe epilepsy with hippocampal sclerosis'), (8, 'Familial mesial temporal lobe epilepsy'), (9, 'Sleep-related hypermotor (hyperkinetic) epilepsy'), (10, 'Familial focal epilepsy with variable foci'), (11, 'Epilepsy with auditory features'), (12, 'Genetic epilepsy with febrile seizures plus'), (13, 'Myoclonic epilepsy in infancy'), (14, 'Epilepsy with myoclonic absences'), (15, 'Epilepsy with eyelid myoclonia'), (16, 'Childhood absence epilepsy'), (17, 'Juvenile absence epilepsy'), (18, 'Juvenile myoclonic epilepsy'), (19, 'Epilepsy with generalized tonic–clonic seizures alone'), (20, 'Early infantile DEE'), (21, 'Epilepsy of infancy with migrating focal seizures'), (22, 'Infantile epileptic spasms syndrome'), (23, 'Dravet syndrome'), (24, 'Etiology-specific DEEs'), (25, 'KCNQ2-DEE'), (26, 'Pyridoxine-dependent and pyridox(am)ine 5′ phosphate deficiency DEE'), (27, 'CDKL5-DEE'), (28, 'PCDH19 clustering epilepsy'), (29, 'GLUT1DS-DEE'), (30, 'Sturge–Weber syndrome'), (31, 'Gelastic seizures with HH'), (32, 'Epilepsy with myoclonic–atonic seizures'), (33, 'Lennox–Gastaut syndrome'), (34, 'DEE or EE with spike-and-wave activation in sleep'), (35, 'Febrile infection-related epilepsy syndrome'), (36, 'Hemiconvulsion–hemiplegia–epilepsy'), (37, 'Rasmussen syndrome'), (38, 'Progressive myoclonus epilepsies'), (39, 'Epilepsy with reading-induced seizures')], default=None, null=True, verbose_name='Is there an identifiable epilepsy syndrome?'),
        ),
    ]
