# Generated by Django 4.2.7 on 2023-11-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0015_historicalsite_transfer_origin_organisation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="epilepsy12user",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Lead Clinician"),
                    (2, "Clinician"),
                    (3, "Administrator"),
                    (4, "RCPCH Audit Team"),
                    (7, "RCPCH Audit Children and Family"),
                ],
                help_text="Enter your role: 1 - Clinical Lead, 2 - Clinician, 3 - E12 Site Administrator, 4 - RCPCH Audit Team .",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalepilepsy12user",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Lead Clinician"),
                    (2, "Clinician"),
                    (3, "Administrator"),
                    (4, "RCPCH Audit Team"),
                    (7, "RCPCH Audit Children and Family"),
                ],
                help_text="Enter your role: 1 - Clinical Lead, 2 - Clinician, 3 - E12 Site Administrator, 4 - RCPCH Audit Team .",
                null=True,
            ),
        ),
    ]
