# Generated by Django 4.2.2 on 2023-06-18 08:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "epilepsy12",
            "0015_rename_is_clinician_epilepsy12user_is_rcpch_staff_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registration",
            options={
                "permissions": [
                    (
                        "can_approve_eligibility",
                        "Can approve eligibility for Epilepsy12.",
                    ),
                    (
                        "can_register_child_in_epilepsy12",
                        "Can register child in Epilepsy12. (A cohort number is automatically allocaeted)",
                    ),
                    (
                        "can_unregister_child_in_epilepsy12",
                        "Can unregister a child in Epilepsy. Their record and previously entered data is untouched.",
                    ),
                    (
                        "can_consent_to_audit_participation",
                        "Can consent to participating in Epilepsy12.",
                    ),
                ],
                "verbose_name": "Registration",
                "verbose_name_plural": "Registrations",
            },
        ),
        migrations.AddField(
            model_name="auditprogress",
            name="consent_patient_confirmed",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="auditprogress",
            name="details_patient_confirmed",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="epilepsy12user",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Audit Centre Lead Clinician"),
                    (2, "Audit Centre Clinician"),
                    (3, "Audit Centre Administrator"),
                    (4, "RCPCH Audit Team"),
                    (7, "RCPCH Audit Children and Family"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalepilepsy12user",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Audit Centre Lead Clinician"),
                    (2, "Audit Centre Clinician"),
                    (3, "Audit Centre Administrator"),
                    (4, "RCPCH Audit Team"),
                    (7, "RCPCH Audit Children and Family"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="Geocode_Coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, default=None, null=True, srid=27700
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="Geocode_Coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, default=None, null=True, srid=27700
            ),
        ),
    ]
