# Generated by Django 4.1.2 on 2022-10-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0016_remove_registration_referring_clinician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epilepsy12user',
            name='view_preference',
            field=models.SmallIntegerField(choices=[(0, 'hospital'), (1, 'trust'), (2, 'national')], default=0),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_definition',
            field=models.CharField(choices=[('a', 'This was a single episode'), ('b', 'This was a cluster within 24 hours'), ('c', 'These were 2 or more episodes more than 24 hours apart')], default=None, help_text={'label': 'Episode definition', 'reference': 'Episode definition. Part of case definition and defines if represents a cluster or discrete episodes.'}, max_length=1, null=True, verbose_name='Episode definition. Part of case definition and defines if represents a cluster or discrete episodes.'),
        ),
    ]
