# Generated by Django 4.0.4 on 2022-09-03 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0016_alter_antiepilepsymedicine_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiepilepsymedicine',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='comorbidity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='epilepsycontext',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='management',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='multiaxialdiagnosis',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='site',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='syndrome',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
    ]
