# Generated by Django 4.2.2 on 2023-06-24 09:37

from django.db import migrations, models
import epilepsy12.validators


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0016_alter_registration_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalregistration",
            name="registration_date",
            field=models.DateField(
                default=None,
                help_text={
                    "label": "First paediatric assessment",
                    "reference": "Setting this date is an irreversible step. Confirmation will be requested to complete this step.",
                },
                null=True,
                validators=[epilepsy12.validators.not_in_the_future_validator],
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="registration_date",
            field=models.DateField(
                default=None,
                help_text={
                    "label": "First paediatric assessment",
                    "reference": "Setting this date is an irreversible step. Confirmation will be requested to complete this step.",
                },
                null=True,
                validators=[epilepsy12.validators.not_in_the_future_validator],
            ),
        ),
    ]
