# Generated by Django 4.1.2 on 2022-10-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0017_epilepsy12user_view_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epilepsy12user',
            name='has_rcpch_view_preference',
        ),
    ]
