# Generated by Django 4.2.4 on 2023-08-11 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0017_alter_historicalregistration_registration_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kpiaggregation",
            options={
                "verbose_name": "KPI Aggregation Result",
                "verbose_name_plural": "KPI Aggregation Results",
            },
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="abstraction_level",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="assessment_of_mental_health_issues",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="assessment_of_mental_health_issues_average",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="assessment_of_mental_health_issues_total",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="care_planning_has_been_updated_when_necessary",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="care_planning_has_been_updated_when_necessary_average",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="care_planning_has_been_updated_when_necessary_total",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="comprehensive_care_planning_agreement",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="comprehensive_care_planning_agreement_average",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="comprehensive_care_planning_agreement_total",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="comprehensive_care_planning_content",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="comprehensive_care_planning_content_average",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="comprehensive_care_planning_content_total",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="ecg",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="ecg_average",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="ecg_total",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="epilepsy_specialist_nurse",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="epilepsy_specialist_nurse_average",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="epilepsy_specialist_nurse_total",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="epilepsy_surgery_referral",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="epilepsy_surgery_referral_average",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="epilepsy_surgery_referral_total",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="first_aid",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="first_aid_average",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="first_aid_total",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="general_participation_and_risk",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="general_participation_and_risk_average",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="general_participation_and_risk_total",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="mental_health_support",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="mental_health_support_average",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="mental_health_support_total",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="mri",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="mri_average",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="mri_total",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="paediatrician_with_expertise_in_epilepsies",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="paediatrician_with_expertise_in_epilepsies_average",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="paediatrician_with_expertise_in_epilepsies_total",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="parental_prolonged_seizures_care_plan",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="parental_prolonged_seizures_care_plan_average",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="parental_prolonged_seizures_care_plan_total",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="patient_carer_parent_agreement_to_the_care_planning",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="patient_carer_parent_agreement_to_the_care_planning_average",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="patient_carer_parent_agreement_to_the_care_planning_total",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="patient_held_individualised_epilepsy_document",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="patient_held_individualised_epilepsy_document_average",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="patient_held_individualised_epilepsy_document_total",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="school_individual_healthcare_plan",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="school_individual_healthcare_plan_average",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="school_individual_healthcare_plan_total",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="service_contact_details",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="service_contact_details_average",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="service_contact_details_total",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="sodium_valproate",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="sodium_valproate_average",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="sodium_valproate_total",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="sudep",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="sudep_average",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="sudep_total",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="tertiary_input",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="tertiary_input_average",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="tertiary_input_total",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="total_number_of_cases",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="water_safety",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="water_safety_average",
        ),
        migrations.RemoveField(
            model_name="kpiaggregation",
            name="water_safety_total",
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="assessment_of_mental_health_issues_incomplete",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="assessment_of_mental_health_issues_ineligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="assessment_of_mental_health_issues_passed",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="assessment_of_mental_health_issues_total_eligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="care_planning_has_been_updated_when_necessary_incomplete",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="care_planning_has_been_updated_when_necessary_ineligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="care_planning_has_been_updated_when_necessary_passed",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="care_planning_has_been_updated_when_necessary_total_eligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="comprehensive_care_planning_agreement_incomplete",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="comprehensive_care_planning_agreement_ineligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="comprehensive_care_planning_agreement_passed",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="comprehensive_care_planning_agreement_total_eligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="comprehensive_care_planning_content_incomplete",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="comprehensive_care_planning_content_ineligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="comprehensive_care_planning_content_passed",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="comprehensive_care_planning_content_total_eligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="ecg_incomplete",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="ecg_ineligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="ecg_passed",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="ecg_total_eligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="epilepsy_specialist_nurse_incomplete",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="epilepsy_specialist_nurse_ineligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="epilepsy_specialist_nurse_passed",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="epilepsy_specialist_nurse_total_eligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="epilepsy_surgery_referral_incomplete",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="epilepsy_surgery_referral_ineligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="epilepsy_surgery_referral_passed",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="epilepsy_surgery_referral_total_eligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="first_aid_incomplete",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="first_aid_ineligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="first_aid_passed",
            field=models.IntegerField(
                default=11, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="first_aid_total_eligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="general_participation_and_risk_incomplete",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="general_participation_and_risk_ineligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="general_participation_and_risk_passed",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="general_participation_and_risk_total_eligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="mental_health_support_incomplete",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="mental_health_support_ineligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="mental_health_support_passed",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="mental_health_support_total_eligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="mri_incomplete",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="mri_ineligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="mri_passed",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="mri_total_eligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="paediatrician_with_expertise_in_epilepsies_incomplete",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="paediatrician_with_expertise_in_epilepsies_ineligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="paediatrician_with_expertise_in_epilepsies_passed",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="paediatrician_with_expertise_in_epilepsies_total_eligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="parental_prolonged_seizures_care_plan_incomplete",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="parental_prolonged_seizures_care_plan_ineligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="parental_prolonged_seizures_care_plan_passed",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="parental_prolonged_seizures_care_plan_total_eligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="patient_carer_parent_agreement_to_the_care_planning_incomplete",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="patient_carer_parent_agreement_to_the_care_planning_ineligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="patient_carer_parent_agreement_to_the_care_planning_passed",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="patient_carer_parent_agreement_to_the_care_planning_total_eligible",
            field=models.IntegerField(
                db_column="pt_carer_parent_agree_care_place_total_eligible",
                default=1,
                help_text={"label": "", "reference": ""},
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="patient_held_individualised_epilepsy_document_incomplete",
            field=models.IntegerField(
                default=11, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="patient_held_individualised_epilepsy_document_ineligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="patient_held_individualised_epilepsy_document_passed",
            field=models.IntegerField(
                default=11, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="patient_held_individualised_epilepsy_document_total_eligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="school_individual_healthcare_plan_incomplete",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="school_individual_healthcare_plan_ineligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="school_individual_healthcare_plan_passed",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="school_individual_healthcare_plan_total_eligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="service_contact_details_incomplete",
            field=models.IntegerField(
                default=11, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="service_contact_details_ineligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="service_contact_details_passed",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="service_contact_details_total_eligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="sodium_valproate_incomplete",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="sodium_valproate_ineligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="sodium_valproate_passed",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="sodium_valproate_total_eligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="sudep_incomplete",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="sudep_ineligible",
            field=models.IntegerField(
                default=11, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="sudep_passed",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="sudep_total_eligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="tertiary_input_incomplete",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="tertiary_input_ineligible",
            field=models.IntegerField(
                default=11, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="tertiary_input_passed",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="tertiary_input_total_eligible",
            field=models.IntegerField(
                default=11, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="water_safety_incomplete",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="water_safety_ineligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="water_safety_passed",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpiaggregation",
            name="water_safety_total_eligible",
            field=models.IntegerField(
                default=1, help_text={"label": "", "reference": ""}
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comorbidity",
            name="multiaxial_diagnosis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comorbidities",
                to="epilepsy12.multiaxialdiagnosis",
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="multiaxial_diagnosis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="episodes",
                to="epilepsy12.multiaxialdiagnosis",
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvestigations",
            name="eeg_indicated",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text={
                    "label": "Has a first EEG been requested?",
                    "reference": "If a diagnosis of epilepsy is suspected, a routine EEG should be carried out to support the diagnosis. CYP undergoing initial investigations for epilepsy should have tests within 4 weeks of being requested.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="investigations",
            name="eeg_indicated",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text={
                    "label": "Has a first EEG been requested?",
                    "reference": "If a diagnosis of epilepsy is suspected, a routine EEG should be carried out to support the diagnosis. CYP undergoing initial investigations for epilepsy should have tests within 4 weeks of being requested.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="syndrome",
            name="multiaxial_diagnosis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="syndromes",
                to="epilepsy12.multiaxialdiagnosis",
            ),
        ),
    ]
