# Generated by Django 4.0.4 on 2022-09-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0017_alter_antiepilepsymedicine_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antiepilepsymedicine',
            options={'verbose_name': ('Antiepilepsy Medicine',), 'verbose_name_plural': 'Antiepilepsy Medicines'},
        ),
        migrations.AlterModelOptions(
            name='assessment',
            options={'verbose_name': ('Milestones',), 'verbose_name_plural': 'Milestones'},
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelOptions(
            name='comorbidity',
            options={'verbose_name': 'Comorbidity', 'verbose_name_plural': 'Comorbidities'},
        ),
        migrations.AlterModelOptions(
            name='epilepsy12user',
            options={'verbose_name': ('Epilepsy12 User',), 'verbose_name_plural': 'Epilepsy12 Users'},
        ),
        migrations.AlterModelOptions(
            name='epilepsycontext',
            options={'verbose_name': 'Epilepsy Context', 'verbose_name_plural': 'Epilepsy Contexts'},
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'verbose_name': ('Nonepilepsy',), 'verbose_name_plural': 'Nonepilepsies'},
        ),
        migrations.AlterModelOptions(
            name='hospitaltrust',
            options={'verbose_name': 'Hospital Trust', 'verbose_name_plural': 'Hospital Trusts'},
        ),
        migrations.AlterModelOptions(
            name='initialassessment',
            options={'verbose_name': 'First Paediatric Assessment', 'verbose_name_plural': 'First Paediatric Assessments'},
        ),
        migrations.AlterModelOptions(
            name='management',
            options={'verbose_name': ('Management Plan',), 'verbose_name_plural': 'Management Plans'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
        migrations.AlterModelOptions(
            name='syndrome',
            options={'verbose_name': 'Syndrome', 'verbose_name_plural': 'Syndromes'},
        ),
    ]
