# Generated by Django 4.2.4 on 2023-08-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0018_alter_kpiaggregation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kpiaggregation",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, help_text={"label": "", "reference": ""}
            ),
        ),
    ]
