# Generated by Django 4.1.2 on 2022-10-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0018_remove_epilepsy12user_has_rcpch_view_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='is_a_pregnancy_prevention_programme_in_place',
        ),
        migrations.AddField(
            model_name='antiepilepsymedicine',
            name='is_a_pregnancy_prevention_programme_in_place',
            field=models.BooleanField(blank=True, default=None, help_text={'label': 'Is a pregnancy prevention programme (PPP) in place?', 'reference': 'For girls and young women who are presecribed sodium valproate, it is recommended that pregnancy prevention is actively discussed and documented.'}, null=True),
        ),
        migrations.AddField(
            model_name='antiepilepsymedicine',
            name='is_a_pregnancy_prevention_programme_needed',
            field=models.BooleanField(blank=True, default=None, help_text={'label': 'Is a pregnancy prevention programme indicated?', 'reference': 'For girls and young women who are presecribed sodium valproate, it is recommended that pregnancy prevention is actively discussed and documented.'}, null=True),
        ),
        migrations.AlterField(
            model_name='antiepilepsymedicine',
            name='antiepilepsy_medicine_risk_discussed',
            field=models.BooleanField(blank=True, default=None, help_text={'label': 'Antiseizure medication risks discussed?', 'reference': 'Have the risks related to the antiseizure medicine been discussed with the child/young person and their family?'}, null=True),
        ),
        migrations.AlterField(
            model_name='antiepilepsymedicine',
            name='antiepilepsy_medicine_snomed_code',
            field=models.CharField(blank=True, default=None, help_text={'label': 'Antiseizure medicine SNOMED-CT code', 'reference': 'Antiseizure medicine SNOMED-CT code'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='antiepilepsymedicine',
            name='antiepilepsy_medicine_snomed_preferred_name',
            field=models.CharField(blank=True, default=None, help_text={'label': 'Antiseizure medicine SNOMED-CT preferred name', 'reference': 'Antiseizure medicine SNOMED-CT preferred name'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='antiepilepsymedicine',
            name='antiepilepsy_medicine_start_date',
            field=models.DateField(blank=True, default=None, help_text={'label': 'Antiepilepsy medicine start date', 'reference': 'Antiepilepsy medicine start date'}, null=True),
        ),
        migrations.AlterField(
            model_name='antiepilepsymedicine',
            name='antiepilepsy_medicine_stop_date',
            field=models.DateField(blank=True, default=None, help_text={'label': 'Antiseizure medicine discontinued date', 'reference': 'Antiseizure medicine discontinued date'}, null=True),
        ),
        migrations.AlterField(
            model_name='antiepilepsymedicine',
            name='antiepilepsy_medicine_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Acetazolamide'), (2, 'ACTH'), (3, 'Carbamazepine'), (4, 'Clobazam'), (5, 'Clonazepam'), (6, 'Eslicarbazepine acetate'), (7, 'Ethosuximide'), (8, 'Gabapentin'), (9, 'Lacosamide'), (10, 'Lamotrigine'), (11, 'Levetiracetam'), (12, 'Methylprednisolone'), (13, 'Nitrazepam'), (14, 'Oxcarbazepine'), (15, 'Perampanel'), (16, 'Piracetam'), (17, 'Phenobarbital'), (18, 'Phenytoin'), (19, 'Pregabalin'), (20, 'Prednisolone'), (21, 'Primidone'), (22, 'Rufinamide'), (23, 'Sodium valproate'), (24, 'Stiripentol'), (25, 'Sulthiame'), (26, 'Tiagabine'), (27, 'Topiramate'), (28, 'Vigabatrin'), (29, 'Zonisamide'), ('O', 'Other')], default=None, help_text={'label': 'Antiseizure medicine name', 'reference': 'Please enter antiseizure medicine name.'}, null=True),
        ),
        migrations.AlterField(
            model_name='antiepilepsymedicine',
            name='is_rescue_medicine',
            field=models.BooleanField(blank=True, default=None, help_text={'label': 'Is the medicine a rescue medicine?', 'reference': 'Is the medicine a rescue medicine?'}, null=True),
        ),
    ]
