# Generated by Django 4.2.7 on 2023-11-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0018_alter_organisationkpiaggregation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalregistration",
            name="completed_first_year_of_care_date",
            field=models.DateField(
                default=None,
                help_text={
                    "label": "First year of care completion date",
                    "reference": "Date which completes first year of epilepsy care",
                },
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="completed_first_year_of_care_date",
            field=models.DateField(
                default=None,
                help_text={
                    "label": "First year of care completion date",
                    "reference": "Date which completes first year of epilepsy care",
                },
                null=True,
            ),
        ),
    ]
