# Generated by Django 4.2.7 on 2023-11-23 22:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "epilepsy12",
            "0019_historicalregistration_completed_first_year_of_care_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalregistration",
            name="registration_close_date",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="registration_close_date",
        ),
    ]
