# Generated by Django 4.2.7 on 2023-11-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "epilepsy12",
            "0020_remove_historicalregistration_registration_close_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorganisation",
            name="email",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="email",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="seizure_onset_date_confidence",
            field=models.CharField(
                choices=[
                    ("Apx", "Approximate date"),
                    ("Exc", "Exact date"),
                    ("NK", "Not known"),
                ],
                default=None,
                help_text={
                    "label": "Confidence in reported date of episode",
                    "reference": "How accurate is the date of this episode? Even if date 'Not known', please enter a date above",
                },
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalepisode",
            name="seizure_onset_date_confidence",
            field=models.CharField(
                choices=[
                    ("Apx", "Approximate date"),
                    ("Exc", "Exact date"),
                    ("NK", "Not known"),
                ],
                default=None,
                help_text={
                    "label": "Confidence in reported date of episode",
                    "reference": "How accurate is the date of this episode? Even if date 'Not known', please enter a date above",
                },
                max_length=3,
                null=True,
            ),
        ),
    ]
