# Generated by Django 4.2.7 on 2023-12-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "epilepsy12",
            "0020_remove_historicalregistration_registration_close_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="seizure_onset_date_confidence",
            field=models.CharField(
                choices=[
                    ("Apx", "Approximate date"),
                    ("Exc", "Exact date"),
                    ("NK", "Not known"),
                ],
                default=None,
                help_text={
                    "label": "Confidence in reported date of episode",
                    "reference": "How accurate is the date of this episode? Even if date 'Not known', please enter a date above",
                },
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalepisode",
            name="seizure_onset_date_confidence",
            field=models.CharField(
                choices=[
                    ("Apx", "Approximate date"),
                    ("Exc", "Exact date"),
                    ("NK", "Not known"),
                ],
                default=None,
                help_text={
                    "label": "Confidence in reported date of episode",
                    "reference": "How accurate is the date of this episode? Even if date 'Not known', please enter a date above",
                },
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmanagement",
            name="individualised_care_plan_includes_ehcp",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text={
                    "label": "A School Individual Health Care Plan",
                    "reference": "Does the individualised care plan include a School Individual Health Care Plan?",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="management",
            name="individualised_care_plan_includes_ehcp",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text={
                    "label": "A School Individual Health Care Plan",
                    "reference": "Does the individualised care plan include a School Individual Health Care Plan?",
                },
                null=True,
            ),
        ),
    ]
