# Generated by Django 4.2.9 on 2024-01-10 21:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0021_alter_episode_seizure_onset_date_confidence_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="case",
            options={
                "ordering": ["surname"],
                "permissions": [
                    (
                        "can_lock_child_case_data_from_editing",
                        "Can lock a child's record from editing.",
                    ),
                    (
                        "can_unlock_child_case_data_from_editing",
                        "Can unlock a child's record from editing.",
                    ),
                    (
                        "can_opt_out_child_from_inclusion_in_audit",
                        "Can sanction an opt out from participating in the audit. Note all the child's date except Epilepsy12 unique identifier are irretrievably deleted.",
                    ),
                    (
                        "can_consent_to_audit_participation",
                        "Can consent to participating in Epilepsy12.",
                    ),
                ],
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
            },
        ),
    ]
