# Generated by Django 4.2.4 on 2023-08-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0021_trustkpiaggregation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="parent_organisation_ods_code",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
