# Generated by Django 4.0.4 on 2022-08-07 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0022_remove_hospitaltrust_epilepsy12__organis_abe360_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eeg_indicated', models.BooleanField(default=None, null=True)),
                ('eeg_request_date', models.DateTimeField(blank=True, null=True)),
                ('eeg_performed_date', models.DateTimeField(blank=True, null=True)),
                ('twelve_lead_ecg_status', models.BooleanField(blank=True, default=None, null=True)),
                ('ct_head_scan_status', models.BooleanField(default=False)),
                ('mri_indicated', models.BooleanField(blank=True, default=None, null=True)),
                ('mri_brain_date', models.DateField(blank=True, default=None, null=True)),
                ('registration', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='epilepsy12.registration', verbose_name='Related Registration')),
            ],
            options={
                'verbose_name': 'Investigation Milestones',
                'verbose_name_plural': 'Investigation Milestones',
            },
        ),
    ]
