# Generated by Django 4.2.4 on 2023-08-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0022_alter_trustkpiaggregation_parent_organisation_ods_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="assessment_of_mental_health_issues_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="assessment_of_mental_health_issues_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="assessment_of_mental_health_issues_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="assessment_of_mental_health_issues_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="care_planning_has_been_updated_when_necessary_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="care_planning_has_been_updated_when_necessary_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="care_planning_has_been_updated_when_necessary_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="care_planning_has_been_updated_when_necessary_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="comprehensive_care_planning_agreement_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="comprehensive_care_planning_agreement_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="comprehensive_care_planning_agreement_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="comprehensive_care_planning_agreement_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="comprehensive_care_planning_content_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="comprehensive_care_planning_content_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="comprehensive_care_planning_content_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="comprehensive_care_planning_content_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="ecg_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="ecg_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="ecg_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="ecg_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="epilepsy_specialist_nurse_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="epilepsy_specialist_nurse_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="epilepsy_specialist_nurse_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="epilepsy_specialist_nurse_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="epilepsy_surgery_referral_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="epilepsy_surgery_referral_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="epilepsy_surgery_referral_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="epilepsy_surgery_referral_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="first_aid_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="first_aid_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="first_aid_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="first_aid_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="general_participation_and_risk_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="general_participation_and_risk_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="general_participation_and_risk_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="general_participation_and_risk_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="mental_health_support_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="mental_health_support_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="mental_health_support_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="mental_health_support_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="mri_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="mri_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="mri_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="mri_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="paediatrician_with_expertise_in_epilepsies_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="paediatrician_with_expertise_in_epilepsies_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="paediatrician_with_expertise_in_epilepsies_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="paediatrician_with_expertise_in_epilepsies_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="parental_prolonged_seizures_care_plan_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="parental_prolonged_seizures_care_plan_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="parental_prolonged_seizures_care_plan_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="parental_prolonged_seizures_care_plan_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="patient_carer_parent_agreement_to_the_care_planning_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="patient_carer_parent_agreement_to_the_care_planning_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="patient_carer_parent_agreement_to_the_care_planning_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="patient_carer_parent_agreement_to_the_care_planning_total_eligible",
            field=models.IntegerField(
                db_column="pt_carer_parent_agree_care_place_total_eligible",
                default=None,
                help_text={"label": "", "reference": ""},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="patient_held_individualised_epilepsy_document_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="patient_held_individualised_epilepsy_document_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="patient_held_individualised_epilepsy_document_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="patient_held_individualised_epilepsy_document_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="school_individual_healthcare_plan_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="school_individual_healthcare_plan_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="school_individual_healthcare_plan_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="school_individual_healthcare_plan_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="service_contact_details_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="service_contact_details_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="service_contact_details_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="service_contact_details_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="sodium_valproate_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="sodium_valproate_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="sodium_valproate_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="sodium_valproate_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="sudep_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="sudep_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="sudep_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="sudep_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="tertiary_input_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="tertiary_input_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="tertiary_input_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="tertiary_input_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="water_safety_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="water_safety_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="water_safety_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="water_safety_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="assessment_of_mental_health_issues_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="assessment_of_mental_health_issues_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="assessment_of_mental_health_issues_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="assessment_of_mental_health_issues_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="care_planning_has_been_updated_when_necessary_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="care_planning_has_been_updated_when_necessary_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="care_planning_has_been_updated_when_necessary_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="care_planning_has_been_updated_when_necessary_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="comprehensive_care_planning_agreement_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="comprehensive_care_planning_agreement_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="comprehensive_care_planning_agreement_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="comprehensive_care_planning_agreement_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="comprehensive_care_planning_content_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="comprehensive_care_planning_content_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="comprehensive_care_planning_content_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="comprehensive_care_planning_content_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="ecg_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="ecg_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="ecg_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="ecg_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="epilepsy_specialist_nurse_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="epilepsy_specialist_nurse_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="epilepsy_specialist_nurse_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="epilepsy_specialist_nurse_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="epilepsy_surgery_referral_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="epilepsy_surgery_referral_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="epilepsy_surgery_referral_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="epilepsy_surgery_referral_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="first_aid_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="first_aid_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="first_aid_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="first_aid_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="general_participation_and_risk_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="general_participation_and_risk_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="general_participation_and_risk_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="general_participation_and_risk_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="mental_health_support_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="mental_health_support_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="mental_health_support_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="mental_health_support_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="mri_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="mri_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="mri_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="mri_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="paediatrician_with_expertise_in_epilepsies_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="paediatrician_with_expertise_in_epilepsies_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="paediatrician_with_expertise_in_epilepsies_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="paediatrician_with_expertise_in_epilepsies_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="parental_prolonged_seizures_care_plan_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="parental_prolonged_seizures_care_plan_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="parental_prolonged_seizures_care_plan_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="parental_prolonged_seizures_care_plan_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="patient_carer_parent_agreement_to_the_care_planning_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="patient_carer_parent_agreement_to_the_care_planning_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="patient_carer_parent_agreement_to_the_care_planning_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="patient_carer_parent_agreement_to_the_care_planning_total_eligible",
            field=models.IntegerField(
                db_column="pt_carer_parent_agree_care_place_total_eligible",
                default=None,
                help_text={"label": "", "reference": ""},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="patient_held_individualised_epilepsy_document_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="patient_held_individualised_epilepsy_document_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="patient_held_individualised_epilepsy_document_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="patient_held_individualised_epilepsy_document_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="school_individual_healthcare_plan_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="school_individual_healthcare_plan_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="school_individual_healthcare_plan_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="school_individual_healthcare_plan_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="service_contact_details_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="service_contact_details_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="service_contact_details_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="service_contact_details_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="sodium_valproate_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="sodium_valproate_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="sodium_valproate_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="sodium_valproate_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="sudep_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="sudep_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="sudep_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="sudep_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="tertiary_input_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="tertiary_input_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="tertiary_input_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="tertiary_input_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="water_safety_incomplete",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="water_safety_ineligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="water_safety_passed",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="water_safety_total_eligible",
            field=models.IntegerField(
                default=None, help_text={"label": "", "reference": ""}, null=True
            ),
        ),
    ]
