# Generated by Django 4.2.9 on 2024-01-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0022_alter_case_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorganisation",
            name="ods_code",
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="ods_code",
            field=models.CharField(
                blank=True, default=None, max_length=100, null=True, unique=True
            ),
        ),
    ]
