# Generated by Django 4.2.4 on 2023-08-15 13:15

from django.db import migrations, models
import django.db.models.deletion
import epilepsy12.models_folder.help_text_mixin


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0024_alter_organisationkpiaggregation_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trustkpiaggregation",
            options={
                "verbose_name": "Trust KPI Aggregation Model",
                "verbose_name_plural": "Trust KPI Aggregation Models",
            },
        ),
        migrations.CreateModel(
            name="OpenUKKPIAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "open_access",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "paediatrician_with_expertise_in_epilepsies_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "paediatrician_with_expertise_in_epilepsies_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "paediatrician_with_expertise_in_epilepsies_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "paediatrician_with_expertise_in_epilepsies_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_specialist_nurse_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_specialist_nurse_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_specialist_nurse_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_specialist_nurse_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "tertiary_input_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "tertiary_input_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "tertiary_input_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "tertiary_input_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_surgery_referral_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_surgery_referral_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_surgery_referral_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_surgery_referral_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "ecg_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "ecg_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "ecg_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "ecg_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mri_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mri_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mri_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mri_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "assessment_of_mental_health_issues_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "assessment_of_mental_health_issues_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "assessment_of_mental_health_issues_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "assessment_of_mental_health_issues_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mental_health_support_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mental_health_support_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mental_health_support_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mental_health_support_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sodium_valproate_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sodium_valproate_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sodium_valproate_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sodium_valproate_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_agreement_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_agreement_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_agreement_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_agreement_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_held_individualised_epilepsy_document_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_held_individualised_epilepsy_document_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_held_individualised_epilepsy_document_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_held_individualised_epilepsy_document_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_carer_parent_agreement_to_the_care_planning_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_carer_parent_agreement_to_the_care_planning_total_eligible",
                    models.IntegerField(
                        db_column="pt_carer_parent_agree_care_place_total_eligible",
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_carer_parent_agreement_to_the_care_planning_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_carer_parent_agreement_to_the_care_planning_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "care_planning_has_been_updated_when_necessary_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "care_planning_has_been_updated_when_necessary_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "care_planning_has_been_updated_when_necessary_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "care_planning_has_been_updated_when_necessary_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_content_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_content_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_content_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_content_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "parental_prolonged_seizures_care_plan_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "parental_prolonged_seizures_care_plan_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "parental_prolonged_seizures_care_plan_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "parental_prolonged_seizures_care_plan_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "water_safety_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "water_safety_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "water_safety_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "water_safety_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "first_aid_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "first_aid_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "first_aid_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "first_aid_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "general_participation_and_risk_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "general_participation_and_risk_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "general_participation_and_risk_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "general_participation_and_risk_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "service_contact_details_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "service_contact_details_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "service_contact_details_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "service_contact_details_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sudep_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sudep_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sudep_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sudep_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "school_individual_healthcare_plan_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "school_individual_healthcare_plan_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "school_individual_healthcare_plan_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "school_individual_healthcare_plan_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text={"label": "", "reference": ""}
                    ),
                ),
                (
                    "abstraction_relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="epilepsy12.openuknetworkentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "OpenUK KPI Aggregation Model",
                "verbose_name_plural": "OpenUK KPI Aggregation Models",
            },
            bases=(
                models.Model,
                epilepsy12.models_folder.help_text_mixin.HelpTextMixin,
            ),
        ),
        migrations.CreateModel(
            name="NHSRegionKPIAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "open_access",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "paediatrician_with_expertise_in_epilepsies_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "paediatrician_with_expertise_in_epilepsies_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "paediatrician_with_expertise_in_epilepsies_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "paediatrician_with_expertise_in_epilepsies_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_specialist_nurse_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_specialist_nurse_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_specialist_nurse_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_specialist_nurse_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "tertiary_input_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "tertiary_input_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "tertiary_input_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "tertiary_input_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_surgery_referral_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_surgery_referral_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_surgery_referral_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_surgery_referral_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "ecg_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "ecg_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "ecg_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "ecg_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mri_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mri_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mri_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mri_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "assessment_of_mental_health_issues_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "assessment_of_mental_health_issues_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "assessment_of_mental_health_issues_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "assessment_of_mental_health_issues_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mental_health_support_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mental_health_support_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mental_health_support_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mental_health_support_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sodium_valproate_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sodium_valproate_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sodium_valproate_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sodium_valproate_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_agreement_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_agreement_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_agreement_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_agreement_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_held_individualised_epilepsy_document_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_held_individualised_epilepsy_document_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_held_individualised_epilepsy_document_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_held_individualised_epilepsy_document_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_carer_parent_agreement_to_the_care_planning_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_carer_parent_agreement_to_the_care_planning_total_eligible",
                    models.IntegerField(
                        db_column="pt_carer_parent_agree_care_place_total_eligible",
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_carer_parent_agreement_to_the_care_planning_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_carer_parent_agreement_to_the_care_planning_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "care_planning_has_been_updated_when_necessary_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "care_planning_has_been_updated_when_necessary_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "care_planning_has_been_updated_when_necessary_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "care_planning_has_been_updated_when_necessary_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_content_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_content_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_content_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_content_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "parental_prolonged_seizures_care_plan_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "parental_prolonged_seizures_care_plan_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "parental_prolonged_seizures_care_plan_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "parental_prolonged_seizures_care_plan_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "water_safety_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "water_safety_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "water_safety_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "water_safety_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "first_aid_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "first_aid_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "first_aid_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "first_aid_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "general_participation_and_risk_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "general_participation_and_risk_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "general_participation_and_risk_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "general_participation_and_risk_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "service_contact_details_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "service_contact_details_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "service_contact_details_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "service_contact_details_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sudep_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sudep_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sudep_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sudep_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "school_individual_healthcare_plan_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "school_individual_healthcare_plan_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "school_individual_healthcare_plan_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "school_individual_healthcare_plan_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text={"label": "", "reference": ""}
                    ),
                ),
                (
                    "abstraction_relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="epilepsy12.nhsregionentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "NHSRegionEntity KPI Aggregation Model",
                "verbose_name_plural": "NHSRegionEntity KPI Aggregation Models",
            },
            bases=(
                models.Model,
                epilepsy12.models_folder.help_text_mixin.HelpTextMixin,
            ),
        ),
        migrations.CreateModel(
            name="ICBKPIAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "open_access",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "paediatrician_with_expertise_in_epilepsies_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "paediatrician_with_expertise_in_epilepsies_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "paediatrician_with_expertise_in_epilepsies_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "paediatrician_with_expertise_in_epilepsies_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_specialist_nurse_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_specialist_nurse_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_specialist_nurse_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_specialist_nurse_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "tertiary_input_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "tertiary_input_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "tertiary_input_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "tertiary_input_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_surgery_referral_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_surgery_referral_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_surgery_referral_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "epilepsy_surgery_referral_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "ecg_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "ecg_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "ecg_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "ecg_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mri_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mri_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mri_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mri_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "assessment_of_mental_health_issues_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "assessment_of_mental_health_issues_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "assessment_of_mental_health_issues_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "assessment_of_mental_health_issues_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mental_health_support_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mental_health_support_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mental_health_support_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "mental_health_support_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sodium_valproate_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sodium_valproate_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sodium_valproate_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sodium_valproate_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_agreement_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_agreement_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_agreement_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_agreement_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_held_individualised_epilepsy_document_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_held_individualised_epilepsy_document_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_held_individualised_epilepsy_document_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_held_individualised_epilepsy_document_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_carer_parent_agreement_to_the_care_planning_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_carer_parent_agreement_to_the_care_planning_total_eligible",
                    models.IntegerField(
                        db_column="pt_carer_parent_agree_care_place_total_eligible",
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_carer_parent_agreement_to_the_care_planning_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "patient_carer_parent_agreement_to_the_care_planning_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "care_planning_has_been_updated_when_necessary_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "care_planning_has_been_updated_when_necessary_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "care_planning_has_been_updated_when_necessary_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "care_planning_has_been_updated_when_necessary_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_content_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_content_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_content_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "comprehensive_care_planning_content_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "parental_prolonged_seizures_care_plan_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "parental_prolonged_seizures_care_plan_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "parental_prolonged_seizures_care_plan_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "parental_prolonged_seizures_care_plan_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "water_safety_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "water_safety_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "water_safety_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "water_safety_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "first_aid_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "first_aid_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "first_aid_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "first_aid_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "general_participation_and_risk_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "general_participation_and_risk_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "general_participation_and_risk_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "general_participation_and_risk_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "service_contact_details_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "service_contact_details_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "service_contact_details_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "service_contact_details_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sudep_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sudep_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sudep_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "sudep_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "school_individual_healthcare_plan_passed",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "school_individual_healthcare_plan_total_eligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "school_individual_healthcare_plan_ineligible",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "school_individual_healthcare_plan_incomplete",
                    models.IntegerField(
                        default=None,
                        help_text={"label": "", "reference": ""},
                        null=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text={"label": "", "reference": ""}
                    ),
                ),
                (
                    "abstraction_relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="epilepsy12.integratedcareboardentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "IntegratedCareBoardEntity KPI Aggregation Model",
                "verbose_name_plural": "IntegratedCareBoardEntity KPI Aggregation Models",
            },
            bases=(
                models.Model,
                epilepsy12.models_folder.help_text_mixin.HelpTextMixin,
            ),
        ),
    ]
