# Generated by Django 4.0.4 on 2022-08-08 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0024_alter_investigation_eeg_performed_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antiepilepsymedicine',
            name='antiepilepsy_medicine_type_other',
        ),
        migrations.RemoveField(
            model_name='antiepilepsymedicine',
            name='assessment',
        ),
        migrations.AddField(
            model_name='antiepilepsymedicine',
            name='is_a_pregnancy_prevention_programme_in_place',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Is there a pregnancy prevention programme (PPP) in place?'),
        ),
        migrations.AddField(
            model_name='antiepilepsymedicine',
            name='is_rescue_medicine',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Is the medicine a rescue medicine?'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='epilepsy_specialist_nurse_input_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date seen by an epilepsy nurse specialist'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='epilepsy_specialist_nurse_referral_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date of referral to an epilepsy nurse specialist'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='epilepsy_specialist_nurse_referral_made',
            field=models.BooleanField(default=False, null=True, verbose_name='Has a referral to an epilepsy nurse specialist been made?'),
        ),
        migrations.AlterField(
            model_name='antiepilepsymedicine',
            name='antiepilepsy_medicine_risk_discussed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='have the risks related to the antiepilepsy medicine been discussed?'),
        ),
        migrations.AlterField(
            model_name='antiepilepsymedicine',
            name='antiepilepsy_medicine_snomed_code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='antiepilepsy medicine SNOMED-CT code'),
        ),
        migrations.AlterField(
            model_name='antiepilepsymedicine',
            name='antiepilepsy_medicine_start_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='antiepilepsy medicine start date'),
        ),
        migrations.AlterField(
            model_name='antiepilepsymedicine',
            name='antiepilepsy_medicine_stop_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='antiepilepsy medicine start date'),
        ),
        migrations.AlterField(
            model_name='antiepilepsymedicine',
            name='antiepilepsy_medicine_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Acetazolamide'), (2, 'ACTH'), (3, 'Carbamazepine'), (4, 'Clobazam'), (5, 'Clonazepam'), (6, 'Eslicarbazepine acetate'), (7, 'Ethosuximide'), (8, 'Gabapentin'), (9, 'Lacosamide'), (10, 'Lamotrigine'), (11, 'Levetiracetam'), (12, 'Methylprednisolone'), (13, 'Nitrazepam'), (14, 'Oxcarbazepine'), (15, 'Perampanel'), (16, 'Piracetam'), (17, 'Phenobarbital'), (18, 'Phenytoin'), (19, 'Pregabalin'), (20, 'Prednisolone'), (21, 'Primidone'), (22, 'Rufinamide'), (23, 'Sodium valproate'), (24, 'Stiripentol'), (25, 'Sulthiame'), (26, 'Tiagabine'), (27, 'Topiramate'), (28, 'Vigabatrin'), (29, 'Zonisamide'), ('O', 'Other')], default=None, null=True, verbose_name='antiepilepsy medicine name'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='has_an_aed_been_given',
            field=models.BooleanField(default=False, null=True, verbose_name='Has an antiepilepsy medicine been prescribed?'),
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_an_aed_been_given', models.BooleanField(default=False, null=True, verbose_name='Has an antiepilepsy medicine been prescribed?')),
                ('has_rescue_medication_prescribed', models.BooleanField(default=False, null=True, verbose_name='Has a rescue medicine been prescribed?')),
                ('rescue_medication_prescribed', models.CharField(default=False, max_length=100, null=True, verbose_name='Which rescue medicine has been prescribed?')),
                ('individualised_care_plan_in_place', models.BooleanField(default=None, null=True, verbose_name='Has an individualised care plan been put in place?')),
                ('individualised_care_plan_date', models.DateField(default=None, null=True, verbose_name='Has an individualised care plan been put in place?')),
                ('individualised_care_plan_has_parent_carer_child_agreement', models.BooleanField(default=None, null=True, verbose_name='Has the parent or carer and child agreement to an individualised care plan been documented?')),
                ('individualised_care_plan_includes_service_contact_details', models.BooleanField(default=None, null=True, verbose_name='Does the individualised care plan include service contact details?')),
                ('individualised_care_plan_include_first_aid', models.BooleanField(default=None, null=True, verbose_name='Does the individualised care plan include first aid advice?')),
                ('individualised_care_plan_includes_parental_prolonged_seizure_care', models.BooleanField(default=None, null=True, verbose_name='Does the individualised care plan include parental advice on managing prolonged seizures?')),
                ('individualised_care_plan_includes_general_participation_risk', models.BooleanField(default=None, null=True, verbose_name='Does the individualised care plan include general participation and risk assessment?')),
                ('individualised_care_plan_addresses_water_safety', models.BooleanField(default=None, null=True, verbose_name='Does the individualised care plan address water safety?')),
                ('individualised_care_plan_addresses_sudep', models.BooleanField(default=None, null=True, verbose_name='Does the individualised care plan address sudden unexplained death in epilepsy?')),
                ('individualised_care_plan_includes_aihp', models.BooleanField(default=None, null=True, verbose_name='Does the individualised care plan include AIHP?')),
                ('individualised_care_plan_includes_ehcp', models.BooleanField(default=None, null=True, verbose_name='Does the individualised care plan include an educational health care plan (EHCP)?')),
                ('has_individualised_care_plan_been_updated_in_the_last_year', models.BooleanField(default=None, null=True, verbose_name='Has the individualised care plan been updated in the last year?')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='epilepsy12.registration', verbose_name='related registration')),
            ],
            options={
                'verbose_name': ('management',),
                'verbose_name_plural': 'managements',
            },
        ),
        migrations.AddField(
            model_name='antiepilepsymedicine',
            name='management',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='epilepsy12.management', verbose_name='related management'),
        ),
    ]
