# Generated by Django 4.2.9 on 2024-01-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0024_seed_kpi_aggregations_update"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="antiepilepsymedicine",
            options={
                "ordering": ["management__registration__case"],
                "verbose_name": "Antiepilepsy Medicine",
                "verbose_name_plural": "Antiepilepsy Medicines",
            },
        ),
        migrations.AlterModelOptions(
            name="assessment",
            options={
                "ordering": ["registration__case"],
                "verbose_name": "Assessment",
                "verbose_name_plural": "Assessment",
            },
        ),
        migrations.AlterModelOptions(
            name="auditprogress",
            options={
                "ordering": ["registration__case"],
                "verbose_name": "Audit Progress",
                "verbose_name_plural": "Audit Progresses",
            },
        ),
        migrations.AlterModelOptions(
            name="case",
            options={
                "ordering": ["surname"],
                "permissions": [
                    (
                        "can_lock_child_case_data_from_editing",
                        "Can lock a child's record from editing.",
                    ),
                    (
                        "can_unlock_child_case_data_from_editing",
                        "Can unlock a child's record from editing.",
                    ),
                    (
                        "can_opt_out_child_from_inclusion_in_audit",
                        "Can sanction an opt out from participating in the audit. Note all the child's date except Epilepsy12 unique identifier are irretrievably deleted.",
                    ),
                    (
                        "can_consent_to_audit_participation",
                        "Can consent to participating in Epilepsy12.",
                    ),
                ],
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
            },
        ),
        migrations.AlterModelOptions(
            name="comorbidity",
            options={
                "ordering": [
                    "multiaxial_diagnosis__registration__case",
                    "comorbidityentity",
                ],
                "verbose_name": "Comorbidity",
                "verbose_name_plural": "Comorbidities",
            },
        ),
        migrations.AlterModelOptions(
            name="epilepsycontext",
            options={
                "ordering": ["registration__case"],
                "verbose_name": "Epilepsy Context",
                "verbose_name_plural": "Epilepsy Contexts",
            },
        ),
        migrations.AlterModelOptions(
            name="episode",
            options={
                "ordering": ["multiaxial_diagnosis__registration__case"],
                "verbose_name": "Episode",
                "verbose_name_plural": "Episodes",
            },
        ),
        migrations.AlterModelOptions(
            name="firstpaediatricassessment",
            options={
                "ordering": ["registration__case"],
                "verbose_name": "First Paediatric Assessment",
                "verbose_name_plural": "First Paediatric Assessments",
            },
        ),
        migrations.AlterModelOptions(
            name="investigations",
            options={
                "ordering": ["registration__case"],
                "verbose_name": "Investigations",
                "verbose_name_plural": "Investigations",
            },
        ),
        migrations.AlterModelOptions(
            name="kpi",
            options={
                "ordering": ["registration__case"],
                "verbose_name": "KPI ",
                "verbose_name_plural": "KPIs",
            },
        ),
        migrations.AlterModelOptions(
            name="management",
            options={
                "ordering": ["registration__case"],
                "verbose_name": "Management",
                "verbose_name_plural": "Management Plans",
            },
        ),
        migrations.AlterModelOptions(
            name="multiaxialdiagnosis",
            options={
                "ordering": ["registration__case"],
                "verbose_name": "Multiaxial Diagnosis",
                "verbose_name_plural": "Multiaxial diagnosis assessments",
            },
        ),
        migrations.AlterModelOptions(
            name="registration",
            options={
                "ordering": ["case"],
                "permissions": [
                    (
                        "can_approve_eligibility",
                        "Can approve eligibility for Epilepsy12.",
                    ),
                    (
                        "can_register_child_in_epilepsy12",
                        "Can register child in Epilepsy12. (A cohort number is automatically allocated)",
                    ),
                    (
                        "can_unregister_child_in_epilepsy12",
                        "Can unregister a child in Epilepsy. Their record and previously entered data is untouched.",
                    ),
                    (
                        "can_consent_to_audit_participation",
                        "Can consent to participating in Epilepsy12.",
                    ),
                ],
                "verbose_name": "Registration",
                "verbose_name_plural": "Registrations",
            },
        ),
        migrations.AlterModelOptions(
            name="syndrome",
            options={
                "ordering": ["multiaxial_diagnosis__registration__case"],
                "verbose_name": "Syndrome",
                "verbose_name_plural": "Syndromes",
            },
        ),
        migrations.AlterField(
            model_name="case",
            name="ethnicity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "White British"),
                    ("B", "White - Irish"),
                    ("C", "White - Any other White background"),
                    ("D", "Mixed (White and Black Caribbean)"),
                    ("E", "Mixed (White and Black African)"),
                    ("F", "Mixed (White and Asian)"),
                    ("G", "Mixed - Any other mixed background"),
                    ("H", "Indian or British Indian"),
                    ("J", "Asian or Asian British - Pakistani"),
                    ("K", "Asian or Asian British - Bangladeshi"),
                    ("L", "Asian or Asian British - Any other Asian background"),
                    ("M", "Black or Black British - Caribbean"),
                    ("N", "Black or Black British - African"),
                    ("P", "Black or Black British - Any other Black background"),
                    ("S", "Other Ethnic Groups - Any other ethnic group"),
                    ("R", "Other Ethnic Groups - Chinese"),
                    ("Z", "Not Stated"),
                ],
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="ethnicity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "White British"),
                    ("B", "White - Irish"),
                    ("C", "White - Any other White background"),
                    ("D", "Mixed (White and Black Caribbean)"),
                    ("E", "Mixed (White and Black African)"),
                    ("F", "Mixed (White and Asian)"),
                    ("G", "Mixed - Any other mixed background"),
                    ("H", "Indian or British Indian"),
                    ("J", "Asian or Asian British - Pakistani"),
                    ("K", "Asian or Asian British - Bangladeshi"),
                    ("L", "Asian or Asian British - Any other Asian background"),
                    ("M", "Black or Black British - Caribbean"),
                    ("N", "Black or Black British - African"),
                    ("P", "Black or Black British - Any other Black background"),
                    ("S", "Other Ethnic Groups - Any other ethnic group"),
                    ("R", "Other Ethnic Groups - Chinese"),
                    ("Z", "Not Stated"),
                ],
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="ods_code",
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="ods_code",
            field=models.CharField(
                blank=True, default=None, max_length=100, null=True, unique=True
            ),
        ),
    ]
