# Generated by Django 4.1.2 on 2022-10-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0024_multiaxialdiagnosis_mental_health_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiaxialdiagnosis',
            name='mental_health_issue',
            field=models.CharField(blank=True, choices=[('MoD', 'Mood disorder'), ('AxD', 'Anxiety disorder'), ('EmB', 'Emotional/ behavioural'), ('SHm', 'Self harm'), ('Oth', 'Other')], default=None, help_text={'label': 'Add details of any known mental health problem(s)', 'reference': 'Add details of any known mental health problem(s)'}, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='multiaxialdiagnosis',
            name='mental_health_issue_identified',
            field=models.BooleanField(blank=True, default=None, help_text={'label': 'Has a mental health issue been identified?', 'reference': 'Does the child have any mental health issue identified?'}, null=True),
        ),
        migrations.AlterField(
            model_name='multiaxialdiagnosis',
            name='mental_health_screen',
            field=models.BooleanField(blank=True, default=None, help_text={'label': 'Has a mental health concern been sought?', 'reference': 'Is there evidence of the child being assessed for mental health problems via clinical enquiry or the use of a screening questionnaire?'}, null=True),
        ),
    ]
