# Generated by Django 4.2.4 on 2023-08-15 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0025_alter_trustkpiaggregation_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organisationkpiaggregation",
            old_name="organisation",
            new_name="abstraction_relation",
        ),
        migrations.RenameField(
            model_name="trustkpiaggregation",
            old_name="parent_organisation_ods_code",
            new_name="abstraction_relation",
        ),
    ]
