# Generated by Django 4.0.4 on 2022-08-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0025_remove_antiepilepsymedicine_antiepilepsy_medicine_type_other_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='management',
            old_name='individualised_care_plan_includes_parental_prolonged_seizure_care',
            new_name='individualised_care_plan_parental_prolonged_seizure_care',
        ),
    ]
