# Generated by Django 4.1.2 on 2022-10-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0025_alter_multiaxialdiagnosis_mental_health_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='has_been_referred_for_mental_health_support',
            field=models.BooleanField(blank=True, default=None, help_text={'label': 'Has a referral for mental health support been made?', 'reference': 'Has the child been referred for support with their mental health?'}, null=True),
        ),
        migrations.AddField(
            model_name='management',
            name='has_support_for_mental_health_support',
            field=models.BooleanField(blank=True, default=None, help_text={'label': 'Is mental health support in place?', 'reference': 'Is there evidence of the child receiving support for their mental health?'}, null=True),
        ),
    ]
