# Generated by Django 4.2.10 on 2024-02-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0025_alter_antiepilepsymedicine_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kpi",
            name="sudep",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "v. Sudden unexpected death in epilepsy",
                    "reference": "Percentage of children and young people with epilepsy with evidence of discussion regarding SUDEP (Sudden unexpected death in epilepsy).",
                },
                null=True,
            ),
        ),
    ]
