# Generated by Django 4.1.2 on 2022-10-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0026_management_has_been_referred_for_mental_health_support_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='nonepileptic_seizure_behavioural',
            field=models.CharField(blank=True, choices=[('a', 'Daydreaming / Inattention'), ('b', 'Infantile gratification'), ('c', 'Eidetic imagery'), ('d', 'Tantrums and rage reactions'), ('e', 'Out of body experiences'), ('f', 'Panic attacks'), ('g', 'Dissociative states'), ('h', 'Non-epileptic seizures'), ('i', 'Hallucinations in psychiatric disorders'), ('j', 'Fabricated / factitious illness')], default=None, help_text={'label': 'How best describes the <i>type</i> of behavioural episode?', 'reference': 'How best describes the <i>type</i> of behavioural episode?'}, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='nonepileptic_seizure_migraine',
            field=models.CharField(blank=True, choices=[('a', 'Migraine with visual aura'), ('b', 'Familial hemiplegic migraine'), ('c', 'Benign paroxysmal torticollis'), ('d', 'Benign paroxysmal vertigo'), ('e', 'Cyclical vomiting')], default=None, help_text={'label': 'How best describes the <i>type</i> of migraine?', 'reference': 'How best describes the <i>type</i> of migraine?'}, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='nonepileptic_seizure_miscellaneous',
            field=models.CharField(blank=True, choices=[('a', 'Benign myoclonus of infancy and shuddering attacks'), ('b', 'Jitteriness'), ('c', 'Sandifer syndrome'), ('d', 'Non-epileptic head drops'), ('e', 'Spasmus nutans'), ('f', 'Raised intracranial pressure'), ('g', 'Paroxysmal extreme pain disorder'), ('h', 'Spinal myoclonus')], default=None, help_text={'label': 'How best describes the <i>subtype</i>?', 'reference': 'How best describes the <i>subtype</i>?'}, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='nonepileptic_seizure_paroxysmal',
            field=models.CharField(blank=True, choices=[('a', 'Tics'), ('b', 'Stereotypies'), ('c', 'Paroxysmal kinesigenic dyskinesia'), ('d', 'Paroxysmal nonkinesigenic dyskinesia'), ('e', 'Paroxysmal exercise induced dyskinesia'), ('f', 'Benign paroxysmal tonic upgaze'), ('g', 'Episodic ataxias'), ('h', 'Alternating hemiplegia'), ('i', 'Hyperekplexia'), ('j', 'Opsoclonus-myoclonus syndrome')], default=None, help_text={'label': 'How best describes the <i>type</i> of paroxysmal event?', 'reference': 'How best describes the <i>type</i> of paroxysmal event?'}, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='nonepileptic_seizure_sleep',
            field=models.CharField(blank=True, choices=[('a', 'Sleep related rhythmic movement disorders'), ('b', 'Hypnogogic jerks'), ('c', 'Parasomnias'), ('d', 'REM sleep disorders'), ('e', 'Benign neonatal sleep myoclonus'), ('f', 'Periodic leg movements'), ('g', 'Narcolepsy-cataplexy')], default=None, help_text={'label': 'How best describes the <i>type</i> of sleep event?', 'reference': 'How best describes the <i>type</i> of sleep event?'}, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='nonepileptic_seizure_syncope',
            field=models.CharField(blank=True, choices=[('a', 'Vasovagal syncope'), ('b', 'Reflex anoxic seizures'), ('c', 'Breath-holding attacks'), ('d', 'Hyperventilation syncope'), ('e', 'Compulsive valsalva'), ('f', 'Neurological syncope'), ('g', 'Imposed upper airways obstruction'), ('h', 'Orthostatic intolerance'), ('i', 'Long QT and cardiac syncope'), ('j', 'Hyper-cyanotic spells')], default=None, help_text={'label': 'How best describes the <i>type</i> of syncope?', 'reference': 'How best describes the <i>type</i> of syncope?'}, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='nonepileptic_seizure_unknown_onset',
            field=models.CharField(blank=True, choices=[('TCl', 'Tonic-clonic'), ('EpS', 'Epileptic spasms'), ('BAr', 'Behaviour arrest'), ('Oth', 'Other')], default=None, help_text={'label': 'How best describes the generalised nature of the nonepileptic episode(s)?', 'reference': 'How best describes the generalised nature of the nonepileptic episode(s)?'}, max_length=3, null=True),
        ),
    ]
