# Generated by Django 5.0.3 on 2024-05-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0026_alter_kpi_sudep"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="focal_onset_laterality_unknown",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalepisode",
            name="focal_onset_laterality_unknown",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="consultant_paediatrician_referral_date",
            field=models.DateField(
                blank=True,
                default=None,
                help_text={
                    "label": "Date of referral to a consultant paediatrician with expertise in epilepsies.",
                    "reference": "Date referral made to a consultant paediatrician with expertise in epilepsies.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="consultant_paediatrician_referral_made",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text={
                    "label": "Has a referral been made to a consultant paediatrician with expertise in epilepsies?",
                    "reference": "A 'paediatrician with expertise' is a paediatric consultant (or associate specialist) defined by themselves, their employer and tertiary services/networks has having: 1) Training & continuing education in epilepsies, 2) Peer review of practice and 3) Regular audit of diagnosis (eg. participation in Epilepsy12). A paediatric neurologist is also defined as a paediatrician with expertise. Informs KPI 1",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalassessment",
            name="consultant_paediatrician_referral_date",
            field=models.DateField(
                blank=True,
                default=None,
                help_text={
                    "label": "Date of referral to a consultant paediatrician with expertise in epilepsies.",
                    "reference": "Date referral made to a consultant paediatrician with expertise in epilepsies.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalassessment",
            name="consultant_paediatrician_referral_made",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text={
                    "label": "Has a referral been made to a consultant paediatrician with expertise in epilepsies?",
                    "reference": "A 'paediatrician with expertise' is a paediatric consultant (or associate specialist) defined by themselves, their employer and tertiary services/networks has having: 1) Training & continuing education in epilepsies, 2) Peer review of practice and 3) Regular audit of diagnosis (eg. participation in Epilepsy12). A paediatric neurologist is also defined as a paediatrician with expertise. Informs KPI 1",
                },
                null=True,
            ),
        ),
    ]
