# Generated by Django 4.1.2 on 2022-10-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0027_alter_episode_nonepileptic_seizure_behavioural_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_close_date',
            field=models.DateField(default=None, help_text={'label': 'First paediatric assessment closing date', 'reference': 'Date on which the registration is due to close'}, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.DateField(default=None, help_text={'label': 'Date of first paediatric assessment', 'reference': 'Date of first paediatric assessment'}, null=True),
        ),
    ]
