# Generated by Django 4.0.4 on 2022-08-09 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0027_remove_assessment_has_an_aed_been_given_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='management',
            old_name='has_rescue_medication_prescribed',
            new_name='has_rescue_medication_been_prescribed',
        ),
    ]
