# Generated by Django 4.1.2 on 2022-10-29 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0028_alter_registration_registration_close_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InitialAssessment',
            new_name='FirstPaediatricAssessment',
        ),
        migrations.RenameField(
            model_name='auditprogress',
            old_name='initial_assessment_complete',
            new_name='first_paediatric_assessment_complete',
        ),
        migrations.RenameField(
            model_name='auditprogress',
            old_name='initial_assessment_total_completed_fields',
            new_name='first_paediatric_assessment_total_completed_fields',
        ),
        migrations.RenameField(
            model_name='auditprogress',
            old_name='initial_assessment_total_expected_fields',
            new_name='first_paediatric_assessment_total_expected_fields',
        ),
    ]
