# Generated by Django 5.0.3 on 2024-05-18 16:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "epilepsy12",
            "0028_epilepsy12user_created_at_epilepsy12user_created_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="longitude and latitude of the postcode",
                null=True,
                srid=27700,
            ),
        ),
        migrations.AddField(
            model_name="historicalcase",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="longitude and latitude of the postcode",
                null=True,
                srid=27700,
            ),
        ),
        migrations.AlterField(
            model_name="epilepsy12user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="epilepsy12user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalepilepsy12user",
            name="created_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="historicalepilepsy12user",
            name="updated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="visitactivity",
            name="activity",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Successful login"),
                    (2, "Login failed"),
                    (3, "Logout"),
                    (4, "Password Reset link sent"),
                    (5, "Password reset"),
                    (6, "Two factor authentication set up"),
                ],
                default=1,
            ),
        ),
    ]
