# Generated by Django 5.0.3 on 2024-05-19 16:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0029_case_location_historicalcase_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="location",
        ),
        migrations.RemoveField(
            model_name="historicalcase",
            name="location",
        ),
        migrations.AddField(
            model_name="case",
            name="location_bng",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="longitude and latitude of the postcode as British National Grid (BNG)",
                null=True,
                srid=27700,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="location_wgs",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="longitude and latitude of the postcode as British National Grid (BNG)",
                null=True,
                srid=27700,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="location_wgs84",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="longitude and latitude of the postcode as WGS 84",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AddField(
            model_name="historicalcase",
            name="location_bng",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="longitude and latitude of the postcode as British National Grid (BNG)",
                null=True,
                srid=27700,
            ),
        ),
        migrations.AddField(
            model_name="historicalcase",
            name="location_wgs",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="longitude and latitude of the postcode as British National Grid (BNG)",
                null=True,
                srid=27700,
            ),
        ),
        migrations.AddField(
            model_name="historicalcase",
            name="location_wgs84",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="longitude and latitude of the postcode as WGS 84",
                null=True,
                srid=4326,
            ),
        ),
    ]
