# Generated by Django 4.1.2 on 2022-11-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0030_alter_multiaxialdiagnosis_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'permissions': (('can_only_view_general_paediatric_centre', 'Can only view general paediatric centre.'), ('can_only_view_tertiary_neurology_centre', 'Can only view tertiary neurology centre.'), ('can_only_view_childrens_epilepsy_surgery_centre', "Can only view children's epilepsy surgery centre."), ('can_allocate_general_paediatric_centre', 'Can allocate general paediatric centre.'), ('can_update_general_paediatric_centre', 'Can edit or update but not delete general paediatric centre.'), ('can_delete_general_paediatric_centre', 'Can delete general paediatric centre.'), ('can_allocate_tertiary_neurology_centre', 'Can allocate tertiary neurology centre.'), ('can_edit_tertiary_neurology_centre', 'Can edit or update but not delete tertiary neurology centre.'), ('can_delete_tertiary_neurology_centre', 'Can delete tertiary neurology centre.'), ('can_confirm_childrens_epilepsy_surgical_service_referral_criteria_met', "Can confirm children's epilepsy surgery centre referral criteria have been met."), ('can_allocate_childrens_epilepsy_surgery_centre', "Can allocate children's epilepsy surgery centre."), ('can_edit_childrens_epilepsy_surgery_centre', "Can edit or update but not delete children's epilepsy surgery centre."), ('can_delete_childrens_epilepsy_surgery_centre', "Can delete children's epilepsy surgery centre.")), 'verbose_name': 'Assessment', 'verbose_name_plural': 'Assessment'},
        ),
        migrations.AlterModelOptions(
            name='investigations',
            options={'verbose_name': 'Investigations', 'verbose_name_plural': 'Investigations'},
        ),
        migrations.AlterModelOptions(
            name='management',
            options={'verbose_name': 'Management', 'verbose_name_plural': 'Management Plans'},
        ),
        migrations.AlterField(
            model_name='antiepilepsymedicine',
            name='medicine_id',
            field=models.IntegerField(blank=True, default=None, help_text={'label': 'Medicine Name', 'reference': 'Please enter the medicine.'}, null=True),
        ),
    ]
