# Generated by Django 4.2.4 on 2023-08-22 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "epilepsy12",
            "0030_alter_countrykpiaggregation_abstraction_relation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="countrykpiaggregation",
            name="abstraction_relation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="epilepsy12.onscountryentity",
            ),
        ),
        migrations.AlterField(
            model_name="icbkpiaggregation",
            name="abstraction_relation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="epilepsy12.integratedcareboardentity",
            ),
        ),
        migrations.AlterField(
            model_name="nhsregionkpiaggregation",
            name="abstraction_relation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="epilepsy12.nhsregionentity",
            ),
        ),
        migrations.AlterField(
            model_name="openukkpiaggregation",
            name="abstraction_relation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="epilepsy12.openuknetworkentity",
            ),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="abstraction_relation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="epilepsy12.organisation",
            ),
        ),
    ]
