# Generated by Django 5.0.3 on 2024-08-30 15:46

import epilepsy12.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "epilepsy12",
            "0030_remove_case_location_remove_historicalcase_location_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalregistration",
            name="first_paediatric_assessment_date",
            field=models.DateField(
                default=None,
                help_text={
                    "label": "First paediatric assessment",
                    "reference": "'First paediatric assessment' is when the patient was initally seen by a paedaitric professional for parozysmal episodes in any healthcare setting. Setting this date is an irreversible step. Confirmation will be requested to complete this step.",
                },
                null=True,
                validators=[epilepsy12.validators.not_in_the_future_validator],
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="paediatrician_with_expertise_in_epilepsies",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "1. Paediatrician with expertise",
                    "reference": "Percentage of children and young people with epilepsy, with input by a 'consultant paediatrician with expertise in epilepsies' within 2 weeks of initial referral",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="school_individual_healthcare_plan",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "10. School Individual Healthcare Plan",
                    "reference": "Percentage of children and young people with epilepsy aged 4 years and above with evidence of a school individual healthcare plan by 1 year after first paediatric assessment.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="tertiary_input",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "3a. Tertiary involvement",
                    "reference": "Percentage of children and young people meeting defined criteria for paediatric neurology referral, with input of tertiary care and/or CESS referral within the first year of care.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="first_paediatric_assessment_date",
            field=models.DateField(
                default=None,
                help_text={
                    "label": "First paediatric assessment",
                    "reference": "'First paediatric assessment' is when the patient was initally seen by a paedaitric professional for parozysmal episodes in any healthcare setting. Setting this date is an irreversible step. Confirmation will be requested to complete this step.",
                },
                null=True,
                validators=[epilepsy12.validators.not_in_the_future_validator],
            ),
        ),
    ]
