# Generated by Django 4.0.4 on 2022-08-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0030_alter_antiepilepsymedicine_antiepilepsy_medicine_snomed_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antiepilepsymedicine',
            name='is_a_pregnancy_prevention_programme_in_place',
        ),
        migrations.AddField(
            model_name='management',
            name='is_a_pregnancy_prevention_programme_in_place',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Is there a pregnancy prevention programme (PPP) in place?'),
        ),
    ]
