# Generated by Django 5.0.3 on 2024-09-24 15:10

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import epilepsy12.models_folder.help_text_mixin
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "epilepsy12",
            "0031_alter_historicalregistration_first_paediatric_assessment_date_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationalAuditSubmissionPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("is_open", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="OrganisationalAuditSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "S01WTEConsultants",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=7, null=True
                    ),
                ),
                (
                    "S01WTEConsultantsEpilepsy",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=7, null=True
                    ),
                ),
                ("S01EpilepsyClinicalLead", models.BooleanField(blank=True, null=True)),
                (
                    "S01EpilepsyClinicalLeadTitle",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "S01EpilepsyClinicalLeadFirstName",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "S01EpilepsyClinicalLeadSurname",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "S01WTEEpilepsySpecialistNurses",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=7, null=True
                    ),
                ),
                (
                    "S01ESNFunctions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(
                            choices=[
                                (1, "ED visits"),
                                (2, "Home visits"),
                                (
                                    3,
                                    "School Individual Healthcare Plan (IHP) facilitation",
                                ),
                                (4, "Nurse led clinics"),
                                (5, "Nurse prescribing"),
                                (6, "Rescue medication training for parents"),
                                (7, "Rescue medication training for schools"),
                                (8, "School meetings"),
                                (9, "Ward visits"),
                                (10, "None of the above"),
                            ]
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "S01JobPlannedHoursPerWeekLeadershipQIActivities",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "S02DefinedEpilepsyClinics",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S02EpilepsyClinicsPerWeek",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=7, null=True
                    ),
                ),
                ("S02Consultant20Mins", models.BooleanField(blank=True, null=True)),
                (
                    "S02TFC223",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "Not applicable"),
                            (2, "Yes"),
                            (3, "No, not at all"),
                            (4, "No, in development"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "S03WTEPaediatricNeurologists",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=7, null=True
                    ),
                ),
                (
                    "S03PathwaysTertiaryPaedNeurology",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S03PaedNeurologistsDirectReferrals",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S03SatellitePaediatricNeurologyClinics",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S03CommenceKetogenicDiet",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S03ReviewKetogenicDiet",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S03VNSInsertion",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S03VNSReview",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04LeadECG",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04AwakeMRI",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04MriWithSedation",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04MriWithGeneralAnaesthetic",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04StandardEeg",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04SleepDeprivedEeg",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04MelatoninInducedEeg",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04SedatedEeg",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S042448HAmbulatoryEeg",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04InpatientVideoTelemetry",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04OutpatientVideoTelemetry",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04HomeVideoTelemetry",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04PortableEEGOnWardAreaWithinTrust",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S05ContactEpilepsyServiceForSpecialistAdvice",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S05AdviceAvailableAllWeekdays",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S05AdviceAvailableAllOutOfHours",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S05AdviceAvailable52WeeksPerYear",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S05TypicalTimeToAchieveSpecialistAdvice",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "Same working day"),
                            (2, "By next working day"),
                            (3, "Within 3-4 working days"),
                            (4, "Within a working week"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "S05WhoProvidesSpecialistAdvice",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "ESN"),
                            (2, "Consultant Paediatrician with expertise in epilepsy"),
                            (3, "Paediatric neurologist"),
                            (4, "Trainee paediatric neurologist"),
                            (5, "Other"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "S05WhoProvidesSpecialistAdviceOther",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "S05evidenceclearpointofcontact",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S06AgreeedReferralPathwaysAdultServices",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S06OutpatientClinicYoungPeopleEpilepsies",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S06WhatAgeDoesThisClinicAcceptYoungPeople",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "S06ServiceForEpilepsyBopthAdultAndPaed",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S06IsThisUsually",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "A single joint appointment"),
                            (2, "A series of several joint appointments"),
                            (
                                3,
                                "A flexible appraoch including mixture of joint or individual reviews",
                            ),
                            (4, "Other"),
                        ],
                        null=True,
                    ),
                ),
                ("S06IsThisUsuallyOther", models.CharField(blank=True, null=True)),
                (
                    "S06PercentageOfYoungPeopleTransferred",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "S06ProfessionalsRoutinelyInvolvedInTransitionAdultESN",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "Adult ESN"),
                            (2, "Adult Learning difficulty ESN"),
                            (3, "Adult Neurologist"),
                            (4, "Youth Worker"),
                            (5, "Other"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "S06ProfessionalsRoutinelyInvolvedInTransitionAdultESNOther",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "S06StructuredResourcesToSupportTransition",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S07ScreenForIssuesMentalHealth",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S07MentalHealthQuestionnaire",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "BDI - Beck Depression Inventory"),
                            (2, "Connor's Questionnaire"),
                            (3, "Emotional Thermometers Tool"),
                            (4, "GAD - Generalised Anxiety Disorder"),
                            (5, "GAD 2 - Generalised Anxiety Disorder 2"),
                            (6, "GAD 7 - Generalised Anxiety Disorder 7"),
                            (7, "HADS - Hospital Anxiety and Depression Scale"),
                            (
                                8,
                                "MFQ - Mood and Feelings Questionnaire (Child, Parent, Adult versions)",
                            ),
                            (
                                9,
                                "NDDI-E Neurological Disorders Depression Inventory for Epilepsy",
                            ),
                            (10, "PHQ - Patient Health Questionnaire, PHQ 2, PHQ 9"),
                            (11, "SDQ (Strengths and Difficulties Questionnaire)"),
                            (12, "Other"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "S07MentalHealthQuestionnaireOther",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "S07MentalHealthAgreedPathway",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "Anxiety"),
                            (2, "Depression"),
                            (3, "Mood Disorders"),
                            (4, "Non-epileptic attack disorders"),
                            (5, "Other"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "S07MentalHealthAgreedPathwayOther",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "S07MentalHealthProvisionEpilepsyClinics",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S07DoesThisCompromise",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (
                                1,
                                "Epilepsy Clinics where mental health professionals can provide direct co-located clinical care",
                            ),
                            (
                                2,
                                "MDT meetings where epilepsy and mental health professionals discuss individual patients",
                            ),
                            (3, "Other"),
                        ],
                        null=True,
                    ),
                ),
                ("S07DoesThisCompromiseOther", models.CharField(blank=True, null=True)),
                (
                    "S07CurrentTrustActionPlanCoLocatedMentalHealth",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S07TrustAchieve",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "Clinical psychology assessment"),
                            (2, "Educational psychology assessment"),
                            (3, "Formal developmental assessment"),
                            (4, "Neurospsychology assessment"),
                            (5, "Psychiatric assessment"),
                            (6, "Cannot achieve any of the above"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "S08ScreenForNeurodevelopmentalConditions",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S08AgreedReferralCriteriaChildrenNeurodevelopmental",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "ADHD"),
                            (2, "ASD"),
                            (3, "Behavioural difficulties"),
                            (4, "Developmental Coordination Disorder"),
                            (5, "Intellectual disability/Global developmental delay"),
                            (6, "Learning disabilities"),
                            (8, "None of the above"),
                            (7, "Other"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "S08AgreedReferralCriteriaChildrenNeurodevelopmentalOther",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "S09ComprehensiveCarePlanningChildrenEpilepsy",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S10TrustMaintainADatabaseOfChildrenWithEpilepsy",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "Yes, for all children"),
                            (2, "Yes, for some children"),
                            (3, "No"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="record created by user in %(class)",
                    ),
                ),
                (
                    "local_health_board",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="epilepsy12.localhealthboard",
                    ),
                ),
                (
                    "trust",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="epilepsy12.trust",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="record updated by user in %(class)",
                    ),
                ),
                (
                    "submission_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="epilepsy12.organisationalauditsubmissionperiod",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                models.Model,
                epilepsy12.models_folder.help_text_mixin.HelpTextMixin,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalOrganisationalAuditSubmission",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "S01WTEConsultants",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=7, null=True
                    ),
                ),
                (
                    "S01WTEConsultantsEpilepsy",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=7, null=True
                    ),
                ),
                ("S01EpilepsyClinicalLead", models.BooleanField(blank=True, null=True)),
                (
                    "S01EpilepsyClinicalLeadTitle",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "S01EpilepsyClinicalLeadFirstName",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "S01EpilepsyClinicalLeadSurname",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "S01WTEEpilepsySpecialistNurses",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=7, null=True
                    ),
                ),
                (
                    "S01ESNFunctions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(
                            choices=[
                                (1, "ED visits"),
                                (2, "Home visits"),
                                (
                                    3,
                                    "School Individual Healthcare Plan (IHP) facilitation",
                                ),
                                (4, "Nurse led clinics"),
                                (5, "Nurse prescribing"),
                                (6, "Rescue medication training for parents"),
                                (7, "Rescue medication training for schools"),
                                (8, "School meetings"),
                                (9, "Ward visits"),
                                (10, "None of the above"),
                            ]
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "S01JobPlannedHoursPerWeekLeadershipQIActivities",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "S02DefinedEpilepsyClinics",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S02EpilepsyClinicsPerWeek",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=7, null=True
                    ),
                ),
                ("S02Consultant20Mins", models.BooleanField(blank=True, null=True)),
                (
                    "S02TFC223",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "Not applicable"),
                            (2, "Yes"),
                            (3, "No, not at all"),
                            (4, "No, in development"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "S03WTEPaediatricNeurologists",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=7, null=True
                    ),
                ),
                (
                    "S03PathwaysTertiaryPaedNeurology",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S03PaedNeurologistsDirectReferrals",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S03SatellitePaediatricNeurologyClinics",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S03CommenceKetogenicDiet",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S03ReviewKetogenicDiet",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S03VNSInsertion",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S03VNSReview",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04LeadECG",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04AwakeMRI",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04MriWithSedation",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04MriWithGeneralAnaesthetic",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04StandardEeg",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04SleepDeprivedEeg",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04MelatoninInducedEeg",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04SedatedEeg",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S042448HAmbulatoryEeg",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04InpatientVideoTelemetry",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04OutpatientVideoTelemetry",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04HomeVideoTelemetry",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S04PortableEEGOnWardAreaWithinTrust",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                        null=True,
                    ),
                ),
                (
                    "S05ContactEpilepsyServiceForSpecialistAdvice",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S05AdviceAvailableAllWeekdays",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S05AdviceAvailableAllOutOfHours",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S05AdviceAvailable52WeeksPerYear",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S05TypicalTimeToAchieveSpecialistAdvice",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "Same working day"),
                            (2, "By next working day"),
                            (3, "Within 3-4 working days"),
                            (4, "Within a working week"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "S05WhoProvidesSpecialistAdvice",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "ESN"),
                            (2, "Consultant Paediatrician with expertise in epilepsy"),
                            (3, "Paediatric neurologist"),
                            (4, "Trainee paediatric neurologist"),
                            (5, "Other"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "S05WhoProvidesSpecialistAdviceOther",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "S05evidenceclearpointofcontact",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S06AgreeedReferralPathwaysAdultServices",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S06OutpatientClinicYoungPeopleEpilepsies",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S06WhatAgeDoesThisClinicAcceptYoungPeople",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "S06ServiceForEpilepsyBopthAdultAndPaed",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S06IsThisUsually",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "A single joint appointment"),
                            (2, "A series of several joint appointments"),
                            (
                                3,
                                "A flexible appraoch including mixture of joint or individual reviews",
                            ),
                            (4, "Other"),
                        ],
                        null=True,
                    ),
                ),
                ("S06IsThisUsuallyOther", models.CharField(blank=True, null=True)),
                (
                    "S06PercentageOfYoungPeopleTransferred",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "S06ProfessionalsRoutinelyInvolvedInTransitionAdultESN",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "Adult ESN"),
                            (2, "Adult Learning difficulty ESN"),
                            (3, "Adult Neurologist"),
                            (4, "Youth Worker"),
                            (5, "Other"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "S06ProfessionalsRoutinelyInvolvedInTransitionAdultESNOther",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "S06StructuredResourcesToSupportTransition",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S07ScreenForIssuesMentalHealth",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S07MentalHealthQuestionnaire",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "BDI - Beck Depression Inventory"),
                            (2, "Connor's Questionnaire"),
                            (3, "Emotional Thermometers Tool"),
                            (4, "GAD - Generalised Anxiety Disorder"),
                            (5, "GAD 2 - Generalised Anxiety Disorder 2"),
                            (6, "GAD 7 - Generalised Anxiety Disorder 7"),
                            (7, "HADS - Hospital Anxiety and Depression Scale"),
                            (
                                8,
                                "MFQ - Mood and Feelings Questionnaire (Child, Parent, Adult versions)",
                            ),
                            (
                                9,
                                "NDDI-E Neurological Disorders Depression Inventory for Epilepsy",
                            ),
                            (10, "PHQ - Patient Health Questionnaire, PHQ 2, PHQ 9"),
                            (11, "SDQ (Strengths and Difficulties Questionnaire)"),
                            (12, "Other"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "S07MentalHealthQuestionnaireOther",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "S07MentalHealthAgreedPathway",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "Anxiety"),
                            (2, "Depression"),
                            (3, "Mood Disorders"),
                            (4, "Non-epileptic attack disorders"),
                            (5, "Other"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "S07MentalHealthAgreedPathwayOther",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "S07MentalHealthProvisionEpilepsyClinics",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S07DoesThisCompromise",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (
                                1,
                                "Epilepsy Clinics where mental health professionals can provide direct co-located clinical care",
                            ),
                            (
                                2,
                                "MDT meetings where epilepsy and mental health professionals discuss individual patients",
                            ),
                            (3, "Other"),
                        ],
                        null=True,
                    ),
                ),
                ("S07DoesThisCompromiseOther", models.CharField(blank=True, null=True)),
                (
                    "S07CurrentTrustActionPlanCoLocatedMentalHealth",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S07TrustAchieve",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "Clinical psychology assessment"),
                            (2, "Educational psychology assessment"),
                            (3, "Formal developmental assessment"),
                            (4, "Neurospsychology assessment"),
                            (5, "Psychiatric assessment"),
                            (6, "Cannot achieve any of the above"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "S08ScreenForNeurodevelopmentalConditions",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S08AgreedReferralCriteriaChildrenNeurodevelopmental",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "ADHD"),
                            (2, "ASD"),
                            (3, "Behavioural difficulties"),
                            (4, "Developmental Coordination Disorder"),
                            (5, "Intellectual disability/Global developmental delay"),
                            (6, "Learning disabilities"),
                            (8, "None of the above"),
                            (7, "Other"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "S08AgreedReferralCriteriaChildrenNeurodevelopmentalOther",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "S09ComprehensiveCarePlanningChildrenEpilepsy",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "S10TrustMaintainADatabaseOfChildrenWithEpilepsy",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "Yes, for all children"),
                            (2, "Yes, for some children"),
                            (3, "No"),
                        ],
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="record created by user in %(class)",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "local_health_board",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="epilepsy12.localhealthboard",
                    ),
                ),
                (
                    "trust",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="epilepsy12.trust",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="record updated by user in %(class)",
                    ),
                ),
                (
                    "submission_period",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="epilepsy12.organisationalauditsubmissionperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical organisational audit submission",
                "verbose_name_plural": "historical organisational audit submissions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
