# Generated by Django 4.2.4 on 2023-08-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "epilepsy12",
            "0031_alter_countrykpiaggregation_abstraction_relation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="countrykpiaggregation",
            name="cohort",
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="icbkpiaggregation",
            name="cohort",
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="nationalkpiaggregation",
            name="cohort",
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="nhsregionkpiaggregation",
            name="cohort",
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="openukkpiaggregation",
            name="cohort",
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="organisationkpiaggregation",
            name="cohort",
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="trustkpiaggregation",
            name="cohort",
            field=models.PositiveSmallIntegerField(default=None),
        ),
    ]
