# Generated by Django 5.0.3 on 2024-09-24 09:50

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "epilepsy12",
            "0031_alter_historicalregistration_first_paediatric_assessment_date_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationalAuditSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "S01WTEConsultants",
                    models.DecimalField(decimal_places=3, max_digits=7, null=True),
                ),
                (
                    "S01WTEConsultantsEpilepsy",
                    models.DecimalField(decimal_places=3, max_digits=7, null=True),
                ),
                ("S01EpilepsyClinicalLead", models.BooleanField(null=True)),
                ("S01EpilepsyClinicalLeadTitle", models.CharField(null=True)),
                ("S01EpilepsyClinicalLeadFirstName", models.CharField(null=True)),
                ("S01EpilepsyClinicalLeadSurname", models.CharField(null=True)),
                (
                    "S01WTEEpilepsySpecialistNurses",
                    models.DecimalField(decimal_places=3, max_digits=7, null=True),
                ),
                (
                    "S01ESNFunctions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(
                            choices=[
                                (1, "ED visits"),
                                (2, "Home visits"),
                                (
                                    3,
                                    "School Individual Healthcare Plan (IHP) facilitation",
                                ),
                                (4, "Nurse led clinics"),
                                (5, "Nurse prescribing"),
                                (6, "Rescue medication training for parents"),
                                (7, "Rescue medication training for schools"),
                                (8, "School meetings"),
                                (9, "Ward visits"),
                                (10, "None of the above"),
                            ],
                            null=True,
                        ),
                        size=None,
                    ),
                ),
                (
                    "S01JobPlannedHoursPerWeekLeadershipQIActivities",
                    models.PositiveIntegerField(null=True),
                ),
                ("S02DefinedEpilepsyClinics", models.BooleanField(null=True)),
                (
                    "S02EpilepsyClinicsPerWeek",
                    models.DecimalField(decimal_places=3, max_digits=7, null=True),
                ),
                ("S02Consultant20Mins", models.BooleanField(null=True)),
                (
                    "S02TFC223",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Not applicable"),
                            (2, "Yes"),
                            (3, "No, not at all"),
                            (4, "No, in development"),
                        ]
                    ),
                ),
                (
                    "S03WTEPaediatricNeurologists",
                    models.DecimalField(decimal_places=3, max_digits=7, null=True),
                ),
                ("S03PathwaysTertiaryPaedNeurology", models.BooleanField(null=True)),
                ("S03PaedNeurologistsDirectReferrals", models.BooleanField(null=True)),
                (
                    "S03SatellitePaediatricNeurologyClinics",
                    models.BooleanField(null=True),
                ),
                (
                    "S03CommenceKetogenicDiet",
                    models.PositiveIntegerField(
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
                    ),
                ),
                (
                    "S03ReviewKetogenicDiet",
                    models.PositiveIntegerField(
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
                    ),
                ),
                (
                    "S03VNSInsertion",
                    models.PositiveIntegerField(
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
                    ),
                ),
                (
                    "S03VNSReview",
                    models.PositiveIntegerField(
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
                    ),
                ),
                (
                    "S04LeadECG",
                    models.PositiveIntegerField(
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
                    ),
                ),
                (
                    "S04AwakeMRI",
                    models.PositiveIntegerField(
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
                    ),
                ),
                (
                    "S04MriWithSedation",
                    models.PositiveIntegerField(
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
                    ),
                ),
                (
                    "S04MriWithGeneralAnaesthetic",
                    models.PositiveIntegerField(
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
                    ),
                ),
                (
                    "S04StandardEeg",
                    models.PositiveIntegerField(
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
                    ),
                ),
                (
                    "S04SleepDeprivedEeg",
                    models.PositiveIntegerField(
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
                    ),
                ),
                (
                    "S04MelatoninInducedEeg",
                    models.PositiveIntegerField(
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
                    ),
                ),
                (
                    "S04SedatedEeg",
                    models.PositiveIntegerField(
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
                    ),
                ),
                (
                    "S042448HAmbulatoryEeg",
                    models.PositiveIntegerField(
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
                    ),
                ),
                (
                    "S04InpatientVideoTelemetry",
                    models.PositiveIntegerField(
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
                    ),
                ),
                (
                    "S04OutpatientVideoTelemetry",
                    models.PositiveIntegerField(
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
                    ),
                ),
                (
                    "S04HomeVideoTelemetry",
                    models.PositiveIntegerField(
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
                    ),
                ),
                (
                    "S04PortableEEGOnWardAreaWithinTrust",
                    models.PositiveIntegerField(
                        choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
                    ),
                ),
                (
                    "S05ContactEpilepsyServiceForSpecialistAdvice",
                    models.BooleanField(null=True),
                ),
                ("S05AdviceAvailableAllWeekdays", models.BooleanField(null=True)),
                ("S05AdviceAvailableAllOutOfHours", models.BooleanField(null=True)),
                ("S05AdviceAvailable52WeeksPerYear", models.BooleanField(null=True)),
                (
                    "S05TypicalTimeToAchieveSpecialistAdvice",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Same working day"),
                            (2, "By next working day"),
                            (3, "Within 3-4 working days"),
                            (4, "Within a working week"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "S05WhoProvidesSpecialistAdvice",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "ESN"),
                            (2, "Consultant Paediatrician with expertise in epilepsy"),
                            (3, "Paediatric neurologist"),
                            (4, "Trainee paediatric neurologist"),
                            (5, "Other"),
                        ],
                        null=True,
                    ),
                ),
                ("S05WhoProvidesSpecialistAdviceOther", models.CharField(null=True)),
                ("S05evidenceclearpointofcontact", models.BooleanField(null=True)),
                (
                    "S06AgreeedReferralPathwaysAdultServices",
                    models.BooleanField(null=True),
                ),
                (
                    "S06OutpatientClinicYoungPeopleEpilepsies",
                    models.BooleanField(null=True),
                ),
                (
                    "S06WhatAgeDoesThisClinicAcceptYoungPeople",
                    models.PositiveIntegerField(null=True),
                ),
                (
                    "S06ServiceForEpilepsyBopthAdultAndPaed",
                    models.BooleanField(null=True),
                ),
                (
                    "S06IsThisUsually",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "A single joint appointment"),
                            (2, "A series of several joint appointments"),
                            (
                                3,
                                "A flexible appraoch including mixture of joint or individual reviews",
                            ),
                            (4, "Other"),
                        ],
                        null=True,
                    ),
                ),
                ("S06IsThisUsuallyOther", models.CharField(null=True)),
                (
                    "S06PercentageOfYoungPeopleTransferred",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "S06ProfessionalsRoutinelyInvolvedInTransitionAdultESN",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Adult ESN"),
                            (2, "Adult Learning difficulty ESN"),
                            (3, "Adult Neurologist"),
                            (4, "Youth Worker"),
                            (5, "Other"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "S06ProfessionalsRoutinelyInvolvedInTransitionAdultESNOther",
                    models.CharField(null=True),
                ),
                (
                    "S06StructuredResourcesToSupportTransition",
                    models.BooleanField(null=True),
                ),
                ("S07ScreenForIssuesMentalHealth", models.BooleanField(null=True)),
                (
                    "S07MentalHealthQuestionnaire",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "BDI - Beck Depression Inventory"),
                            (2, "Connor's Questionnaire"),
                            (3, "Emotional Thermometers Tool"),
                            (4, "GAD - Generalised Anxiety Disorder"),
                            (5, "GAD 2 - Generalised Anxiety Disorder 2"),
                            (6, "GAD 7 - Generalised Anxiety Disorder 7"),
                            (7, "HADS - Hospital Anxiety and Depression Scale"),
                            (
                                8,
                                "MFQ - Mood and Feelings Questionnaire (Child, Parent, Adult versions)",
                            ),
                            (
                                9,
                                "NDDI-E Neurological Disorders Depression Inventory for Epilepsy",
                            ),
                            (10, "PHQ - Patient Health Questionnaire, PHQ 2, PHQ 9"),
                            (11, "SDQ (Strengths and Difficulties Questionnaire)"),
                            (12, "Other"),
                        ],
                        null=True,
                    ),
                ),
                ("S07MentalHealthQuestionnaireOther", models.CharField(null=True)),
                (
                    "S07MentalHealthAgreedPathway",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Anxiety"),
                            (2, "Depression"),
                            (3, "Mood Disorders"),
                            (4, "Non-epileptic attack disorders"),
                            (5, "Other"),
                        ],
                        null=True,
                    ),
                ),
                ("S07MentalHealthAgreedPathwayOther", models.CharField(null=True)),
                (
                    "S07MentalHealthProvisionEpilepsyClinics",
                    models.BooleanField(null=True),
                ),
                (
                    "S07DoesThisCompromise",
                    models.PositiveIntegerField(
                        choices=[
                            (
                                1,
                                "Epilepsy Clinics where mental health professionals can provide direct co-located clinical care",
                            ),
                            (
                                2,
                                "MDT meetings where epilepsy and mental health professionals discuss individual patients",
                            ),
                            (3, "Other"),
                        ],
                        null=True,
                    ),
                ),
                ("S07DoesThisCompromiseOther", models.CharField(null=True)),
                (
                    "S07CurrentTrustActionPlanCoLocatedMentalHealth",
                    models.BooleanField(null=True),
                ),
                (
                    "S07TrustAchieve",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Clinical psychology assessment"),
                            (2, "Educational psychology assessment"),
                            (3, "Formal developmental assessment"),
                            (4, "Neurospsychology assessment"),
                            (5, "Psychiatric assessment"),
                            (6, "Cannot achieve any of the above"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "S08ScreenForNeurodevelopmentalConditions",
                    models.BooleanField(null=True),
                ),
                (
                    "S08AgreedReferralCriteriaChildrenNeurodevelopmental",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "ADHD"),
                            (2, "ASD"),
                            (3, "Behavioural difficulties"),
                            (4, "Developmental Coordination Disorder"),
                            (5, "Intellectual disability/Global developmental delay"),
                            (6, "Learning disabilities"),
                            (8, "None of the above"),
                            (7, "Other"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "S08AgreedReferralCriteriaChildrenNeurodevelopmentalOther",
                    models.CharField(null=True),
                ),
                (
                    "S09ComprehensiveCarePlanningChildrenEpilepsy",
                    models.BooleanField(null=True),
                ),
                (
                    "S10TrustMaintainADatabaseOfChildrenWithEpilepsy",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Yes, for all children"),
                            (2, "Yes, for some children"),
                            (3, "No"),
                        ],
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganisationalAuditSubmissionPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("is_open", models.BooleanField(default=False)),
            ],
        ),
    ]
