# Generated by Django 4.1.2 on 2022-11-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0031_alter_assessment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiepilepsymedicine',
            name='has_a_valproate_annual_risk_acknowledgement_form_been_completed',
            field=models.BooleanField(blank=True, default=None, help_text={'label': 'Has a Valproate - Annual Risk Acknowledgment Form been completed?', 'reference': 'For girls and young women who are presecribed sodium valproate, it is recommended that Has an annual Valproate - Annual Risk Acknowledgment Form is completed.'}, null=True),
        ),
        migrations.AlterField(
            model_name='antiepilepsymedicine',
            name='is_a_pregnancy_prevention_programme_in_place',
            field=models.BooleanField(blank=True, default=None, help_text={'label': 'Is the Valproate Pregnancy Prevention Programme in place?', 'reference': 'For girls and young women who are presecribed sodium valproate, it is recommended that pregnancy prevention is actively discussed and documented.'}, null=True),
        ),
    ]
