# Generated by Django 5.0.3 on 2024-09-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0032_organisationalauditsubmissionperiod_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S02TFC223",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Not applicable"),
                    (2, "Yes"),
                    (3, "No, not at all"),
                    (4, "No, in development"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05TypicalTimeToAchieveSpecialistAdvice",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Same working day"),
                    (2, "By next working day"),
                    (3, "Within 3-4 working days"),
                    (4, "Within a working week"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05WhoProvidesSpecialistAdvice",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "ESN"),
                    (2, "Consultant Paediatrician with expertise in epilepsy"),
                    (3, "Paediatric neurologist"),
                    (4, "Trainee paediatric neurologist"),
                    (5, "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06IsThisUsually",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "A single joint appointment"),
                    (2, "A series of several joint appointments"),
                    (
                        3,
                        "A flexible appraoch including mixture of joint or individual reviews",
                    ),
                    (4, "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06ProfessionalsRoutinelyInvolvedInTransitionAdultESN",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Adult ESN"),
                    (2, "Adult Learning difficulty ESN"),
                    (3, "Adult Neurologist"),
                    (4, "Youth Worker"),
                    (5, "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07DoesThisCompromise",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (
                        1,
                        "Epilepsy Clinics where mental health professionals can provide direct co-located clinical care",
                    ),
                    (
                        2,
                        "MDT meetings where epilepsy and mental health professionals discuss individual patients",
                    ),
                    (3, "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07MentalHealthAgreedPathway",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Anxiety"),
                    (2, "Depression"),
                    (3, "Mood Disorders"),
                    (4, "Non-epileptic attack disorders"),
                    (5, "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07MentalHealthQuestionnaire",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "BDI - Beck Depression Inventory"),
                    (2, "Connor's Questionnaire"),
                    (3, "Emotional Thermometers Tool"),
                    (4, "GAD - Generalised Anxiety Disorder"),
                    (5, "GAD 2 - Generalised Anxiety Disorder 2"),
                    (6, "GAD 7 - Generalised Anxiety Disorder 7"),
                    (7, "HADS - Hospital Anxiety and Depression Scale"),
                    (
                        8,
                        "MFQ - Mood and Feelings Questionnaire (Child, Parent, Adult versions)",
                    ),
                    (
                        9,
                        "NDDI-E Neurological Disorders Depression Inventory for Epilepsy",
                    ),
                    (10, "PHQ - Patient Health Questionnaire, PHQ 2, PHQ 9"),
                    (11, "SDQ (Strengths and Difficulties Questionnaire)"),
                    (12, "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07TrustAchieve",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Clinical psychology assessment"),
                    (2, "Educational psychology assessment"),
                    (3, "Formal developmental assessment"),
                    (4, "Neurospsychology assessment"),
                    (5, "Psychiatric assessment"),
                    (6, "Cannot achieve any of the above"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S08AgreedReferralCriteriaChildrenNeurodevelopmental",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "ADHD"),
                    (2, "ASD"),
                    (3, "Behavioural difficulties"),
                    (4, "Developmental Coordination Disorder"),
                    (5, "Intellectual disability/Global developmental delay"),
                    (6, "Learning disabilities"),
                    (8, "None of the above"),
                    (7, "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S10TrustMaintainADatabaseOfChildrenWithEpilepsy",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Yes, for all children"),
                    (2, "Yes, for some children"),
                    (3, "No"),
                ],
                null=True,
            ),
        ),
    ]
