# Generated by Django 5.1 on 2024-09-25 12:38

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0032_organisationalauditsubmissionperiod_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S01ESNFunctions",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    (1, "ED visits"),
                    (2, "Home visits"),
                    (3, "School Individual Healthcare Plan (IHP) facilitation"),
                    (4, "Nurse led clinics"),
                    (5, "Nurse prescribing"),
                    (6, "Rescue medication training for parents"),
                    (7, "Rescue medication training for schools"),
                    (8, "School meetings"),
                    (9, "Ward visits"),
                    (10, "None of the above"),
                ],
                help_text={
                    "label": "Which of the following Paediatric ESN functions is the epilepsy service currently able to support?",
                    "parent_question_number": "1.4",
                    "question_number": "1.4i",
                },
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S01EpilepsyClinicalLead",
            field=models.BooleanField(
                blank=True,
                help_text={
                    "label": "Does the Health Board/Trust have a defined paediatric epilepsy clinical lead?",
                    "question_number": "1.3",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S01EpilepsyClinicalLeadFirstName",
            field=models.CharField(
                blank=True,
                help_text={"label": "First name", "parent_question_number": "1.3"},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S01EpilepsyClinicalLeadSurname",
            field=models.CharField(
                blank=True,
                help_text={"label": "Surname", "parent_question_number": "1.3"},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S01EpilepsyClinicalLeadTitle",
            field=models.CharField(
                blank=True,
                help_text={"label": "Title", "parent_question_number": "1.3"},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S01JobPlannedHoursPerWeekLeadershipQIActivities",
            field=models.PositiveIntegerField(
                blank=True,
                help_text={
                    "label": "How many job planned hours are there per week (ESN and/or paediatrician) specified for epilepsy leadership and/or QI activities?",
                    "question_number": "1.5",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S01WTEConsultants",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text={
                    "label": "How many whole time equivalent (WTE) general paediatric consultants (community or hospital based) are there employed within the Health Board/Trust? (Including general paediatric consultants with 'expertise in epilepsy')",
                    "question_number": "1.1",
                    "reference": "Audit Unit - The audit unit is defined by your audit unit profile. Most audit units will include one or more secondary tier paediatric services grouped together using pragmatic boundaries agreed by the paediatric audit unit lead, the project team and the tertiary link. WTE = whole time equivalent. E.g One full time post is 1 WTE; Someone working 3 days a week = 0.6 WTE. 2 people both working 3 days a week = 1.2 WTE",
                },
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S01WTEConsultantsEpilepsy",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text={
                    "label": "Of these, how many whole time equivalent (WTE) general paediatric consultants with ‘expertise in epilepsy’ are there employed within the Health Board/Trust ? (Paediatric neurologists should not be included in your response.)",
                    "question_number": "1.2",
                    "reference": "Paediatrician with expertise -Paediatric consultant (or associate specialist) defined by themselves, their employer and tertiary service/network as having: training and continuing education in epilepsies AND peer review of practice AND regular audit of diagnosis (e.g. participation in Epilepsy12).",
                },
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S01WTEEpilepsySpecialistNurses",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text={
                    "label": "How many whole time equivalent (WTE) paediatric epilepsy specialist nurses (ESNs) are there employed within the Health Board/Trust?",
                    "question_number": "1.4",
                    "reference": "Paediatric ESN - A children’s nurse with a defined role and specific qualification and/or training in children’s epilepsies",
                },
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S02Consultant20Mins",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S02DefinedEpilepsyClinics",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S02EpilepsyClinicsPerWeek",
            field=models.DecimalField(
                blank=True, decimal_places=3, help_text=None, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S03PaedNeurologistsDirectReferrals",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S03PathwaysTertiaryPaedNeurology",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S03SatellitePaediatricNeurologyClinics",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S03WTEPaediatricNeurologists",
            field=models.DecimalField(
                blank=True, decimal_places=3, help_text=None, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S05AdviceAvailable52WeeksPerYear",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S05AdviceAvailableAllOutOfHours",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S05AdviceAvailableAllWeekdays",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S05ContactEpilepsyServiceForSpecialistAdvice",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S05WhoProvidesSpecialistAdviceOther",
            field=models.CharField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S05evidenceclearpointofcontact",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S06AgreeedReferralPathwaysAdultServices",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S06IsThisUsuallyOther",
            field=models.CharField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S06OutpatientClinicYoungPeopleEpilepsies",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S06ProfessionalsRoutinelyInvolvedInTransitionAdultESNOther",
            field=models.CharField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S06ServiceForEpilepsyBopthAdultAndPaed",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S06StructuredResourcesToSupportTransition",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S06WhatAgeDoesThisClinicAcceptYoungPeople",
            field=models.PositiveIntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S07CurrentTrustActionPlanCoLocatedMentalHealth",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S07DoesThisCompromiseOther",
            field=models.CharField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S07MentalHealthAgreedPathwayOther",
            field=models.CharField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S07MentalHealthProvisionEpilepsyClinics",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S07MentalHealthQuestionnaireOther",
            field=models.CharField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S07ScreenForIssuesMentalHealth",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S08AgreedReferralCriteriaChildrenNeurodevelopmentalOther",
            field=models.CharField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S08ScreenForNeurodevelopmentalConditions",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S09ComprehensiveCarePlanningChildrenEpilepsy",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01ESNFunctions",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    (1, "ED visits"),
                    (2, "Home visits"),
                    (3, "School Individual Healthcare Plan (IHP) facilitation"),
                    (4, "Nurse led clinics"),
                    (5, "Nurse prescribing"),
                    (6, "Rescue medication training for parents"),
                    (7, "Rescue medication training for schools"),
                    (8, "School meetings"),
                    (9, "Ward visits"),
                    (10, "None of the above"),
                ],
                help_text={
                    "label": "Which of the following Paediatric ESN functions is the epilepsy service currently able to support?",
                    "parent_question_number": "1.4",
                    "question_number": "1.4i",
                },
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01EpilepsyClinicalLead",
            field=models.BooleanField(
                blank=True,
                help_text={
                    "label": "Does the Health Board/Trust have a defined paediatric epilepsy clinical lead?",
                    "question_number": "1.3",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01EpilepsyClinicalLeadFirstName",
            field=models.CharField(
                blank=True,
                help_text={"label": "First name", "parent_question_number": "1.3"},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01EpilepsyClinicalLeadSurname",
            field=models.CharField(
                blank=True,
                help_text={"label": "Surname", "parent_question_number": "1.3"},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01EpilepsyClinicalLeadTitle",
            field=models.CharField(
                blank=True,
                help_text={"label": "Title", "parent_question_number": "1.3"},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01JobPlannedHoursPerWeekLeadershipQIActivities",
            field=models.PositiveIntegerField(
                blank=True,
                help_text={
                    "label": "How many job planned hours are there per week (ESN and/or paediatrician) specified for epilepsy leadership and/or QI activities?",
                    "question_number": "1.5",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01WTEConsultants",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text={
                    "label": "How many whole time equivalent (WTE) general paediatric consultants (community or hospital based) are there employed within the Health Board/Trust? (Including general paediatric consultants with 'expertise in epilepsy')",
                    "question_number": "1.1",
                    "reference": "Audit Unit - The audit unit is defined by your audit unit profile. Most audit units will include one or more secondary tier paediatric services grouped together using pragmatic boundaries agreed by the paediatric audit unit lead, the project team and the tertiary link. WTE = whole time equivalent. E.g One full time post is 1 WTE; Someone working 3 days a week = 0.6 WTE. 2 people both working 3 days a week = 1.2 WTE",
                },
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01WTEConsultantsEpilepsy",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text={
                    "label": "Of these, how many whole time equivalent (WTE) general paediatric consultants with ‘expertise in epilepsy’ are there employed within the Health Board/Trust ? (Paediatric neurologists should not be included in your response.)",
                    "question_number": "1.2",
                    "reference": "Paediatrician with expertise -Paediatric consultant (or associate specialist) defined by themselves, their employer and tertiary service/network as having: training and continuing education in epilepsies AND peer review of practice AND regular audit of diagnosis (e.g. participation in Epilepsy12).",
                },
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01WTEEpilepsySpecialistNurses",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text={
                    "label": "How many whole time equivalent (WTE) paediatric epilepsy specialist nurses (ESNs) are there employed within the Health Board/Trust?",
                    "question_number": "1.4",
                    "reference": "Paediatric ESN - A children’s nurse with a defined role and specific qualification and/or training in children’s epilepsies",
                },
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S02Consultant20Mins",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S02DefinedEpilepsyClinics",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S02EpilepsyClinicsPerWeek",
            field=models.DecimalField(
                blank=True, decimal_places=3, help_text=None, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03PaedNeurologistsDirectReferrals",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03PathwaysTertiaryPaedNeurology",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03SatellitePaediatricNeurologyClinics",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03WTEPaediatricNeurologists",
            field=models.DecimalField(
                blank=True, decimal_places=3, help_text=None, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05AdviceAvailable52WeeksPerYear",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05AdviceAvailableAllOutOfHours",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05AdviceAvailableAllWeekdays",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05ContactEpilepsyServiceForSpecialistAdvice",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05WhoProvidesSpecialistAdviceOther",
            field=models.CharField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05evidenceclearpointofcontact",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06AgreeedReferralPathwaysAdultServices",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06IsThisUsuallyOther",
            field=models.CharField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06OutpatientClinicYoungPeopleEpilepsies",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06ProfessionalsRoutinelyInvolvedInTransitionAdultESNOther",
            field=models.CharField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06ServiceForEpilepsyBopthAdultAndPaed",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06StructuredResourcesToSupportTransition",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06WhatAgeDoesThisClinicAcceptYoungPeople",
            field=models.PositiveIntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07CurrentTrustActionPlanCoLocatedMentalHealth",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07DoesThisCompromiseOther",
            field=models.CharField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07MentalHealthAgreedPathwayOther",
            field=models.CharField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07MentalHealthProvisionEpilepsyClinics",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07MentalHealthQuestionnaireOther",
            field=models.CharField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07ScreenForIssuesMentalHealth",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S08AgreedReferralCriteriaChildrenNeurodevelopmentalOther",
            field=models.CharField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S08ScreenForNeurodevelopmentalConditions",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S09ComprehensiveCarePlanningChildrenEpilepsy",
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
    ]
