# Generated by Django 4.0.4 on 2022-08-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0032_alter_management_individualised_care_plan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='ct_head_scan_status',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Has a CT head been performed?'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='eeg_indicated',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Is an EEG indicated?'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='eeg_performed_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date EEG performed'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='eeg_request_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date EEG requested'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='mri_brain_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='MRI brain date'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='mri_indicated',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Is an MRI brain indicated?'),
        ),
    ]
