# Generated by Django 5.0.3 on 2024-09-24 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0032_organisationalauditsubmission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationalauditsubmissionperiod",
            name="submissions",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="epilepsy12.organisationalauditsubmission",
            ),
        ),
    ]
