# Generated by Django 4.2.4 on 2023-08-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0032_alter_countrykpiaggregation_cohort_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nationalkpiaggregation",
            name="cohort",
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
