# Generated by Django 4.1.2 on 2022-11-30 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0032_antiepilepsymedicine_has_a_valproate_annual_risk_acknowledgement_form_been_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='nonepileptic_seizure_type',
            field=models.CharField(blank=True, choices=[('BPP', 'Behavioral Psychological And Psychiatric Disorders'), ('MAD', 'Migraine Associated Disorders'), ('ME', 'Miscellaneous Events'), ('SRC', 'Sleep Related Conditions'), ('SAS', 'Syncope And Anoxic Seizures'), ('PMD', 'Paroxysmal Movement Disorders'), ('Oth', 'Other')], default=None, help_text={'label': 'How best describes the generalised nature of the nonepileptic episode(s)?', 'reference': 'How best describes the generalised nature of the nonepileptic episode(s)?'}, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='nonepileptic_seizure_unknown_onset',
            field=models.CharField(blank=True, choices=[('BAr', 'Behaviour arrest'), ('EpS', 'Epileptic spasms'), ('TCl', 'Tonic-clonic'), ('Oth', 'Other')], default=None, help_text={'label': 'How best describes the generalised nature of the nonepileptic episode(s)?', 'reference': 'How best describes the generalised nature of the nonepileptic episode(s)?'}, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='multiaxialdiagnosis',
            name='mental_health_issue',
            field=models.CharField(blank=True, choices=[('AxD', 'Anxiety disorder'), ('EmB', 'Emotional/ behavioural'), ('MoD', 'Mood disorder'), ('SHm', 'Self harm'), ('Oth', 'Other')], default=None, help_text={'label': 'Add details of any known mental health problem(s)', 'reference': 'Add details of any known mental health problem(s)'}, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='multiaxialdiagnosis',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multiaxialdescription', to='epilepsy12.registration'),
        ),
    ]
