# Generated by Django 5.1 on 2024-10-08 13:49

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0033_alter_kpi_school_individual_healthcare_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S01EpilepsyClinicalLead",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S02Consultant20Mins",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S02DefinedEpilepsyClinics",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S02TFC223",
            field=models.TextField(
                blank=True,
                choices=[
                    ("NA", "Not applicable"),
                    ("Y", "Yes"),
                    ("N", "No, not at all"),
                    ("NID", "No, in development"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S03CommenceKetogenicDiet",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S03PaedNeurologistsDirectReferrals",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S03PathwaysTertiaryPaedNeurology",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S03ReviewKetogenicDiet",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S03SatellitePaediatricNeurologyClinics",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S03VNSInsertion",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S03VNSReview",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S042448HAmbulatoryEeg",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04AwakeMRI",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04HomeVideoTelemetry",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04InpatientVideoTelemetry",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04LeadECG",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04MelatoninInducedEeg",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04MriWithGeneralAnaesthetic",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04MriWithSedation",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04OutpatientVideoTelemetry",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04PortableEEGOnWardAreaWithinTrust",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04SedatedEeg",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04SleepDeprivedEeg",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04StandardEeg",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04WholeGenomeSequencing",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S05AdviceAvailable52WeeksPerYear",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S05AdviceAvailableAllOutOfHours",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S05AdviceAvailableAllWeekdays",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S05ContactEpilepsyServiceForSpecialistAdvice",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S05TypicalTimeToAchieveSpecialistAdvice",
            field=models.TextField(
                blank=True,
                choices=[
                    (1, "Same working day"),
                    (2, "By next working day"),
                    (3, "Within 3-4 working days"),
                    (4, "Within a working week"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S05WhoProvidesSpecialistAdvice",
            field=models.TextField(
                blank=True,
                choices=[
                    (1, "ESN"),
                    (2, "Consultant Paediatrician with expertise in epilepsy"),
                    (3, "Paediatric neurologist"),
                    (4, "Trainee paediatric neurologist"),
                    (5, "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S05evidenceclearpointofcontact",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S06AgreedReferralPathwaysAdultServices",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S06IsThisUsually",
            field=models.TextField(
                blank=True,
                choices=[
                    ("SJA", "A single joint appointment"),
                    ("SSA", "A series of several joint appointments"),
                    (
                        "FAM",
                        "A flexible approach including mixture of joint or individual reviews",
                    ),
                    ("Oth", "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S06OutpatientClinicYoungPeopleEpilepsies",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S06ServiceForEpilepsyBothAdultAndPaed",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S06StructuredResourcesToSupportTransition",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S07CurrentTrustActionPlanCoLocatedMentalHealth",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S07DoesThisComprise",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    (
                        1,
                        "Epilepsy Clinics where mental health professionals can provide direct co-located clinical care",
                    ),
                    (
                        2,
                        "MDT meetings where epilepsy and mental health professionals discuss individual patients",
                    ),
                    (3, "Other"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S07MentalHealthProvisionEpilepsyClinics",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S07ScreenForIssuesMentalHealth",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S08ScreenForNeurodevelopmentalConditions",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S09ComprehensiveCarePlanningChildrenEpilepsy",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S10TrustMaintainADatabaseOfChildrenWithEpilepsy",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Y", "Yes, for all children"),
                    ("YS", "Yes, for some children"),
                    ("N", "No"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01EpilepsyClinicalLead",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S02Consultant20Mins",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S02DefinedEpilepsyClinics",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S02TFC223",
            field=models.TextField(
                blank=True,
                choices=[
                    ("NA", "Not applicable"),
                    ("Y", "Yes"),
                    ("N", "No, not at all"),
                    ("NID", "No, in development"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03CommenceKetogenicDiet",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03PaedNeurologistsDirectReferrals",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03PathwaysTertiaryPaedNeurology",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03ReviewKetogenicDiet",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03SatellitePaediatricNeurologyClinics",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03VNSInsertion",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03VNSReview",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S042448HAmbulatoryEeg",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04AwakeMRI",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04HomeVideoTelemetry",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04InpatientVideoTelemetry",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04LeadECG",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04MelatoninInducedEeg",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04MriWithGeneralAnaesthetic",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04MriWithSedation",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04OutpatientVideoTelemetry",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04PortableEEGOnWardAreaWithinTrust",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04SedatedEeg",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04SleepDeprivedEeg",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04StandardEeg",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04WholeGenomeSequencing",
            field=models.TextField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05AdviceAvailable52WeeksPerYear",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05AdviceAvailableAllOutOfHours",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05AdviceAvailableAllWeekdays",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05ContactEpilepsyServiceForSpecialistAdvice",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05TypicalTimeToAchieveSpecialistAdvice",
            field=models.TextField(
                blank=True,
                choices=[
                    (1, "Same working day"),
                    (2, "By next working day"),
                    (3, "Within 3-4 working days"),
                    (4, "Within a working week"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05WhoProvidesSpecialistAdvice",
            field=models.TextField(
                blank=True,
                choices=[
                    (1, "ESN"),
                    (2, "Consultant Paediatrician with expertise in epilepsy"),
                    (3, "Paediatric neurologist"),
                    (4, "Trainee paediatric neurologist"),
                    (5, "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05evidenceclearpointofcontact",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06AgreedReferralPathwaysAdultServices",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06IsThisUsually",
            field=models.TextField(
                blank=True,
                choices=[
                    ("SJA", "A single joint appointment"),
                    ("SSA", "A series of several joint appointments"),
                    (
                        "FAM",
                        "A flexible approach including mixture of joint or individual reviews",
                    ),
                    ("Oth", "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06OutpatientClinicYoungPeopleEpilepsies",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06ServiceForEpilepsyBothAdultAndPaed",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06StructuredResourcesToSupportTransition",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07CurrentTrustActionPlanCoLocatedMentalHealth",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07DoesThisComprise",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    (
                        1,
                        "Epilepsy Clinics where mental health professionals can provide direct co-located clinical care",
                    ),
                    (
                        2,
                        "MDT meetings where epilepsy and mental health professionals discuss individual patients",
                    ),
                    (3, "Other"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07MentalHealthProvisionEpilepsyClinics",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07ScreenForIssuesMentalHealth",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S08ScreenForNeurodevelopmentalConditions",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S09ComprehensiveCarePlanningChildrenEpilepsy",
            field=models.TextField(
                blank=True, choices=[("Y", "Yes"), ("N", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S10TrustMaintainADatabaseOfChildrenWithEpilepsy",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Y", "Yes, for all children"),
                    ("YS", "Yes, for some children"),
                    ("N", "No"),
                ],
                null=True,
            ),
        ),
    ]
