# Generated by Django 4.2.4 on 2023-08-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0033_alter_nationalkpiaggregation_cohort"),
    ]

    operations = [
        migrations.AddField(
            model_name="countrykpiaggregation",
            name="abstraction_name",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="icbkpiaggregation",
            name="abstraction_name",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="nationalkpiaggregation",
            name="abstraction_name",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="nhsregionkpiaggregation",
            name="abstraction_name",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="openukkpiaggregation",
            name="abstraction_name",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="organisationkpiaggregation",
            name="abstraction_name",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trustkpiaggregation",
            name="abstraction_name",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
