# Generated by Django 5.0.3 on 2024-09-24 11:23

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0033_alter_organisationalauditsubmissionperiod_submissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01ESNFunctions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(
                    choices=[
                        (1, "ED visits"),
                        (2, "Home visits"),
                        (3, "School Individual Healthcare Plan (IHP) facilitation"),
                        (4, "Nurse led clinics"),
                        (5, "Nurse prescribing"),
                        (6, "Rescue medication training for parents"),
                        (7, "Rescue medication training for schools"),
                        (8, "School meetings"),
                        (9, "Ward visits"),
                        (10, "None of the above"),
                    ]
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01EpilepsyClinicalLead",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01EpilepsyClinicalLeadFirstName",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01EpilepsyClinicalLeadSurname",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01EpilepsyClinicalLeadTitle",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01JobPlannedHoursPerWeekLeadershipQIActivities",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01WTEConsultants",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01WTEConsultantsEpilepsy",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01WTEEpilepsySpecialistNurses",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S02Consultant20Mins",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S02DefinedEpilepsyClinics",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S02EpilepsyClinicsPerWeek",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S02TFC223",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name={
                    1: "Not applicable",
                    2: "Yes",
                    3: "No, not at all",
                    4: "No, in development",
                },
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03CommenceKetogenicDiet",
            field=models.PositiveIntegerField(
                blank=True, choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03PaedNeurologistsDirectReferrals",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03PathwaysTertiaryPaedNeurology",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03ReviewKetogenicDiet",
            field=models.PositiveIntegerField(
                blank=True, choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03SatellitePaediatricNeurologyClinics",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03VNSInsertion",
            field=models.PositiveIntegerField(
                blank=True, choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03VNSReview",
            field=models.PositiveIntegerField(
                blank=True, choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03WTEPaediatricNeurologists",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S042448HAmbulatoryEeg",
            field=models.PositiveIntegerField(
                blank=True, choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04AwakeMRI",
            field=models.PositiveIntegerField(
                blank=True, choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04HomeVideoTelemetry",
            field=models.PositiveIntegerField(
                blank=True, choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04InpatientVideoTelemetry",
            field=models.PositiveIntegerField(
                blank=True, choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04LeadECG",
            field=models.PositiveIntegerField(
                blank=True, choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04MelatoninInducedEeg",
            field=models.PositiveIntegerField(
                blank=True, choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04MriWithGeneralAnaesthetic",
            field=models.PositiveIntegerField(
                blank=True, choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04MriWithSedation",
            field=models.PositiveIntegerField(
                blank=True, choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04OutpatientVideoTelemetry",
            field=models.PositiveIntegerField(
                blank=True, choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04PortableEEGOnWardAreaWithinTrust",
            field=models.PositiveIntegerField(
                blank=True, choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04SedatedEeg",
            field=models.PositiveIntegerField(
                blank=True, choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04SleepDeprivedEeg",
            field=models.PositiveIntegerField(
                blank=True, choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04StandardEeg",
            field=models.PositiveIntegerField(
                blank=True, choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05AdviceAvailable52WeeksPerYear",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05AdviceAvailableAllOutOfHours",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05AdviceAvailableAllWeekdays",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05ContactEpilepsyServiceForSpecialistAdvice",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05TypicalTimeToAchieveSpecialistAdvice",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name={
                    1: "Same working day",
                    2: "By next working day",
                    3: "Within 3-4 working days",
                    4: "Within a working week",
                },
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05WhoProvidesSpecialistAdvice",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name={
                    1: "ESN",
                    2: "Consultant Paediatrician with expertise in epilepsy",
                    3: "Paediatric neurologist",
                    4: "Trainee paediatric neurologist",
                    5: "Other",
                },
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05WhoProvidesSpecialistAdviceOther",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05evidenceclearpointofcontact",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06AgreeedReferralPathwaysAdultServices",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06IsThisUsually",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name={
                    1: "A single joint appointment",
                    2: "A series of several joint appointments",
                    3: "A flexible appraoch including mixture of joint or individual reviews",
                    4: "Other",
                },
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06IsThisUsuallyOther",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06OutpatientClinicYoungPeopleEpilepsies",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06PercentageOfYoungPeopleTransferred",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06ProfessionalsRoutinelyInvolvedInTransitionAdultESN",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name={
                    1: "Adult ESN",
                    2: "Adult Learning difficulty ESN",
                    3: "Adult Neurologist",
                    4: "Youth Worker",
                    5: "Other",
                },
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06ProfessionalsRoutinelyInvolvedInTransitionAdultESNOther",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06ServiceForEpilepsyBopthAdultAndPaed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06StructuredResourcesToSupportTransition",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06WhatAgeDoesThisClinicAcceptYoungPeople",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07CurrentTrustActionPlanCoLocatedMentalHealth",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07DoesThisCompromise",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name={
                    1: "Epilepsy Clinics where mental health professionals can provide direct co-located clinical care",
                    2: "MDT meetings where epilepsy and mental health professionals discuss individual patients",
                    3: "Other",
                },
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07DoesThisCompromiseOther",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07MentalHealthAgreedPathway",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name={
                    1: "Anxiety",
                    2: "Depression",
                    3: "Mood Disorders",
                    4: "Non-epileptic attack disorders",
                    5: "Other",
                },
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07MentalHealthAgreedPathwayOther",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07MentalHealthProvisionEpilepsyClinics",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07MentalHealthQuestionnaire",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name={
                    1: "BDI - Beck Depression Inventory",
                    2: "Connor's Questionnaire",
                    3: "Emotional Thermometers Tool",
                    4: "GAD - Generalised Anxiety Disorder",
                    5: "GAD 2 - Generalised Anxiety Disorder 2",
                    6: "GAD 7 - Generalised Anxiety Disorder 7",
                    7: "HADS - Hospital Anxiety and Depression Scale",
                    8: "MFQ - Mood and Feelings Questionnaire (Child, Parent, Adult versions)",
                    9: "NDDI-E Neurological Disorders Depression Inventory for Epilepsy",
                    10: "PHQ - Patient Health Questionnaire, PHQ 2, PHQ 9",
                    11: "SDQ (Strengths and Difficulties Questionnaire)",
                    12: "Other",
                },
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07MentalHealthQuestionnaireOther",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07ScreenForIssuesMentalHealth",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07TrustAchieve",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name={
                    1: "Clinical psychology assessment",
                    2: "Educational psychology assessment",
                    3: "Formal developmental assessment",
                    4: "Neurospsychology assessment",
                    5: "Psychiatric assessment",
                    6: "Cannot achieve any of the above",
                },
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S08AgreedReferralCriteriaChildrenNeurodevelopmental",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name={
                    1: "ADHD",
                    2: "ASD",
                    3: "Behavioural difficulties",
                    4: "Developmental Coordination Disorder",
                    5: "Intellectual disability/Global developmental delay",
                    6: "Learning disabilities",
                    7: "Other",
                    8: "None of the above",
                },
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S08AgreedReferralCriteriaChildrenNeurodevelopmentalOther",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S08ScreenForNeurodevelopmentalConditions",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S09ComprehensiveCarePlanningChildrenEpilepsy",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S10TrustMaintainADatabaseOfChildrenWithEpilepsy",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name={
                    1: "Yes, for all children",
                    2: "Yes, for some children",
                    3: "No",
                },
            ),
        ),
    ]
