# Generated by Django 4.1.2 on 2022-11-30 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0033_alter_episode_nonepileptic_seizure_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiaxialdiagnosis',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multiaxialdiagnosis', to='epilepsy12.registration'),
        ),
    ]
