# Generated by Django 5.1 on 2024-09-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "epilepsy12",
            "0033_alter_historicalorganisationalauditsubmission_s01esnfunctions_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorganisationalauditsubmission",
            name="S04WholeGenomeSequencing",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Requesting and consenting of Whole Genome Sequencing (WGS)",
                    "parent_question_number": "4",
                    "question_number": "4.1xiv",
                },
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organisationalauditsubmission",
            name="S04WholeGenomeSequencing",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Requesting and consenting of Whole Genome Sequencing (WGS)",
                    "parent_question_number": "4",
                    "question_number": "4.1xiv",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S01EpilepsyClinicalLead",
            field=models.BooleanField(
                blank=True,
                help_text={
                    "label": "Do you have a defined paediatric epilepsy clinical lead?",
                    "question_number": "1.3",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S01WTEConsultants",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text={
                    "label": "How many whole time equivalent general paediatric consultants do you employ?",
                    "question_number": "1.1",
                    "reference": "\n            <p>\n                Includes general paediatric consultants with 'expertise in epilepsy' (community or hospital based).\n            </p>\n            <p>\n                Audit Unit - The audit unit is defined by your audit unit profile. Most audit units will include one or more secondary tier paediatric services\n                grouped together using pragmatic boundaries agreed by the paediatric audit unit lead, the project team and the tertiary link.\n            </p>\n            <p>\n                WTE = whole time equivalent. E.g One full time post is 1 WTE; Someone working 3 days a week = 0.6 WTE. 2 people both working 3 days a week = 1.2 WTE\n            </p>\n        ",
                },
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S01WTEConsultantsEpilepsy",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text={
                    "label": "Of these, how many have an ‘expertise in epilepsy’?",
                    "question_number": "1.2",
                    "reference": "\n            <p>\n                Answer using whole time equivalent again. Paediatric neurologists should not be included in your response.\n            </p>\n            <p>\n                Paediatrician with expertise - Paediatric consultant (or associate specialist) defined by themselves, their employer and tertiary service/network as having: training and continuing education in epilepsies AND peer review of practice AND regular audit of diagnosis (e.g. participation in Epilepsy12).\n            </p>\n        ",
                },
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S01WTEEpilepsySpecialistNurses",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text={
                    "label": "How many WTE paediatric epilepsy specialist nurses do you employ?",
                    "question_number": "1.4",
                    "reference": "Paediatric ESN - A children’s nurse with a defined role and specific qualification and/or training in children’s epilepsies",
                },
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S02Consultant20Mins",
            field=models.BooleanField(
                blank=True,
                help_text={
                    "label": "Within the epilepsy clinics, does the clinic booking time allow at least 20 minutes of time with a consultant with expertise in epilepsy and an ESN? (This might be 20 min with the doctor and nurse at the same time or 20 mins each in succession)",
                    "parent_question_number": "2.1",
                    "question_number": "2.1ii",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S02DefinedEpilepsyClinics",
            field=models.BooleanField(
                blank=True,
                help_text={
                    "label": "Does the Health Board/Trust have defined epilepsy clinics seeing patients at a secondary level?",
                    "question_number": "2.1",
                    "reference": "A secondary level 'epilepsy clinic' is a clinic run just for children with seizures or epilepsy that takes referrals direct from GPs or emergency department (decimal answers are allowed). An ‘Epilepsy Clinic’ is defined as a paediatric clinic where all the children and young people attending have epilepsy or possible epileptic seizures.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S02EpilepsyClinicsPerWeek",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text={
                    "label": "On average, how many consultant (or associate specialist) led secondary level ‘epilepsy clinics’ for children or young people take place within your Health Board/Trust per week?",
                    "parent_question_number": "2.1",
                    "question_number": "2.1i",
                },
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S02TFC223",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Not applicable"),
                    (2, "Yes"),
                    (3, "No, not at all"),
                    (4, "No, in development"),
                ],
                help_text={
                    "label": "Does the Trust currently run TFC 223 Epilepsy Best Practice Criteria (BPC) clinics?",
                    "question_number": "2.2",
                    "reference": "For Trusts in England only",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S03CommenceKetogenicDiet",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Commence ketogenic diet",
                    "parent_question_label": "Which of the following services can be obtained?",
                    "parent_question_number": "3.5",
                    "parent_question_reference": "If the child would have to travel to a location outside your audit unit then answer ‘no‘",
                    "question_number": "3.5i",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S03PaedNeurologistsDirectReferrals",
            field=models.BooleanField(
                blank=True,
                help_text={
                    "label": "Can paediatric neurologists receive direct referrals from general practice or emergency services to assess children with possible epilepsy?",
                    "question_number": "3.3",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S03PathwaysTertiaryPaedNeurology",
            field=models.BooleanField(
                blank=True,
                help_text={
                    "label": "Does you have agreed referral pathways to tertiary paediatric neurology services?",
                    "question_number": "3.2",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S03ReviewKetogenicDiet",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Ongoing dietetic review of ketogenic diet",
                    "parent_question_number": "3.5",
                    "question_number": "3.5ii",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S03SatellitePaediatricNeurologyClinics",
            field=models.BooleanField(
                blank=True,
                help_text={
                    "label": "Do you host satellite paediatric neurology clinics?",
                    "question_number": "3.4",
                    "reference": "\n            <p>\n                e.g. a paediatric neurologist visits a site within the trust to undertake paediatric neurology clinics\n            </p>\n            <p>\n                A satellite clinic is where a neurologist supports a clinic outside their base hospital. This might be another hospital or clinic location in their trust or another hospital or clinic location in another trust. \n            </p>\n        ",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S03VNSInsertion",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Vagal Nerve Stimulator (VNS) Insertion",
                    "parent_question_number": "3.5",
                    "question_number": "3.5iii",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S03VNSReview",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "VNS review",
                    "parent_question_number": "3.5",
                    "question_number": "3.5iv",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S03WTEPaediatricNeurologists",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text={
                    "label": "How many whole-time equivalent (WTE) paediatric neurologists who manage children with epilepsy do you employ?",
                    "question_number": "3.1",
                    "reference": "\n            <p>\n                Acutely and or non-acutely.\n            </p>\n            <p>\n                This should not include visiting neurologists who are primarily employed by another trust \n            </p>\n        ",
                },
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S042448HAmbulatoryEeg",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "24/48h ambulatory EEG",
                    "parent_question_number": "4",
                    "question_number": "4.1ix",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04AwakeMRI",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "'awake' MRI",
                    "parent_question_number": "4",
                    "question_number": "4.1ii",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04HomeVideoTelemetry",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Home video telemetry",
                    "parent_question_number": "4",
                    "question_number": "4.1xii",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04InpatientVideoTelemetry",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Inpatient video telemetry",
                    "parent_question_number": "4",
                    "question_number": "4.1x",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04LeadECG",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "12 lead ECG",
                    "parent_question_label": "Which of the following investigations can be obtained?",
                    "parent_question_number": "4",
                    "parent_question_reference": "If the child would have to travel to a location outside your audit unit then answer ‘no‘",
                    "question_number": "4.1i",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04MelatoninInducedEeg",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Melatonin induced EEG",
                    "parent_question_number": "4",
                    "question_number": "4.1vii",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04MriWithGeneralAnaesthetic",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "MRI with general anaesthetic",
                    "parent_question_number": "4",
                    "question_number": "4.1iv",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04MriWithSedation",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "MRI with sedation",
                    "parent_question_number": "4",
                    "question_number": "4.1iii",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04OutpatientVideoTelemetry",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Outpatient video telemetry",
                    "parent_question_number": "4",
                    "question_number": "4.1xi",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04PortableEEGOnWardAreaWithinTrust",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Portable EEG on ward area within Trust",
                    "parent_question_number": "4",
                    "question_number": "4.1xiii",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04SedatedEeg",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Sedated EEG",
                    "parent_question_number": "4",
                    "question_number": "4.1viii",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04SleepDeprivedEeg",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Sleep deprived EEG",
                    "parent_question_number": "4",
                    "question_number": "4.1vi",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S04StandardEeg",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Standard EEG",
                    "parent_question_number": "4",
                    "question_number": "4.1v",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S05TypicalTimeToAchieveSpecialistAdvice",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Same working day"),
                    (2, "By next working day"),
                    (3, "Within 3-4 working days"),
                    (4, "Within a working week"),
                ],
                help_text=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S05WhoProvidesSpecialistAdvice",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "ESN"),
                    (2, "Consultant Paediatrician with expertise in epilepsy"),
                    (3, "Paediatric neurologist"),
                    (4, "Trainee paediatric neurologist"),
                    (5, "Other"),
                ],
                help_text=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S06IsThisUsually",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "A single joint appointment"),
                    (2, "A series of several joint appointments"),
                    (
                        3,
                        "A flexible appraoch including mixture of joint or individual reviews",
                    ),
                    (4, "Other"),
                ],
                help_text=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S06ProfessionalsRoutinelyInvolvedInTransitionAdultESN",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Adult ESN"),
                    (2, "Adult Learning difficulty ESN"),
                    (3, "Adult Neurologist"),
                    (4, "Youth Worker"),
                    (5, "Other"),
                ],
                help_text=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S07DoesThisCompromise",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (
                        1,
                        "Epilepsy Clinics where mental health professionals can provide direct co-located clinical care",
                    ),
                    (
                        2,
                        "MDT meetings where epilepsy and mental health professionals discuss individual patients",
                    ),
                    (3, "Other"),
                ],
                help_text=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S07MentalHealthAgreedPathway",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Anxiety"),
                    (2, "Depression"),
                    (3, "Mood Disorders"),
                    (4, "Non-epileptic attack disorders"),
                    (5, "Other"),
                ],
                help_text=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S07MentalHealthQuestionnaire",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "BDI - Beck Depression Inventory"),
                    (2, "Connor's Questionnaire"),
                    (3, "Emotional Thermometers Tool"),
                    (4, "GAD - Generalised Anxiety Disorder"),
                    (5, "GAD 2 - Generalised Anxiety Disorder 2"),
                    (6, "GAD 7 - Generalised Anxiety Disorder 7"),
                    (7, "HADS - Hospital Anxiety and Depression Scale"),
                    (
                        8,
                        "MFQ - Mood and Feelings Questionnaire (Child, Parent, Adult versions)",
                    ),
                    (
                        9,
                        "NDDI-E Neurological Disorders Depression Inventory for Epilepsy",
                    ),
                    (10, "PHQ - Patient Health Questionnaire, PHQ 2, PHQ 9"),
                    (11, "SDQ (Strengths and Difficulties Questionnaire)"),
                    (12, "Other"),
                ],
                help_text=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S07TrustAchieve",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Clinical psychology assessment"),
                    (2, "Educational psychology assessment"),
                    (3, "Formal developmental assessment"),
                    (4, "Neurospsychology assessment"),
                    (5, "Psychiatric assessment"),
                    (6, "Cannot achieve any of the above"),
                ],
                help_text=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S08AgreedReferralCriteriaChildrenNeurodevelopmental",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "ADHD"),
                    (2, "ASD"),
                    (3, "Behavioural difficulties"),
                    (4, "Developmental Coordination Disorder"),
                    (5, "Intellectual disability/Global developmental delay"),
                    (6, "Learning disabilities"),
                    (8, "None of the above"),
                    (7, "Other"),
                ],
                help_text=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S10TrustMaintainADatabaseOfChildrenWithEpilepsy",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Yes, for all children"),
                    (2, "Yes, for some children"),
                    (3, "No"),
                ],
                help_text=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01EpilepsyClinicalLead",
            field=models.BooleanField(
                blank=True,
                help_text={
                    "label": "Do you have a defined paediatric epilepsy clinical lead?",
                    "question_number": "1.3",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01WTEConsultants",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text={
                    "label": "How many whole time equivalent general paediatric consultants do you employ?",
                    "question_number": "1.1",
                    "reference": "\n            <p>\n                Includes general paediatric consultants with 'expertise in epilepsy' (community or hospital based).\n            </p>\n            <p>\n                Audit Unit - The audit unit is defined by your audit unit profile. Most audit units will include one or more secondary tier paediatric services\n                grouped together using pragmatic boundaries agreed by the paediatric audit unit lead, the project team and the tertiary link.\n            </p>\n            <p>\n                WTE = whole time equivalent. E.g One full time post is 1 WTE; Someone working 3 days a week = 0.6 WTE. 2 people both working 3 days a week = 1.2 WTE\n            </p>\n        ",
                },
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01WTEConsultantsEpilepsy",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text={
                    "label": "Of these, how many have an ‘expertise in epilepsy’?",
                    "question_number": "1.2",
                    "reference": "\n            <p>\n                Answer using whole time equivalent again. Paediatric neurologists should not be included in your response.\n            </p>\n            <p>\n                Paediatrician with expertise - Paediatric consultant (or associate specialist) defined by themselves, their employer and tertiary service/network as having: training and continuing education in epilepsies AND peer review of practice AND regular audit of diagnosis (e.g. participation in Epilepsy12).\n            </p>\n        ",
                },
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01WTEEpilepsySpecialistNurses",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text={
                    "label": "How many WTE paediatric epilepsy specialist nurses do you employ?",
                    "question_number": "1.4",
                    "reference": "Paediatric ESN - A children’s nurse with a defined role and specific qualification and/or training in children’s epilepsies",
                },
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S02Consultant20Mins",
            field=models.BooleanField(
                blank=True,
                help_text={
                    "label": "Within the epilepsy clinics, does the clinic booking time allow at least 20 minutes of time with a consultant with expertise in epilepsy and an ESN? (This might be 20 min with the doctor and nurse at the same time or 20 mins each in succession)",
                    "parent_question_number": "2.1",
                    "question_number": "2.1ii",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S02DefinedEpilepsyClinics",
            field=models.BooleanField(
                blank=True,
                help_text={
                    "label": "Does the Health Board/Trust have defined epilepsy clinics seeing patients at a secondary level?",
                    "question_number": "2.1",
                    "reference": "A secondary level 'epilepsy clinic' is a clinic run just for children with seizures or epilepsy that takes referrals direct from GPs or emergency department (decimal answers are allowed). An ‘Epilepsy Clinic’ is defined as a paediatric clinic where all the children and young people attending have epilepsy or possible epileptic seizures.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S02EpilepsyClinicsPerWeek",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text={
                    "label": "On average, how many consultant (or associate specialist) led secondary level ‘epilepsy clinics’ for children or young people take place within your Health Board/Trust per week?",
                    "parent_question_number": "2.1",
                    "question_number": "2.1i",
                },
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S02TFC223",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Not applicable"),
                    (2, "Yes"),
                    (3, "No, not at all"),
                    (4, "No, in development"),
                ],
                help_text={
                    "label": "Does the Trust currently run TFC 223 Epilepsy Best Practice Criteria (BPC) clinics?",
                    "question_number": "2.2",
                    "reference": "For Trusts in England only",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03CommenceKetogenicDiet",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Commence ketogenic diet",
                    "parent_question_label": "Which of the following services can be obtained?",
                    "parent_question_number": "3.5",
                    "parent_question_reference": "If the child would have to travel to a location outside your audit unit then answer ‘no‘",
                    "question_number": "3.5i",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03PaedNeurologistsDirectReferrals",
            field=models.BooleanField(
                blank=True,
                help_text={
                    "label": "Can paediatric neurologists receive direct referrals from general practice or emergency services to assess children with possible epilepsy?",
                    "question_number": "3.3",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03PathwaysTertiaryPaedNeurology",
            field=models.BooleanField(
                blank=True,
                help_text={
                    "label": "Does you have agreed referral pathways to tertiary paediatric neurology services?",
                    "question_number": "3.2",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03ReviewKetogenicDiet",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Ongoing dietetic review of ketogenic diet",
                    "parent_question_number": "3.5",
                    "question_number": "3.5ii",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03SatellitePaediatricNeurologyClinics",
            field=models.BooleanField(
                blank=True,
                help_text={
                    "label": "Do you host satellite paediatric neurology clinics?",
                    "question_number": "3.4",
                    "reference": "\n            <p>\n                e.g. a paediatric neurologist visits a site within the trust to undertake paediatric neurology clinics\n            </p>\n            <p>\n                A satellite clinic is where a neurologist supports a clinic outside their base hospital. This might be another hospital or clinic location in their trust or another hospital or clinic location in another trust. \n            </p>\n        ",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03VNSInsertion",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Vagal Nerve Stimulator (VNS) Insertion",
                    "parent_question_number": "3.5",
                    "question_number": "3.5iii",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03VNSReview",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "VNS review",
                    "parent_question_number": "3.5",
                    "question_number": "3.5iv",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S03WTEPaediatricNeurologists",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text={
                    "label": "How many whole-time equivalent (WTE) paediatric neurologists who manage children with epilepsy do you employ?",
                    "question_number": "3.1",
                    "reference": "\n            <p>\n                Acutely and or non-acutely.\n            </p>\n            <p>\n                This should not include visiting neurologists who are primarily employed by another trust \n            </p>\n        ",
                },
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S042448HAmbulatoryEeg",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "24/48h ambulatory EEG",
                    "parent_question_number": "4",
                    "question_number": "4.1ix",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04AwakeMRI",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "'awake' MRI",
                    "parent_question_number": "4",
                    "question_number": "4.1ii",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04HomeVideoTelemetry",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Home video telemetry",
                    "parent_question_number": "4",
                    "question_number": "4.1xii",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04InpatientVideoTelemetry",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Inpatient video telemetry",
                    "parent_question_number": "4",
                    "question_number": "4.1x",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04LeadECG",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "12 lead ECG",
                    "parent_question_label": "Which of the following investigations can be obtained?",
                    "parent_question_number": "4",
                    "parent_question_reference": "If the child would have to travel to a location outside your audit unit then answer ‘no‘",
                    "question_number": "4.1i",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04MelatoninInducedEeg",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Melatonin induced EEG",
                    "parent_question_number": "4",
                    "question_number": "4.1vii",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04MriWithGeneralAnaesthetic",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "MRI with general anaesthetic",
                    "parent_question_number": "4",
                    "question_number": "4.1iv",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04MriWithSedation",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "MRI with sedation",
                    "parent_question_number": "4",
                    "question_number": "4.1iii",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04OutpatientVideoTelemetry",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Outpatient video telemetry",
                    "parent_question_number": "4",
                    "question_number": "4.1xi",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04PortableEEGOnWardAreaWithinTrust",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Portable EEG on ward area within Trust",
                    "parent_question_number": "4",
                    "question_number": "4.1xiii",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04SedatedEeg",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Sedated EEG",
                    "parent_question_number": "4",
                    "question_number": "4.1viii",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04SleepDeprivedEeg",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Sleep deprived EEG",
                    "parent_question_number": "4",
                    "question_number": "4.1vi",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S04StandardEeg",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Uncertain")],
                help_text={
                    "label": "Standard EEG",
                    "parent_question_number": "4",
                    "question_number": "4.1v",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05TypicalTimeToAchieveSpecialistAdvice",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Same working day"),
                    (2, "By next working day"),
                    (3, "Within 3-4 working days"),
                    (4, "Within a working week"),
                ],
                help_text=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05WhoProvidesSpecialistAdvice",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "ESN"),
                    (2, "Consultant Paediatrician with expertise in epilepsy"),
                    (3, "Paediatric neurologist"),
                    (4, "Trainee paediatric neurologist"),
                    (5, "Other"),
                ],
                help_text=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06IsThisUsually",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "A single joint appointment"),
                    (2, "A series of several joint appointments"),
                    (
                        3,
                        "A flexible appraoch including mixture of joint or individual reviews",
                    ),
                    (4, "Other"),
                ],
                help_text=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S06ProfessionalsRoutinelyInvolvedInTransitionAdultESN",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Adult ESN"),
                    (2, "Adult Learning difficulty ESN"),
                    (3, "Adult Neurologist"),
                    (4, "Youth Worker"),
                    (5, "Other"),
                ],
                help_text=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07DoesThisCompromise",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (
                        1,
                        "Epilepsy Clinics where mental health professionals can provide direct co-located clinical care",
                    ),
                    (
                        2,
                        "MDT meetings where epilepsy and mental health professionals discuss individual patients",
                    ),
                    (3, "Other"),
                ],
                help_text=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07MentalHealthAgreedPathway",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Anxiety"),
                    (2, "Depression"),
                    (3, "Mood Disorders"),
                    (4, "Non-epileptic attack disorders"),
                    (5, "Other"),
                ],
                help_text=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07MentalHealthQuestionnaire",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "BDI - Beck Depression Inventory"),
                    (2, "Connor's Questionnaire"),
                    (3, "Emotional Thermometers Tool"),
                    (4, "GAD - Generalised Anxiety Disorder"),
                    (5, "GAD 2 - Generalised Anxiety Disorder 2"),
                    (6, "GAD 7 - Generalised Anxiety Disorder 7"),
                    (7, "HADS - Hospital Anxiety and Depression Scale"),
                    (
                        8,
                        "MFQ - Mood and Feelings Questionnaire (Child, Parent, Adult versions)",
                    ),
                    (
                        9,
                        "NDDI-E Neurological Disorders Depression Inventory for Epilepsy",
                    ),
                    (10, "PHQ - Patient Health Questionnaire, PHQ 2, PHQ 9"),
                    (11, "SDQ (Strengths and Difficulties Questionnaire)"),
                    (12, "Other"),
                ],
                help_text=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S07TrustAchieve",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Clinical psychology assessment"),
                    (2, "Educational psychology assessment"),
                    (3, "Formal developmental assessment"),
                    (4, "Neurospsychology assessment"),
                    (5, "Psychiatric assessment"),
                    (6, "Cannot achieve any of the above"),
                ],
                help_text=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S08AgreedReferralCriteriaChildrenNeurodevelopmental",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "ADHD"),
                    (2, "ASD"),
                    (3, "Behavioural difficulties"),
                    (4, "Developmental Coordination Disorder"),
                    (5, "Intellectual disability/Global developmental delay"),
                    (6, "Learning disabilities"),
                    (8, "None of the above"),
                    (7, "Other"),
                ],
                help_text=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S10TrustMaintainADatabaseOfChildrenWithEpilepsy",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Yes, for all children"),
                    (2, "Yes, for some children"),
                    (3, "No"),
                ],
                help_text=None,
                null=True,
            ),
        ),
    ]
