# Generated by Django 5.1 on 2024-10-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "epilepsy12",
            "0034_rename_s06professionalsroutinelyinvolvedintransitionadultesn_historicalorganisationalauditsubmission",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S05TypicalTimeToAchieveSpecialistAdvice",
            field=models.TextField(
                blank=True,
                choices=[
                    ("1", "Same working day"),
                    ("2", "By next working day"),
                    ("3", "Within 3-4 working days"),
                    ("4", "Within a working week"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S05WhoProvidesSpecialistAdvice",
            field=models.TextField(
                blank=True,
                choices=[
                    ("1", "ESN"),
                    ("2", "Consultant Paediatrician with expertise in epilepsy"),
                    ("3", "Paediatric neurologist"),
                    ("4", "Trainee paediatric neurologist"),
                    ("5", "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05TypicalTimeToAchieveSpecialistAdvice",
            field=models.TextField(
                blank=True,
                choices=[
                    ("1", "Same working day"),
                    ("2", "By next working day"),
                    ("3", "Within 3-4 working days"),
                    ("4", "Within a working week"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S05WhoProvidesSpecialistAdvice",
            field=models.TextField(
                blank=True,
                choices=[
                    ("1", "ESN"),
                    ("2", "Consultant Paediatrician with expertise in epilepsy"),
                    ("3", "Paediatric neurologist"),
                    ("4", "Trainee paediatric neurologist"),
                    ("5", "Other"),
                ],
                null=True,
            ),
        ),
    ]
