# Generated by Django 4.1.2 on 2022-12-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0034_alter_multiaxialdiagnosis_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='audit_submission_date',
            field=models.DateField(default=None, help_text={'label': 'Epilepsy12 submission date', 'reference': 'Date on which the audit submission is due. It is always on the 2nd Tuesday in January.'}, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.DateField(default=None, help_text={'label': 'Date of first paediatric assessment', 'reference': 'Setting this date is an irreversible step. Confirmation will be requested to complete this step.'}, null=True),
        ),
    ]
