# Generated by Django 4.0.4 on 2022-08-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0036_remove_assessment_epilepsy_surgery_centre_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Investigation',
            new_name='Investigations',
        ),
        migrations.DeleteModel(
            name='Investigation_Management',
        ),
    ]
