# Generated by Django 4.1.2 on 2022-12-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0036_alter_registration_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='locked',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="\n        This determines if the case is locked from editing\n        Cases can be locked under either of 2 sets of circumstances\n        1. The child has opted out of the audit \n        - here all data relating to the child's ID is set to None but the ID retained.\n        - in the UI, blank spaces in the case_list are rendered as ######\n        2. All the fields for the child have been completed and the user has indicated the child is ready for submission.\n        - The upload button in the UI is enabled up until the submission deadline to toggle the locked status\n        3. The submission deadline has passed. The case is locked, irrespective of if fields are complete are not.\n        Locked"),
        ),
    ]
