# Generated by Django 4.0.4 on 2022-08-14 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0037_rename_investigation_investigations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='hospital_trust',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hospital_site', to='epilepsy12.hospitaltrust'),
        ),
    ]
