# Generated by Django 5.1 on 2024-10-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "epilepsy12",
            "0037_alter_historicalorganisationalauditsubmission_s01wteconsultants_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorganisationalauditsubmission",
            name="submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organisationalauditsubmission",
            name="submitted",
            field=models.BooleanField(default=False),
        ),
    ]
