# Generated by Django 5.1 on 2024-10-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0038_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
    ]
