# Generated by Django 4.1.2 on 2022-12-22 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0038_auditprogress_assessment_of_mental_health_issues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epilepsycontext',
            name='registration',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='epilepsy12.registration'),
        ),
    ]
