# Generated by Django 5.1 on 2024-10-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0039_banner_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="user_role_to_target",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Lead Clinician"),
                    (2, "Clinician"),
                    (3, "Administrator"),
                    (4, "RCPCH Audit Team"),
                    (7, "RCPCH Audit Children and Family"),
                ],
                null=True,
            ),
        ),
    ]
