# Generated by Django 4.1.2 on 2022-12-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0039_alter_epilepsycontext_registration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'verbose_name': 'Assessment', 'verbose_name_plural': 'Assessment'},
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'permissions': [('can_lock_child_case_data_from_editing', "Can lock a child's record from editing."), ('can_unlock_child_case_data_from_editing', "Can unlock a child's record from editing."), ('can_opt_out_child_from_inclusion_in_audit', "Can sanction an opt out from participating in the audit. Note all the child's date except Epilepsy12 unique identifier are irretrievably deleted."), ('can_consent_to_audit_participation', 'Can consent to participating in Epilepsy12.')], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'permissions': [('can_approve_eligibility', 'Can approve eligibility for Epilepsy12.'), ('can_remove_approval_of_eligibility', 'Can remove approval of eligibiltiy for Epilepsy12.'), ('can_register_child_in_epilepsy12', 'Can register child in Epilepsy12. (A cohort number is automatically allocaeted)'), ('can_unregister_child_in_epilepsy12', 'Can unregister a child in Epilepsy. Their record and previously entered data is untouched.'), ('can_change_epilepsy12_lead_centre', 'Can change Epilepsy12 lead centre.'), ('can_delete_epilepsy12_lead_centre', 'Can delete Epilepsy12 lead centre.'), ('can_consent_to_audit_participation', 'Can consent to participating in Epilepsy12.')], 'verbose_name': 'Registration', 'verbose_name_plural': 'Registrations'},
        ),
        migrations.AlterField(
            model_name='assessment',
            name='childrens_epilepsy_surgical_service_referral_criteria_met',
            field=models.BooleanField(blank=True, default=None, help_text={'label': 'Are ANY of these criteria present?', 'reference': "Have ANY of the criteria for referral to a children's epilepsy surgery service been met?"}, null=True),
        ),
    ]
