# Generated by Django 4.1.4 on 2023-01-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0040_alter_assessment_options_alter_case_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epilepsy12user',
            name='username',
        ),
        migrations.AlterField(
            model_name='epilepsy12user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email address is already in use.'}, help_text='Enter your email address.', max_length=254, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='epilepsy12user',
            name='first_name',
            field=models.CharField(blank=True, help_text='Enter your first name', max_length=150, null=True, verbose_name='First name'),
        ),
    ]
