# Generated by Django 4.1.4 on 2023-01-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0041_remove_epilepsy12user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epilepsy12user',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
