# Generated by Django 4.0.4 on 2022-08-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0041_alter_desscribe_epilepsy_or_nonepilepsy_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='experienced_prolonged_focal_seizures',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='prolonged_generalized_convulsive_seizures',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='were_any_of_the_epileptic_seizures_convulsive',
        ),
        migrations.AddField(
            model_name='desscribe',
            name='experienced_prolonged_focal_seizures',
            field=models.BooleanField(default=None, null=True, verbose_name='Were there any prolonged focal seizures?'),
        ),
        migrations.AddField(
            model_name='desscribe',
            name='prolonged_generalized_convulsive_seizures',
            field=models.BooleanField(default=None, null=True, verbose_name='Were there any prolonged generalised epileptic seizures?'),
        ),
        migrations.AddField(
            model_name='desscribe',
            name='were_any_of_the_epileptic_seizures_convulsive',
            field=models.BooleanField(default=None, null=True, verbose_name='Were any of the epileptic seizures convulsive?'),
        ),
    ]
