# Generated by Django 4.1.5 on 2023-01-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0042_epilepsy12user_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='epilepsy12user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
