# Generated by Django 4.1.5 on 2023-01-20 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0043_epilepsy12user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditprogress',
            name='assessment_of_mental_health_issues',
        ),
        migrations.RemoveField(
            model_name='auditprogress',
            name='care_planning_has_been_updated_when_necessary',
        ),
        migrations.RemoveField(
            model_name='auditprogress',
            name='comprehensive_care_planning_agreement',
        ),
        migrations.RemoveField(
            model_name='auditprogress',
            name='comprehensive_care_planning_content',
        ),
        migrations.RemoveField(
            model_name='auditprogress',
            name='ecg',
        ),
        migrations.RemoveField(
            model_name='auditprogress',
            name='epilepsy_specialist_nurse',
        ),
        migrations.RemoveField(
            model_name='auditprogress',
            name='epilepsy_surgery_referral',
        ),
        migrations.RemoveField(
            model_name='auditprogress',
            name='first_aid',
        ),
        migrations.RemoveField(
            model_name='auditprogress',
            name='general_participation_and_risk',
        ),
        migrations.RemoveField(
            model_name='auditprogress',
            name='mental_health_support',
        ),
        migrations.RemoveField(
            model_name='auditprogress',
            name='mri',
        ),
        migrations.RemoveField(
            model_name='auditprogress',
            name='paediatrician_with_expertise_in_epilepsies',
        ),
        migrations.RemoveField(
            model_name='auditprogress',
            name='parental_prolonged_seizures_care_plan',
        ),
        migrations.RemoveField(
            model_name='auditprogress',
            name='patient_carer_parent_agreement_to_the_care_planning',
        ),
        migrations.RemoveField(
            model_name='auditprogress',
            name='patient_held_individualised_epilepsy_document',
        ),
        migrations.RemoveField(
            model_name='auditprogress',
            name='school_individual_healthcare_plan',
        ),
        migrations.RemoveField(
            model_name='auditprogress',
            name='service_contact_details',
        ),
        migrations.RemoveField(
            model_name='auditprogress',
            name='sodium_valproate',
        ),
        migrations.RemoveField(
            model_name='auditprogress',
            name='sudep',
        ),
        migrations.RemoveField(
            model_name='auditprogress',
            name='tertiary_input',
        ),
        migrations.RemoveField(
            model_name='auditprogress',
            name='water_safety',
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paediatrician_with_expertise_in_epilepsies', models.IntegerField(default=0, help_text={'label': 'Paediatrician with expertise in epilepsies', 'reference': 'Percentage of children and young people with epilepsy, with input by a ‘consultant paediatrician with expertise in epilepsies’ within 2 weeks of initial referral'}, null=True)),
                ('epilepsy_specialist_nurse', models.IntegerField(default=0, help_text={'label': 'Epilepsy Specialist Nurse', 'reference': 'Percentage of children and young people with epilepsy, with input by epilepsy specialist nurse within the first year of care.'}, null=True)),
                ('tertiary_input', models.IntegerField(default=0, help_text={'label': 'Tertiary input', 'reference': 'Percentage of children and young people meeting defined criteria for paediatric neurology referral, with input of tertiary care and/or CESS referral within the first year of care.'}, null=True)),
                ('epilepsy_surgery_referral', models.IntegerField(default=0, help_text={'label': 'Epilepsy surgery referral', 'reference': 'Percentage of ongoing children and young people meeting defined epilepsy surgery referral criteria with evidence of epilepsy surgery referral.'}, null=True)),
                ('ecg', models.IntegerField(default=0, help_text={'label': 'ECG', 'reference': 'Percentage of children and young people with convulsive seizures and epilepsy, with an ECG at first year.'}, null=True)),
                ('mri', models.IntegerField(default=0, help_text={'label': 'MRI', 'reference': 'Percentage of children and young people with defined indications for an MRI, who had who had timely MRI within 6 weeks of request'}, null=True)),
                ('assessment_of_mental_health_issues', models.IntegerField(default=0, help_text={'label': 'Assessment of mental health issues', 'reference': 'Percentage of children with epilepsy where there is documented evidence that they have been asked about mental health either through clinical screening, or a questionnaire/measure.'}, null=True)),
                ('mental_health_support', models.IntegerField(default=0, help_text={'label': 'Mental health support', 'reference': 'Percentage of children with epilepsy and a mental health problem who have evidence of mental health support'}, null=True)),
                ('sodium_valproate', models.IntegerField(default=0, help_text={'label': 'Sodium Valproate', 'reference': 'Percentage of all females 12 years and above currently on valproate treatment with annual risk acknowledgement form completed'}, null=True)),
                ('comprehensive_care_planning_agreement', models.IntegerField(default=0, help_text={'label': 'Comprehensive care planning agreement', 'reference': 'Percentage of children and young people with epilepsy after 12 months where there is evidence of a comprehensive care plan that is agreed between the person, their family and/or carers and primary and secondary care providers, and the care plan has been updated where necessary.'}, null=True)),
                ('patient_held_individualised_epilepsy_document', models.IntegerField(default=0, help_text={'label': 'Patient-held individualised epilepsy document/copy of clinic letter that includes care planning information', 'reference': 'Percentage of children and young people with epilepsy after 12 months that had an individualised epilepsy document with individualised epilepsy document or a copy clinic letter that includes care planning information.'}, null=True)),
                ('patient_carer_parent_agreement_to_the_care_planning', models.IntegerField(default=0, help_text={'label': 'Patient/carer/parent agreement to the care planning', 'reference': 'Percentage of children and young people with epilepsy after 12 months where there was evidence of agreement between the person, their family and/or carers as appropriate.'}, null=True)),
                ('care_planning_has_been_updated_when_necessary', models.IntegerField(default=0, help_text={'label': 'Care planning has been updated when necessary', 'reference': 'Percentage of children and young people with epilepsy after 12 months where there is evidence that the care plan has been updated where necessary.'}, null=True)),
                ('comprehensive_care_planning_content', models.IntegerField(default=0, help_text={'label': 'Comprehensive care planning content', 'reference': 'Percentage of children diagnosed with epilepsy with documented evidence of communication regarding core elements of care planning.'}, null=True)),
                ('parental_prolonged_seizures_care_plan', models.IntegerField(default=0, help_text={'label': 'Parental prolonged seizures care plan', 'reference': ''}, null=True)),
                ('water_safety', models.IntegerField(default=0, help_text={'label': 'Water safety', 'reference': ''}, null=True)),
                ('first_aid', models.IntegerField(default=0, help_text={'label': 'First aid', 'reference': ''}, null=True)),
                ('general_participation_and_risk', models.IntegerField(default=0, help_text={'label': 'General participation and risk', 'reference': ''}, null=True)),
                ('service_contact_details', models.IntegerField(default=0, help_text={'label': 'Service contact details', 'reference': ''}, null=True)),
                ('sudep', models.IntegerField(default=0, help_text={'label': 'Sudden unexplained death in epilepsy', 'reference': ''}, null=True)),
                ('school_individual_healthcare_plan', models.IntegerField(default=0, help_text={'label': 'School individualised health care plan', 'reference': ''}, null=True)),
                ('parent_trust', models.CharField(max_length=50)),
                ('hospital_organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epilepsy12.hospitaltrust')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='epilepsy12.registration')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
    ]
