# Generated by Django 4.0.4 on 2022-08-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0043_remove_desscribe_seizure_cause_gene_abnormality_snomed_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='assessment_complete',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='epilepsy_context_complete',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='initial_assessment_complete',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='investigation_management_complete',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='multiaxial_description_complete',
        ),
    ]
