# Generated by Django 4.1.5 on 2023-01-20 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0044_remove_auditprogress_assessment_of_mental_health_issues_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='registration',
        ),
        migrations.AddField(
            model_name='registration',
            name='kpi',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='epilepsy12.kpi'),
        ),
    ]
