# Generated by Django 4.0.4 on 2022-08-20 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0045_auditprogress_registration_audit_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='hospital_trust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_trust', to='epilepsy12.hospitaltrust'),
        ),
    ]
