# Generated by Django 4.1.5 on 2023-01-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0045_remove_kpi_registration_registration_kpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='parent_trust',
            field=models.CharField(max_length=250),
        ),
    ]
