# Generated by Django 4.0.4 on 2022-08-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0046_alter_site_hospital_trust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desscribe',
            name='description',
            field=models.CharField(blank=True, default='', help_text='What is the episode(s) like and is the description adequate?', max_length=5000, null=True),
        ),
    ]
