# Generated by Django 4.1.5 on 2023-01-28 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0049_remove_visitactivity_login_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitactivity',
            name='activity_datetime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 1, 28, 11, 0, 22, 920035, tzinfo=datetime.timezone.utc)),
        ),
    ]
