# Generated by Django 4.0.4 on 2022-08-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0050_alter_assessment_childrens_epilepsy_surgical_service_referral_criteria_met_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditprogress',
            options={'verbose_name': 'Audit Progress', 'verbose_name_plural': 'Audit Progresses'},
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='lead_hospital',
        ),
    ]
