# Generated by Django 4.1.5 on 2023-01-28 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0050_alter_visitactivity_activity_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitactivity',
            name='activity_datetime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 1, 28, 13, 46, 1, 300886, tzinfo=datetime.timezone.utc)),
        ),
    ]
