# Generated by Django 5.1.5 on 2025-04-12 19:31
import logging
from django.apps import apps
from django.db import migrations

logger = logging.getLogger(__name__)


def forward_migrate_organisations(apps, schema_editor):
    """Migrate existing organisation_employer relationships to the new model"""
    Epilepsy12User = apps.get_model("epilepsy12", "Epilepsy12User")
    OrganisationEmployer = apps.get_model("epilepsy12", "OrganisationEmployer")
    Organisation = apps.get_model("epilepsy12", "Organisation")

    # Loop through each user
    for user in Epilepsy12User.objects.filter(
        organisation_employer__isnull=False
    ).all():
        if user.organisation_employer._meta.model == OrganisationEmployer:
            # If the user already has an OrganisationEmployer, skip them
            logger.info(
                f"User {user.email} already has an OrganisationEmployer, skipping."
            )
            continue
        organisation = user.organisation_employer
        try:
            # Create an entry in the through table
            OrganisationEmployer.objects.create(
                epilepsy12_user=user,
                employer_organisation=organisation,
            )
            logger.info(
                f"Created OrganisationEmployer for user {user.email} with organisation {user.employer_organisation.all()}"
            )
        except Exception as e:
            logger.error(
                f"Error creating OrganisationEmployer for user {user.email}: {e} from {user.organisation_employer}"
            )
            continue


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0051_alter_epilepsy12user_organisation_employer_and_more"),
    ]

    operations = [
        migrations.RunPython(forward_migrate_organisations),
    ]
