# Generated by Django 4.1.5 on 2023-01-28 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0051_alter_visitactivity_activity_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'permissions': [('can_approve_eligibility', 'Can approve eligibility for Epilepsy12.'), ('can_remove_approval_of_eligibility', 'Can remove approval of eligibiltiy for Epilepsy12.'), ('can_register_child_in_epilepsy12', 'Can register child in Epilepsy12. (A cohort number is automatically allocaeted)'), ('can_unregister_child_in_epilepsy12', 'Can unregister a child in Epilepsy. Their record and previously entered data is untouched.'), ('can_consent_to_audit_participation', 'Can consent to participating in Epilepsy12.')], 'verbose_name': 'Registration', 'verbose_name_plural': 'Registrations'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'permissions': [('can_transfer_epilepsy12_lead_centre', 'Can transfer this child to another Epilepsy12 centre.'), ('can_edit_epilepsy12_lead_centre', "Can edit this child's current Epilepsy12 lead centre."), ('can_delete_epilepsy12_lead_centre', 'Can delete Epilepsy12 lead centre.')], 'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
        migrations.AlterField(
            model_name='epilepsy12user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Audit Centre Lead Clinician'), (2, 'Audit Centre Clinician'), (3, 'Audit Centre Administrator'), (8, 'Audit Centre Manager'), (4, 'RCPCH Audit Lead'), (5, 'RCPCH Audit Analyst'), (6, 'RCPCH Audit Administrator'), (7, 'RCPCH Audit Children and Family')], null=True),
        ),
        migrations.AlterField(
            model_name='historicalepilepsy12user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Audit Centre Lead Clinician'), (2, 'Audit Centre Clinician'), (3, 'Audit Centre Administrator'), (8, 'Audit Centre Manager'), (4, 'RCPCH Audit Lead'), (5, 'RCPCH Audit Analyst'), (6, 'RCPCH Audit Administrator'), (7, 'RCPCH Audit Children and Family')], null=True),
        ),
        migrations.AlterField(
            model_name='visitactivity',
            name='activity_datetime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 1, 28, 18, 18, 24, 177172, tzinfo=datetime.timezone.utc)),
        ),
    ]
