# Generated by Django 5.1.5 on 2025-04-12 19:31
import logging
from django.apps import apps
from django.db import migrations

logger = logging.getLogger(__name__)


def forward_migrate_organisations(apps, schema_editor):
    """Migrate existing organisation_employer relationships to the new model"""
    Epilepsy12User = apps.get_model("epilepsy12", "Epilepsy12User")
    OrganisationEmployer = apps.get_model("epilepsy12", "OrganisationEmployer")

    # Loop through each user
    for user in Epilepsy12User.objects.filter(
        organisation_employer__isnull=False
    ).all():
        # Create an entry in the through table
        user.employer_organisation.add(user.organisation_employer)
        user.save()
        OrganisationEmployer.objects.filter(
            epilepsy12_user=user, employer_organisation=user.organisation_employer
        ).update(
            is_primary=True,
            is_active=True,
        )
        logger.info(
            f"Created OrganisationEmployer for user {user.username} with organisation {user.employer_organisation.all()}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0051_alter_epilepsy12user_organisation_employer_and_more"),
    ]

    operations = [
        migrations.RunPython(forward_migrate_organisations),
    ]
