# Generated by Django 5.1.5 on 2025-04-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0052_migrate_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="epilepsy12user",
            name="organisation_employer",
        ),
        migrations.RemoveField(
            model_name="historicalepilepsy12user",
            name="organisation_employer",
        ),
    ]
