# Generated by Django 4.0.4 on 2022-08-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0052_remove_seizuretype_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditprogress',
            name='assessment_total_completed_fields',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Total Number of fields completed'),
        ),
        migrations.AddField(
            model_name='auditprogress',
            name='assessment_total_expected_fields',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Total Number of fields expected'),
        ),
        migrations.AddField(
            model_name='auditprogress',
            name='epilepsy_context_total_completed_fields',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Total Number of fields completed'),
        ),
        migrations.AddField(
            model_name='auditprogress',
            name='epilepsy_context_total_expected_fields',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Total Number of fields expected'),
        ),
        migrations.AddField(
            model_name='auditprogress',
            name='initial_assessment_total_completed_fields',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Total Number of fields completed'),
        ),
        migrations.AddField(
            model_name='auditprogress',
            name='initial_assessment_total_expected_fields',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Total Number of fields expected'),
        ),
        migrations.AddField(
            model_name='auditprogress',
            name='investigation_total_completed_fields',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Total Number of fields completed'),
        ),
        migrations.AddField(
            model_name='auditprogress',
            name='investigation_total_expected_fields',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Total Number of fields expected'),
        ),
        migrations.AddField(
            model_name='auditprogress',
            name='management_total_completed_fields',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Total Number of fields completed'),
        ),
        migrations.AddField(
            model_name='auditprogress',
            name='management_total_expected_fields',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Total Number of fields expected'),
        ),
        migrations.AddField(
            model_name='auditprogress',
            name='multiaxial_description_total_completed_fields',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Total Number of fields completed'),
        ),
        migrations.AddField(
            model_name='auditprogress',
            name='multiaxial_description_total_expected_fields',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Total Number of fields expected'),
        ),
        migrations.AddField(
            model_name='auditprogress',
            name='registration_total_completed_fields',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Total Number of fields completed'),
        ),
        migrations.AddField(
            model_name='auditprogress',
            name='registration_total_expected_fields',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Total Number of fields expected'),
        ),
    ]
