# Generated by Django 5.1.5 on 2025-04-23 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0053_remove_epilepsy12user_organisation_employer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="epilepsy12_sites",
                to="epilepsy12.case",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patient_sites",
                to="epilepsy12.organisation",
            ),
        ),
    ]
