# Generated by Django 4.0.4 on 2022-08-22 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0053_auditprogress_assessment_total_completed_fields_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='lead_hospital',
        ),
    ]
