# Generated by Django 4.1.6 on 2023-02-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0053_alter_site_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='nonepileptic_seizure_unknown_onset',
            field=models.CharField(blank=True, choices=[('BAr', 'Behaviour arrest'), ('EpS', 'Epileptic spasms'), ('TCl', 'Tonic-clonic'), ('Oth', 'Other')], default=None, help_text={'label': 'How best describes the onset of the nonepileptic episode(s)?', 'reference': 'How best describes the onset of the nonepileptic episode(s)?'}, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='nonepileptic_seizure_unknown_onset',
            field=models.CharField(blank=True, choices=[('BAr', 'Behaviour arrest'), ('EpS', 'Epileptic spasms'), ('TCl', 'Tonic-clonic'), ('Oth', 'Other')], default=None, help_text={'label': 'How best describes the onset of the nonepileptic episode(s)?', 'reference': 'How best describes the onset of the nonepileptic episode(s)?'}, max_length=3, null=True),
        ),
    ]
