# Generated by Django 5.1.5 on 2025-04-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0054_alter_site_case_alter_site_organisation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="epilepsy12user",
            old_name="employer_organisation",
            new_name="employers",
        ),
    ]
