# Generated by Django 4.1.6 on 2023-02-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0054_alter_episode_nonepileptic_seizure_unknown_onset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comorbidity',
            name='comorbidity_diagnosis',
            field=models.CharField(default=None, help_text={'label': 'What is the comorbidity?', 'reference': 'What is the comorbidity?'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcomorbidity',
            name='comorbidity_diagnosis',
            field=models.CharField(default=None, help_text={'label': 'What is the comorbidity?', 'reference': 'What is the comorbidity?'}, max_length=250, null=True),
        ),
    ]
