# Generated by Django 4.1.6 on 2023-02-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0055_alter_comorbidity_comorbidity_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmultiaxialdiagnosis',
            name='epilepsy_cause',
            field=models.CharField(blank=True, default=None, help_text={'label': 'What is the main identified cause of the epilepsy?', 'reference': 'What is the main identified cause of the epilepsy?'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='multiaxialdiagnosis',
            name='epilepsy_cause',
            field=models.CharField(blank=True, default=None, help_text={'label': 'What is the main identified cause of the epilepsy?', 'reference': 'What is the main identified cause of the epilepsy?'}, max_length=250, null=True),
        ),
    ]
