# Generated by Django 5.1.5 on 2025-07-19 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0055_rename_employer_organisation_epilepsy12user_employers"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitactivity",
            name="details",
            field=models.TextField(
                blank=True,
                help_text="Details of the activity, such as the reason for a password reset or the type of CSV uploaded.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="visitactivity",
            name="epilepsy12user_admin",
            field=models.ForeignKey(
                blank=True,
                help_text="The user with admin permissions responsible for the activity, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_activity",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="visitactivity",
            name="activity",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Successful login"),
                    (2, "Login failed"),
                    (3, "Logout"),
                    (4, "Password reset link sent"),
                    (5, "Password reset successfully"),
                    (7, "Password lockout"),
                    (6, "Two factor authentication set up"),
                    (8, "Uploaded CSV"),
                    (9, "Touched patient record"),
                    (10, "Created a user record"),
                    (11, "User record changed"),
                    (12, "User role changed"),
                    (13, "Superuser or admin status changed"),
                    (14, "User record deleted"),
                    (15, "User assigned to PDU"),
                    (16, "User removed from PDU"),
                    (17, "User PDU role changed"),
                ],
                default=1,
            ),
        ),
    ]
