# Generated by Django 5.1.5 on 2025-07-20 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.contrib.gis.geos import Point


def seed_rcpch_organisation(apps, schema_editor):
    Organisation = apps.get_model("epilepsy12", "Organisation")
    
    # Create the RCPCH as an organisation for testing
    Organisation.objects.update_or_create(
        ods_code="8HV48",
        defaults={
            "name": "Royal College of Paediatrics and Child Health",
            "website": "https://www.rcpch.ac.uk/",
            "address1": "5-11, Theobalds Rd",
            "telephone": "02070926000",
            "email": "epilepsy12@rcpch.ac.uk",
            "city": "LONDON",
            "county": "GREATER LONDON",
            "postcode": "WC1X 8SH",
            "latitude": 51.52077435089506,
            "longitude": -0.11583854557536251,
            "geocode_coordinates": Point(
                x=-0.11583854557536251, y=51.52077435089506
            )
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0056_visitactivity_details_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_rcpch_organisation)
    ]
