# Generated by Django 5.2.3 on 2025-08-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0056_visitactivity_details_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="epilepsy12user",
            options={
                "permissions": [
                    (
                        "can_allocate_user_to_organisation",
                        "Can allocate user to organisation.",
                    )
                ],
                "verbose_name": "Epilepsy12 User",
                "verbose_name_plural": "Epilepsy12 Users",
            },
        ),
        migrations.AlterField(
            model_name="case",
            name="organisations",
            field=models.ManyToManyField(
                related_name="cases",
                through="epilepsy12.Site",
                through_fields=("case", "organisation"),
                to="epilepsy12.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="epilepsy12user",
            name="employers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Please select the organisation trust you are affiliated with.",
                through="epilepsy12.OrganisationEmployer",
                through_fields=("epilepsy12_user", "employer_organisation"),
                to="epilepsy12.organisation",
            ),
        ),
    ]
