# Generated by Django 4.1.6 on 2023-03-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "epilepsy12",
            "0056_alter_historicalmultiaxialdiagnosis_epilepsy_cause_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalhospitaltrust",
            name="Country",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalhospitaltrust",
            name="CountryONSCode",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalhospitaltrust",
            name="DateValid",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalhospitaltrust",
            name="ICBName",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalhospitaltrust",
            name="ICBODSCode",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalhospitaltrust",
            name="ICBONSBoundaryCode",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalhospitaltrust",
            name="LocalAuthorityName",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalhospitaltrust",
            name="LocalAuthorityODSCode",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalhospitaltrust",
            name="NHSEnglandRegion",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalhospitaltrust",
            name="NHSEnglandRegionCode",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalhospitaltrust",
            name="NHSEnglandRegionONSCode",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalhospitaltrust",
            name="OPENUKNetworkCode",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalhospitaltrust",
            name="OPENUKNetworkName",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalhospitaltrust",
            name="SubICBName",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalhospitaltrust",
            name="SubICBODSCode",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hospitaltrust",
            name="Country",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hospitaltrust",
            name="CountryONSCode",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hospitaltrust",
            name="DateValid",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="hospitaltrust",
            name="ICBName",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hospitaltrust",
            name="ICBODSCode",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hospitaltrust",
            name="ICBONSBoundaryCode",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hospitaltrust",
            name="LocalAuthorityName",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hospitaltrust",
            name="LocalAuthorityODSCode",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hospitaltrust",
            name="NHSEnglandRegion",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hospitaltrust",
            name="NHSEnglandRegionCode",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hospitaltrust",
            name="NHSEnglandRegionONSCode",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hospitaltrust",
            name="OPENUKNetworkCode",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hospitaltrust",
            name="OPENUKNetworkName",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hospitaltrust",
            name="SubICBName",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hospitaltrust",
            name="SubICBODSCode",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="epilepsy_or_nonepilepsy_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("E", "Epileptic"),
                    ("NE", "Non-epileptic"),
                    ("U", "Uncertain"),
                ],
                default=None,
                help_text={
                    "label": "Is this episode epileptic, non-epileptic or uncertain?",
                    "reference": "Is this episode epileptic, non-epileptic or uncertain?",
                },
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalepisode",
            name="epilepsy_or_nonepilepsy_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("E", "Epileptic"),
                    ("NE", "Non-epileptic"),
                    ("U", "Uncertain"),
                ],
                default=None,
                help_text={
                    "label": "Is this episode epileptic, non-epileptic or uncertain?",
                    "reference": "Is this episode epileptic, non-epileptic or uncertain?",
                },
                max_length=3,
                null=True,
            ),
        ),
    ]
