# Generated by Django 5.2.3 on 2025-09-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0057_alter_epilepsy12user_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="epilepsy12user",
            options={
                "permissions": [
                    (
                        "can_allocate_user_to_organisation",
                        "Can allocate user to organisation.",
                    ),
                    (
                        "can_reset_two_factor_authentication",
                        "Can reset two factor authentication for a user.",
                    ),
                ],
                "verbose_name": "Epilepsy12 User",
                "verbose_name_plural": "Epilepsy12 Users",
            },
        ),
    ]
