# Generated by Django 4.0.4 on 2022-08-24 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0057_delete_electroclinicalsyndrome_delete_seizurecause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialassessment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
    ]
