# Generated by Django 5.2.6 on 2025-10-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0058_alter_epilepsy12user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="index_of_multiple_deprivation_quintile",
            field=models.PositiveSmallIntegerField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="index of multiple deprivation quintile",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="index_of_multiple_deprivation_quintile",
            field=models.PositiveSmallIntegerField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="index of multiple deprivation quintile",
            ),
        ),
    ]
