# Generated by Django 4.1.7 on 2023-03-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0058_alter_episode_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="epilepsycontext",
            name="diagnosis_of_epilepsy_withdrawn",
            field=models.BooleanField(
                default=None,
                help_text={
                    "label": "Has the diagnosis of epilepsy been withdrawn?",
                    "reference": "In the first year after first assessment, has a diagnosis of epilepsy been withdrawn because it has been subsequently deemed incorrect?",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalepilepsycontext",
            name="diagnosis_of_epilepsy_withdrawn",
            field=models.BooleanField(
                default=None,
                help_text={
                    "label": "Has the diagnosis of epilepsy been withdrawn?",
                    "reference": "In the first year after first assessment, has a diagnosis of epilepsy been withdrawn because it has been subsequently deemed incorrect?",
                },
                null=True,
            ),
        ),
    ]
