# Generated by Django 4.0.4 on 2022-08-24 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy12', '0058_alter_initialassessment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiepilepsymedicine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antiepilepsymedicine',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AddField(
            model_name='antiepilepsymedicine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='antiepilepsymedicine',
            name='updated_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='updated_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
        migrations.AddField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AddField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='case',
            name='updated_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
        migrations.AddField(
            model_name='comorbidity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comorbidity',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AddField(
            model_name='comorbidity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comorbidity',
            name='updated_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
        migrations.AddField(
            model_name='desscribe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='desscribe',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AddField(
            model_name='desscribe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='desscribe',
            name='updated_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
        migrations.AddField(
            model_name='epilepsycontext',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='epilepsycontext',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AddField(
            model_name='epilepsycontext',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='epilepsycontext',
            name='updated_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
        migrations.AddField(
            model_name='investigations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investigations',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AddField(
            model_name='investigations',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='investigations',
            name='updated_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
        migrations.AddField(
            model_name='management',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='management',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AddField(
            model_name='management',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='management',
            name='updated_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
        migrations.AddField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AddField(
            model_name='registration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='updated_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
        migrations.AddField(
            model_name='site',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AddField(
            model_name='site',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='site',
            name='updated_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)'),
        ),
        migrations.AlterField(
            model_name='initialassessment',
            name='updated_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)'),
        ),
    ]
