# Generated by Django 4.1.7 on 2023-03-26 13:28

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        (
            "epilepsy12",
            "0059_alter_epilepsycontext_diagnosis_of_epilepsy_withdrawn_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="epilepsycontext",
            name="experienced_prolonged_focal_seizures",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                default=None,
                help_text={
                    "label": "Has the child at any point in time experienced prolonged focal seizures?",
                    "reference": "Has the child at any point in time experienced prolonged focal seizures > 5 min duration (or successive continuing > 5min)?",
                },
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="firstpaediatricassessment",
            name="first_paediatric_assessment_in_acute_or_nonacute_setting",
            field=models.IntegerField(
                choices=[(1, "Acute"), (2, "Non-acute"), (3, "Don't know")],
                default=None,
                help_text={
                    "label": "Was the first paediatric assessment in an acute or nonacute setting?",
                    "reference": "Was the first paediatric assessment in an acute or nonacute setting?",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalepilepsycontext",
            name="experienced_prolonged_focal_seizures",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Uncertain")],
                default=None,
                help_text={
                    "label": "Has the child at any point in time experienced prolonged focal seizures?",
                    "reference": "Has the child at any point in time experienced prolonged focal seizures > 5 min duration (or successive continuing > 5min)?",
                },
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalfirstpaediatricassessment",
            name="first_paediatric_assessment_in_acute_or_nonacute_setting",
            field=models.IntegerField(
                choices=[(1, "Acute"), (2, "Non-acute"), (3, "Don't know")],
                default=None,
                help_text={
                    "label": "Was the first paediatric assessment in an acute or nonacute setting?",
                    "reference": "Was the first paediatric assessment in an acute or nonacute setting?",
                },
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="epilepsy12user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="user_email_ci_uniqueness",
            ),
        ),
    ]
