# Generated by Django 5.2.13 on 2026-04-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "epilepsy12",
            "0059_alter_case_index_of_multiple_deprivation_quintile_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinvestigations",
            name="genome_sequencing_requested",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text={
                    "label": "Has epilepsy related Whole Genome Sequencing been requested?"
                },
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalinvestigations",
            name="r14_test_achieved_date",
            field=models.DateField(
                blank=True,
                default=None,
                help_text={"label": "Date R14 test result achieved"},
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalinvestigations",
            name="r14_test_requested_date",
            field=models.DateField(
                blank=True,
                default=None,
                help_text={"label": "Date of decision to request R14 test"},
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalinvestigations",
            name="r14_test_status",
            field=models.CharField(
                choices=[("R", "Requested"), ("A", "Achieved"), ("N", "Not Requested")],
                default=None,
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalinvestigations",
            name="r27_test_achieved_date",
            field=models.DateField(
                blank=True,
                default=None,
                help_text={"label": "Date R27 test result achieved"},
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalinvestigations",
            name="r27_test_requested_date",
            field=models.DateField(
                blank=True,
                default=None,
                help_text={"label": "Date of decision to request R27 test"},
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalinvestigations",
            name="r27_test_status",
            field=models.CharField(
                choices=[("R", "Requested"), ("A", "Achieved"), ("N", "Not Requested")],
                default=None,
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalinvestigations",
            name="r59_test_achieved_date",
            field=models.DateField(
                blank=True,
                default=None,
                help_text={"label": "Date R59 test result achieved"},
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalinvestigations",
            name="r59_test_requested_date",
            field=models.DateField(
                blank=True,
                default=None,
                help_text={"label": "Date of decision to request R59 test"},
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalinvestigations",
            name="r59_test_status",
            field=models.CharField(
                choices=[("R", "Requested"), ("A", "Achieved"), ("N", "Not Requested")],
                default=None,
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investigations",
            name="genome_sequencing_requested",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text={
                    "label": "Has epilepsy related Whole Genome Sequencing been requested?"
                },
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investigations",
            name="r14_test_achieved_date",
            field=models.DateField(
                blank=True,
                default=None,
                help_text={"label": "Date R14 test result achieved"},
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investigations",
            name="r14_test_requested_date",
            field=models.DateField(
                blank=True,
                default=None,
                help_text={"label": "Date of decision to request R14 test"},
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investigations",
            name="r14_test_status",
            field=models.CharField(
                choices=[("R", "Requested"), ("A", "Achieved"), ("N", "Not Requested")],
                default=None,
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investigations",
            name="r27_test_achieved_date",
            field=models.DateField(
                blank=True,
                default=None,
                help_text={"label": "Date R27 test result achieved"},
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investigations",
            name="r27_test_requested_date",
            field=models.DateField(
                blank=True,
                default=None,
                help_text={"label": "Date of decision to request R27 test"},
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investigations",
            name="r27_test_status",
            field=models.CharField(
                choices=[("R", "Requested"), ("A", "Achieved"), ("N", "Not Requested")],
                default=None,
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investigations",
            name="r59_test_achieved_date",
            field=models.DateField(
                blank=True,
                default=None,
                help_text={"label": "Date R59 test result achieved"},
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investigations",
            name="r59_test_requested_date",
            field=models.DateField(
                blank=True,
                default=None,
                help_text={"label": "Date of decision to request R59 test"},
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investigations",
            name="r59_test_status",
            field=models.CharField(
                choices=[("R", "Requested"), ("A", "Achieved"), ("N", "Not Requested")],
                default=None,
                max_length=2,
                null=True,
            ),
        ),
    ]
