# Generated by Django 5.2.14 on 2026-06-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "epilepsy12",
            "0060_historicalinvestigations_genome_sequencing_requested_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinvestigations",
            name="r14_test_status",
            field=models.CharField(
                choices=[
                    ("R", "Requested"),
                    ("A", "Requested & Achieved"),
                    ("N", "Not Requested"),
                ],
                default=None,
                help_text={"label": "Was an R14 test requested?"},
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvestigations",
            name="r27_test_status",
            field=models.CharField(
                choices=[
                    ("R", "Requested"),
                    ("A", "Requested & Achieved"),
                    ("N", "Not Requested"),
                ],
                default=None,
                help_text={"label": "Was an R27 test requested?"},
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvestigations",
            name="r59_test_status",
            field=models.CharField(
                choices=[
                    ("R", "Requested"),
                    ("A", "Requested & Achieved"),
                    ("N", "Not Requested"),
                ],
                default=None,
                help_text={"label": "Was an R59 test requested?"},
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="investigations",
            name="r14_test_status",
            field=models.CharField(
                choices=[
                    ("R", "Requested"),
                    ("A", "Requested & Achieved"),
                    ("N", "Not Requested"),
                ],
                default=None,
                help_text={"label": "Was an R14 test requested?"},
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="investigations",
            name="r27_test_status",
            field=models.CharField(
                choices=[
                    ("R", "Requested"),
                    ("A", "Requested & Achieved"),
                    ("N", "Not Requested"),
                ],
                default=None,
                help_text={"label": "Was an R27 test requested?"},
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="investigations",
            name="r59_test_status",
            field=models.CharField(
                choices=[
                    ("R", "Requested"),
                    ("A", "Requested & Achieved"),
                    ("N", "Not Requested"),
                ],
                default=None,
                help_text={"label": "Was an R59 test requested?"},
                max_length=2,
                null=True,
            ),
        ),
    ]
