# Generated by Django 4.1.7 on 2023-03-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0061_alter_case_ethnicity_alter_historicalcase_ethnicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kpi",
            name="assessment_of_mental_health_issues",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "6. Assessment of mental health issues",
                    "reference": "Percentage of children with epilepsy where there is documented evidence that they have been asked about mental health either through clinical screening, or a questionnaire/measure.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="care_planning_has_been_updated_when_necessary",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "9c. Care planning has been updated when necessary",
                    "reference": "Percentage of children and young people with epilepsy after 12 months where there is evidence that the care plan has been updated where necessary.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="comprehensive_care_planning_agreement",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "9. Comprehensive care planning agreement",
                    "reference": "Percentage of children and young people with epilepsy after 12 months where there is evidence of a comprehensive care plan that is agreed between the person, their family and/or carers and primary and secondary care providers, and the care plan has been updated where necessary.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="comprehensive_care_planning_content",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "9b. Comprehensive care planning content",
                    "reference": "Percentage of children diagnosed with epilepsy with documented evidence of communication regarding core elements of care planning.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="ecg",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "4. ECG",
                    "reference": "Percentage of children and young people with convulsive seizures and epilepsy, with an ECG at first year.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="epilepsy_specialist_nurse",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "2. Epilepsy Specialist Nurse",
                    "reference": "Percentage of children and young people with epilepsy, with input by epilepsy specialist nurse within the first year of care.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="epilepsy_surgery_referral",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "3b. Epilepsy surgery referral",
                    "reference": "Percentage of ongoing children and young people meeting defined epilepsy surgery referral criteria with evidence of epilepsy surgery referral.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="first_aid",
            field=models.IntegerField(
                default=None,
                help_text={"label": "9c. First aid", "reference": ""},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="general_participation_and_risk",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "9d. General participation and risk",
                    "reference": "",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="mental_health_support",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "7. Mental health support",
                    "reference": "Percentage of children with epilepsy and a mental health problem who have evidence of mental health support",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="mri",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "5. MRI",
                    "reference": "Percentage of children and young people with defined indications for an MRI, who had who had timely MRI within 6 weeks of request",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="paediatrician_with_expertise_in_epilepsies",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "1. Paediatrician with expertise in epilepsies",
                    "reference": "Percentage of children and young people with epilepsy, with input by a 'consultant paediatrician with expertise in epilepsies' within 2 weeks of initial referral",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="parental_prolonged_seizures_care_plan",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "9a. Parental prolonged seizures care plan",
                    "reference": "",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="patient_carer_parent_agreement_to_the_care_planning",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "9b. Patient/carer/parent agreement to the care planning",
                    "reference": "Percentage of children and young people with epilepsy after 12 months where there was evidence of agreement between the person, their family and/or carers as appropriate.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="patient_held_individualised_epilepsy_document",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "9a. Patient-held individualised epilepsy document/copy of clinic letter that includes care planning information",
                    "reference": "Percentage of children and young people with epilepsy after 12 months that had an individualised epilepsy document with individualised epilepsy document or a copy clinic letter that includes care planning information.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="school_individual_healthcare_plan",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "10. School individualised health care plan",
                    "reference": "",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="service_contact_details",
            field=models.IntegerField(
                default=None,
                help_text={"label": "9e. Service contact details", "reference": ""},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="sodium_valproate",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "8. Sodium Valproate",
                    "reference": "Percentage of all females 12 years and above currently on valproate treatment with annual risk acknowledgement form completed",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="sudep",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "9f. Sudden unexplained death in epilepsy",
                    "reference": "",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="tertiary_input",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "3. Tertiary input",
                    "reference": "Percentage of children and young people meeting defined criteria for paediatric neurology referral, with input of tertiary care and/or CESS referral within the first year of care.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="water_safety",
            field=models.IntegerField(
                default=None,
                help_text={"label": "9b. Water safety", "reference": ""},
                null=True,
            ),
        ),
    ]
