# Generated by Django 5.2.14 on 2026-07-11 16:53

import django.db.models.deletion
import epilepsy12.models_folder.help_text_mixin
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0061_alter_historicalinvestigations_r14_test_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text={
                            "label": "Name",
                            "reference": "Optional display name for the audit period.",
                        },
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "cohort_number",
                    models.PositiveSmallIntegerField(
                        help_text={
                            "label": "Cohort Number",
                            "reference": "The cohort allocated, based on the First Paediatric Assessment date.",
                        },
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "recruitment_start_date",
                    models.DateField(
                        help_text={
                            "label": "Start Date",
                            "reference": "The start date for recruitment to this cohort.",
                        }
                    ),
                ),
                (
                    "recruitment_end_date",
                    models.DateField(
                        help_text={
                            "label": "End Date",
                            "reference": "The end date for recruitment to this cohort.",
                        }
                    ),
                ),
                (
                    "data_collection_end_date",
                    models.DateField(
                        help_text={
                            "label": "Data Collection End Date",
                            "reference": "The end date for data collection.",
                        }
                    ),
                ),
                (
                    "submission_deadline",
                    models.DateField(
                        help_text={
                            "label": "Submission Deadline",
                            "reference": "The deadline for submitting data.",
                        }
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=False,
                        help_text={
                            "label": "Is Visible",
                            "reference": "Whether the audit period is visible to the user.",
                        },
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="record created by user in %(class)",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="record updated by user in %(class)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit period",
                "verbose_name_plural": "Audit periods",
                "ordering": ["-recruitment_start_date"],
            },
            bases=(
                epilepsy12.models_folder.help_text_mixin.HelpTextMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="historicalregistration",
            name="audit_period",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="epilepsy12.auditperiod",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="audit_period",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registrations",
                to="epilepsy12.auditperiod",
            ),
        ),
        migrations.CreateModel(
            name="AuditPeriodExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("extended_submission_date", models.DateField()),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "audit_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extensions",
                        to="epilepsy12.auditperiod",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="record created by user in %(class)",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_period_extensions",
                        to="epilepsy12.organisation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="record updated by user in %(class)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Period site extension",
                "verbose_name_plural": "Audit Period site extensions",
            },
        ),
        migrations.CreateModel(
            name="HistoricalAuditPeriod",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text={
                            "label": "Name",
                            "reference": "Optional display name for the audit period.",
                        },
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "cohort_number",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        help_text={
                            "label": "Cohort Number",
                            "reference": "The cohort allocated, based on the First Paediatric Assessment date.",
                        },
                    ),
                ),
                ("slug", models.SlugField(blank=True)),
                (
                    "recruitment_start_date",
                    models.DateField(
                        help_text={
                            "label": "Start Date",
                            "reference": "The start date for recruitment to this cohort.",
                        }
                    ),
                ),
                (
                    "recruitment_end_date",
                    models.DateField(
                        help_text={
                            "label": "End Date",
                            "reference": "The end date for recruitment to this cohort.",
                        }
                    ),
                ),
                (
                    "data_collection_end_date",
                    models.DateField(
                        help_text={
                            "label": "Data Collection End Date",
                            "reference": "The end date for data collection.",
                        }
                    ),
                ),
                (
                    "submission_deadline",
                    models.DateField(
                        help_text={
                            "label": "Submission Deadline",
                            "reference": "The deadline for submitting data.",
                        }
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=False,
                        help_text={
                            "label": "Is Visible",
                            "reference": "Whether the audit period is visible to the user.",
                        },
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="record created by user in %(class)",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="record updated by user in %(class)",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Audit period",
                "verbose_name_plural": "historical Audit periods",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAuditPeriodExtension",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("extended_submission_date", models.DateField()),
                ("reason", models.TextField(blank=True, default="")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "audit_period",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="epilepsy12.auditperiod",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="record created by user in %(class)",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="epilepsy12.organisation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="record updated by user in %(class)",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Audit Period site extension",
                "verbose_name_plural": "historical Audit Period site extensions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name="auditperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("recruitment_start_date__lt", models.F("recruitment_end_date"))
                ),
                name="audit_period_start_date_before_end_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("recruitment_end_date__gt", models.F("data_collection_end_date"))
                ),
                name="audit_period_data_collection_end_date_after_recruitment_end_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("submission_deadline__gt", models.F("data_collection_end_date"))
                ),
                name="audit_period_submission_deadline_after_data_collection_end_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditperiodextension",
            constraint=models.UniqueConstraint(
                fields=("audit_period", "organisation"),
                name="one_extension_per_organisation_per_audit_period",
            ),
        ),
    ]
