# Generated by Django 5.2.14 on 2026-07-11 17:24
from django.db import migrations

# Historical facts, deliberately hardcoded
# which may change or be removed. recruitment start/end, data collection end, deadline.
# only goes up to cohort 9 - NOTE: existing patients in cohort 9 that registered
# in December 2025 will be assigned to cohort 8 under the new rules. They will
# not be included in this migration and need to be manually updated.
from epilepsy12.constants.audit_period_dates import AUDIT_PERIODS


def seed_audit_periods(apps, schema_editor):
    AuditPeriod = apps.get_model("epilepsy12", "AuditPeriod")
    for cohort_number, (rec_start, rec_end, dc_end, deadline) in AUDIT_PERIODS.items():
        AuditPeriod.objects.get_or_create(
            cohort_number=cohort_number,
            defaults={
                "recruitment_start_date": rec_start,
                "recruitment_end_date": rec_end,
                "data_collection_end_date": dc_end,
                "submission_deadline": deadline,
                "slug": f"cohort-{cohort_number}",   # save() is NOT called by historical models
                "is_visible": True,
            },
        )

def backfill_registrations(apps, schema_editor):
    AuditPeriod = apps.get_model("epilepsy12", "AuditPeriod")
    Registration = apps.get_model("epilepsy12", "Registration")
    for period in AuditPeriod.objects.all():
        # queryset.update(): no per-row save(), no signals, no history churn
        Registration.objects.filter(
            cohort=period.cohort_number, audit_period__isnull=True
        ).update(audit_period=period)

def reverse(apps, schema_editor):
    AuditPeriod = apps.get_model("epilepsy12", "AuditPeriod")
    Registration = apps.get_model("epilepsy12", "Registration")
    seeded = AuditPeriod.objects.filter(cohort_number__in=AUDIT_PERIODS.keys())
    Registration.objects.filter(audit_period__in=seeded).update(audit_period=None)
    seeded.delete()  # still cascades to extensions

class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0062_auditperiod_historicalregistration_audit_period_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_audit_periods, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(backfill_registrations, reverse_code=reverse),
    ]
