# Generated by Django 4.1.7 on 2023-04-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0062_alter_kpi_assessment_of_mental_health_issues_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalHospitalTrust",
            new_name="HistoricalOrganisation",
        ),
        migrations.RenameModel(
            old_name="HospitalTrust",
            new_name="Organisation",
        ),
        migrations.RenameField(
            model_name="case",
            old_name="hospital_trusts",
            new_name="organisations",
        ),
        migrations.RenameField(
            model_name="epilepsy12user",
            old_name="hospital_employer",
            new_name="organisation_employer",
        ),
        migrations.RenameField(
            model_name="historicalepilepsy12user",
            old_name="hospital_employer",
            new_name="organisation_employer",
        ),
        migrations.RenameField(
            model_name="historicalsite",
            old_name="hospital_trust",
            new_name="organisation",
        ),
        migrations.RenameField(
            model_name="kpi",
            old_name="hospital_organisation",
            new_name="organisation",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="hospital_trust",
            new_name="organisation",
        ),
        migrations.RenameIndex(
            model_name="organisation",
            new_name="epilepsy12__Organis_7e589c_idx",
            old_name="epilepsy12__Organis_abe360_idx",
        ),
        migrations.AlterField(
            model_name="epilepsy12user",
            name="view_preference",
            field=models.SmallIntegerField(
                choices=[(0, "organisation"), (1, "trust"), (2, "national")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="historicalepilepsy12user",
            name="view_preference",
            field=models.SmallIntegerField(
                choices=[(0, "organisation"), (1, "trust"), (2, "national")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="comprehensive_care_planning_agreement",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "9A. Comprehensive care planning agreement",
                    "reference": "Percentage of children and young people with epilepsy after 12 months where there is evidence of a comprehensive care plan that is agreed between the person, their family and/or carers and primary and secondary care providers, and the care plan has been updated where necessary.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="comprehensive_care_planning_content",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "9B. Comprehensive care planning content",
                    "reference": "Percentage of children diagnosed with epilepsy with documented evidence of communication regarding core elements of care planning.",
                },
                null=True,
            ),
        ),
    ]
