# Generated by Django 5.2.14 on 2026-07-11 17:24
from datetime import date
from django.db import migrations

# Historical facts, deliberately hardcoded
# which may change or be removed. recruitment start/end, data collection end, deadline.
COHORTS = {
    4:  (date(2020, 12, 1), date(2021, 11, 30), date(2022, 11, 30), date(2023, 1, 10)),
    5:  (date(2021, 12, 1), date(2022, 11, 30), date(2023, 11, 30), date(2024, 1, 9)),
    6:  (date(2022, 12, 1), date(2023, 11, 30), date(2024, 11, 30), date(2025, 1, 14)),
    7:  (date(2023, 12, 1), date(2024, 11, 30), date(2025, 11, 30), date(2026, 1, 13)),
    8:  (date(2024, 12, 1), date(2025, 11, 30), date(2026, 11, 30), date(2027, 1, 12)),
    9:  (date(2025, 12, 1), date(2026, 11, 30), date(2027, 11, 30), date(2028, 1, 11)),
}

def seed_audit_periods(apps, schema_editor):
    AuditPeriod = apps.get_model("epilepsy12", "AuditPeriod")
    for cohort_number, (rec_start, rec_end, dc_end, deadline) in COHORTS.items():
        AuditPeriod.objects.get_or_create(
            cohort_number=cohort_number,
            defaults={
                "recruitment_start_date": rec_start,
                "recruitment_end_date": rec_end,
                "data_collection_end_date": dc_end,
                "submission_deadline": deadline,
                "slug": f"cohort-{cohort_number}",   # save() is NOT called by historical models
                "is_visible": False,
            },
        )

def backfill_registrations(apps, schema_editor):
    AuditPeriod = apps.get_model("epilepsy12", "AuditPeriod")
    Registration = apps.get_model("epilepsy12", "Registration")
    for period in AuditPeriod.objects.all():
        # queryset.update(): no per-row save(), no signals, no history churn
        Registration.objects.filter(
            cohort=period.cohort_number, audit_period__isnull=True
        ).update(audit_period=period)

def reverse(apps, schema_editor):
    apps.get_model("epilepsy12", "Registration").objects.update(audit_period=None)
    apps.get_model("epilepsy12", "AuditPeriod").objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0062_auditperiod_historicalregistration_audit_period_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_audit_periods, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(backfill_registrations, reverse_code=reverse),
    ]
