# Generated by Django 5.2.15 on 2026-07-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0063_seed_audit_periods"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditperiodextension",
            options={
                "permissions": [
                    (
                        "can_extend_submission_deadline",
                        "Can extend the submission deadline for an audit period.",
                    )
                ],
                "verbose_name": "Audit Period site extension",
                "verbose_name_plural": "Audit Period site extensions",
            },
        ),
        migrations.AlterField(
            model_name="auditperiodextension",
            name="reason",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Organisation Request"),
                    (1, "RCPCH Audit Team Request"),
                    (2, "Technical Request"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalauditperiodextension",
            name="reason",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Organisation Request"),
                    (1, "RCPCH Audit Team Request"),
                    (2, "Technical Request"),
                ],
                null=True,
            ),
        ),
    ]
