# Generated by Django 4.1.7 on 2023-04-01 23:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "epilepsy12",
            "0063_rename_historicalhospitaltrust_historicalorganisation_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalorganisation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Organisation",
                "verbose_name_plural": "historical Organisations",
            },
        ),
        migrations.AlterModelOptions(
            name="organisation",
            options={
                "ordering": ("OrganisationName",),
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisations",
            },
        ),
    ]
