# Generated by Django 5.2.15 on 2026-08-09 11:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0064_alter_auditperiodextension_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=27700
            ),
        ),
        migrations.AlterField(
            model_name="integratedcareboard",
            name="bng_e",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="integratedcareboard",
            name="bng_n",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="integratedcareboard",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=27700
            ),
        ),
        migrations.AlterField(
            model_name="integratedcareboard",
            name="globalid",
            field=models.CharField(blank=True, max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name="integratedcareboard",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="integratedcareboard",
            name="long",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="localhealthboard",
            name="bng_e",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="localhealthboard",
            name="bng_n",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="localhealthboard",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=27700
            ),
        ),
        migrations.AlterField(
            model_name="localhealthboard",
            name="globalid",
            field=models.CharField(blank=True, max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name="localhealthboard",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="localhealthboard",
            name="long",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nhsenglandregion",
            name="bng_e",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nhsenglandregion",
            name="bng_n",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nhsenglandregion",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=27700
            ),
        ),
        migrations.AlterField(
            model_name="nhsenglandregion",
            name="globalid",
            field=models.CharField(blank=True, max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name="nhsenglandregion",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nhsenglandregion",
            name="long",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
