# Generated by Django 4.1.7 on 2023-04-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0064_alter_historicalorganisation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="expected_score",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalepisode",
            name="expected_score",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
