# Generated by Django 5.2.15 on 2026-08-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0065_make_boundary_fields_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="country",
            name="welsh_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="address1",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="address2",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="address3",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="postcode",
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="website",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="integratedcareboard",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="localhealthboard",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="localhealthboard",
            name="welsh_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="nhsenglandregion",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="address1",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="address2",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="address3",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="postcode",
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="website",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="trust",
            name="address_line_1",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="trust",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="trust",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="trust",
            name="postcode",
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="trust",
            name="website",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
