# Generated by Django 4.1.7 on 2023-04-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0065_episode_expected_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="calculated_score",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalepisode",
            name="calculated_score",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
