# Generated by Django 5.2.15 on 2026-08-16 20:22

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0066_widen_char_field_max_lengths"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalAuditPeriodOrganisation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "included_in_reporting",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this organisation contributes to reporting for this audit period. Set to False for organisations that participated in the audit but are excluded from aggregated reporting.",
                    ),
                ),
                (
                    "country_name_snapshot",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "trust_name_snapshot",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "local_health_board_name_snapshot",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "integrated_care_board_name_snapshot",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "nhs_england_region_name_snapshot",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "openuk_network_name_snapshot",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the audit team approved this membership row. Null for sync-sourced candidate rows that have not yet been reviewed.",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="api_snapshot",
                        help_text="Provenance of this row. 'api_snapshot' for rows populated by the per-cohort sync; 'manual' for rows created or corrected by the audit team.",
                        max_length=32,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-text notes from the audit team, e.g. reasons for correcting a sync-sourced assignment.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The audit-team user who approved this membership row.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "audit_period",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The audit period this membership applies to.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="epilepsy12.auditperiod",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="epilepsy12.country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="record created by user in %(class)",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "integrated_care_board",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="epilepsy12.integratedcareboard",
                    ),
                ),
                (
                    "local_health_board",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Welsh local health boards. Null for English organisations.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="epilepsy12.localhealthboard",
                    ),
                ),
                (
                    "nhs_england_region",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="epilepsy12.nhsenglandregion",
                    ),
                ),
                (
                    "openuk_network",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="epilepsy12.openuknetwork",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The organisation this membership is for. Points at the Organisation row whose ODS code was in use during this audit period (which may be a predecessor ODS code).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="epilepsy12.organisation",
                    ),
                ),
                (
                    "trust",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="English trusts. Null for Welsh organisations.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="epilepsy12.trust",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="record updated by user in %(class)",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Audit period organisation",
                "verbose_name_plural": "historical Audit period organisations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOrganisationIdentity",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Current display name for the hospital. Used for admin and debugging only; historical reporting reads period-specific names from AuditPeriodOrganisation.",
                        max_length=255,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="record created by user in %(class)",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="record updated by user in %(class)",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Organisation identity",
                "verbose_name_plural": "historical Organisation identities",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="OrganisationIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Current display name for the hospital. Used for admin and debugging only; historical reporting reads period-specific names from AuditPeriodOrganisation.",
                        max_length=255,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="record created by user in %(class)",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="record updated by user in %(class)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation identity",
                "verbose_name_plural": "Organisation identities",
            },
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="identity",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The stable identity of the physical hospital, independent of ODS code. Links successive Organisation rows that represent the same hospital across ODS code changes.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="epilepsy12.organisationidentity",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="identity",
            field=models.ForeignKey(
                blank=True,
                help_text="The stable identity of the physical hospital, independent of ODS code. Links successive Organisation rows that represent the same hospital across ODS code changes.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ods_codes",
                to="epilepsy12.organisationidentity",
            ),
        ),
        migrations.CreateModel(
            name="AuditPeriodOrganisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "included_in_reporting",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this organisation contributes to reporting for this audit period. Set to False for organisations that participated in the audit but are excluded from aggregated reporting.",
                    ),
                ),
                (
                    "country_name_snapshot",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "trust_name_snapshot",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "local_health_board_name_snapshot",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "integrated_care_board_name_snapshot",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "nhs_england_region_name_snapshot",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "openuk_network_name_snapshot",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the audit team approved this membership row. Null for sync-sourced candidate rows that have not yet been reviewed.",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="api_snapshot",
                        help_text="Provenance of this row. 'api_snapshot' for rows populated by the per-cohort sync; 'manual' for rows created or corrected by the audit team.",
                        max_length=32,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-text notes from the audit team, e.g. reasons for correcting a sync-sourced assignment.",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The audit-team user who approved this membership row.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_audit_period_organisations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "audit_period",
                    models.ForeignKey(
                        help_text="The audit period this membership applies to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organisation_memberships",
                        to="epilepsy12.auditperiod",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_period_organisations",
                        to="epilepsy12.country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="record created by user in %(class)",
                    ),
                ),
                (
                    "integrated_care_board",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_period_organisations",
                        to="epilepsy12.integratedcareboard",
                    ),
                ),
                (
                    "local_health_board",
                    models.ForeignKey(
                        blank=True,
                        help_text="Welsh local health boards. Null for English organisations.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_period_organisations",
                        to="epilepsy12.localhealthboard",
                    ),
                ),
                (
                    "nhs_england_region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_period_organisations",
                        to="epilepsy12.nhsenglandregion",
                    ),
                ),
                (
                    "openuk_network",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_period_organisations",
                        to="epilepsy12.openuknetwork",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        help_text="The organisation this membership is for. Points at the Organisation row whose ODS code was in use during this audit period (which may be a predecessor ODS code).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_period_memberships",
                        to="epilepsy12.organisation",
                    ),
                ),
                (
                    "trust",
                    models.ForeignKey(
                        blank=True,
                        help_text="English trusts. Null for Welsh organisations.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_period_organisations",
                        to="epilepsy12.trust",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="record updated by user in %(class)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit period organisation",
                "verbose_name_plural": "Audit period organisations",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("audit_period", "organisation"),
                        name="unique_organisation_membership_per_audit_period",
                    )
                ],
            },
        ),
    ]
