# Generated by Django 5.2.15 on 2026-08-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0067_audit_period_organisation_and_organisation_identity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditperiodorganisation",
            name="source",
            field=models.CharField(
                default="snapshot",
                help_text="Provenance of this row. 'snapshot' for rows populated by the per-cohort sync from the API snapshot endpoint; 'detail_fallback' for rows populated from the detail endpoint (current state) when the snapshot had no temporal history for the date; 'manual' for rows created or corrected by the audit team.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicalauditperiodorganisation",
            name="source",
            field=models.CharField(
                default="snapshot",
                help_text="Provenance of this row. 'snapshot' for rows populated by the per-cohort sync from the API snapshot endpoint; 'detail_fallback' for rows populated from the detail endpoint (current state) when the snapshot had no temporal history for the date; 'manual' for rows created or corrected by the audit team.",
                max_length=32,
            ),
        ),
    ]
