# Generated by Django 5.2.15 on 2026-08-18 21:26

import django.contrib.gis.db.models.fields
from django.db import migrations


def clear_geocode_coordinates(apps, schema_editor):
    """Set all geocode_coordinates to NULL before changing the column SRID.

    The column is currently SRID 27700 (BNG). We need to change it to 4326
    (WGS84), but PostGIS enforces that stored geometries must match the
    column SRID — so we can't transform in place. Setting to NULL and
    repopulating from latitude/longitude after the SRID change is the
    cleanest approach. The sync_nhs_organisations command repopulates
    geocode_coordinates from the API's latitude/longitude fields.
    """
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "UPDATE epilepsy12_organisation SET geocode_coordinates = NULL "
            "WHERE geocode_coordinates IS NOT NULL"
        )
        cursor.execute(
            "UPDATE epilepsy12_historicalorganisation SET geocode_coordinates = NULL "
            "WHERE geocode_coordinates IS NOT NULL"
        )


def noop_reverse(apps, schema_editor):
    """No-op reverse — the data is repopulated by the sync."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0068_alter_auditperiodorganisation_source_default"),
    ]

    operations = [
        # Step 1: clear existing geocode_coordinates (can't transform in
        # place because PostGIS enforces column SRID on stored geometries)
        migrations.RunPython(
            clear_geocode_coordinates,
            reverse_code=noop_reverse,
        ),
        # Step 2: change the column SRID to 4326
        migrations.AlterField(
            model_name="historicalorganisation",
            name="geocode_coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, default=None, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="geocode_coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, default=None, null=True, srid=4326
            ),
        ),
    ]
