# Generated by Django 5.2.15 on 2026-08-18 21:26

import django.contrib.gis.db.models.fields
from django.db import migrations


def transform_geocode_coordinates_to_4326(apps, schema_editor):
    """Transform existing geocode_coordinates from SRID 27700 (BNG) to
    SRID 4326 (WGS84) using PostGIS ALTER TABLE ... TYPE ... USING.

    This transforms the data and changes the column type in one atomic
    statement, avoiding the "Geometry SRID does not match column SRID"
    error that occurs when trying to store a 4326 geometry in a 27700
    column.

    Points that fail the transform (out of the valid range for the BNG
    transform, e.g. Jersey) are set to NULL via a CASE expression —
    they will be repopulated from latitude/longitude by the sync.
    """
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        # Transform the organisation table: change column type to 4326
        # and transform existing data in one statement. Points that fail
        # ST_Transform (out of range) become NULL.
        cursor.execute("""
            ALTER TABLE epilepsy12_organisation
            ALTER COLUMN geocode_coordinates TYPE geometry(Point, 4326)
            USING CASE
                WHEN geocode_coordinates IS NULL THEN NULL
                WHEN ST_SRID(geocode_coordinates) = 27700 THEN
                    ST_Transform(geocode_coordinates, 4326)
                WHEN ST_SRID(geocode_coordinates) = 4326 THEN
                    geocode_coordinates
                ELSE NULL
            END
        """)

        # Transform the historical organisation table the same way.
        cursor.execute("""
            ALTER TABLE epilepsy12_historicalorganisation
            ALTER COLUMN geocode_coordinates TYPE geometry(Point, 4326)
            USING CASE
                WHEN geocode_coordinates IS NULL THEN NULL
                WHEN ST_SRID(geocode_coordinates) = 27700 THEN
                    ST_Transform(geocode_coordinates, 4326)
                WHEN ST_SRID(geocode_coordinates) = 4326 THEN
                    geocode_coordinates
                ELSE NULL
            END
        """)


def transform_geocode_coordinates_to_27700(apps, schema_editor):
    """Reverse: transform from 4326 back to 27700."""
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE epilepsy12_organisation
            ALTER COLUMN geocode_coordinates TYPE geometry(Point, 27700)
            USING CASE
                WHEN geocode_coordinates IS NULL THEN NULL
                WHEN ST_SRID(geocode_coordinates) = 4326 THEN
                    ST_Transform(geocode_coordinates, 27700)
                WHEN ST_SRID(geocode_coordinates) = 27700 THEN
                    geocode_coordinates
                ELSE NULL
            END
        """)

        cursor.execute("""
            ALTER TABLE epilepsy12_historicalorganisation
            ALTER COLUMN geocode_coordinates TYPE geometry(Point, 27700)
            USING CASE
                WHEN geocode_coordinates IS NULL THEN NULL
                WHEN ST_SRID(geocode_coordinates) = 4326 THEN
                    ST_Transform(geocode_coordinates, 27700)
                WHEN ST_SRID(geocode_coordinates) = 27700 THEN
                    geocode_coordinates
                ELSE NULL
            END
        """)


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0068_alter_auditperiodorganisation_source_default"),
    ]

    operations = [
        # Transform existing data from 27700 to 4326 and change the column
        # type in one atomic PostGIS operation. This avoids the "Geometry
        # SRID does not match column SRID" error.
        migrations.RunPython(
            transform_geocode_coordinates_to_4326,
            reverse_code=transform_geocode_coordinates_to_27700,
        ),
        # Tell Django the field has changed (so the migration state matches
        # the database state). The actual column change was done by the
        # RunPython above; these AlterField operations update Django's
        # migration state without re-issuing the ALTER TABLE.
        migrations.AlterField(
            model_name="historicalorganisation",
            name="geocode_coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, default=None, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="geocode_coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, default=None, null=True, srid=4326
            ),
        ),
    ]
