# Generated by Django 5.2.15 on 2026-08-22 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0069_alter_organisation_geocode_coordinates_srid_to_4326"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="integrated_care_board",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="epilepsy12.integratedcareboard",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="local_health_board",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="epilepsy12.localhealthboard",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="london_borough",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="epilepsy12.londonborough",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="nhs_england_region",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="epilepsy12.nhsenglandregion",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="openuk_network",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="epilepsy12.openuknetwork",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="trust",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="epilepsy12.trust",
            ),
        ),
    ]
