# Generated by Django 4.2 on 2023-04-08 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0070_historicalepilepsycause_epilepsycause"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EpilepsyCause",
            new_name="EpilepsyCauseEntity",
        ),
        migrations.RenameModel(
            old_name="HistoricalEpilepsyCause",
            new_name="HistoricalEpilepsyCauseEntity",
        ),
    ]
