# Generated by Django 4.2 on 2023-04-08 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0071_rename_epilepsycause_epilepsycauseentity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmultiaxialdiagnosis",
            name="epilepsy_cause_fk",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                help_text={
                    "label": "What is the main identified cause of the epilepsy?",
                    "reference": "What is the main identified cause of the epilepsy?",
                },
                max_length=250,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="epilepsy12.epilepsycauseentity",
            ),
        ),
        migrations.AddField(
            model_name="multiaxialdiagnosis",
            name="epilepsy_cause_fk",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text={
                    "label": "What is the main identified cause of the epilepsy?",
                    "reference": "What is the main identified cause of the epilepsy?",
                },
                max_length=250,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="epilepsy12.epilepsycauseentity",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmultiaxialdiagnosis",
            name="epilepsy_cause",
            field=models.CharField(
                blank=True,
                default=None,
                help_text={
                    "label": "What is the main identified cause of the epilepsy?",
                    "reference": "What is the main identified cause of the epilepsy?",
                },
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="multiaxialdiagnosis",
            name="epilepsy_cause",
            field=models.CharField(
                blank=True,
                default=None,
                help_text={
                    "label": "What is the main identified cause of the epilepsy?",
                    "reference": "What is the main identified cause of the epilepsy?",
                },
                max_length=50,
                null=True,
            ),
        ),
    ]
