# Generated by Django 4.2 on 2023-04-08 16:23

from django.db import migrations


def fill_epilepsy_cause_fk(apps, schema_editor):
    MultiaxialDiagnosis = apps.get_model('epilepsy12', 'MultiaxialDiagnosis')
    EpilepsyCauseEntity = apps.get_model('epilepsy12', 'EpilepsyCauseEntity')
    for multiaxialdiagnosis in MultiaxialDiagnosis.objects.all():
        if multiaxialdiagnosis.epilepsy_cause is not None:
            multiaxialdiagnosis.epilepsy_cause_fk = EpilepsyCauseEntity.objects.filter(
                conceptId=multiaxialdiagnosis.epilepsy_cause).first()
            multiaxialdiagnosis.save()


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0072_historicalmultiaxialdiagnosis_epilepsy_cause_fk_and_more"),
    ]

    operations = [
        migrations.RunPython(fill_epilepsy_cause_fk),
    ]
