# Generated by Django 4.2 on 2023-04-08 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0073_auto_20230408_1723"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmultiaxialdiagnosis",
            name="epilepsy_cause",
        ),
        migrations.RemoveField(
            model_name="multiaxialdiagnosis",
            name="epilepsy_cause",
        ),
    ]
