# Generated by Django 4.2 on 2023-04-08 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "epilepsy12",
            "0074_remove_historicalmultiaxialdiagnosis_epilepsy_cause_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalmultiaxialdiagnosis",
            old_name="epilepsy_cause_fk",
            new_name="epilepsy_cause",
        ),
        migrations.RenameField(
            model_name="multiaxialdiagnosis",
            old_name="epilepsy_cause_fk",
            new_name="epilepsy_cause",
        ),
    ]
