# Generated by Django 4.2 on 2023-04-16 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# epilepsy12.migrations.0077_auto_20230409_0943

def fill_comorbidity(apps, schema_editor):
    Comorbidity = apps.get_model('epilepsy12', 'Comorbidity')
    ComorbidityEntity = apps.get_model('epilepsy12', 'ComorbidityEntity')
    for comorbidity in Comorbidity.objects.all():
        if comorbidity.comorbidity_diagnosis is not None:
            comorbidity.comorbidityentity = ComorbidityEntity.objects.filter(
                conceptId=comorbidity.comorbidity_diagnosis).first()
            comorbidity.save()


class Migration(migrations.Migration):

    replaces = [('epilepsy12', '0076_alter_comorbidity_comorbidity_diagnosis_and_more'), ('epilepsy12',
                                                                                          '0077_auto_20230409_0943'), ('epilepsy12', '0078_remove_comorbidity_comorbidity_diagnosis_and_more')]

    dependencies = [
        ('epilepsy12', '0075_rename_epilepsy_cause_fk_historicalmultiaxialdiagnosis_epilepsy_cause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comorbidity',
            name='comorbidity_diagnosis',
            field=models.CharField(blank=True, default=None, help_text={
                                   'label': 'What is the comorbidity?', 'reference': 'What is the comorbidity?'}, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcomorbidity',
            name='comorbidity_diagnosis',
            field=models.CharField(blank=True, default=None, help_text={
                                   'label': 'What is the comorbidity?', 'reference': 'What is the comorbidity?'}, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalComorbidityEntity',
            fields=[
                ('id', models.BigIntegerField(auto_created=True,
                 blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('conceptId', models.CharField(blank=True, default=None, null=True)),
                ('term', models.CharField(blank=True, default=None, null=True)),
                ('preferredTerm', models.CharField(
                    blank=True, default=None, null=True)),
                ('description', models.CharField(
                    blank=True, default=None, null=True)),
                ('snomed_ct_edition', models.CharField(
                    blank=True, default=None, null=True)),
                ('snomed_ct_version', models.CharField(
                    blank=True, default=None, null=True)),
                ('icd_code', models.CharField(blank=True, default=None, null=True)),
                ('icd_version', models.IntegerField(
                    blank=True, default=None, null=True)),
                ('dsm_code', models.CharField(blank=True, default=None, null=True)),
                ('dsm_version', models.IntegerField(
                    blank=True, default=None, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(
                    max_length=100, null=True)),
                ('history_type', models.CharField(choices=[
                 ('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                 related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)')),
                ('history_user', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                 related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)')),
            ],
            options={
                'verbose_name': 'historical ComorbidityEntity',
                'verbose_name_plural': 'historical ComorbidityEntities',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ComorbidityEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conceptId', models.CharField(blank=True, default=None, null=True)),
                ('term', models.CharField(blank=True, default=None, null=True)),
                ('preferredTerm', models.CharField(
                    blank=True, default=None, null=True)),
                ('description', models.CharField(
                    blank=True, default=None, null=True)),
                ('snomed_ct_edition', models.CharField(
                    blank=True, default=None, null=True)),
                ('snomed_ct_version', models.CharField(
                    blank=True, default=None, null=True)),
                ('icd_code', models.CharField(blank=True, default=None, null=True)),
                ('icd_version', models.IntegerField(
                    blank=True, default=None, null=True)),
                ('dsm_code', models.CharField(blank=True, default=None, null=True)),
                ('dsm_version', models.IntegerField(
                    blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='craeted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record created by user in %(class)')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='record updated by user in %(class)')),
            ],
            options={
                'verbose_name': 'ComorbidityEntity',
                'verbose_name_plural': 'ComorbidityEntities',
            },
        ),
        migrations.AddField(
            model_name='comorbidity',
            name='comorbidityentity',
            field=models.ForeignKey(default=None, help_text={'label': 'What is the comorbidity?', 'reference': 'What is the comorbidity?'},
                                    null=True, on_delete=django.db.models.deletion.PROTECT, to='epilepsy12.comorbidityentity'),
        ),
        migrations.AddField(
            model_name='historicalcomorbidity',
            name='comorbidityentity',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, help_text={
                                    'label': 'What is the comorbidity?', 'reference': 'What is the comorbidity?'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='epilepsy12.comorbidityentity'),
        ),
        migrations.RunPython(
            fill_comorbidity,
        ),
        migrations.RemoveField(
            model_name='comorbidity',
            name='comorbidity_diagnosis',
        ),
        migrations.RemoveField(
            model_name='historicalcomorbidity',
            name='comorbidity_diagnosis',
        ),
        migrations.AlterField(
            model_name='comorbidity',
            name='comorbidityentity',
            field=models.ForeignKey(default=None, help_text={
                                    'label': 'What is the comorbidity?', 'reference': 'What is the comorbidity?'}, on_delete=django.db.models.deletion.PROTECT, to='epilepsy12.comorbidityentity'),
        ),
    ]
