# Generated by Django 4.2 on 2023-04-08 19:41

from django.db import migrations


def fill_comorbidity(apps, schema_editor):
    Comorbidity = apps.get_model('epilepsy12', 'Comorbidity')
    ComorbidityEntity = apps.get_model('epilepsy12', 'ComorbidityEntity')
    for comorbidity in Comorbidity.objects.all():
        if comorbidity.comorbidity_diagnosis is not None:
            comorbidity.comorbidityentity = ComorbidityEntity.objects.filter(
                conceptId=comorbidity.comorbidity_diagnosis).first()
            comorbidity.save()


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0076_historicalcomorbidityentity_comorbidityentity_and_more"),
    ]

    operations = [
        migrations.RunPython(fill_comorbidity),
    ]
