# Generated by Django 4.2 on 2023-04-09 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0077_auto_20230409_0943"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comorbidity",
            name="comorbidity_diagnosis",
        ),
        migrations.RemoveField(
            model_name="historicalcomorbidity",
            name="comorbidity_diagnosis",
        ),
        migrations.AlterField(
            model_name="comorbidity",
            name="comorbidityentity",
            field=models.ForeignKey(
                default=None,
                help_text={
                    "label": "What is the comorbidity?",
                    "reference": "What is the comorbidity?",
                },
                on_delete=django.db.models.deletion.PROTECT,
                to="epilepsy12.comorbidityentity",
            ),
        ),
    ]
