# Generated by Django 4.2 on 2023-04-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0078_remove_comorbidity_comorbidity_diagnosis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comorbidityentity",
            name="conceptId",
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcomorbidityentity",
            name="conceptId",
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
