# Generated by Django 4.2 on 2023-04-09 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0078_remove_comorbidity_comorbidity_diagnosis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text={
                    "label": "What is the episode(s) like and is the description adequate?",
                    "reference": "Glossary of Descriptive Terminology for Ictal Semiology: Report of the ILAE Task Force on Classification and Terminology, 2002",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="epileptic_seizure_onset_type",
            field=models.CharField(
                choices=[
                    ("FO", "Focal onset"),
                    ("GO", "Generalised onset"),
                    ("UO", "Unknown onset"),
                    ("UC", "Unclassified"),
                ],
                default=None,
                help_text={
                    "label": "How best would describe the onset of the epileptic episode?",
                    "reference": "Operational classification of seizure types by the International League Against Epilepsy: Position Paper of the ILAE Commission for Classification and Terminology. Epilepsia, 58(4):522–530, 2017.",
                },
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="nonepileptic_seizure_unknown_onset",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BAr", "Behaviour arrest"),
                    ("EpS", "Epileptic spasms"),
                    ("TCl", "Tonic-clonic"),
                    ("Oth", "Other"),
                ],
                default=None,
                help_text={
                    "label": "How best describes the onset of the nonepileptic episode(s)?",
                    "reference": "Operational classification of seizure types by the International League Against Epilepsy: Position Paper of the ILAE Commission for Classification and Terminology. Epilepsia, 58(4):522–530, 2017.",
                },
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalepisode",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text={
                    "label": "What is the episode(s) like and is the description adequate?",
                    "reference": "Glossary of Descriptive Terminology for Ictal Semiology: Report of the ILAE Task Force on Classification and Terminology, 2002",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalepisode",
            name="epileptic_seizure_onset_type",
            field=models.CharField(
                choices=[
                    ("FO", "Focal onset"),
                    ("GO", "Generalised onset"),
                    ("UO", "Unknown onset"),
                    ("UC", "Unclassified"),
                ],
                default=None,
                help_text={
                    "label": "How best would describe the onset of the epileptic episode?",
                    "reference": "Operational classification of seizure types by the International League Against Epilepsy: Position Paper of the ILAE Commission for Classification and Terminology. Epilepsia, 58(4):522–530, 2017.",
                },
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalepisode",
            name="nonepileptic_seizure_unknown_onset",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BAr", "Behaviour arrest"),
                    ("EpS", "Epileptic spasms"),
                    ("TCl", "Tonic-clonic"),
                    ("Oth", "Other"),
                ],
                default=None,
                help_text={
                    "label": "How best describes the onset of the nonepileptic episode(s)?",
                    "reference": "Operational classification of seizure types by the International League Against Epilepsy: Position Paper of the ILAE Commission for Classification and Terminology. Epilepsia, 58(4):522–530, 2017.",
                },
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalsyndrome",
            name="syndrome",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                help_text={
                    "label": "The syndrome name.",
                    "reference": "Methodology for classification and definition of epilepsy syndromes with list of syndromes: Report of the ILAE Task Force on Nosology and Definitions, Epilepsia 2017",
                },
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="epilepsy12.syndromeentity",
            ),
        ),
        migrations.AlterField(
            model_name="syndrome",
            name="syndrome",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text={
                    "label": "The syndrome name.",
                    "reference": "Methodology for classification and definition of epilepsy syndromes with list of syndromes: Report of the ILAE Task Force on Nosology and Definitions, Epilepsia 2017",
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="epilepsy12.syndromeentity",
            ),
        ),
    ]
