# Generated by Django 4.2 on 2023-04-12 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0079_alter_episode_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comorbidity",
            name="comorbidityentity",
            field=models.ForeignKey(
                default=None,
                help_text={
                    "label": "What is the comorbidity?",
                    "reference": "Paediatric neurodisability outpatient diagnosis simple reference set (999001751000000105), SNOMED-CT",
                },
                on_delete=django.db.models.deletion.PROTECT,
                to="epilepsy12.comorbidityentity",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomorbidity",
            name="comorbidityentity",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                help_text={
                    "label": "What is the comorbidity?",
                    "reference": "Paediatric neurodisability outpatient diagnosis simple reference set (999001751000000105), SNOMED-CT",
                },
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="epilepsy12.comorbidityentity",
            ),
        ),
    ]
