# Generated by Django 4.2 on 2023-04-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0080_alter_comorbidity_comorbidityentity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="surname",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Surname"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="surname",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Surname"
            ),
        ),
    ]
