# Generated by Django 4.2 on 2023-04-12 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0082_seed_medicines"),
    ]

    operations = [
        migrations.AddField(
            model_name="antiepilepsymedicine",
            name="medicine_entity",
            field=models.ForeignKey(
                default=None,
                null=True,
                help_text={
                    "label": "Medicine Name",
                    "reference": "Please enter the medicine.",
                },
                on_delete=django.db.models.deletion.PROTECT,
                to="epilepsy12.medicineentity",
            ),
        ),
        migrations.AddField(
            model_name="historicalantiepilepsymedicine",
            name="medicine_entity",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                help_text={
                    "label": "Medicine Name",
                    "reference": "Please enter the medicine.",
                },
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="epilepsy12.medicineentity",
            ),
        ),
    ]
