# Generated by Django 4.2 on 2023-04-12 14:46

from django.db import migrations


def create_foreign_key_for_existing_medications(apps, schema_editor):
    """
    loop through table with existing medicines and add to new relationship
    """
    MedicineEntity = apps.get_model('epilepsy12', 'MedicineEntity')
    AntiEpilepsyMedicine = apps.get_model('epilepsy12', 'AntiEpilepsyMedicine')
    for antiepilepsy_medicine in AntiEpilepsyMedicine.objects.all():
        if antiepilepsy_medicine.medicine_entity is None and antiepilepsy_medicine.medicine_name is not None:
            # no relationship exists with MedicineEntity yet and a medicine has been allocated previously
            if MedicineEntity.objects.filter(medicine_name=antiepilepsy_medicine.medicine_name).exists():
                new_medicine = MedicineEntity.objects.filter(
                    medicine_name=antiepilepsy_medicine.medicine_name).first()
                antiepilepsy_medicine.medicine_entity = new_medicine
                antiepilepsy_medicine.save()


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0084_antiepilepsymedicine_medicine_entity_and_more"),
    ]

    operations = [
        migrations.RunPython(create_foreign_key_for_existing_medications)
    ]
