# Generated by Django 4.2 on 2023-04-12 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epilepsy12", "0085_alter_antiepilepsymedicine_medicine_entity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="antiepilepsymedicine",
            name="antiepilepsy_medicine_snomed_code",
        ),
        migrations.RemoveField(
            model_name="antiepilepsymedicine",
            name="antiepilepsy_medicine_snomed_preferred_name",
        ),
        migrations.RemoveField(
            model_name="antiepilepsymedicine",
            name="medicine_id",
        ),
        migrations.RemoveField(
            model_name="antiepilepsymedicine",
            name="medicine_name",
        ),
        migrations.RemoveField(
            model_name="historicalantiepilepsymedicine",
            name="antiepilepsy_medicine_snomed_code",
        ),
        migrations.RemoveField(
            model_name="historicalantiepilepsymedicine",
            name="antiepilepsy_medicine_snomed_preferred_name",
        ),
        migrations.RemoveField(
            model_name="historicalantiepilepsymedicine",
            name="medicine_id",
        ),
        migrations.RemoveField(
            model_name="historicalantiepilepsymedicine",
            name="medicine_name",
        ),
    ]
