# Generated by Django 4.2 on 2023-04-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "epilepsy12",
            "0086_remove_antiepilepsymedicine_antiepilepsy_medicine_snomed_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="surname",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Surname"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="surname",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Surname"
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="assessment_of_mental_health_issues",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "6. Assessment of mental health issues",
                    "reference": "Percentage of children and young people with epilepsy where there is documented evidence that they have been asked about mental health either through clinical screening, or a questionnaire/measure.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="comprehensive_care_planning_content",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "9B. Comprehensive care planning content",
                    "reference": "Percentage of children diagnosed with epilepsy with documented evidence of communication regarding core elements of care planning (items a - f).",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="first_aid",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "9c. First aid",
                    "reference": "Percentage of children and young people with epilepsy with evidence of discussion regarding first aid.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="general_participation_and_risk",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "9d. General participation and risk",
                    "reference": "Percentage of children and young people with epilepsy with evidence of discussion regarding general participation and risk.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="mental_health_support",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "7. Mental health support",
                    "reference": "Percentage of children and young people with epilepsy and a mental health problem who have evidence of mental health support",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="mri",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "5. MRI",
                    "reference": "Percentage of children and young people with defined indications for an MRI, who had timely MRI within 6 weeks of request",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="parental_prolonged_seizures_care_plan",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "9a. Parental prolonged seizures care plan",
                    "reference": "Percentage of children and young people with epilepsy who have been prescribed rescue medication and have evidence of a written prolonged seizures plan.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="school_individual_healthcare_plan",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "10. School individualised health care plan",
                    "reference": "Percentage of children and young people with epilepsy aged 4 years and above with evidence of a school individual healthcare plan by 1 year after first paediatric assessment.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="service_contact_details",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "9f. Service contact details",
                    "reference": "Percentage of children and young people with epilepsy with evidence of being given service contact details.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="sudep",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "9e. Sudden unexplained death in epilepsy",
                    "reference": "Percentage of children and young people with epilepsy with evidence of discussion regarding SUDEP and evidence of a prolonged seizures care plan.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="water_safety",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "9b. Water safety",
                    "reference": "Percentage of children and young people with epilepsy with evidence of discussion regarding water safety.",
                },
                null=True,
            ),
        ),
    ]
