#!/bin/bash -e

az acr login --name ${AZURE_REGISTRY_NAME}

# Download .env file (--query avoids outputting all the info about the blob in our public logs)
az storage file download \
    --auth-mode login \
    --enable-file-backup-request-intent \
    --account-name ${AZURE_CONFIG_STORAGE_ACCOUNT} \
    --share-name ${AZURE_CONFIG_FILE_SHARE} \
    --query 'size' \
    --path .env --dest envs/.env

# Tests (against local Postgres)
# TODO MRB: enable again before merge
docker compose build
# docker compose up -d
# docker compose exec django pytest -v
# docker compose down

# Push to Azure
AZURE_TAG="${AZURE_REGISTRY_NAME}.azurecr.io/e12-django:${GITHUB_SHA}"
docker tag e12-django:built ${AZURE_TAG}
docker push ${AZURE_TAG}