#!/bin/bash

# scripts may need to be made executable on some platforms before they can be run
# chmod +x <filename> is the command to do this on unixy systems

# deletes all the data in Docker volumes
echo "WARNING: This will delete all the data in Docker volumes."
echo "This is irreversible and must NEVER be done on Live or Production systems."
echo "Are you sure you want to continue? Type 'delete' to continue."
read -r response

if [[ "$response" = "delete" ]]; then
    echo "Deleting local data..."
    # shuts down the Docker Compose setup and remove containers and images
    docker compose down -v --rmi local # removes the volumes, container and local images
    echo "Local data has been deleted."
else
    echo "Aborting. No data has been deleted."
fi



