#!/bin/bash

# scripts may need to be made executable on some platforms before they can be run
# chmod +x <filename> is the command to do this on unixy systems

# starts the postgres and application containers
# migrates db, seeds db, creates superuser, runs server

docker compose -f docker-compose.dev.yml down -v # removes all the containers AND the DB volume
docker compose -f docker-compose.dev-init.yml up # starts everything up again