#!/bin/bash

# scripts may need to be made executable on some platforms before they can be run
# chmod +x <filename> is the command to do this on unixy systems

#!/bin/bash

echo "WARNING: This will delete all Epilepsy12 data in Docker volumes."
echo "Are you sure you want to continue? (yes/no)"
read -r response

if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    if [[ -d "./data" ]]; then
        echo "Deleting local data..."
        # shuts down the Docker Compose setup and remove containers and images
        docker compose down -v --rmi local # removes the volumes, container and local images
        echo "Local data has been deleted."
    fi
else
    echo "Aborting. No data has been deleted."
fi



