#!/bin/bash

# scripts may need to be made executable on some platforms before they can be run
# chmod +x <filename> is the command to do this on unixy systems

# creates a superuser interactively
docker compose exec django python manage.py createsuperuser --username epilepsy12admin --email incubator@rcpch.ac.uk

