#!/bin/bash

# scripts may need to be made executable on some platforms before they can be run
# chmod +x <filename> is the command to do this on unixy systems

# docker down and remove containers and images
docker compose down --rmi local # removes the container and local images
