#!/bin/bash -e

# Avoid the start-dev script seeding and pytest seeding fighting
# each other and causing OOM errors
DJANGO_START_COMMAND='s/start-test' docker compose up -d --wait
s/test -m 'not slow'
s/test -m 'slow'
docker compose down
