#!/bin/bash -e

# Avoid the start-dev script seeding and pytest seeding fighting
# each other and causing OOM errors
DJANGO_START_COMMAND='sleep 100000' docker compose up -d --wait
s/test -s -m 'not slow'
s/test -s -m 'slow'
docker compose down
