#!/bin/bash

# scripts may need to be made executable on some platforms before they can be run
# chmod +x <filename> is the command to do this on unixy systems

### IMPORTANT ###
# you will need the `gh` (GitHub CLI) executable installed and configured on your system

# Define the path to the .env file
env_file_path="envs/.env"
repo="rcpch/rcpch-audit-engine"
secret_name="ENVIRONMENT"


# Check if the file exists
if [ ! -f "$env_file_path" ]; then
    echo "File not found at $env_file_path!"
    exit 1
fi

# Base64 encode the file
encoded_content=$(base64 "$env_file_path")

# Ask for confirmation
read -p "Are you sure you want to set the content of $env_file_path as a GitHub secret? (y/n) " confirm

if [ "$confirm" != "y" ]; then
    echo "Operation cancelled."
    exit 1
fi

# Set the secret using GitHub CLI
gh secret set "$secret_name" -b"$encoded_content" --repo "$repo"

echo "Secret set successfully."

