#!/bin/bash

set -v  # Enable verbose mode
set -e  # Exit on error

# scripts may need to be made executable on some platforms before they can be run
# chmod +x <filename> is the command to do this on unixy systems

### IMPORTANT ###
# you will need the `gh` (GitHub CLI) executable installed and configured on your system

# Set variables
env_file_path="envs/.env"
repo="rcpch/rcpch-audit-engine"
secret_name="ENVIRONMENT"

# Check if the .env file exists
if [ ! -f "$env_file_path" ]; then
    echo "File not found at $env_file_path!"
    exit 1
fi

# Base64 encode the .env file contents
encoded_content=$(base64 "$env_file_path")

# Ask for confirmation
read -p "Are you sure you want to set the content of $env_file_path as a GitHub secret? (y/n) " confirm

if [ "$confirm" != "y" ]; then
    echo "Operation cancelled."
    exit 1
fi

# Set the secret using GitHub CLI
gh secret set "$secret_name" -b"$encoded_content" --repo "$repo"

# Check if the `gh` command was successful
if [ $? -eq 0 ]; then
    echo "Secret set successfully."
else
    echo "Failed to set the secret."
    exit 1
fi
