#!/bin/bash -e

python manage.py collectstatic --noinput
python manage.py migrate
python manage.py seed --mode=seed_groups_and_permissions
python manage.py create_dev_users
python manage.py runserver 0.0.0.0:8000