#!/bin/bash -e

python manage.py write_azure_pg_password_file
python manage.py collectstatic --noinput
python manage.py migrate
python manage.py seed --mode=seed_groups_and_permissions
gunicorn --bind=0.0.0.0:8000 --timeout 600 acatest.wsgi
