# Runs the Pytest test suite when PRs are made against any branch

name: Run Pytest via Docker Compose on all PRs

on:
    pull_request:
      branches:
        - "*"

jobs:
  build-and-run-pytest-suite-in-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full code repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0 # to allow git_context_processor.py to still work

      - name: Create .env file
        run: |
          cp envs/env-template envs/.env

      - name: Run PR check script
        run: |
          s/pr-check
